### ISSUE TITLE
Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by pirog** [kalabox/kalabox#1022]
## Exception in Kalabox
Cannot read property 'id' of undefined

[View on Bugsnag](https://bugsnag.com/kalabox/kalabox/errors/56c22a1907141bdbdacf7ac0?event_id=56c22dea9d48998c1b9e621c)

## Stacktrace

[View full stacktrace](https://bugsnag.com/kalabox/kalabox/errors/56c22a1907141bdbdacf7ac0?event_id=56c22dea9d48998c1b9e621c)

**Comment by pirog** [comment]
I can't seem to replicate this.

**Comment by pirog** [comment]
I can't replicate this using terminus 0.10.2 or 0.10.3. 

One thing that is notable is our internal getUUID terminus wrapper is returning an array while calling `site info` directly returns an object. 

Going to backlog this for now.

**Comment by jdleonard** [comment]
I'm encountering this on alpha2 when trying to pull down the Pantheon database and files for an existing site via GUI or CLI.

<pre>
JDs-MacBook-Pro:code jd$ kbox pull
? Which database backup do you want to use? dev
? Retrieve latest DB instead of most recent backup? (y/N) No
? Which files do you want to use? dev
Pulling screenshot.
Pulling code.
Warning: Permanently added '[codeserver.dev.00b89304-8961-4dd7-8a12-966f33309de5.drush.in]:2222,[192.237.164.70]:2222' (RSA) to the list of known hosts.
remote: Counting objects: 129, done.
remote: Compressing objects: 100% (28/28), done.
remote: Total 28 (delta 22), reused 0 (delta 0)
Unpacking objects: 100% (28/28), done.
From ssh://codeserver.dev.00b89304-8961-4dd7-8a12-966f33309de5.drush.in:2222/~/repository
 * branch            master     -> FETCH_HEAD
   548fd1c..0d269cf  master     -> origin/master
Merge made by the 'recursive' strategy.
 .../copperly/tpl/copperly-quotes-page.tpl.php      | 166 +++++++++++++++++----
 sites/all/themes/sevenmod/scripts.js               |   7 +
 sites/all/themes/sevenmod/sevenmod.info            |   2 +
 sites/all/themes/victory/css/style.less            |  27 ++--
 sites/all/themes/victory/scripts/scripts.js        |  45 ++----
 5 files changed, 180 insertions(+), 67 deletions(-)
 create mode 100644 sites/all/themes/sevenmod/scripts.js
Pulling database.
Pulling files.
Cannot read property 'id' of undefined
TypeError: Cannot read property 'id' of undefined
    at /Users/jd/.kalabox/apps/copperly/plugins/kalabox-plugin-pantheon/lib/terminus.js:265:24
From previous event:
    at Terminus.getUUID (/Users/jd/.kalabox/apps/copperly/plugins/kalabox-plugin-pantheon/lib/terminus.js:264:4)
    at pullFilesRsync (/Users/jd/.kalabox/apps/copperly/plugins/kalabox-plugin-pantheon/lib/pull.js:232:21)
    at Object.pullFiles (/Users/jd/.kalabox/apps/copperly/plugins/kalabox-plugin-pantheon/lib/pull.js:328:14)
    at /Users/jd/.kalabox/apps/copperly/plugins/kalabox-plugin-pantheon/lib/tasks.js:284:31
    at process._tickCallback (node.js:917:13)
From previous event:
    at null.completed (/Users/jd/.kalabox/apps/copperly/plugins/kalabox-plugin-pantheon/lib/tasks.js:276:14)
    at PromptUI.onCompletion (/Users/jd/.kalabox/apps/copperly/node_modules/inquirer/lib/ui/prompt.js:56:10)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (/Users/jd/.kalabox/apps/copperly/node_modules/rx-lite/rx.lite.js:1826:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/Users/jd/.kalabox/apps/copperly/node_modules/rx-lite/rx.lite.js:1763:14)
    at AnonymousObserver.tryCatcher (/Users/jd/.kalabox/apps/copperly/node_modules/rx-lite/rx.lite.js:537:29)
    at AutoDetachObserverPrototype.completed (/Users/jd/.kalabox/apps/copperly/node_modules/rx-lite/rx.lite.js:5435:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/Users/jd/.kalabox/apps/copperly/node_modules/rx-lite/rx.lite.js:1763:14)
    at InnerObserver.onCompleted (/Users/jd/.kalabox/apps/copperly/node_modules/rx-lite/rx.lite.js:2885:65)
    at InnerObserver.tryCatcher (/Users/jd/.kalabox/apps/copperly/node_modules/rx-lite/rx.lite.js:537:29)
    at AutoDetachObserverPrototype.completed (/Users/jd/.kalabox/apps/copperly/node_modules/rx-lite/rx.lite.js:5435:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/Users/jd/.kalabox/apps/copperly/node_modules/rx-lite/rx.lite.js:1763:14)
    at AutoDetachObserver.tryCatcher (/Users/jd/.kalabox/apps/copperly/node_modules/rx-lite/rx.lite.js:537:29)
    at AutoDetachObserverPrototype.completed (/Users/jd/.kalabox/apps/copperly/node_modules/rx-lite/rx.lite.js:5435:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/Users/jd/.kalabox/apps/copperly/node_modules/rx-lite/rx.lite.js:1763:14)
    at InnerObserver.onCompleted (/Users/jd/.kalabox/apps/copperly/node_modules/rx-lite/rx.lite.js:2885:65)
    at InnerObserver.tryCatcher (/Users/jd/.kalabox/apps/copperly/node_modules/rx-lite/rx.lite.js:537:29)
    at AutoDetachObserverPrototype.completed (/Users/jd/.kalabox/apps/copperly/node_modules/rx-lite/rx.lite.js:5435:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/Users/jd/.kalabox/apps/copperly/node_modules/rx-lite/rx.lite.js:1763:14)
    at AutoDetachObserver.tryCatcher (/Users/jd/.kalabox/apps/copperly/node_modules/rx-lite/rx.lite.js:537:29)
</pre>

**Comment by jdleonard** [comment]
destroy and create worked around this.
