### ISSUE TITLE
Cannot read property 'mysql_command' of undefined error on kbox push

### ISSUE THREAD

**Issue by labboy0276** [kalabox/kalabox#1035]
Hello!

Pushing up the DB only to a multidev (0.11.2 Kalabox version), results in this:

```
john@kalamuna:~/kalabox/apps/fiksu/code$ kbox push
? Tell us about your changes DB
? Which env do you want to push the DB to? zendesk
? Which env do you want to push the files to? Do not push the files
info: TERMINUS =>  Run definition:  compose=[/home/john/kalabox/apps/fiksu/kalabox-compose.yml, /home/john/kalabox/apps/fiksu/kalabox-cli.yml], project=fiksu, services=[terminus], mode=collect, entrypoint=[bash, --login, -c], cmd=[terminus, site, environment-info, --format=json, --site=fiksu, --env=zendesk]
info: COMPOSE =>  0=--project-name, 1=fiksu, 2=--file, 3=/home/john/kalabox/apps/fiksu/kalabox-compose.yml, 4=--file, 5=/home/john/kalabox/apps/fiksu/kalabox-cli.yml, 6=run, 7=-d, 8=--entrypoint, 9=tail, 10=terminus, 11=-f, 12=/dev/null, mode=false
info: TERMINUS =>  Run returned: 
info: TERMINUS =>  Run definition:  compose=[/home/john/kalabox/apps/fiksu/kalabox-compose.yml, /home/john/kalabox/apps/fiksu/kalabox-cli.yml], project=fiksu, services=[terminus], mode=collect, entrypoint=[bash, --login, -c], cmd=[terminus, site, code, diffstat, --format=json, --site=fiksu, --env=zendesk]
info: COMPOSE =>  0=--project-name, 1=fiksu, 2=--file, 3=/home/john/kalabox/apps/fiksu/kalabox-compose.yml, 4=--file, 5=/home/john/kalabox/apps/fiksu/kalabox-cli.yml, 6=run, 7=-d, 8=--entrypoint, 9=tail, 10=terminus, 11=-f, 12=/dev/null, mode=false
info: TERMINUS =>  Run returned: 
info: TERMINUS =>  Run definition:  compose=[/home/john/kalabox/apps/fiksu/kalabox-compose.yml, /home/john/kalabox/apps/fiksu/kalabox-cli.yml], project=fiksu, services=[terminus], mode=collect, entrypoint=[bash, --login, -c], cmd=[terminus, site, set-connection-mode, --format=json, --site=fiksu, --env=zendesk, --mode=git]
info: COMPOSE =>  0=--project-name, 1=fiksu, 2=--file, 3=/home/john/kalabox/apps/fiksu/kalabox-compose.yml, 4=--file, 5=/home/john/kalabox/apps/fiksu/kalabox-cli.yml, 6=run, 7=-d, 8=--entrypoint, 9=tail, 10=terminus, 11=-f, 12=/dev/null, mode=false
info: TERMINUS =>  Run returned: 
info: TERMINUS =>  Run definition:  compose=[/home/john/kalabox/apps/fiksu/kalabox-compose.yml, /home/john/kalabox/apps/fiksu/kalabox-cli.yml], project=fiksu, services=[terminus], mode=collect, entrypoint=[bash, --login, -c], cmd=[terminus, site, wake, --site=fiksu, --env=zendesk, --format=json]
info: COMPOSE =>  0=--project-name, 1=fiksu, 2=--file, 3=/home/john/kalabox/apps/fiksu/kalabox-compose.yml, 4=--file, 5=/home/john/kalabox/apps/fiksu/kalabox-cli.yml, 6=run, 7=-d, 8=--entrypoint, 9=tail, 10=terminus, 11=-f, 12=/dev/null, mode=false
info: TERMINUS =>  Run returned: 
info: KGIT =>  compose=[/home/john/kalabox/apps/fiksu/kalabox-compose.yml, /home/john/kalabox/apps/fiksu/kalabox-cli.yml], project=fiksu, mode=attach, services=[cli], entrypoint=kgit, cmd=[add, --all]
info: COMPOSE =>  0=--project-name, 1=fiksu, 2=--file, 3=/home/john/kalabox/apps/fiksu/kalabox-compose.yml, 4=--file, 5=/home/john/kalabox/apps/fiksu/kalabox-cli.yml, 6=run, 7=-d, 8=--entrypoint, 9=tail, 10=cli, 11=-f, 12=/dev/null, mode=false
info: KGIT =>  compose=[/home/john/kalabox/apps/fiksu/kalabox-compose.yml, /home/john/kalabox/apps/fiksu/kalabox-cli.yml], project=fiksu, mode=attach, services=[cli], entrypoint=kgit, cmd=[commit, --allow-empty, -m, DB]
info: COMPOSE =>  0=--project-name, 1=fiksu, 2=--file, 3=/home/john/kalabox/apps/fiksu/kalabox-compose.yml, 4=--file, 5=/home/john/kalabox/apps/fiksu/kalabox-cli.yml, 6=run, 7=-d, 8=--entrypoint, 9=tail, 10=cli, 11=-f, 12=/dev/null, mode=false
[zendesk a0a8b3a] DB
info: KGIT =>  compose=[/home/john/kalabox/apps/fiksu/kalabox-compose.yml, /home/john/kalabox/apps/fiksu/kalabox-cli.yml], project=fiksu, mode=attach, services=[cli], entrypoint=kgit, cmd=[push, origin, zendesk]
info: COMPOSE =>  0=--project-name, 1=fiksu, 2=--file, 3=/home/john/kalabox/apps/fiksu/kalabox-compose.yml, 4=--file, 5=/home/john/kalabox/apps/fiksu/kalabox-cli.yml, 6=run, 7=-d, 8=--entrypoint, 9=tail, 10=cli, 11=-f, 12=/dev/null, mode=false
Warning: Permanently added '[codeserver.dev.c488d6fa-122a-58ca-f2b4-2f4949a4facb.drush.in]:2222,[192.237.160.128]:2222' (RSA) to the list of known hosts.
Counting objects: 1, done.
Writing objects: 100% (1/1), 181 bytes | 0 bytes/s, done.
Total 1 (delta 0), reused 0 (delta 0)
To ssh://codeserver.dev.c488d6fa-122a-58ca-f2b4-2f4949a4facb@codeserver.dev.c488d6fa-122a-58ca-f2b4-2f4949a4facb.drush.in:2222/~/repository.git
   78381a7..a0a8b3a  zendesk -> zendesk
info: TERMINUS =>  Run definition:  compose=[/home/john/kalabox/apps/fiksu/kalabox-compose.yml, /home/john/kalabox/apps/fiksu/kalabox-cli.yml], project=fiksu, services=[terminus], mode=collect, entrypoint=[bash, --login, -c], cmd=[terminus, site, set-connection-mode, --format=json, --site=fiksu, --env=zendesk, --mode=sftp]
info: COMPOSE =>  0=--project-name, 1=fiksu, 2=--file, 3=/home/john/kalabox/apps/fiksu/kalabox-compose.yml, 4=--file, 5=/home/john/kalabox/apps/fiksu/kalabox-cli.yml, 6=run, 7=-d, 8=--entrypoint, 9=tail, 10=terminus, 11=-f, 12=/dev/null, mode=false
info: TERMINUS =>  Run returned: 
info: COMPOSE =>  0=--project-name, 1=fiksu, 2=--file, 3=/home/john/kalabox/apps/fiksu/kalabox-compose.yml, 4=--file, 5=/home/john/kalabox/apps/fiksu/kalabox-cli.yml, 6=run, 7=-d, 8=--entrypoint, 9=tail, 10=db, 11=-f, 12=/dev/null, mode=false
info: TERMINUS =>  Run definition:  compose=[/home/john/kalabox/apps/fiksu/kalabox-compose.yml, /home/john/kalabox/apps/fiksu/kalabox-cli.yml], project=fiksu, services=[terminus], mode=collect, entrypoint=[bash, --login, -c], cmd=[terminus, site, connection-info, --format=json, --site=fiksu, --env=zendesk]
info: COMPOSE =>  0=--project-name, 1=fiksu, 2=--file, 3=/home/john/kalabox/apps/fiksu/kalabox-compose.yml, 4=--file, 5=/home/john/kalabox/apps/fiksu/kalabox-cli.yml, 6=run, 7=-d, 8=--entrypoint, 9=tail, 10=terminus, 11=-f, 12=/dev/null, mode=false
info: TERMINUS =>  Run returned: 
Cannot read property 'mysql_command' of undefined
TypeError: Cannot read property 'mysql_command' of undefined
    at /home/john/kalabox/apps/fiksu/plugins/kalabox-plugin-pantheon/lib/push.js:130:37
From previous event:
    at Object.pushDB (/home/john/kalabox/apps/fiksu/plugins/kalabox-plugin-pantheon/lib/push.js:123:6)
    at /home/john/kalabox/apps/fiksu/plugins/kalabox-plugin-pantheon/lib/tasks.js:357:29
    at process._tickCallback (node.js:803:1)
From previous event:
    at null.completed (/home/john/kalabox/apps/fiksu/plugins/kalabox-plugin-pantheon/lib/tasks.js:355:12)
    at PromptUI.onCompletion (/home/john/kalabox/apps/fiksu/node_modules/inquirer/lib/ui/prompt.js:56:10)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (/home/john/kalabox/apps/fiksu/node_modules/rx-lite/rx.lite.js:1826:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/home/john/kalabox/apps/fiksu/node_modules/rx-lite/rx.lite.js:1763:14)
    at AnonymousObserver.tryCatcher (/home/john/kalabox/apps/fiksu/node_modules/rx-lite/rx.lite.js:537:29)
    at AutoDetachObserverPrototype.completed (/home/john/kalabox/apps/fiksu/node_modules/rx-lite/rx.lite.js:5435:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/home/john/kalabox/apps/fiksu/node_modules/rx-lite/rx.lite.js:1763:14)
    at InnerObserver.onCompleted (/home/john/kalabox/apps/fiksu/node_modules/rx-lite/rx.lite.js:2885:65)
    at InnerObserver.tryCatcher (/home/john/kalabox/apps/fiksu/node_modules/rx-lite/rx.lite.js:537:29)
    at AutoDetachObserverPrototype.completed (/home/john/kalabox/apps/fiksu/node_modules/rx-lite/rx.lite.js:5435:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/home/john/kalabox/apps/fiksu/node_modules/rx-lite/rx.lite.js:1763:14)
    at AutoDetachObserver.tryCatcher (/home/john/kalabox/apps/fiksu/node_modules/rx-lite/rx.lite.js:537:29)
    at AutoDetachObserverPrototype.completed (/home/john/kalabox/apps/fiksu/node_modules/rx-lite/rx.lite.js:5435:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/home/john/kalabox/apps/fiksu/node_modules/rx-lite/rx.lite.js:1763:14)
    at InnerObserver.onCompleted (/home/john/kalabox/apps/fiksu/node_modules/rx-lite/rx.lite.js:2885:65)
    at InnerObserver.tryCatcher (/home/john/kalabox/apps/fiksu/node_modules/rx-lite/rx.lite.js:537:29)
    at AutoDetachObserverPrototype.completed (/home/john/kalabox/apps/fiksu/node_modules/rx-lite/rx.lite.js:5435:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/home/john/kalabox/apps/fiksu/node_modules/rx-lite/rx.lite.js:1763:14)
    at AutoDetachObserver.tryCatcher (/home/john/kalabox/apps/fiksu/node_modules/rx-lite/rx.lite.js:537:29)
```

**Comment by pirog** [comment]
Fairly sure this is a terminus bug that will be resolved in their latest release
https://github.com/pantheon-systems/terminus/issues/910

If i run `terminus site connection-info --format=json --site=fiksu --env=zendesk` using terminus 0.10.3 i get the correct response. What do you get when you run `kbox terminus site connection-info --format=json --site=fiksu --env=zendesk`?

**Comment by pirog** [comment]
As a workaround you can go into your `kalabox-cli.yml` and edit the terminus image to be

```
  image: kalabox/terminus:dev
```

Then `kbox rebuild`

**Comment by labboy0276** [comment]
Hello!

I get this weird message, also asks me to log in?

```
john@kalamuna:~/kalabox/apps/fiksu/code$ kbox terminus site connection-info --format=json --site=fiksu --env=zendesk
info: COMPOSE =>  0=--project-name, 1=fiksu, 2=--file, 3=/home/john/kalabox/apps/fiksu/kalabox-compose.yml, 4=--file, 5=/home/john/kalabox/apps/fiksu/kalabox-cli.yml, 6=--file, 7=/home/john/kalabox/apps/fiksu/kalabox-cli.yml, 8=run, 9=-d, 10=--entrypoint, 11=tail, 12=terminus, 13=-f, 14=/dev/null, mode=false
PHP Warning:  unlink(/root/.terminus/cache/session): Device or resource busy in phar:///usr/local/bin/terminus/php/Terminus/FileCache.php on line 91
PHP Stack trace:
PHP   1. {main}() /usr/local/bin/terminus:0
PHP   2. include() /usr/local/bin/terminus:4
PHP   3. include() phar:///usr/local/bin/terminus/php/boot-phar.php:4
PHP   4. Terminus\Runner->run() phar:///usr/local/bin/terminus/php/boot-cl.php:26
PHP   5. Terminus\Runner->_runCommand() phar:///usr/local/bin/terminus/php/Terminus/Runner.php:151
PHP   6. Terminus\Runner->runCommand() phar:///usr/local/bin/terminus/php/Terminus/Runner.php:185
PHP   7. Terminus\Dispatcher\Subcommand->invoke() phar:///usr/local/bin/terminus/php/Terminus/Runner.php:167
PHP   8. call_user_func:{phar:///usr/local/bin/terminus/php/Terminus/Dispatcher/Subcommand.php:117}() phar:///usr/local/bin/terminus/php/Terminus/Dispatcher/Subcommand.php:117
PHP   9. Terminus\Dispatcher\CommandFactory::Terminus\Dispatcher\{closure}() phar:///usr/local/bin/terminus/php/Terminus/Dispatcher/Subcommand.php:117
PHP  10. Terminus\Commands\SiteCommand->__construct() phar:///usr/local/bin/terminus/php/Terminus/Dispatcher/CommandFactory.php:97
PHP  11. Terminus\Auth::ensureLogin() phar:///usr/local/bin/terminus/php/Terminus/Commands/SiteCommand.php:25
PHP  12. Terminus\Session::instance() phar:///usr/local/bin/terminus/php/Terminus/Auth.php:41
PHP  13. Terminus\Session->__construct() phar:///usr/local/bin/terminus/php/Terminus/Session.php:92
PHP  14. Terminus::getCache() phar:///usr/local/bin/terminus/php/Terminus/Session.php:23
PHP  15. Terminus\FileCache->clean() phar:///usr/local/bin/terminus/php/Terminus.php:121
PHP  16. unlink() phar:///usr/local/bin/terminus/php/Terminus/FileCache.php:91

Warning: unlink(/root/.terminus/cache/session): Device or resource busy in phar:///usr/local/bin/terminus/php/Terminus/FileCache.php on line 91

Call Stack:
    0.0243     257008   1. {main}() /usr/local/bin/terminus:0
    0.0652     776360   2. include('phar:///usr/local/bin/terminus/php/boot-phar.php') /usr/local/bin/terminus:4
    0.0654     786464   3. include('phar:///usr/local/bin/terminus/php/boot-cl.php') phar:///usr/local/bin/terminus/php/boot-phar.php:4
    0.1022    2028672   4. Terminus\Runner->run() phar:///usr/local/bin/terminus/php/boot-cl.php:26
    0.1335    2736392   5. Terminus\Runner->_runCommand() phar:///usr/local/bin/terminus/php/Terminus/Runner.php:151
    0.1335    2736576   6. Terminus\Runner->runCommand() phar:///usr/local/bin/terminus/php/Terminus/Runner.php:185
    0.1336    2737408   7. Terminus\Dispatcher\Subcommand->invoke() phar:///usr/local/bin/terminus/php/Terminus/Runner.php:167
    0.1349    2800768   8. call_user_func:{phar:///usr/local/bin/terminus/php/Terminus/Dispatcher/Subcommand.php:117}() phar:///usr/local/bin/terminus/php/Terminus/Dispatcher/Subcommand.php:117
    0.1349    2800832   9. Terminus\Dispatcher\CommandFactory::Terminus\Dispatcher\{closure}() phar:///usr/local/bin/terminus/php/Terminus/Dispatcher/Subcommand.php:117
    0.1349    2801064  10. Terminus\Commands\SiteCommand->__construct() phar:///usr/local/bin/terminus/php/Terminus/Dispatcher/CommandFactory.php:97
    0.1355    2847248  11. Terminus\Auth::ensureLogin() phar:///usr/local/bin/terminus/php/Terminus/Commands/SiteCommand.php:25
    0.1357    2868488  12. Terminus\Session::instance() phar:///usr/local/bin/terminus/php/Terminus/Auth.php:41
    0.1357    2868720  13. Terminus\Session->__construct() phar:///usr/local/bin/terminus/php/Terminus/Session.php:92
    0.1357    2868792  14. Terminus::getCache() phar:///usr/local/bin/terminus/php/Terminus/Session.php:23
    0.1365    2938928  15. Terminus\FileCache->clean() phar:///usr/local/bin/terminus/php/Terminus.php:121
    0.1641    3218824  16. unlink() phar:///usr/local/bin/terminus/php/Terminus/FileCache.php:91

PHP Warning:  unlink(/root/.terminus/cache/session): Device or resource busy in phar:///usr/local/bin/terminus/php/Terminus/FileCache.php on line 210
PHP Stack trace:
PHP   1. {main}() /usr/local/bin/terminus:0
PHP   2. include() /usr/local/bin/terminus:4
PHP   3. include() phar:///usr/local/bin/terminus/php/boot-phar.php:4
PHP   4. Terminus\Runner->run() phar:///usr/local/bin/terminus/php/boot-cl.php:26
PHP   5. Terminus\Runner->_runCommand() phar:///usr/local/bin/terminus/php/Terminus/Runner.php:151
PHP   6. Terminus\Runner->runCommand() phar:///usr/local/bin/terminus/php/Terminus/Runner.php:185
PHP   7. Terminus\Dispatcher\Subcommand->invoke() phar:///usr/local/bin/terminus/php/Terminus/Runner.php:167
PHP   8. call_user_func:{phar:///usr/local/bin/terminus/php/Terminus/Dispatcher/Subcommand.php:117}() phar:///usr/local/bin/terminus/php/Terminus/Dispatcher/Subcommand.php:117
PHP   9. Terminus\Dispatcher\CommandFactory::Terminus\Dispatcher\{closure}() phar:///usr/local/bin/terminus/php/Terminus/Dispatcher/Subcommand.php:117
PHP  10. Terminus\Commands\SiteCommand->__construct() phar:///usr/local/bin/terminus/php/Terminus/Dispatcher/CommandFactory.php:97
PHP  11. Terminus\Auth::ensureLogin() phar:///usr/local/bin/terminus/php/Terminus/Commands/SiteCommand.php:25
PHP  12. Terminus\Session::instance() phar:///usr/local/bin/terminus/php/Terminus/Auth.php:41
PHP  13. Terminus\Session->__construct() phar:///usr/local/bin/terminus/php/Terminus/Session.php:92
PHP  14. Terminus\FileCache->getData() phar:///usr/local/bin/terminus/php/Terminus/Session.php:24
PHP  15. Terminus\FileCache->read() phar:///usr/local/bin/terminus/php/Terminus/FileCache.php:162
PHP  16. Terminus\FileCache->has() phar:///usr/local/bin/terminus/php/Terminus/FileCache.php:265
PHP  17. unlink() phar:///usr/local/bin/terminus/php/Terminus/FileCache.php:210

Warning: unlink(/root/.terminus/cache/session): Device or resource busy in phar:///usr/local/bin/terminus/php/Terminus/FileCache.php on line 210

Call Stack:
    0.0243     257008   1. {main}() /usr/local/bin/terminus:0
    0.0652     776360   2. include('phar:///usr/local/bin/terminus/php/boot-phar.php') /usr/local/bin/terminus:4
    0.0654     786464   3. include('phar:///usr/local/bin/terminus/php/boot-cl.php') phar:///usr/local/bin/terminus/php/boot-phar.php:4
    0.1022    2028672   4. Terminus\Runner->run() phar:///usr/local/bin/terminus/php/boot-cl.php:26
    0.1335    2736392   5. Terminus\Runner->_runCommand() phar:///usr/local/bin/terminus/php/Terminus/Runner.php:151
    0.1335    2736576   6. Terminus\Runner->runCommand() phar:///usr/local/bin/terminus/php/Terminus/Runner.php:185
    0.1336    2737408   7. Terminus\Dispatcher\Subcommand->invoke() phar:///usr/local/bin/terminus/php/Terminus/Runner.php:167
    0.1349    2800768   8. call_user_func:{phar:///usr/local/bin/terminus/php/Terminus/Dispatcher/Subcommand.php:117}() phar:///usr/local/bin/terminus/php/Terminus/Dispatcher/Subcommand.php:117
    0.1349    2800832   9. Terminus\Dispatcher\CommandFactory::Terminus\Dispatcher\{closure}() phar:///usr/local/bin/terminus/php/Terminus/Dispatcher/Subcommand.php:117
    0.1349    2801064  10. Terminus\Commands\SiteCommand->__construct() phar:///usr/local/bin/terminus/php/Terminus/Dispatcher/CommandFactory.php:97
    0.1355    2847248  11. Terminus\Auth::ensureLogin() phar:///usr/local/bin/terminus/php/Terminus/Commands/SiteCommand.php:25
    0.1357    2868488  12. Terminus\Session::instance() phar:///usr/local/bin/terminus/php/Terminus/Auth.php:41
    0.1357    2868720  13. Terminus\Session->__construct() phar:///usr/local/bin/terminus/php/Terminus/Session.php:92
    0.1842    3230824  14. Terminus\FileCache->getData() phar:///usr/local/bin/terminus/php/Terminus/Session.php:24
    0.1842    3231752  15. Terminus\FileCache->read() phar:///usr/local/bin/terminus/php/Terminus/FileCache.php:162
    0.1842    3231952  16. Terminus\FileCache->has() phar:///usr/local/bin/terminus/php/Terminus/FileCache.php:265
    0.1846    3232248  17. unlink() phar:///usr/local/bin/terminus/php/Terminus/FileCache.php:210

{"date":"2016-02-17 18:00:49","level":"WARNING","message":"You are not logged in. Run `auth login` to authenticate or `help auth login` for more info."}
```

**Comment by pirog** [comment]
Is that after you upgraded or before?

**Comment by labboy0276** [comment]
before, after i upgraded, it did this:

```
john@kalamuna:~/kalabox/apps/fiksu/code$ kbox terminus cli version
info: COMPOSE =>  0=--project-name, 1=fiksu, 2=--file, 3=/home/john/kalabox/apps/fiksu/kalabox-compose.yml, 4=--file, 5=/home/john/kalabox/apps/fiksu/kalabox-cli.yml, 6=--file, 7=/home/john/kalabox/apps/fiksu/kalabox-cli.yml, 8=run, 9=-d, 10=--entrypoint, 11=tail, 12=terminus, 13=-f, 14=/dev/null, mode=false
[2016-02-17 18:11:36] [info] API Request Error: {msg}
[2016-02-17 18:11:36] [info] Cannot retrieve current Terminus version.
+------------------+----------+
| Key              | Value    |
+------------------+----------+
| Terminus version | 0.10.3   |
| Terminus script  | terminus |
+------------------+----------+
john@kalamuna:~/kalabox/apps/fiksu/code$ kbox terminus site connection-info --format=json --site=fiksu --env=zendesk
info: COMPOSE =>  0=--project-name, 1=fiksu, 2=--file, 3=/home/john/kalabox/apps/fiksu/kalabox-compose.yml, 4=--file, 5=/home/john/kalabox/apps/fiksu/kalabox-cli.yml, 6=--file, 7=/home/john/kalabox/apps/fiksu/kalabox-cli.yml, 8=run, 9=-d, 10=--entrypoint, 11=tail, 12=terminus, 13=-f, 14=/dev/null, mode=false
{"date":"2016-02-17 18:11:50","level":"INFO","message":"API Request Error: {msg}"}
{"date":"2016-02-17 18:11:50","level":"INFO","message":"Cannot retrieve current Terminus version."}
{"sftp_username":"zendesk.c488d6fa-122a-58ca-f2b4-2f4949a4facb","sftp_host":"appserver.zendesk.c488d6fa-122a-58ca-f2b4-2f4949a4facb.drush.in","sftp_password":"Use your account password","sftp_url":"sftp:\/\/zendesk.c488d6fa-122a-58ca-f2b4-2f4949a4facb@appserver.zendesk.c488d6fa-122a-58ca-f2b4-2f4949a4facb.drush.in:2222","sftp_command":"sftp -o Port=2222 zendesk.c488d6fa-122a-58ca-f2b4-2f4949a4facb@appserver.zendesk.c488d6fa-122a-58ca-f2b4-2f4949a4facb.drush.in","git_username":"codeserver.dev.c488d6fa-122a-58ca-f2b4-2f4949a4facb","git_host":"codeserver.dev.c488d6fa-122a-58ca-f2b4-2f4949a4facb.drush.in","git_port":2222,"git_url":"ssh:\/\/codeserver.dev.c488d6fa-122a-58ca-f2b4-2f4949a4facb@codeserver.dev.c488d6fa-122a-58ca-f2b4-2f4949a4facb.drush.in:2222\/~\/repository.git","git_command":"git clone ssh:\/\/codeserver.dev.c488d6fa-122a-58ca-f2b4-2f4949a4facb@codeserver.dev.c488d6fa-122a-58ca-f2b4-2f4949a4facb.drush.in:2222\/~\/repository.git fiksu","mysql_host":"dbserver.zendesk.c488d6fa-122a-58ca-f2b4-2f4949a4facb.drush.in","mysql_username":"pantheon","mysql_password":"a8db7fea3e3641529e6a737c7d521128","mysql_port":14075,"mysql_database":"pantheon","mysql_url":"mysql:\/\/pantheon:a8db7fea3e3641529e6a737c7d521128@dbserver.zendesk.c488d6fa-122a-58ca-f2b4-2f4949a4facb.drush.in:14075\/pantheon","mysql_command":"mysql -u pantheon -pa8db7fea3e3641529e6a737c7d521128 -h dbserver.zendesk.c488d6fa-122a-58ca-f2b4-2f4949a4facb.drush.in -P 14075 pantheon","redis_password":"33952a58bb52452aad51c65e901f63ab","redis_host":"104.130.221.103","redis_port":12004,"redis_url":"redis:\/\/pantheon:33952a58bb52452aad51c65e901f63ab@104.130.221.103:12004","redis_command":"redis-cli -h 104.130.221.103 -p 12004 -a 33952a58bb52452aad51c65e901f63ab"}john@kalamuna:~/kalabox/apps/fiksu/code$ 
```

= you win

**Comment by pirog** [comment]
You probably don't want to post connection strings to kalamuna clients on a
public GitHub issue
