### ISSUE TITLE
Better document where the uncommitted changes are on kbox push

### ISSUE THREAD

**Issue by macronomicus** [kalabox/kalabox#1036]
Im not sure what leads to the issue but after some days of using an app kbox push stops working, giving the error below.  When I check on pantheon there are no outstanding changes to commit, im the only one working on the site so nobody else has added anything either.  Im not certain because the kbox error isnt saying, but it seems git is out of sync.
Im using kbox version 0.11.2 on Windows 10.
This happened a couple times before, the only thing I found to quickly fix it was use git to force push all my local code changes up and then destroy and rebuild my local app again.  Am I missing something simple that's a preferred solution? Or is this a bug?  Even after using git to force my local code up Im not able to have the local site kbox push or kbox pull, thats why I ended up doing a destroy and fresh create.

--------------------------------------------------------------------------------
Joshua@MEEP /C/Users/Joshua/kalabox/apps/thewebsite
$ kbox push
? Tell us about your changes testing kalabox
? Which env do you want to push the DB to? dev
? Which env do you want to push the files to? dev
info: TERMINUS =>  Run definition:  compose=[c:\Users\Joshua\kalabox\apps\thewebsite\kalabox-compose.yml, c:\Users\Joshua\kalabox\apps\thewebsite\kalabox-cli.yml], project=thewebsite, services=[terminus], mode=collect, entrypoint=[bash, --login, -c], cmd=[terminus, site, environment-info, --format=json, --site=plasma-health, --env=dev]
info: COMPOSE =>  0=--project-name, 1=thewebsite, 2=--file, 3=c:\Users\Joshua\kalabox\apps\thewebsite\kalabox-compose.yml, 4=--file, 5=c:\Users\Joshua\kalabox\apps\thewebsite\kalabox-cli.yml, 6=run, 7=-d, 8=--entrypoint, 9=tail, 10=terminus, 11=-f, 12=/dev/null, mode=false
info: TERMINUS =>  Run returned:  data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now
info: TERMINUS =>  Run definition:  compose=[c:\Users\Joshua\kalabox\apps\thewebsite\kalabox-compose.yml, c:\Users\Joshua\kalabox\apps\thewebsite\kalabox-cli.yml], project=thewebsite, services=[terminus], mode=collect, entrypoint=[bash, --login, -c], cmd=[terminus, site, code, diffstat, --format=json, --site=plasma-health, --env=dev]
info: COMPOSE =>  0=--project-name, 1=thewebsite, 2=--file, 3=c:\Users\Joshua\kalabox\apps\thewebsite\kalabox-compose.yml, 4=--file, 5=c:\Users\Joshua\kalabox\apps\thewebsite\kalabox-cli.yml, 6=run, 7=-d, 8=--entrypoint, 9=tail, 10=terminus, 11=-f, 12=/dev/null, mode=false
info: TERMINUS =>  Run returned:  data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now, data=now
Kalabox has detected you have uncommitted changes. Please commit those changes and try kbox push again
Error: Kalabox has detected you have uncommitted changes. Please commit those changes and try kbox push again
    at c:\Users\Joshua\kalabox\apps\thewebsite\plugins\kalabox-plugin-pantheon\lib\push.js:39:19
From previous event:
    at terminus.getConnectionMode.tap.tap.tap.git (c:\Users\Joshua\kalabox\apps\thewebsite\plugins\kalabox-plugin-pantheon\lib\push.js:32:10)
From previous event:
    at Object.pushCode (c:\Users\Joshua\kalabox\apps\thewebsite\plugins\kalabox-plugin-pantheon\lib\push.js:26:6)
    at c:\Users\Joshua\kalabox\apps\thewebsite\plugins\kalabox-plugin-pantheon\lib\tasks.js:342:27
    at process._tickCallback (node.js:803:1)
From previous event:
    at null.completed (c:\Users\Joshua\kalabox\apps\thewebsite\plugins\kalabox-plugin-pantheon\lib\tasks.js:341:12)
    at PromptUI.onCompletion (c:\Users\Joshua\kalabox\apps\thewebsite\node_modules\inquirer\lib\ui\prompt.js:56:10)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (c:\Users\Joshua\kalabox\apps\thewebsite\node_modules\rx-lite\rx.lite.js:1826:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (c:\Users\Joshua\kalabox\apps\thewebsite\node_modules\rx-lite\rx.lite.js:1763:14)
    at AnonymousObserver.tryCatcher (c:\Users\Joshua\kalabox\apps\thewebsite\node_modules\rx-lite\rx.lite.js:537:29)
    at AutoDetachObserverPrototype.completed (c:\Users\Joshua\kalabox\apps\thewebsite\node_modules\rx-lite\rx.lite.js:5435:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (c:\Users\Joshua\kalabox\apps\thewebsite\node_modules\rx-lite\rx.lite.js:1763:14)
    at InnerObserver.onCompleted (c:\Users\Joshua\kalabox\apps\thewebsite\node_modules\rx-lite\rx.lite.js:2885:65)
    at InnerObserver.tryCatcher (c:\Users\Joshua\kalabox\apps\thewebsite\node_modules\rx-lite\rx.lite.js:537:29)
    at AutoDetachObserverPrototype.completed (c:\Users\Joshua\kalabox\apps\thewebsite\node_modules\rx-lite\rx.lite.js:5435:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (c:\Users\Joshua\kalabox\apps\thewebsite\node_modules\rx-lite\rx.lite.js:1763:14)
    at AutoDetachObserver.tryCatcher (c:\Users\Joshua\kalabox\apps\thewebsite\node_modules\rx-lite\rx.lite.js:537:29)
    at AutoDetachObserverPrototype.completed (c:\Users\Joshua\kalabox\apps\thewebsite\node_modules\rx-lite\rx.lite.js:5435:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (c:\Users\Joshua\kalabox\apps\thewebsite\node_modules\rx-lite\rx.lite.js:1763:14)
    at InnerObserver.onCompleted (c:\Users\Joshua\kalabox\apps\thewebsite\node_modules\rx-lite\rx.lite.js:2885:65)
    at InnerObserver.tryCatcher (c:\Users\Joshua\kalabox\apps\thewebsite\node_modules\rx-lite\rx.lite.js:537:29)
    at AutoDetachObserverPrototype.completed (c:\Users\Joshua\kalabox\apps\thewebsite\node_modules\rx-lite\rx.lite.js:5435:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (c:\Users\Joshua\kalabox\apps\thewebsite\node_modules\rx-lite\rx.lite.js:1763:14)
    at AutoDetachObserver.tryCatcher (c:\Users\Joshua\kalabox\apps\thewebsite\node_modules\rx-lite\rx.lite.js:537:29)

**Comment by pirog** [comment]
@macronomicus this is designed to stop you from overwriting any uncommitted changes you might have on pantheon. That said this looks like a bug that was fixed and is slotted for the v0.11.3 release. 

If you'd like to manually update your code in the meantime i think this is the relevant diff
https://github.com/kalabox/kalabox-app-pantheon/commit/ea86b39c8e8fd65920b5a81c696df96e42dd5ab4

**Comment by macronomicus** [comment]
Ahhh, awesome man, I will try that shortly.  Thanks for the help.

**Comment by macronomicus** [comment]
Yes that did the trick for me, combined with #1035 im going strong again here, thanks for the pointer and for kalabox, love it!
