### ISSUE TITLE
Error when cloning new site or trying to push files on existing site

### ISSUE THREAD

**Issue by bmcclure** [kalabox/kalabox#1107]
(Note that this is on a different machine than the other issue I just created, since with that issue I can't get an environment set up at all)

This is on Windows 10 64-bit running the latest kbox.exe release. Everything seems to have been working fine, and kbox wasn't updated or changed to my knowledge, but suddenly as of yesterday when trying to push changed files up to Pantheon, or when trying to create a new site from Pantheon, the following error is received from kbox.exe:

```
Cannot read property 'id' of undefined
TypeError: Cannot read property 'id' of undefined
   at C:\Users\dev\site\plugins\kalabox-plugin-pantheon\lib\terminus.js:265:24
From previous event:
   at Terminus.getUUID (C:\Users\dev\site\plugins\kalabox-plugin-pantheon\lib\terminus.js:264:4)
   at Object.pushFiles (C:\Users\dev\site\plugins\kalabox-plugin-pantheon\lib\push.js:157:21)
   at C:\Users\dev\site\plugins\kalabox-plugin-pantheon\lib\tasks.js:364:29
   at process._tickCallback (node.js:803:1)
From previous event:
   at null.completed (C:\Users\dev\site\plugins\kalabox-plugin-pantheon\lib\tasks.js:362:12)
   at PromptUI.onCompletion (C:\Users\dev\site\node_modules\inquirer\lib\ui\prompt.js:56:10)
   at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (C:\Users\dev\site\node_modules\rx-lite\rx.lite.js:1826:12)
   at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (C:\Users\dev\site\node_modules\rx-lite\rx.lite.js:1763:14)
   at AnonymousObserver.tryCatcher (C:\Users\dev\site\node_modules\rx-lite\rx.lite.js:537:29)
   at AutoDetachObserverPrototype.completed (C:\Users\dev\site\node_modules\rx-lite\rx.lite.js:5435:56)
   at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (C:\Users\dev\site\node_modules\rx-lite\rx.lite.js:1763:14)
   at InnerObserver.onCompleted (C:\Users\dev\site\node_modules\rx-lite\rx.lite.js:2885:65)
   at InnerObserver.tryCatcher (C:\Users\dev\site\node_modules\rx-lite\rx.lite.js:537:29)
   at AutoDetachObserverPrototype.completed (C:\Users\dev\site\node_modules\rx-lite\rx.lite.js:5435:56)
   at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (C:\Users\dev\site\node_modules\rx-lite\rx.lite.js:1763:14)
   at AutoDetachObserver.tryCatcher (C:\Users\dev\site\node_modules\rx-lite\rx.lite.js:537:29)
   at AutoDetachObserverPrototype.completed (C:\Users\dev\site\node_modules\rx-lite\rx.lite.js:5435:56)
   at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (C:\Users\dev\site\node_modules\rx-lite\rx.lite.js:1763:14)
   at InnerObserver.onCompleted (C:\Users\dev\site\node_modules\rx-lite\rx.lite.js:2885:65)
   at InnerObserver.tryCatcher (C:\Users\dev\site\node_modules\rx-lite\rx.lite.js:537:29)
   at AutoDetachObserverPrototype.completed (C:\Users\dev\site\node_modules\rx-lite\rx.lite.js:5435:56)
   at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (C:\Users\dev\site\node_modules\rx-lite\rx.lite.js:1763:14)
   at AutoDetachObserver.tryCatcher (C:\Users\dev\site\node_modules\rx-lite\rx.lite.js:537:29)
```

Additionally, when trying to push database back up to Pantheon, the following error is received from kbox.exe:

```
TypeError: Cannot read property 'mysql_command' of undefined
   at C:\Users\dev\site\plugins\kalabox-plugin-pantheon\lib\push.js:135:37
From previous event:
   at Object.pushDB (C:\Users\dev\site\plugins\kalabox-plugin-pantheon\lib\push.js:128:6)
   at C:\Users\dev\site\plugins\kalabox-plugin-pantheon\lib\tasks.js:357:29
   at process._tickCallback (node.js:803:1)
From previous event:
   at null.completed (C:\Users\dev\site\plugins\kalabox-plugin-pantheon\lib\tasks.js:355:12)
   at PromptUI.onCompletion (C:\Users\dev\site\node_modules\inquirer\lib\ui\prompt.js:56:10)
   at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (C:\Users\dev\site\node_modules\rx-lite\rx.lite.js:1826:12)
   at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (C:\Users\dev\site\node_modules\rx-lite\rx.lite.js:1763:14)
   at AnonymousObserver.tryCatcher (C:\Users\dev\site\node_modules\rx-lite\rx.lite.js:537:29)
   at AutoDetachObserverPrototype.completed (C:\Users\dev\site\node_modules\rx-lite\rx.lite.js:5435:56)
   at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (C:\Users\dev\site\node_modules\rx-lite\rx.lite.js:1763:14)
   at InnerObserver.onCompleted (C:\Users\dev\site\node_modules\rx-lite\rx.lite.js:2885:65)
   at InnerObserver.tryCatcher (C:\Users\dev\site\node_modules\rx-lite\rx.lite.js:537:29)
   at AutoDetachObserverPrototype.completed (C:\Users\dev\site\node_modules\rx-lite\rx.lite.js:5435:56)
   at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (C:\Users\dev\site\node_modules\rx-lite\rx.lite.js:1763:14)
   at AutoDetachObserver.tryCatcher (C:\Users\dev\site\node_modules\rx-lite\rx.lite.js:537:29)
   at AutoDetachObserverPrototype.completed (C:\Users\dev\site\node_modules\rx-lite\rx.lite.js:5435:56)
   at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (C:\Users\dev\site\node_modules\rx-lite\rx.lite.js:1763:14)
   at InnerObserver.onCompleted (C:\Users\dev\site\node_modules\rx-lite\rx.lite.js:2885:65)
   at InnerObserver.tryCatcher (C:\Users\dev\site\node_modules\rx-lite\rx.lite.js:537:29)
   at AutoDetachObserverPrototype.completed (C:\Users\dev\site\node_modules\rx-lite\rx.lite.js:5435:56)
   at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (C:\Users\dev\site\node_modules\rx-lite\rx.lite.js:1763:14)
   at AutoDetachObserver.tryCatcher (C:\Users\dev\site\node_modules\rx-lite\rx.lite.js:537:29)
```

**Comment by pirog** [comment]
If you didnt change kalabox the most likely explanation is that terminus, which we use to get information from pantheon about your site, is not able to retrieve this information. this could happen if your internet connection is down or if pantheon is having issues on their end.
