### ISSUE TITLE
(node) warning: possible EventEmitter memory leak detected (alpha3)

### ISSUE THREAD

**Issue by jdleonard** [kalabox/kalabox#1252]
1. Fresh install of alpha3 on OS X 10.11.4 (15E65).
2. `kbox create pantheon`
3. Follow the prompts.
4. Site is successfully created and is functional, but this warning is shown:
<pre>
...
files_dev/skipped.log
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at ReadStream.addListener (events.js:140:15)
    at ReadStream.Stream.pipe (stream.js:96:10)
    at /usr/local/bin/plugins/kalabox-engine-docker/provider/docker/docker.js.jx:334:25
    at tryCatcher (/usr/local/bin/node_modules/bluebird/js/main/util.js.jx:25:23)
    at Promise._settlePromiseFromHandler (/usr/local/bin/node_modules/bluebird/js/main/promise.js.jx:506:31)
    at Promise._settlePromiseAt (/usr/local/bin/node_modules/bluebird/js/main/promise.js.jx:580:18)
    at Promise._settlePromises (/usr/local/bin/node_modules/bluebird/js/main/promise.js.jx:696:14)
    at Async._drainQueue (/usr/local/bin/node_modules/bluebird/js/main/async.js.jx:122:16)
    at Async._drainQueues (/usr/local/bin/node_modules/bluebird/js/main/async.js.jx:132:10)
    at Async.drainQueues (/usr/local/bin/node_modules/bluebird/js/main/async.js.jx:14:14)
    at process._tickCallback (node.js:917:13)
The registry has been rebuilt via registry_rebuild (A). 
...
</pre>

**Comment by pirog** [comment]
@jdleonard does this interfere with anything or is it just a warning?

**Comment by jdleonard** [comment]
To the best of my knowledge, just a warning.

**Comment by pirog** [comment]
Closing this in favor of #1368
