### ISSUE TITLE
Add additional services (python, etc.) to make CLI container more robust

### ISSUE THREAD

**Issue by reynoldsalec** [kalabox/kalabox#1261]
**Story**
As a PHP developer with a workflow that includes npm-powered build tools, I want to be able to easily run my build workflow using Kalabox's containerized virtual environment so I don't need to worry about local dependency issues for myself and my teammates.

**Current issue**
On Kalabox v0.12.0-alpha3, if you try to use `kbox npm install` to download any dependency which uses node-gyp to build it, installation will fail since the kalabox/cli container doesn't include python. 

**Replicate**

1. Download a site that has a build tool downloaded via NPM (Greenbiz works well)
2. Run `kbox npm install`
3. If you have node-sass or another common dependency built via node-gyp, you should receive an error similar to:

```
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at F (/code/sites/all/themes/greenbiz/node_modules/grunt-sass/node_modules/node-sass/node_modules/node-gyp/node_modules/which/which.js:63:19)
gyp verb `which` failed     at E (/code/sites/all/themes/greenbiz/node_modules/grunt-sass/node_modules/node-sass/node_modules/node-gyp/node_modules/which/which.js:72:29)
gyp verb `which` failed     at /code/sites/all/themes/greenbiz/node_modules/grunt-sass/node_modules/node-sass/node_modules/node-gyp/node_modules/which/which.js:81:16
gyp verb `which` failed     at /code/sites/all/themes/greenbiz/node_modules/grunt-sass/node_modules/node-sass/node_modules/node-gyp/node_modules/which/node_modules/isexe/index.js:44:5
gyp verb `which` failed     at /code/sites/all/themes/greenbiz/node_modules/grunt-sass/node_modules/node-sass/node_modules/node-gyp/node_modules/which/node_modules/isexe/access.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:82:15)
gyp verb `which` failed  python2 [Error: not found: python2]
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at F (/code/sites/all/themes/greenbiz/node_modules/grunt-sass/node_modules/node-sass/node_modules/node-gyp/node_modules/which/which.js:63:19)
gyp verb `which` failed     at E (/code/sites/all/themes/greenbiz/node_modules/grunt-sass/node_modules/node-sass/node_modules/node-gyp/node_modules/which/which.js:72:29)
gyp verb `which` failed     at /code/sites/all/themes/greenbiz/node_modules/grunt-sass/node_modules/node-sass/node_modules/node-gyp/node_modules/which/which.js:81:16
gyp verb `which` failed     at /code/sites/all/themes/greenbiz/node_modules/grunt-sass/node_modules/node-sass/node_modules/node-gyp/node_modules/which/node_modules/isexe/index.js:44:5
gyp verb `which` failed     at /code/sites/all/themes/greenbiz/node_modules/grunt-sass/node_modules/node-sass/node_modules/node-gyp/node_modules/which/node_modules/isexe/access.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:82:15)
gyp verb `which` failed  python [Error: not found: python]
```

**Suggested Enhancements**

- [ ] Add python and ruby to the kalabox/cli container: https://hub.docker.com/r/kalabox/cli/
- [ ] Update documentation regarding grunt/gulp: https://kalabox.freshdesk.com/solution/articles/14000019947

**Comment by pirog** [comment]
@reynoldsalec `node-gyp` documentation which might help us here
https://www.npmjs.com/package/node-gyp

specifically 
```
On Unix:
python (v2.7 recommended, v3.x.x is not supported)
make
A proper C/C++ compiler toolchain, like GCC
```
