### ISSUE TITLE
Rsync doesn't appear to work.

### ISSUE THREAD

**Issue by Mchampsee** [kalabox/kalabox#1279]
Please complete the following steps. **The more steps you complete the more
likely we are to address your issue!**

1. Please review the [current list of issues](https://github.com/kalabox/kalabox/issues) to make sure you are not submitting a duplicate.
2. Please tag your issue appropriately. Please review the [tagging criteria](https://github.com/kalabox/kalabox/blob/HEAD/CONTRIBUTING.md).
3. Based on the issue type tag selected above please fill in the relevant section below.

Bug Report
==========

What version of Kalabox are you using?

v0.12.0-alpha3

What operating system are you using?

Mac OS X El Capitan

Have you previously installed Kalabox? If so, what version?

Yes, 0.11.5

**Tell us about your bug**

Rsync isn't working. Both trying to run an rsync command via the command line as well as any changes to files on the host system don't sync to the kbox machine.

Can you recreate this bug?

 Yes

Please detail the steps we can take to replicate this bug. Be as detailed as possible.

 1. Go to a project in the command line and type kbox start
 2. Edit a file in the code directory
 3. type in kbox terminal and navigate to the directory with the file you changed
 4. type in more [name of file]
 5. You will see that the file is in its original state
 6. exit out of terminal and type in kbox rsync
 7. you will see an error message

Could better documentation have prevented this issue? if so what should we change?

Probably not

Does this bug prevent you from using Kalabox?

Yes

**Comment by Mchampsee** [comment]
output of `kbox rsync` as follows:

```
Unhandled rejection VError: code: 1err:Starting aetcnrc_data_1
Container command not found or does not exist.

    at /usr/local/bin/lib/util/shell.js.jx:65:16
    at /usr/local/bin/node_modules/shelljs/src/exec.js.jx:166:7
    at ChildProcess.exithandler (child_process.js:669:7)
    at ChildProcess.emit (events.js:85:17)
    at maybeClose (child_process.js:773:16)
    at Process.ChildProcess._handle.onexit (child_process.js:839:5)
From previous event:
    at Object.exports.exec (/usr/local/bin/lib/util/shell.js.jx:62:10)
    at Object.sh (/usr/local/bin/plugins/kalabox-engine-docker/provider/docker/lib/bin.js.jx:114:20)
    at shCompose (/usr/local/bin/plugins/kalabox-engine-docker/provider/docker/compose.js.jx:60:16)
    at Object.run (/usr/local/bin/plugins/kalabox-engine-docker/provider/docker/compose.js.jx:362:12)
    at /usr/local/bin/plugins/kalabox-engine-docker/index.js.jx:207:22
    at arrayMap (/usr/local/bin/node_modules/lodash/index.js.jx:1405:25)
    at Function.map (/usr/local/bin/node_modules/lodash/index.js.jx:6709:14)
    at Object.run (/usr/local/bin/plugins/kalabox-engine-docker/index.js.jx:190:26)
From previous event:
    at /usr/local/bin/lib/engine.js.jx:496:29
From previous event:
    at Object.exports.run (/usr/local/bin/lib/engine.js.jx:495:4)
    at Object.task.func (/usr/local/bin/plugins/kalabox-cmd/lib/tasks.js.jx:143:40)
    at Object.exports.run (/usr/local/bin/lib/core/tasks.js.jx:893:15)
    at processTask (/usr/local/bin/bin/kbox.js.jx:181:16)
    at Object.<anonymous> (/usr/local/bin/bin/kbox.js.jx:240:12)
    at process._tickCallback (node.js:917:13)
From previous event:
    at main (/usr/local/bin/bin/kbox.js.jx:239:4)
    at Object.<anonymous> (/usr/local/bin/bin/kbox.js.jx:248:1)
    at Module._compile (module.js:619:26)
    at readX (module.js:1645:5)
    at Object.Module._extensions..jx (module.js:2102:10)
    at Module.load (module.js:440:36)
    at Function.Module._load (module.js:405:12)
    at Module.require (module.js:475:17)
    at require (module.js:493:17)
    at Object.<anonymous> (_jx_source:17:3)
    at Module._compile (module.js:619:26)
    at Module.load (module.js:449:12)
    at Function.Module._load (module.js:405:12)
    at Function.Module.runMain (module.js:871:12)
    at startup (node.js:485:18)
    at node.js:1604:3

```

**Comment by pirog** [comment]
@Mchampsee what is the exact `rsync` command you are trying to run? What are you trying to accomplish specifically?

**Comment by Mchampsee** [comment]
The automatic `rsync` doesn't seem to work which was why I was trying to do it manually...so I guess that's the real issue.

**Comment by pirog** [comment]
`kbox rsync` is just a wrapper around normal `rsync`. It isn't related to how we share files between your host and kalabox. I assume you are talking about syncthing?

If so have you looked at any of the open syncthing issues to see if they reflect the issue you are having?

**Comment by Mchampsee** [comment]
Thanks @pirog . I wasn't aware that that was how it worked. I'll look into syncthing issues.

**Comment by pirog** [comment]
Definitely open up another ticket if you cant find an issue that reflects what you are experiencing
