### ISSUE TITLE
code1err:more:Pulling repository docker.io/library/redis adding D7 and D8 sites from Pantheon with Beta 1 and Alpha 3

### ISSUE THREAD

**Issue by Soundvessel** [kalabox/kalabox#1331]
Windows 10 Pro

Kalabox v0.12.0 Beta 1

Uninstalled previous alpha version and removed `.kalabox` and `.docker` directories from `C:\Users`.

Installed Kalabox Beta 1, entered my Patheon login credentals, selected a D8 site we setup on Pantheon and during Kalabox's setup of the app DANGER WILL ROBINSON! `code1err:more:Pulling repository docker.io/library/redis`

Trying to remove the app got the same error plus

`Error while removing dir: C:\Users\Matthew Giacomazzo\.kalabox\apps\utla-panth-dev: EPERM: operation not permitted, unlink 'C:\Users\Matthew Giacomazzo\.kalabox\apps\utla-panth-dev\code\.stfolder'`

I am going to try and uninstall and switch back to Alpha 3 because I need a working local environment today.

**Comment by Soundvessel** [comment]
Same `code1err:more:Pulling repository docker.io/library/redis` error with Alpha 3. Maybe this is an issue on Pantheon's end?

**Comment by Soundvessel** [comment]
Switched back to Beta 1. Here is my console output when I get the `code1err:more:Pulling repository docker.io/library/redis` error.

```
###############################################################
                                                               
                 WHERE IS EVERYTHING!?!?!                      
                                                               
 Cannot detect a working Kalabox environment!                  
                                                               
 We need to install some special things to make sure you are   
 good to go. Please download the Kalabox Installer and make    
 sure you have completed the installation process.             
                                                               
###############################################################
guiEngine.js:59 ERROR: code1err:more:Pulling repository docker.io/library/redis

guiEngine.js:60 VError: code1err:more:Pulling repository docker.io/library/redis

    at ChildProcess.<anonymous> (C:\Users\MATTHE~1\AppData\Local\Temp\nw1464_22521\node_modules\kalabox-cli\lib\util\shell.js:140:16)
    at emitTwo (events.js:85:13)
    at ChildProcess.emit (events.js:153:7)
    at maybeClose (child_process.js:984:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1057:5)
From previous event:
    at Object.exports.spawn (C:\Users\MATTHE~1\AppData\Local\Temp\nw1464_22521\node_modules\kalabox-cli\lib\util\shell.js:98:10)
    at Object.sh (C:\Users\MATTHE~1\AppData\Local\Temp\nw1464_22521\node_modules\kalabox-cli\plugins\kalabox-engine-docker\provider\docker\lib\bin.js:107:20)
    at shCompose (C:\Users\MATTHE~1\AppData\Local\Temp\nw1464_22521\node_modules\kalabox-cli\plugins\kalabox-engine-docker\provider\docker\compose.js:60:16)
    at Object.up [as start] (C:\Users\MATTHE~1\AppData\Local\Temp\nw1464_22521\node_modules\kalabox-cli\plugins\kalabox-engine-docker\provider\docker\compose.js:256:12)
    at C:\Users\MATTHE~1\AppData\Local\Temp\nw1464_22521\node_modules\kalabox-cli\plugins\kalabox-engine-docker\index.js:124:22
From previous event:
    at Object.start (C:\Users\MATTHE~1\AppData\Local\Temp\nw1464_22521\node_modules\kalabox-cli\plugins\kalabox-engine-docker\index.js:123:20)
From previous event:
    at C:\Users\MATTHE~1\AppData\Local\Temp\nw1464_22521\node_modules\kalabox-cli\lib\engine.js:455:29
From previous event:
    at Object.exports.start (C:\Users\MATTHE~1\AppData\Local\Temp\nw1464_22521\node_modules\kalabox-cli\lib\engine.js:454:4)
    at C:\Users\MATTHE~1\AppData\Local\Temp\nw1464_22521\node_modules\kalabox-cli\lib\app.js:606:19
From previous event:
    at Object.exports.start (C:\Users\MATTHE~1\AppData\Local\Temp\nw1464_22521\node_modules\kalabox-cli\lib\app.js:604:4)
    at C:\Users\MATTHE~1\AppData\Local\Temp\nw1464_22521\node_modules\kalabox-cli\lib\create.js:397:25
From previous event:
    at C:\Users\MATTHE~1\AppData\Local\Temp\nw1464_22521\node_modules\kalabox-cli\lib\create.js:395:8
From previous event:
    at Object.createApp (C:\Users\MATTHE~1\AppData\Local\Temp\nw1464_22521\node_modules\kalabox-cli\lib\create.js:372:6)
    at Object.<anonymous> (file:///C:/Users/MATTHE~1/AppData/Local/Temp/nw1464_22521/src/modules/guiEngine/sites.js:381:28)
    at processImmediate [as _immediateCallback] (timers.js:321:17)
From previous event:
    at file:///C:/Users/MATTHE~1/AppData/Local/Temp/nw1464_22521/src/modules/guiEngine/sites.js:367:19
    at file:///C:/Users/MATTHE~1/AppData/Local/Temp/nw1464_22521/src/modules/guiEngine/queue.js:47:20
    at tryCatcher (file:///C:/Users/MATTHE~1/AppData/Local/Temp/nw1464_22521/src/lib/vendor/bluebird/js/browser/bluebird.js:5098:23)
    at Function.Promise.attempt.Promise.try (file:///C:/Users/MATTHE~1/AppData/Local/Temp/nw1464_22521/src/lib/vendor/bluebird/js/browser/bluebird.js:2496:29)
    at file:///C:/Users/MATTHE~1/AppData/Local/Temp/nw1464_22521/src/modules/guiEngine/queue.js:46:24
    at tryCatcher (file:///C:/Users/MATTHE~1/AppData/Local/Temp/nw1464_22521/src/lib/vendor/bluebird/js/browser/bluebird.js:5098:23)
    at Promise._settlePromiseFromHandler (file:///C:/Users/MATTHE~1/AppData/Local/Temp/nw1464_22521/src/lib/vendor/bluebird/js/browser/bluebird.js:3129:31)
    at Promise._settlePromise (file:///C:/Users/MATTHE~1/AppData/Local/Temp/nw1464_22521/src/lib/vendor/bluebird/js/browser/bluebird.js:3186:18)
    at Promise._settlePromiseCtx (file:///C:/Users/MATTHE~1/AppData/Local/Temp/nw1464_22521/src/lib/vendor/bluebird/js/browser/bluebird.js:3223:10)
    at Async._drainQueue (file:///C:/Users/MATTHE~1/AppData/Local/Temp/nw1464_22521/src/lib/vendor/bluebird/js/browser/bluebird.js:195:12)
    at Async._drainQueues (file:///C:/Users/MATTHE~1/AppData/Local/Temp/nw1464_22521/src/lib/vendor/bluebird/js/browser/bluebird.js:200:10)
    at Async.drainQueues (file:///C:/Users/MATTHE~1/AppData/Local/Temp/nw1464_22521/src/lib/vendor/bluebird/js/browser/bluebird.js:69:14)
    at Scope.$eval (file:///C:/Users/MATTHE~1/AppData/Local/Temp/nw1464_22521/src/lib/vendor/angular/angular.js:16359:28)
    at Scope.$digest (file:///C:/Users/MATTHE~1/AppData/Local/Temp/nw1464_22521/src/lib/vendor/angular/angular.js:16175:31)
    at file:///C:/Users/MATTHE~1/AppData/Local/Temp/nw1464_22521/src/lib/vendor/angular/angular.js:16398:26
    at completeOutstandingRequest (file:///C:/Users/MATTHE~1/AppData/Local/Temp/nw1464_22521/src/lib/vendor/angular/angular.js:5754:10)
    at file:///C:/Users/MATTHE~1/AppData/Local/Temp/nw1464_22521/src/lib/vendor/angular/angular.js:6031:7
bluebird.js:1473 Warning: a promise was created in a handler but was not returned from it
    at Scope.$eval (file:///C:/Users/MATTHE~1/AppData/Local/Temp/nw1464_22521/src/lib/vendor/angular/angular.js:16359:28)
    at Scope.$digest (file:///C:/Users/MATTHE~1/AppData/Local/Temp/nw1464_22521/src/lib/vendor/angular/angular.js:16175:31)
    at file:///C:/Users/MATTHE~1/AppData/Local/Temp/nw1464_22521/src/lib/vendor/angular/angular.js:16398:26
    at completeOutstandingRequest (file:///C:/Users/MATTHE~1/AppData/Local/Temp/nw1464_22521/src/lib/vendor/angular/angular.js:5754:10)
    at file:///C:/Users/MATTHE~1/AppData/Local/Temp/nw1464_22521/src/lib/vendor/angular/angular.js:6031:7
From previous event:
    at $http (file:///C:/Users/MATTHE~1/AppData/Local/Temp/nw1464_22521/src/lib/vendor/angular/angular.js:10535:24)
    at Function.$http.(anonymous function) (file:///C:/Users/MATTHE~1/AppData/Local/Temp/nw1464_22521/src/lib/vendor/angular/angular.js:10743:18)
    at handleRequestFn (file:///C:/Users/MATTHE~1/AppData/Local/Temp/nw1464_22521/src/lib/vendor/angular/angular.js:18053:20)
    at compileTemplateUrl (file:///C:/Users/MATTHE~1/AppData/Local/Temp/nw1464_22521/src/lib/vendor/angular/angular.js:8735:7)
    at applyDirectivesToNode (file:///C:/Users/MATTHE~1/AppData/Local/Temp/nw1464_22521/src/lib/vendor/angular/angular.js:8344:24)
    at compileNodes (file:///C:/Users/MATTHE~1/AppData/Local/Temp/nw1464_22521/src/lib/vendor/angular/angular.js:7888:15)
    at compile (file:///C:/Users/MATTHE~1/AppData/Local/Temp/nw1464_22521/src/lib/vendor/angular/angular.js:7787:15)
    at Object.w.open (file:///C:/Users/MATTHE~1/AppData/Local/Temp/nw1464_22521/src/lib/vendor/angular-bootstrap/ui-bootstrap-tpls.min.js:9:26212)
    at file:///C:/Users/MATTHE~1/AppData/Local/Temp/nw1464_22521/src/lib/vendor/angular-bootstrap/ui-bootstrap-tpls.min.js:9:29328
    at Scope.$eval (file:///C:/Users/MATTHE~1/AppData/Local/Temp/nw1464_22521/src/lib/vendor/angular/angular.js:16359:28)
    at Scope.$digest (file:///C:/Users/MATTHE~1/AppData/Local/Temp/nw1464_22521/src/lib/vendor/angular/angular.js:16175:31)
    at file:///C:/Users/MATTHE~1/AppData/Local/Temp/nw1464_22521/src/lib/vendor/angular/angular.js:16398:26
From previous event:
    at Promise.$qBluebird.then (file:///C:/Users/MATTHE~1/AppData/Local/Temp/nw1464_22521/src/lib/vendor/angular-bluebird-promises/dist/angular-bluebird-promises.js:128:24)
    at Object.l.open (file:///C:/Users/MATTHE~1/AppData/Local/Temp/nw1464_22521/src/lib/vendor/angular-bootstrap/ui-bootstrap-tpls.min.js:9:28782)
    at Scope.$scope.open (file:///C:/Users/MATTHE~1/AppData/Local/Temp/nw1464_22521/src/modules/dashboard/dashboard.js:145:38)
    at file:///C:/Users/MATTHE~1/AppData/Local/Temp/nw1464_22521/src/modules/dashboard/dashboard.js:240:14
From previous event:
    at file:///C:/Users/MATTHE~1/AppData/Local/Temp/nw1464_22521/src/modules/guiEngine/recloop.js:47:24
kalabox.js:64 code1err:more:Pulling repository docker.io/library/redis

kalabox.js:65 VError: code1err:more:Pulling repository docker.io/library/redis

    at ChildProcess.<anonymous> (C:\Users\MATTHE~1\AppData\Local\Temp\nw1464_22521\node_modules\kalabox-cli\lib\util\shell.js:140:16)
    at emitTwo (events.js:85:13)
    at ChildProcess.emit (events.js:153:7)
    at maybeClose (child_process.js:984:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1057:5)
From previous event:
    at Object.exports.spawn (C:\Users\MATTHE~1\AppData\Local\Temp\nw1464_22521\node_modules\kalabox-cli\lib\util\shell.js:98:10)
    at Object.sh (C:\Users\MATTHE~1\AppData\Local\Temp\nw1464_22521\node_modules\kalabox-cli\plugins\kalabox-engine-docker\provider\docker\lib\bin.js:107:20)
    at shCompose (C:\Users\MATTHE~1\AppData\Local\Temp\nw1464_22521\node_modules\kalabox-cli\plugins\kalabox-engine-docker\provider\docker\compose.js:60:16)
    at Object.up [as start] (C:\Users\MATTHE~1\AppData\Local\Temp\nw1464_22521\node_modules\kalabox-cli\plugins\kalabox-engine-docker\provider\docker\compose.js:256:12)
    at C:\Users\MATTHE~1\AppData\Local\Temp\nw1464_22521\node_modules\kalabox-cli\plugins\kalabox-engine-docker\index.js:124:22
From previous event:
    at Object.start (C:\Users\MATTHE~1\AppData\Local\Temp\nw1464_22521\node_modules\kalabox-cli\plugins\kalabox-engine-docker\index.js:123:20)
From previous event:
    at C:\Users\MATTHE~1\AppData\Local\Temp\nw1464_22521\node_modules\kalabox-cli\lib\engine.js:455:29
From previous event:
    at Object.exports.start (C:\Users\MATTHE~1\AppData\Local\Temp\nw1464_22521\node_modules\kalabox-cli\lib\engine.js:454:4)
    at C:\Users\MATTHE~1\AppData\Local\Temp\nw1464_22521\node_modules\kalabox-cli\lib\app.js:606:19
From previous event:
    at Object.exports.start (C:\Users\MATTHE~1\AppData\Local\Temp\nw1464_22521\node_modules\kalabox-cli\lib\app.js:604:4)
    at C:\Users\MATTHE~1\AppData\Local\Temp\nw1464_22521\node_modules\kalabox-cli\lib\create.js:397:25
From previous event:
    at C:\Users\MATTHE~1\AppData\Local\Temp\nw1464_22521\node_modules\kalabox-cli\lib\create.js:395:8
From previous event:
    at Object.createApp (C:\Users\MATTHE~1\AppData\Local\Temp\nw1464_22521\node_modules\kalabox-cli\lib\create.js:372:6)
    at Object.<anonymous> (file:///C:/Users/MATTHE~1/AppData/Local/Temp/nw1464_22521/src/modules/guiEngine/sites.js:381:28)
    at processImmediate [as _immediateCallback] (timers.js:321:17)
From previous event:
    at file:///C:/Users/MATTHE~1/AppData/Local/Temp/nw1464_22521/src/modules/guiEngine/sites.js:367:19
    at file:///C:/Users/MATTHE~1/AppData/Local/Temp/nw1464_22521/src/modules/guiEngine/queue.js:47:20
    at tryCatcher (file:///C:/Users/MATTHE~1/AppData/Local/Temp/nw1464_22521/src/lib/vendor/bluebird/js/browser/bluebird.js:5098:23)
    at Function.Promise.attempt.Promise.try (file:///C:/Users/MATTHE~1/AppData/Local/Temp/nw1464_22521/src/lib/vendor/bluebird/js/browser/bluebird.js:2496:29)
    at file:///C:/Users/MATTHE~1/AppData/Local/Temp/nw1464_22521/src/modules/guiEngine/queue.js:46:24
    at tryCatcher (file:///C:/Users/MATTHE~1/AppData/Local/Temp/nw1464_22521/src/lib/vendor/bluebird/js/browser/bluebird.js:5098:23)
    at Promise._settlePromiseFromHandler (file:///C:/Users/MATTHE~1/AppData/Local/Temp/nw1464_22521/src/lib/vendor/bluebird/js/browser/bluebird.js:3129:31)
    at Promise._settlePromise (file:///C:/Users/MATTHE~1/AppData/Local/Temp/nw1464_22521/src/lib/vendor/bluebird/js/browser/bluebird.js:3186:18)
    at Promise._settlePromiseCtx (file:///C:/Users/MATTHE~1/AppData/Local/Temp/nw1464_22521/src/lib/vendor/bluebird/js/browser/bluebird.js:3223:10)
    at Async._drainQueue (file:///C:/Users/MATTHE~1/AppData/Local/Temp/nw1464_22521/src/lib/vendor/bluebird/js/browser/bluebird.js:195:12)
    at Async._drainQueues (file:///C:/Users/MATTHE~1/AppData/Local/Temp/nw1464_22521/src/lib/vendor/bluebird/js/browser/bluebird.js:200:10)
    at Async.drainQueues (file:///C:/Users/MATTHE~1/AppData/Local/Temp/nw1464_22521/src/lib/vendor/bluebird/js/browser/bluebird.js:69:14)
    at Scope.$eval (file:///C:/Users/MATTHE~1/AppData/Local/Temp/nw1464_22521/src/lib/vendor/angular/angular.js:16359:28)
    at Scope.$digest (file:///C:/Users/MATTHE~1/AppData/Local/Temp/nw1464_22521/src/lib/vendor/angular/angular.js:16175:31)
    at file:///C:/Users/MATTHE~1/AppData/Local/Temp/nw1464_22521/src/lib/vendor/angular/angular.js:16398:26
    at completeOutstandingRequest (file:///C:/Users/MATTHE~1/AppData/Local/Temp/nw1464_22521/src/lib/vendor/angular/angular.js:5754:10)
    at file:///C:/Users/MATTHE~1/AppData/Local/Temp/nw1464_22521/src/lib/vendor/angular/angular.js:6031:7
```

**Comment by pirog** [comment]
@Soundvessel i dont think any of this should have changed between alpha3 and beta1. Is it possible that your install did not complete correctly? 

Do you have a Kalabox2 VM in virtualbox?

**Comment by Soundvessel** [comment]
@pirog -- The same D8 and D7 site from Pantheon previously worked on Kalabox alpha 4. However when everything failed with Beta 1 I uninstalled and had access to the Alpha 3 installer but everything failed under that in the same manner.

So just to try everything again...

I uninstalled everything, Kalabox, Virtualbox, Git and removed any leftover directories from `C:\Users`.

Kalabox Beta 1 Installer
http://prntscr.com/b14e6q

Installer finished without issue
http://prntscr.com/b14gsq

Started Kalabox and confirmed Kalabox2 VM is in VirtualBox
http://prntscr.com/b14h8e

Entered my Pantheon credentials, selected a d8 site we just setup on Pantheon, gave it name and selected environment
http://prntscr.com/b14i4g

Clicked submit and when it got to saying it was adding containers in the Kalabox UI I got the error `code1err:more:Pulling repository docker.io/library/redis`
http://prntscr.com/b14ith

Hitting "ok" on error window I checked the code directory and was empty. Hitting the power button on the app to try and get it start just brought the error up repeatedly.
http://prntscr.com/b14jvl

I am completely blocked and out of ideas here. My skype is matthew.giacomazzo if you want to connect for debugging.

**Comment by pirog** [comment]
@Soundvessel usually when you get errors pulling from docker it's DNS related. That said we haven't changed anything DNS related for quite some time. 

There are two things i can suggest at this point

#### Send the Kalabox log file over to `mike@kalabox.io`. 

Should be in `~/.kalabox/logs/kalabox.log`.

#### Check to see if you can pull an image from the docker 

```bash
# Make the Kalabox VM is started
~/.kalabox/bin/docker-machine start Kalabox2

# SSH into the VM
~/.kalabox/bin/docker-machine ssh Kalabox2

# Attempt to pull a trivial container
docker pull redis
```

**Comment by Soundvessel** [comment]
@pirog --

Alright tried again after using the Windows command line to flush my DNS resolver cache first.

Failed in same manner. Log emailed.

When using the command line to check if the Kalabox2 VM is started I got the following

`Starting "Kalabox2"...
(Kalabox2) Check network to re-create if needed...
Error setting up host only network on machine start: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe modifyvm Kalabox2 --nic2 hostonly --nictype2 82540EM --nicpromisc2 deny --hostonlyadapter2 VirtualBox Host-Only Ethernet Adapter #2 --cableconnected2 on failed:
VBoxManage.exe: error: Code E_FAIL (0x80004005) - Unspecified error (extended info not available)
VBoxManage.exe: error: Context: "LockMachine(a->session, LockType_Write)" at line 493 of file VBoxManageModifyVM.cpp`

**Comment by pirog** [comment]
Hmmm, ok that definitely looks like it could be causing this.

**Comment by pirog** [comment]
@Soundvessel i would also check out 
https://kalabox.freshdesk.com/solution/articles/14000023077-my-installation-failed-now-what-can-i-do-

It's for OSX mostly but i think the duplicate host-only adapter issue may be relevant and worth checking out.

**Comment by Soundvessel** [comment]
@pirog -- Bingo! I closed out Kalabox and turned off the Kalabox2 VM machine from Virtualbox. Removed the host-only adapter from the Kalabox2 VM in virtualbox and then uninstalled all 3 of the host-only network devices from Windows Device Manager. Starting Kalabox a single Host-Only device was created and the D8 site was pulled without issue.... except....

.... new issue. My host file appears to have not been modified so the site.kbox link from the app produces a DNS address could not be found error in browser. I will create a new issue thread for that if I can't find a quick fix here soon.

**Comment by pirog** [comment]
You might just need to restart your app to get the site.kbox to show.

What browser are you using?

**Comment by Soundvessel** [comment]
@pirog -- Google Chrome, the same I have used with Alpha 3 and 4. Turning on and off the apps as well as Kalabox doesn't resolve the issue of the apps not coming up in browser.

Shouldn't it be creating entries in my host file in Windows? Not seeing any entries for *.kbox etc.

**Comment by pirog** [comment]
Nope. We have reserve proxy and dns containers that handle the routing.

It's possible that these service were not installed during install because
of the error you got.

I would just run the installer again, you shouldn't need to uninstall. Then
give your apps a restart.

If that doesn't work let me know.

**Comment by Soundvessel** [comment]
Running the installer again worked like a charm!

Thank you so much @pirog (Mike) for your help resolving this issue. Got 7 weeks of Drupal 8 development on Pantheon to rock out now. :)

**Comment by pirog** [comment]
Awesome! We will def try to make the documentation clearer so we can direct people to the right places.

**Comment by shaal** [comment]
Fresh new windows 10 installation.
and I installed XAMPP on my computer,
then I installed Kalabox Beta 1.

Installation seems to work well.

I was trying to add a Drupal 7 site, from Pantheon, and after the stage of "starting containers" - 
I got this error message -
` code1err:more:Pulling repository http://docker.io/library/redis `

**Comment by pirog** [comment]
@shaal this seems like a different issue? Possibly https://github.com/kalabox/kalabox/issues/1330

**Comment by shaal** [comment]
@pirog - possible. I don't know.

When you saw my installation last time - I think that was before the new GUI, and i remember there was an issue with resolving the address. so is that the same bug? (i didn't have a chance to check Kalabox since0

**Comment by pirog** [comment]
Yes @shaal i *think* this is the same bug and i *think* #1330 should resolve it.

**Comment by shaal** [comment]
@pirog - do you know if there's anything I can do manually to fix the issue on my machine, before the next version of Kalabox comes out?

**Comment by pirog** [comment]
@shaal we havent released an official version yet but the forthcoming `0.13.x` release should resolve this.
