### ISSUE TITLE
Cannot find module 'lodash' on create, destroy or any commands on Linux beta1

### ISSUE THREAD

**Issue by labboy0276** [kalabox/kalabox#1350]
Bug Report
==========

**Tell us about your setup**

What is your Kalabox version and operating system?

Xubuntu 14.04

Have you previously installed Kalabox? If so, what version?

Yes all the versions

**Tell us about your bug**

Give a brief description of what happened, including any error messages that appeared.

I tried to create a pantheon site and it gave me a node error that it couldn't find the lodash module.

Please detail the steps we can take to replicate this bug. Be as detailed as possible.

I started up my kalabox, went in to create a panthoen site and it stopped with a lodash not found error as seen below all this typing.

```
john@kalamuna:~/.kalabox/apps$ kbox create pantheon
? Choose a Pantheon account. john@kalamuna.com
? Which site? csi-auth-proxy
? Which environment? dev
? What will you call this monster you have created: csi-auth-proxy
Creating.
Cleaning up.
Creating app structure.
Downloading: [NaN%] ...labox/kalabox-app-pantheon/tarball/v0.12
Configuring app.
Running pre create tasks.
kalabox-plugin-pantheon -> Cannot find module 'lodash'
Error: kalabox-plugin-pantheon -> Cannot find module 'lodash'
    at Function.Module._oldRes (module.js:800:15)
    at Function.Module._resolveFilename (module.js:1965:17)
    at Function.Module._load (module.js:360:25)
    at Module.require (module.js:475:17)
    at require (module.js:493:17)
    at module.exports (/home/john/.kalabox/apps/csi-auth-proxy/plugins/kalabox-plugin-pantheon/lib/events.js:6:11)
    at module.exports (/home/john/.kalabox/apps/csi-auth-proxy/plugins/kalabox-plugin-pantheon/index.js:7:29)
    at /usr/local/bin/lib/require.js.jx:271:20
    at /usr/local/bin/lib/require.js.jx:270:29
    at requireInternal (/usr/local/bin/lib/require.js.jx:228:4)
    at Promise.resolve.then.then.mod (/usr/local/bin/lib/require.js.jx:331:14)
    at Object.exports.require (/usr/local/bin/lib/require.js.jx:327:4)
    at /usr/local/bin/lib/kbox.js.jx:117:28
    at Object.exports.require (/usr/local/bin/lib/kbox.js.jx:109:21)
    at /usr/local/bin/lib/app.js.jx:91:17
    at exports.loadPlugins (/usr/local/bin/lib/app.js.jx:90:18)
    at /usr/local/bin/lib/app.js.jx:189:12
    at _create (/usr/local/bin/lib/app.js.jx:188:4)
    at Object.exports.create (/usr/local/bin/lib/app.js.jx:237:12)
    at kbox.core.events.emit.then.tap.kbox.metrics.reportAction.app (/usr/local/bin/lib/create.js.jx:383:25)
    at /usr/local/bin/lib/create.js.jx:382:8
    at process._tickCallback (node.js:917:13)
    at createApp (/usr/local/bin/lib/create.js.jx:372:6)
    at PromptUI.completed (/usr/local/bin/lib/create.js.jx:498:16)
    at PromptUI.onCompletion (/usr/local/bin/node_modules/inquirer/lib/ui/prompt.js.jx:68:10)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:1792:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:1729:14)
    at AnonymousObserver.tryCatcher (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:566:29)
    at AutoDetachObserverPrototype.completed (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:5287:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:1729:14)
    at InnerObserver.onCompleted (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:3424:65)
    at InnerObserver.tryCatcher (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:566:29)
    at AutoDetachObserverPrototype.completed (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:5287:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:1729:14)
    at AutoDetachObserver.tryCatcher (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:566:29)
    at AutoDetachObserverPrototype.completed (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:5287:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:1729:14)
    at InnerObserver.onCompleted (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:3424:65)
    at InnerObserver.tryCatcher (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:566:29)
    at AutoDetachObserverPrototype.completed (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:5287:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:1729:14)
From previous event:
    at /usr/local/bin/lib/require.js.jx:274:17
From previous event:
    at requireInternal (/usr/local/bin/lib/require.js.jx:228:4)
    at Promise.resolve.then.then.mod (/usr/local/bin/lib/require.js.jx:331:14)
From previous event:
    at Object.exports.require (/usr/local/bin/lib/require.js.jx:327:4)
    at /usr/local/bin/lib/kbox.js.jx:117:28
From previous event:
    at Object.exports.require (/usr/local/bin/lib/kbox.js.jx:109:21)
    at /usr/local/bin/lib/app.js.jx:91:17
From previous event:
    at exports.loadPlugins (/usr/local/bin/lib/app.js.jx:90:18)
    at /usr/local/bin/lib/app.js.jx:189:12
From previous event:
    at _create (/usr/local/bin/lib/app.js.jx:188:4)
    at Object.exports.create (/usr/local/bin/lib/app.js.jx:237:12)
    at kbox.core.events.emit.then.tap.kbox.metrics.reportAction.app (/usr/local/bin/lib/create.js.jx:383:25)
From previous event:
    at /usr/local/bin/lib/create.js.jx:382:8
    at process._tickCallback (node.js:917:13)
From previous event:
    at createApp (/usr/local/bin/lib/create.js.jx:372:6)
    at PromptUI.completed (/usr/local/bin/lib/create.js.jx:498:16)
    at PromptUI.onCompletion (/usr/local/bin/node_modules/inquirer/lib/ui/prompt.js.jx:68:10)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:1792:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:1729:14)
    at AnonymousObserver.tryCatcher (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:566:29)
    at AutoDetachObserverPrototype.completed (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:5287:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:1729:14)
    at InnerObserver.onCompleted (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:3424:65)
    at InnerObserver.tryCatcher (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:566:29)
    at AutoDetachObserverPrototype.completed (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:5287:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:1729:14)
    at AutoDetachObserver.tryCatcher (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:566:29)
    at AutoDetachObserverPrototype.completed (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:5287:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:1729:14)
    at InnerObserver.onCompleted (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:3424:65)
    at InnerObserver.tryCatcher (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:566:29)
    at AutoDetachObserverPrototype.completed (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:5287:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:1729:14)
```

I tried to destroy the app to no avail, same error as below.

I purged node and npm and reinstalled, I am on the following versions:

```
john@kalamuna:~/.kalabox/apps$ node -v
v4.4.4
john@kalamuna:~/.kalabox/apps$ npm -v
2.15.1
```

I am going to uninstall and reinstall, not sure what happened here.

**Tell us more**

Could better documentation have prevented this issue? if so what should we change?
No

Does this bug prevent you from using Kalabox?
Yes

**Comment by labboy0276** [comment]
I was on the dev version when @pirog tried some stuff and things to fix multidev stuff. 

I purged and went back to stable and all is well.
