### ISSUE TITLE
Docker daemon bridge duplication prevents daemon from starting. Shows up as "cannot get list of container" error

### ISSUE THREAD

**Issue by max-ink** [kalabox/kalabox#1386]
# Bug Report

**Tell us about your setup**

Version 0.12.16 on OS X 10.11.3

Have you previously installed Kalabox? If so, what version?

not on this machine

**Tell us about your bug**

I tried to create a pantheon site but got a "Error querying docker for list of containers.: operation timed out" 

Which leaves an unstarted site box. I try to delete said box. and i get the same error. 

Please detail the steps we can take to replicate this bug. Be as detailed as possible.

> 1. Started up GUI
> 2. Clicked on my Pantheon account in the sidebar
> 3. Selected a site and an environment "agci"
> 4. Kept the default create options and pressed submit and get error as it is attempting to Create. 
>    "Error querying docker for list of containers.: operation timed out"
> 5. Hit OK on the error modal. Left with box in "creating..." state 
> 6. Restart Kalabox 
> 7. Try to Start or Delete box "agci"
>    RESULT: Error querying docker for list of containers.: operation timed out

**Tell us more**

When trying to use terminal to create. ie "kbox create pantheon" from a specified directory i get the following error. 

Error querying docker for list of containers.: operation timed out
TimeoutError: operation timed out
    at Timer.listOnTimeout [as ontimeout](timers.js:120:15)
From previous event:
    at Object.list (/usr/local/bin/plugins/kalabox-engine-docker/provider/docker/docker.js.jx:115:6)
    at /usr/local/bin/plugins/kalabox-engine-docker/index.js.jx:84:21
From previous event:
    at Object.list (/usr/local/bin/plugins/kalabox-engine-docker/index.js.jx:83:6)
From previous event:
    at /usr/local/bin/lib/engine.js.jx:357:29
From previous event:
    at Object.exports.list (/usr/local/bin/lib/engine.js.jx:356:4)
    at /usr/local/bin/lib/app.js.jx:550:34
    at process._tickCallback (node.js:917:13)
From previous event:
    at Object.exports.cleanup (/usr/local/bin/lib/app.js.jx:549:4)
    at createApp (/usr/local/bin/lib/create.js.jx:357:21)
    at PromptUI.completed (/usr/local/bin/lib/create.js.jx:498:16)
    at PromptUI.onCompletion (/usr/local/bin/node_modules/inquirer/lib/ui/prompt.js.jx:68:10)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:1792:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:1729:14)
    at AnonymousObserver.tryCatcher (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:566:29)
    at AutoDetachObserverPrototype.completed (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:5287:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:1729:14)
    at InnerObserver.onCompleted (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:3424:65)
    at InnerObserver.tryCatcher (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:566:29)
    at AutoDetachObserverPrototype.completed (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:5287:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:1729:14)
    at AutoDetachObserver.tryCatcher (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:566:29)
    at AutoDetachObserverPrototype.completed (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:5287:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:1729:14)
    at InnerObserver.onCompleted (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:3424:65)
    at InnerObserver.tryCatcher (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:566:29)
    at AutoDetachObserverPrototype.completed (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:5287:56)

**Comment by martic** [comment]
I get this on windows 10 also. this is the same as #1387

**Comment by labboy0276** [comment]
Started getting this on Ubuntu 14.04 as well today.  Trying to find out why:

```
john@kalamuna:~/.kalabox/apps$ kbox create pantheon
? Choose a Pantheon account. john@kalamuna.com
? Which site? huddle
? Which environment? zendesk
? What will you call this monster you have created: huddle
Creating.
Cleaning up.
Error querying docker for list of containers.: operation timed out
TimeoutError: operation timed out
    at Timer.listOnTimeout [as ontimeout] (timers.js:120:15)
From previous event:
    at Object.list (/usr/local/bin/plugins/kalabox-engine-docker/provider/docker/docker.js.jx:115:6)
    at /usr/local/bin/plugins/kalabox-engine-docker/index.js.jx:84:21
From previous event:
    at Object.list (/usr/local/bin/plugins/kalabox-engine-docker/index.js.jx:83:6)
From previous event:
    at /usr/local/bin/lib/engine.js.jx:357:29
From previous event:
    at Object.exports.list (/usr/local/bin/lib/engine.js.jx:356:4)
    at /usr/local/bin/lib/app.js.jx:550:34
    at process._tickCallback (node.js:917:13)
From previous event:
    at Object.exports.cleanup (/usr/local/bin/lib/app.js.jx:549:4)
    at createApp (/usr/local/bin/lib/create.js.jx:357:21)
    at PromptUI.completed (/usr/local/bin/lib/create.js.jx:498:16)
    at PromptUI.onCompletion (/usr/local/bin/node_modules/inquirer/lib/ui/prompt.js.jx:68:10)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:1792:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:1729:14)
    at AnonymousObserver.tryCatcher (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:566:29)
    at AutoDetachObserverPrototype.completed (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:5287:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:1729:14)
    at InnerObserver.onCompleted (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:3424:65)
    at InnerObserver.tryCatcher (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:566:29)
    at AutoDetachObserverPrototype.completed (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:5287:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:1729:14)
    at AutoDetachObserver.tryCatcher (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:566:29)
    at AutoDetachObserverPrototype.completed (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:5287:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:1729:14)
    at InnerObserver.onCompleted (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:3424:65)
    at InnerObserver.tryCatcher (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:566:29)
    at AutoDetachObserverPrototype.completed (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:5287:56)
```

**Comment by labboy0276** [comment]
My daemon docker doesn't start:

goto: /usr/share/kalabox/scripts
run: sudo ./daemonup

output is:
```
DEBU[0000] sudo group found. gid: 27                    
DEBU[0000] Server created for HTTP on unix (/usr/share/kalabox/docker.socket) 
WARN[0000] /!\ DON'T BIND ON ANY IP ADDRESS WITHOUT setting -tlsverify IF YOU DON'T KNOW WHAT YOU'RE DOING /!\ 
DEBU[0000] Server created for HTTP on tcp (10.13.37.100:2375) 
INFO[0000] API listen on /usr/share/kalabox/docker.socket 
INFO[0000] API listen on 10.13.37.100:2375              
INFO[0000] [graphdriver] using prior storage driver "aufs" 
DEBU[0000] Using graph driver aufs                      
DEBU[0000] Using default logging driver json-file       
DEBU[0000] Migrating existing containers                
DEBU[0000] Creating images graph                        
DEBU[0000] Restored 184 elements                        
DEBU[0000] Creating repository list                     
DEBU[0000] Option DefaultDriver: bridge                 
DEBU[0000] Option DefaultNetwork: bridge                
INFO[0000] Firewalld running: false                     
DEBU[0000] /sbin/iptables, [--wait -t nat -D PREROUTING -m addrtype --dst-type LOCAL -j DOCKER] 
DEBU[0000] /sbin/iptables, [--wait -t nat -D OUTPUT -m addrtype --dst-type LOCAL ! --dst 127.0.0.0/8 -j DOCKER] 
DEBU[0000] /sbin/iptables, [--wait -t nat -D OUTPUT -m addrtype --dst-type LOCAL -j DOCKER] 
DEBU[0000] /sbin/iptables, [--wait -t nat -D PREROUTING] 
DEBU[0000] /sbin/iptables, [--wait -t nat -D OUTPUT]    
DEBU[0000] /sbin/iptables, [--wait -t nat -F DOCKER]    
DEBU[0000] /sbin/iptables, [--wait -t nat -X DOCKER]    
DEBU[0000] /sbin/iptables, [--wait -t nat -n -L DOCKER] 
DEBU[0000] /sbin/iptables, [--wait -t nat -N DOCKER]    
DEBU[0000] /sbin/iptables, [--wait -t filter -n -L DOCKER] 
DEBU[0000] Registering ipam provider: default           
DEBU[0000] Cleaning up old shm/mqueue mounts: start.    
FATA[0000] Error starting daemon: Error initializing network controller: could not delete the default bridge network: network bridge has active endpoints
```

**Comment by pirog** [comment]
Looked at this with @labboy0276 and it seems to happen when there is cruft leftover in `/usr/share/kalabox/docker.graph/network` after a hard reset of your machine. 

Removing `/usr/share/kalabox/docker.graph/network` and then running `sudo service kalabox start` seems to resolve the issue. 

Maybe we should try to purge this directory when we boot up the daemon?

**Comment by kscheirer** [comment]
I'm seeing this Timer.listOnTimeout error as well, on osx 10.11.6. I don't have a `/usr/share/kalabox`, where else could this file be located? This happens both with GUI and kbox.

**Comment by pirog** [comment]
This issue is specific to Linux so I'm guessing your issue is something
else

**Comment by kscheirer** [comment]
@pirog Makes sense, looks similar to the original bug report though - any ideas?

**Comment by pirog** [comment]
Would open a new ticket on this so we don't muddy the waters too much!

**Comment by kscheirer** [comment]
done, thanks!

**Comment by pirog** [comment]
So this can also happen on OSX although im not exactly sure why. The resolution is similar.

```bash
export DOCKER_MACHINE=/Applications/Kalabox.app/Contents/MacOS/bin/docker-machine
$DOCKER_MACHINE start Kalabox2
$DOCKER_MACHINE ssh Kalabox2 

# This will drop you into the kalabox2 VM
sudo rm -rf /var/lib/docker/network
sudo /etc/init.d/docker start
```

**Comment by pirog** [comment]
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!
