### ISSUE TITLE
Cannot read property 'AuthOptions' of undefined

### ISSUE THREAD

**Issue by sandipsclarion** [kalabox/kalabox#1434]
Bug Report
==========

**Tell us about your setup**

What is your Kalabox version and operating system?
 v0.12.0-beta1 on Windows 8.1 Eternprise*
64 Bit 
DockerToolbox-1.11.2

Have you previously installed Kalabox? If so, what version?

Yes, I've installed kalabox-v0.12.0-beta.1*

**Tell us about your bug**

I am trying to setup "hub.docker.com/r/viperks/web/" 
on local machine and trying to follow the steps as per given.
while using "kbox start" facing the error of "Cannot read property 'AuthOptions' of undefined"
![screenshot 1467700890](https://cloud.githubusercontent.com/assets/16461960/16576094/85385a68-42aa-11e6-84ed-a3df28aa0371.jpg)

> Example: 

> 1. Install docker
> 2. install kalabox
> 3. clone the repo using docker "hub.docker.com/r/viperks/web/"
> 4. run the command in api folder "kbox start"

**Tell us more**
----

**Comment by pirog** [comment]
Usually when you see this error it means that your install was not successful. Can you verify that you have a Kalabox2 VM in VirtualBox?

**Comment by sandipsclarion** [comment]
yes, i tried to install and reinstallation multiple time. I am sure I have kalabox2 VM in VirtualBox .
but giving the same error.

Sometimes it throws an error "timeout for a list of containers."

**Comment by pirog** [comment]
hey @sandipsclarion 

I think this has been resolved in our hot off the press release. Check that out over at
https://github.com/kalabox/kalabox/releases/tag/v0.13.0-beta.2 (we haven't updated the download on kalabox.io yet) and def read the docs on how to [update your kalabox](http://docs.kalabox.io/en/stable/users/updating/)

If the issue persists please reopen this (or submit a new) issue!

**Comment by shaal** [comment]
I installed v0.13.0-beta.2
and I am getting the same error -

`
$ kbox status -- -d
debug: EVENTS ==> Emitting event [pre-task-add]. 0=up
verbose: DOCKER MACHINE ==> Running ["inspect"]
debug: EVENTS ==> No listeners [pre-task-add].
debug: EVENTS ==> Emitting event [pre-task-add]. 0=down
debug: EVENTS ==> No listeners [pre-task-add].
debug: EVENTS ==> Emitting event [pre-task-add]. 0=status
debug: EVENTS ==> No listeners [pre-task-add].
debug: EVENTS ==> Finished dispatching event listeners [pre-task-add].
debug: EVENTS ==> Finished dispatching event listeners [pre-task-add].
debug: EVENTS ==> Finished dispatching event listeners [pre-task-add].
debug: EVENTS ==> Emitting event [pre-task-add]. 0=config
debug: EVENTS ==> No listeners [pre-task-add].
debug: EVENTS ==> Emitting event [pre-task-add]. 0=env
debug: EVENTS ==> No listeners [pre-task-add].
debug: EVENTS ==> Emitting event [pre-task-add]. 0=list
debug: EVENTS ==> No listeners [pre-task-add].
debug: EVENTS ==> Emitting event [pre-task-add]. 0=version
debug: EVENTS ==> No listeners [pre-task-add].
debug: EVENTS ==> Finished dispatching event listeners [pre-task-add].
debug: EVENTS ==> Finished dispatching event listeners [pre-task-add].
debug: EVENTS ==> Finished dispatching event listeners [pre-task-add].
debug: EVENTS ==> Finished dispatching event listeners [pre-task-add].
debug: EVENTS ==> Emitting event [pre-task-add]. 0=create, 1=backdrop
debug: EVENTS ==> No listeners [pre-task-add].
debug: EVENTS ==> Emitting event [pre-task-add]. 0=create, 1=drupal7
debug: EVENTS ==> No listeners [pre-task-add].
debug: EVENTS ==> Emitting event [pre-task-add]. 0=create, 1=drupal8
debug: EVENTS ==> No listeners [pre-task-add].
debug: EVENTS ==> Emitting event [pre-task-add]. 0=create, 1=wordpress
debug: EVENTS ==> No listeners [pre-task-add].
debug: EVENTS ==> Finished dispatching event listeners [pre-task-add].
debug: EVENTS ==> Finished dispatching event listeners [pre-task-add].
debug: EVENTS ==> Finished dispatching event listeners [pre-task-add].
debug: EVENTS ==> Finished dispatching event listeners [pre-task-add].
debug: EVENTS ==> Emitting event [pre-task-add]. 0=create, 1=pantheon
debug: EVENTS ==> No listeners [pre-task-add].
debug: EVENTS ==> Finished dispatching event listeners [pre-task-add].
debug: APP REGISTRY ==> Apps in registry: []
debug: SHELL EXEC ==> Running command C:\Program Files\Kalabox\bin\docker-machine.exe,inspect,Kalabox2
verbose: DOCKER MACHINE ==> Running ["inspect"]
debug: SHELL EXEC ==> Running command C:\Program Files\Kalabox\bin\docker-machine.exe,inspect,Kalabox2
verbose: DOCKER MACHINE ==> Running ["inspect"]
debug: SHELL EXEC ==> Running command C:\Program Files\Kalabox\bin\docker-machine.exe,inspect,Kalabox2
verbose: DOCKER MACHINE ==> Running ["inspect"]
debug: SHELL EXEC ==> Running command C:\Program Files\Kalabox\bin\docker-machine.exe,inspect,Kalabox2
verbose: DOCKER MACHINE ==> Running ["inspect"]
debug: SHELL EXEC ==> Running command C:\Program Files\Kalabox\bin\docker-machine.exe,inspect,Kalabox2
Cannot read property 'AuthOptions' of undefined
error:  TypeError: Cannot read property 'AuthOptions' of undefined
    at C:\Program Files\Kalabox\bin\plugins\kalabox-engine-docker\provider\docker\machine.js.jx:272:34
From previous event:
    at Object.getEngineConfig [as engineConfig] (C:\Program Files\Kalabox\bin\plugins\kalabox-engine-docker\provider\docker\machine.js.jx:269:6)
    at C:\Program Files\Kalabox\bin\lib\engine.js.jx:57:23
From previous event:
    at C:\Program Files\Kalabox\bin\lib\engine.js.jx:54:6
From previous event:
    at Object.exports.provider (C:\Program Files\Kalabox\bin\lib\engine.js.jx:52:4)
    at Object.task.func (C:\Program Files\Kalabox\bin\plugins\kalabox-engine-docker\lib\tasks.js.jx:55:14)
    at Object.exports.run (C:\Program Files\Kalabox\bin\lib\core\tasks.js.jx:888:15)
    at processTask (C:\Program Files\Kalabox\bin\bin\kbox.js.jx:181:16)
    at Object.<anonymous> (C:\Program Files\Kalabox\bin\bin\kbox.js.jx:240:12)
    at process._tickCallback (node.js:917:13)
From previous event:
    at main (C:\Program Files\Kalabox\bin\bin\kbox.js.jx:239:4)
    at Object.<anonymous> (C:\Program Files\Kalabox\bin\bin\kbox.js.jx:248:1)
    at Module._compile (module.js:619:26)
    at readX (module.js:1645:5)
    at Object.Module._extensions..jx (module.js:2102:10)
    at Module.load (module.js:440:36)
    at Function.Module._load (module.js:405:12)
    at Module.require (module.js:475:17)
    at require (module.js:493:17)
    at Object.<anonymous> (_jx_source:17:3)
    at Module._compile (module.js:619:26)
    at Module.load (module.js:449:12)
    at Function.Module._load (module.js:405:12)
    at Function.Module.runMain (module.js:871:12)
    at startup (node.js:485:18)
    at node.js:1604:3
TypeError: Cannot read property 'AuthOptions' of undefined
    at C:\Program Files\Kalabox\bin\plugins\kalabox-engine-docker\provider\docker\machine.js.jx:272:34
From previous event:
    at Object.getEngineConfig [as engineConfig] (C:\Program Files\Kalabox\bin\plugins\kalabox-engine-docker\provider\docker\machine.js.jx:269:6)
    at C:\Program Files\Kalabox\bin\lib\engine.js.jx:57:23
From previous event:
    at C:\Program Files\Kalabox\bin\lib\engine.js.jx:54:6
From previous event:
    at Object.exports.provider (C:\Program Files\Kalabox\bin\lib\engine.js.jx:52:4)
    at Object.task.func (C:\Program Files\Kalabox\bin\plugins\kalabox-engine-docker\lib\tasks.js.jx:55:14)
    at Object.exports.run (C:\Program Files\Kalabox\bin\lib\core\tasks.js.jx:888:15)
    at processTask (C:\Program Files\Kalabox\bin\bin\kbox.js.jx:181:16)
    at Object.<anonymous> (C:\Program Files\Kalabox\bin\bin\kbox.js.jx:240:12)
    at process._tickCallback (node.js:917:13)
From previous event:
    at main (C:\Program Files\Kalabox\bin\bin\kbox.js.jx:239:4)
    at Object.<anonymous> (C:\Program Files\Kalabox\bin\bin\kbox.js.jx:248:1)
    at Module._compile (module.js:619:26)
    at readX (module.js:1645:5)
    at Object.Module._extensions..jx (module.js:2102:10)
    at Module.load (module.js:440:36)
    at Function.Module._load (module.js:405:12)
    at Module.require (module.js:475:17)
    at require (module.js:493:17)
    at Object.<anonymous> (_jx_source:17:3)
    at Module._compile (module.js:619:26)
    at Module.load (module.js:449:12)
    at Function.Module._load (module.js:405:12)
    at Function.Module.runMain (module.js:871:12)
    at startup (node.js:485:18)
    at node.js:1604:3
debug: METRICS ==> Reporting. action=error, message=Cannot read property 'AuthOptions' of undefined, stack=TypeError: Cannot read property 'AuthOptions' of undefined
    at C:\Program Files\Kalabox\bin\plugins\kalabox-engine-docker\provider\docker\machine.js.jx:272:34
From previous event:
    at Object.getEngineConfig [as engineConfig] (C:\Program Files\Kalabox\bin\plugins\kalabox-engine-docker\provider\docker\machine.js.jx:269:6)
    at C:\Program Files\Kalabox\bin\lib\engine.js.jx:57:23
From previous event:
    at C:\Program Files\Kalabox\bin\lib\engine.js.jx:54:6
From previous event:
    at Object.exports.provider (C:\Program Files\Kalabox\bin\lib\engine.js.jx:52:4)
    at Object.task.func (C:\Program Files\Kalabox\bin\plugins\kalabox-engine-docker\lib\tasks.js.jx:55:14)
    at Object.exports.run (C:\Program Files\Kalabox\bin\lib\core\tasks.js.jx:888:15)
    at processTask (C:\Program Files\Kalabox\bin\bin\kbox.js.jx:181:16)
    at Object.<anonymous> (C:\Program Files\Kalabox\bin\bin\kbox.js.jx:240:12)
    at process._tickCallback (node.js:917:13)
From previous event:
    at main (C:\Program Files\Kalabox\bin\bin\kbox.js.jx:239:4)
    at Object.<anonymous> (C:\Program Files\Kalabox\bin\bin\kbox.js.jx:248:1)
    at Module._compile (module.js:619:26)
    at readX (module.js:1645:5)
    at Object.Module._extensions..jx (module.js:2102:10)
    at Module.load (module.js:440:36)
    at Function.Module._load (module.js:405:12)
    at Module.require (module.js:475:17)
    at require (module.js:493:17)
    at Object.<anonymous> (_jx_source:17:3)
    at Module._compile (module.js:619:26)
    at Module.load (module.js:449:12)
    at Function.Module._load (module.js:405:12)
    at Function.Module.runMain (module.js:871:12)
    at startup (node.js:485:18)
    at node.js:1604:3, tags=[], mode=cli, devMode=false, version=0.13.0-beta.2, type=Windows_NT, platform=win32, release=6.3.9600, arch=x64, nodeVersion=v0.10.40, created=2016-07-21T15:55:59.264Z
`

**Comment by pirog** [comment]
And you have  `Kalabox2` VM inside of VirtualBox?

**Comment by shaal** [comment]
nope

**Comment by pirog** [comment]
Well, that definitely explains the error you are getting then. Did you get any errors during install?

**Comment by shaal** [comment]
install had no errors, I'll try uninstall everything, and then run install again

**Comment by pirog** [comment]
i would also check out our new docs site. there might are a few helpful pointers for troubleshooting there... specifically how to access the install logs
http://docs.kalabox.io/en/stable/troubleshooting/

**Comment by shaal** [comment]
after uninstalling and restarting (windows...)
installation went smooth, installation log looked good, and I have Kalabox2 in VirtualBox.

While the GUI seems to be stuck forever, I checked that kalabox status was up.
I tried creating a copy of a pantheon drupal website, and got this error.
(I think it's the same old old problem since ever, and wish i knew how to manually fix it)

```
kbox create pantheon
? Choose a Pantheon account: add a different token
? Enter a Pantheon machine token: *********************************************
? Which site? website
? Which environment? dev
? What will you call this monster you have created: website
Creating.
Cleaning up.
Creating app structure.
Configuring app.
Running pre create tasks.
Starting app.
Starting.
Cleaning up.
Running pre start tasks.
Starting containers.
Pulling redis (redis:2.8)...
ERROR: Network timed out while trying to connect to https://index.docker.io/v1/repositories/library/redis/images. You may want to check your internet connection or if you are behind a proxy.
code1err:more:Pulling repository docker.io/library/redis

VError: code1err:more:Pulling repository docker.io/library/redis

    at ChildProcess.<anonymous> (C:\Program Files\Kalabox\bin\lib\util\shell.js.jx:149:16)
    at ChildProcess.emit (events.js:85:17)
    at maybeClose (child_process.js:773:16)
    at Process.ChildProcess._handle.onexit (child_process.js:839:5)
From previous event:
    at Object.exports.spawn (C:\Program Files\Kalabox\bin\lib\util\shell.js.jx:100:10)
    at Object.sh (C:\Program Files\Kalabox\bin\plugins\kalabox-engine-docker\provider\docker\lib\bin.js.jx:104:20)
    at shCompose (C:\Program Files\Kalabox\bin\plugins\kalabox-engine-docker\provider\docker\compose.js.jx:61:16)
    at Object.up [as start] (C:\Program Files\Kalabox\bin\plugins\kalabox-engine-docker\provider\docker\compose.js.jx:257:12)
    at C:\Program Files\Kalabox\bin\plugins\kalabox-engine-docker\index.js.jx:124:22
From previous event:
    at Object.start (C:\Program Files\Kalabox\bin\plugins\kalabox-engine-docker\index.js.jx:123:20)
From previous event:
    at C:\Program Files\Kalabox\bin\lib\engine.js.jx:455:29
From previous event:
    at Object.exports.start (C:\Program Files\Kalabox\bin\lib\engine.js.jx:454:4)
    at C:\Program Files\Kalabox\bin\lib\app.js.jx:614:19
From previous event:
    at Object.exports.start (C:\Program Files\Kalabox\bin\lib\app.js.jx:612:4)
    at C:\Program Files\Kalabox\bin\lib\create.js.jx:362:25
From previous event:
    at C:\Program Files\Kalabox\bin\lib\create.js.jx:360:8
    at process._tickCallback (node.js:917:13)
From previous event:
    at createApp (C:\Program Files\Kalabox\bin\lib\create.js.jx:332:6)
    at PromptUI.completed (C:\Program Files\Kalabox\bin\lib\create.js.jx:463:16)
    at PromptUI.onCompletion (C:\Program Files\Kalabox\bin\node_modules\inquirer\lib\ui\prompt.js.jx:68:10)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (C:\Program Files\Kalabox\bin\node_modules\inquirer\node_modules\rx\dist\rx.js.jx:1792:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (C:\Program Files\Kalabox\bin\node_modules\inquirer\node_modules\rx\dist\rx.js.jx:1729:14)
    at AnonymousObserver.tryCatcher (C:\Program Files\Kalabox\bin\node_modules\inquirer\node_modules\rx\dist\rx.js.jx:566:29)
    at AutoDetachObserverPrototype.completed (C:\Program Files\Kalabox\bin\node_modules\inquirer\node_modules\rx\dist\rx.js.jx:5287:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (C:\Program Files\Kalabox\bin\node_modules\inquirer\node_modules\rx\dist\rx.js.jx:1729:14)
    at InnerObserver.onCompleted (C:\Program Files\Kalabox\bin\node_modules\inquirer\node_modules\rx\dist\rx.js.jx:3424:65)
    at InnerObserver.tryCatcher (C:\Program Files\Kalabox\bin\node_modules\inquirer\node_modules\rx\dist\rx.js.jx:566:29)
    at AutoDetachObserverPrototype.completed (C:\Program Files\Kalabox\bin\node_modules\inquirer\node_modules\rx\dist\rx.js.jx:5287:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (C:\Program Files\Kalabox\bin\node_modules\inquirer\node_modules\rx\dist\rx.js.jx:1729:14)
    at AutoDetachObserver.tryCatcher (C:\Program Files\Kalabox\bin\node_modules\inquirer\node_modules\rx\dist\rx.js.jx:566:29)
    at AutoDetachObserverPrototype.completed (C:\Program Files\Kalabox\bin\node_modules\inquirer\node_modules\rx\dist\rx.js.jx:5287:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (C:\Program Files\Kalabox\bin\node_modules\inquirer\node_modules\rx\dist\rx.js.jx:1729:14)
    at InnerObserver.onCompleted (C:\Program Files\Kalabox\bin\node_modules\inquirer\node_modules\rx\dist\rx.js.jx:3424:65)
    at InnerObserver.tryCatcher (C:\Program Files\Kalabox\bin\node_modules\inquirer\node_modules\rx\dist\rx.js.jx:566:29)
    at AutoDetachObserverPrototype.completed (C:\Program Files\Kalabox\bin\node_modules\inquirer\node_modules\rx\dist\rx.js.jx:5287:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (C:\Program Files\Kalabox\bin\node_modules\inquirer\node_modules\rx\dist\rx.js.jx:1729:14)
```

**Comment by pirog** [comment]
@shaal not sure if you saw the release email but yeah the GUI does not currently work on Windows. It's our top priority. https://github.com/kalabox/kalabox/issues/1435

That looks slightly different than the error you've gotten in the past. I think beforehand you couldn't even resolve the docker.hub (ie a dns issue) and now it seems like maybe you don't even have access to the internet inside the VM?

**Comment by shaal** [comment]
I went into the Virtualbox Kalabox2 machine,
I can run ping successfully, and i was able to run
`wget index.docker.io/v1/repositories/library/redis/images` successfully as well.

**Comment by pirog** [comment]
hmmm that is even more confusing then since we are running command directly in the VM. 

Can you do `docker pull redis` in the VM?

**Comment by shaal** [comment]
I tried running the command twice in the VM, here's the screenshot of the result -

![docker pull redis3](https://cloud.githubusercontent.com/assets/22901/17034812/4a6811bc-4f52-11e6-8624-a4a62f43dd10.png)

**Comment by shaal** [comment]
I waited 2 minutes, and run the same command again.
now it looks like it was successful.

![docker pull redis4](https://cloud.githubusercontent.com/assets/22901/17034981/0e07efca-4f53-11e6-8cc5-dc4ebeaa9c2f.png)

**Comment by pirog** [comment]
@shaal can you actually open up a separate issue for this and report this stuff? 

from what youve pasted so far this does look more like the original DNS issue you had although it looks like the DNS is working... just not consistently. combined with the timeout in your first attempt im guessing maybe your host is just not resolving these requests within the allotted time?
