### ISSUE TITLE
(node) warning: possible EventEmitter memory leak detected on DB push

### ISSUE THREAD

**Issue by jserrao** [kalabox/kalabox#1502]
Bug Report
==========

What is your Kalabox version and operating system?
v0.13.0-beta.3 on OSX 10.11.6

Have you previously installed Kalabox? If so, what version?
Yes, but I uninstalled as best I could to try out beta3 cleanly (others versions haven't been stable enough for me so far to use productively).

Bug:
Using `kbox push` to dev for both code and DB, I received the following error (2x) once for pushing code and once for pushing the DB:

```
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at ReadStream.addListener (events.js:140:15)
    at ReadStream.Stream.pipe (stream.js:96:10)
    at /Applications/Kalabox.app/Contents/MacOS/bin/plugins/kalabox-engine-docker/provider/docker/docker.js.jx:319:25
    at tryCatcher (/Applications/Kalabox.app/Contents/MacOS/bin/node_modules/bluebird/js/main/util.js.jx:25:23)
    at Promise._settlePromiseFromHandler (/Applications/Kalabox.app/Contents/MacOS/bin/node_modules/bluebird/js/main/promise.js.jx:506:31)
    at Promise._settlePromiseAt (/Applications/Kalabox.app/Contents/MacOS/bin/node_modules/bluebird/js/main/promise.js.jx:580:18)
    at Promise._settlePromises (/Applications/Kalabox.app/Contents/MacOS/bin/node_modules/bluebird/js/main/promise.js.jx:696:14)
    at Async._drainQueue (/Applications/Kalabox.app/Contents/MacOS/bin/node_modules/bluebird/js/main/async.js.jx:122:16)
    at Async._drainQueues (/Applications/Kalabox.app/Contents/MacOS/bin/node_modules/bluebird/js/main/async.js.jx:132:10)
    at Async.drainQueues (/Applications/Kalabox.app/Contents/MacOS/bin/node_modules/bluebird/js/main/async.js.jx:14:14)
    at process._tickCallback (node.js:917:13)
```

```
Pushing files.
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at ReadStream.addListener (events.js:140:15)
    at ReadStream.Stream.pipe (stream.js:50:12)
    at /Applications/Kalabox.app/Contents/MacOS/bin/plugins/kalabox-engine-docker/provider/docker/docker.js.jx:319:25
    at tryCatcher (/Applications/Kalabox.app/Contents/MacOS/bin/node_modules/bluebird/js/main/util.js.jx:25:23)
    at Promise._settlePromiseFromHandler (/Applications/Kalabox.app/Contents/MacOS/bin/node_modules/bluebird/js/main/promise.js.jx:506:31)
    at Promise._settlePromiseAt (/Applications/Kalabox.app/Contents/MacOS/bin/node_modules/bluebird/js/main/promise.js.jx:580:18)
    at Promise._settlePromises (/Applications/Kalabox.app/Contents/MacOS/bin/node_modules/bluebird/js/main/promise.js.jx:696:14)
    at Async._drainQueue (/Applications/Kalabox.app/Contents/MacOS/bin/node_modules/bluebird/js/main/async.js.jx:122:16)
    at Async._drainQueues (/Applications/Kalabox.app/Contents/MacOS/bin/node_modules/bluebird/js/main/async.js.jx:132:10)
    at Async.drainQueues (/Applications/Kalabox.app/Contents/MacOS/bin/node_modules/bluebird/js/main/async.js.jx:14:14)
    at process._tickCallback (node.js:917:13)
```

This seems to be a non-critical error as both my code and DB made the jump. It just looks like you need to increase the memory available to bluebird.js with `emitter.setMaxListeners()` according to the error.

**Comment by pirog** [comment]
Yeah this is just a warning and should be non-critical

**Comment by jserrao** [comment]
Thanks, this version seems a lot more stable. You're doing something right.

**Comment by pirog** [comment]
@jserrao what version are you upgrading from?

**Comment by jserrao** [comment]
beta1. After 20-30 minutes on the old beta, I would almost always have to do `kbox down` then `kbox up` to stop the process as it became unstable. You've fixed that, which was a blocking bug for me. I'll keep testing but it's stable so far.

**Comment by pirog** [comment]
awesome! we've gotten similar feedback from others and are pretty excited to be moving into a more stable state.

**Comment by pirog** [comment]
@jserrao so strangely i only get this warning using the compiled `kbox` binary. Running the CLI from source seems to work ok.

**Comment by jserrao** [comment]
Did you recompile this into a nightly? I can retest if you like.

**Comment by pirog** [comment]
@jserrao we don't have a nightly but we do roll a dev release with every commit merged into each version branch so this fix should be available. Links to the dev releases should be on the main readme.

**Comment by jserrao** [comment]
Ok cool, I'll try and test if I have some time this week.

**Comment by pirog** [comment]
@jserrao thanks! sounds good!

**Comment by jserrao** [comment]
@pirog - I can confirm after multiple `kbox pull` + `kbox push`, this error is no longer occurring on v0.13.0-beta.4 on OSX 10.11.6.

**Comment by pirog** [comment]
@jserrao huzzah!

**Comment by bianqui149** [comment]
I have the same issue in OS 10.13.4. Do you have the solution?
