### ISSUE TITLE
Tag 70 not found in repository docker.io/kalabox/pantheon-appserver

### ISSUE THREAD

**Issue by mustela** [kalabox/kalabox#1527]
Guys I'm trying to pull a website from pantheon and I'm getting 

```
Creating.
Cleaning up.
Creating app structure.
Configuring app.
Running pre create tasks.
Starting app.
Starting.
Cleaning up.
Running pre start tasks.
Starting containers.
Pulling appserver (kalabox/pantheon-appserver:70)...
ERROR: Tag 70 not found in repository docker.io/kalabox/pantheon-appserver
code1err:more:Pulling repository docker.io/kalabox/pantheon-appserver

VError: code1err:more:Pulling repository docker.io/kalabox/pantheon-appserver

    at ChildProcess.<anonymous> (/Applications/Kalabox.app/Contents/MacOS/bin/lib/util/shell.js.jx:149:16)
    at ChildProcess.emit (events.js:85:17)
    at maybeClose (child_process.js:773:16)
    at Process.ChildProcess._handle.onexit (child_process.js:839:5)
From previous event:
    at Object.exports.spawn (/Applications/Kalabox.app/Contents/MacOS/bin/lib/util/shell.js.jx:100:10)
    at Object.sh (/Applications/Kalabox.app/Contents/MacOS/bin/plugins/kalabox-engine-docker/provider/docker/lib/bin.js.jx:104:20)
    at shCompose (/Applications/Kalabox.app/Contents/MacOS/bin/plugins/kalabox-engine-docker/provider/docker/compose.js.jx:61:16)
    at Object.up [as start] (/Applications/Kalabox.app/Contents/MacOS/bin/plugins/kalabox-engine-docker/provider/docker/compose.js.jx:257:12)
    at /Applications/Kalabox.app/Contents/MacOS/bin/plugins/kalabox-engine-docker/index.js.jx:124:22
From previous event:
    at Object.start (/Applications/Kalabox.app/Contents/MacOS/bin/plugins/kalabox-engine-docker/index.js.jx:123:20)
From previous event:
    at /Applications/Kalabox.app/Contents/MacOS/bin/lib/engine.js.jx:455:29
From previous event:
    at Object.exports.start (/Applications/Kalabox.app/Contents/MacOS/bin/lib/engine.js.jx:454:4)
    at /Applications/Kalabox.app/Contents/MacOS/bin/lib/app.js.jx:614:19
From previous event:
    at Object.exports.start (/Applications/Kalabox.app/Contents/MacOS/bin/lib/app.js.jx:612:4)
    at /Applications/Kalabox.app/Contents/MacOS/bin/lib/create.js.jx:362:25
From previous event:
    at /Applications/Kalabox.app/Contents/MacOS/bin/lib/create.js.jx:360:8
    at process._tickCallback (node.js:917:13)
From previous event:
    at createApp (/Applications/Kalabox.app/Contents/MacOS/bin/lib/create.js.jx:332:6)
    at PromptUI.completed (/Applications/Kalabox.app/Contents/MacOS/bin/lib/create.js.jx:463:16)
    at PromptUI.onCompletion (/Applications/Kalabox.app/Contents/MacOS/bin/node_modules/inquirer/lib/ui/prompt.js.jx:68:10)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (/Applications/Kalabox.app/Contents/MacOS/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:1792:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/Applications/Kalabox.app/Contents/MacOS/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:1729:14)
    at AnonymousObserver.tryCatcher (/Applications/Kalabox.app/Contents/MacOS/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:566:29)
    at AutoDetachObserverPrototype.completed (/Applications/Kalabox.app/Contents/MacOS/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:5287:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/Applications/Kalabox.app/Contents/MacOS/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:1729:14)
    at InnerObserver.onCompleted (/Applications/Kalabox.app/Contents/MacOS/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:3424:65)
    at InnerObserver.tryCatcher (/Applications/Kalabox.app/Contents/MacOS/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:566:29)
    at AutoDetachObserverPrototype.completed (/Applications/Kalabox.app/Contents/MacOS/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:5287:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/Applications/Kalabox.app/Contents/MacOS/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:1729:14)
    at AutoDetachObserver.tryCatcher (/Applications/Kalabox.app/Contents/MacOS/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:566:29)
    at AutoDetachObserverPrototype.completed (/Applications/Kalabox.app/Contents/MacOS/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:5287:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/Applications/Kalabox.app/Contents/MacOS/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:1729:14)
    at InnerObserver.onCompleted (/Applications/Kalabox.app/Contents/MacOS/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:3424:65)
    at InnerObserver.tryCatcher (/Applications/Kalabox.app/Contents/MacOS/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:566:29)
    at AutoDetachObserverPrototype.completed (/Applications/Kalabox.app/Contents/MacOS/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:5287:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/Applications/Kalabox.app/Contents/MacOS/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:1729:14)
```

So it seems you have removed the `70 tag`: https://hub.docker.com/r/kalabox/pantheon-appserver/tags/

I'm using: Kalabox: v0.1.12.0-beta3 on OS X El Capitan 10.11.6

**Comment by pirog** [comment]
@mustela we never had `70` tags. Pantheon recently added some new php versions which we do not support yet. Def +1 this issue though so we can get support from them to add them.
https://github.com/kalabox/kalabox/issues/1383

That said, we've put in a resolution to default to 5.5 in the meantime for sites that are running pantheons new 5.6 or 7.0 see: #1500 

You also can manually set the pantheon php version via terminus to either 5.3/5.5 and re pull your site or manually change the kalabox version and `kbox rebuild && kbox pull` 
http://pantheon.kalabox.io/en/stable/users/config/

**Comment by pembo13** [comment]
I see this is closed, but I'm having a similar issue, and I'm not clear what the resolution is from #1500 

```
Pulling appserver (kalabox/pantheon-appserver:56)...
Pulling image kalabox/pantheon-appserver.
ERROR: Tag 56 not found in repository docker.io/kalabox/pantheon-appserver
2.8: Pulling from library/redis
Digest: sha256:fe38fdf76ed2a547550bc3702f33e5d65cb0d474d80b58182f53864ec24d012b
Status: Downloaded newer image for redis:2.8
latest: Pulling from library/busybox
Digest: sha256:98a0bd48d22ff96ca23bfda2fe1cf72034ea803bd79e64a5a5f274aca0f9c51c
Status: Downloaded newer image for busybox:latest
stable: Pulling from kalabox/pantheon-solr
Digest: sha256:4b038360c8df69052e8a168ac62686b62ebd932ebba22bb2f01ee30f233b4871
Status: Downloaded newer image for kalabox/pantheon-solr:stable
5.5: Pulling from library/mariadb
Digest: sha256:b62c821322c72fd3794cab9e58d80957bb54f0d06ca567216a2bcd9814ac01fb
Status: Downloaded newer image for mariadb:5.5
56: Pulling from kalabox/pantheon-appserver
Pulling repository docker.io/kalabox/pantheon-appserver

2.8: Pulling from library/redis
Digest: sha256:fe38fdf76ed2a547550bc3702f33e5d65cb0d474d80b58182f53864ec24d012b
Status: Downloaded newer image for redis:2.8
latest: Pulling from library/busybox
Digest: sha256:98a0bd48d22ff96ca23bfda2fe1cf72034ea803bd79e64a5a5f274aca0f9c51c
Status: Downloaded newer image for busybox:latest
stable: Pulling from kalabox/pantheon-solr
Digest: sha256:4b038360c8df69052e8a168ac62686b62ebd932ebba22bb2f01ee30f233b4871
Status: Downloaded newer image for kalabox/pantheon-solr:stable
5.5: Pulling from library/mariadb
Digest: sha256:b62c821322c72fd3794cab9e58d80957bb54f0d06ca567216a2bcd9814ac01fb
Status: Downloaded newer image for mariadb:5.5
56: Pulling from kalabox/pantheon-appserver
Pulling repository docker.io/kalabox/pantheon-appserver
: 2.8: Pulling from library/redis
Digest: sha256:fe38fdf76ed2a547550bc3702f33e5d65cb0d474d80b58182f53864ec24d012b
Status: Downloaded newer image for redis:2.8
latest: Pulling from library/busybox
Digest: sha256:98a0bd48d22ff96ca23bfda2fe1cf72034ea803bd79e64a5a5f274aca0f9c51c
Status: Downloaded newer image for busybox:latest
stable: Pulling from kalabox/pantheon-solr
Digest: sha256:4b038360c8df69052e8a168ac62686b62ebd932ebba22bb2f01ee30f233b4871
Status: Downloaded newer image for kalabox/pantheon-solr:stable
5.5: Pulling from library/mariadb
Digest: sha256:b62c821322c72fd3794cab9e58d80957bb54f0d06ca567216a2bcd9814ac01fb
Status: Downloaded newer image for mariadb:5.5
56: Pulling from kalabox/pantheon-appserver
Pulling repository docker.io/kalabox/pantheon-appserver

    at buildVerror (/usr/share/kalabox/bin/lib/util/shell.js.jx:52:10)
    at ChildProcess.<anonymous> (/usr/share/kalabox/bin/lib/util/shell.js.jx:163:16)
    at ChildProcess.emit (events.js:85:17)
    at maybeClose (child_process.js:773:16)
    at Process.ChildProcess._handle.onexit (child_process.js:839:5)
```

**Comment by pirog** [comment]
tag definitely exists: https://hub.docker.com/r/kalabox/pantheon-appserver/tags/

is it possible you had intermittent internet?

**Comment by pembo13** [comment]
There's a possibility, though I didn't notice any internet problems form that machine. I'll retry and report back. Just to be clear, I should be using the stable .RPM builds off of the main website, correct?

**Comment by pirog** [comment]
@pembo13 yup, or the experimental branch in the github releases which should be relatively unchanged for linux.

that said, the RPM based versions are a little bit of a question mark. We have very few people using  this on Fedora/Centos so its probably a little more wild west at this point.
