### ISSUE TITLE
rc2 - 403 on app create

### ISSUE THREAD

**Issue by labboy0276** [kalabox/kalabox#1583]
Bug Report
==========

**Tell us about your setup**

What is your Kalabox version and operating system?

Kalabox v0.13.0-rc2 - Ubuntu 16.04 

Have you previously installed Kalabox? If so, what version?

Yes all, although I purged on rc2

**Tell us about your bug**

Purged the system and installed rc2, tried to create an app and I get a 403 error:

```
john@kalamuna:~/.kalabox/apps$ kbox create pantheon
? Choose a Pantheon account: john@kalamuna.com
? Which site? huddle
? Which environment? newforms
? What will you call this monster you have created: huddle
Creating.
Cleaning up.
Creating app structure.
Configuring app.
Running pre create tasks.
Starting app.
Starting.
Cleaning up.
Running pre start tasks.
Starting containers.
Creating huddle_redis_1
Creating huddle_data_1
Creating huddle_solr_1
Creating huddle_db_1
Creating huddle_appserver_1
Creating huddle_cli_1
Creating huddle_terminus_1
Creating huddle_web_1
Creating huddle_edge_1
Running post start tasks.
kalabox_proxy_1 is up-to-date
kalabox_dns_1 is up-to-date
Running post create tasks.
[2016-09-14 13:47:55] [info] An update to Terminus is available. Please update to 0.12.0.
    version: '0.12.0'
[2016-09-14 13:47:56] [info] Added SSH key from file /home/1000/keys/pantheon.kalabox.id_rsa.pub.
    file: '/home/1000/keys/pantheon.kalabox.id_rsa.pub'
Pulling screenshot.
Failed after 5 retries. {"max":5,"backoff":500}: Response code 403 (Forbidden)
HTTPError: Response code 403 (Forbidden)
    at EventEmitter.<anonymous> (/usr/share/kalabox/bin/node_modules/download/node_modules/got/index.js.jx:191:24)
    at EventEmitter.emit (events.js:82:17)
    at Object._onImmediate (/usr/share/kalabox/bin/node_modules/download/node_modules/got/index.js.jx:57:8)
    at processImmediate [as _immediateCallback] (timers.js:370:15)
```

Please detail the steps we can take to replicate this bug. Be as detailed as possible.
1. purge system of rc1 (I also manually deleted /usr/local/bin/kbox && /usr/share/kalabox)
2. install rc2
3. Try and create an app

**Comment by dalin-** [comment]
I'm running into the same error:

```
~/Sites dave ☼ kbox create pantheon -- --nofiles
? Choose a Pantheon account: dave@advomatic.com
? Which site? episcopalassetmap
? Which environment? refresh
? What will you call this monster you have created: episcopalassetmap
Creating.
Cleaning up.
Creating app structure.
Configuring app.
Running pre create tasks.
Starting app.
Starting.
Cleaning up.
Running pre start tasks.
Starting containers.
Pulling redis (redis:2.8)...
Pulling image library/redis.
Pulling data (busybox:latest)...
Pulling image library/busybox.
Pulling solr (kalabox/pantheon-solr:stable)...
Pulling image kalabox/pantheon-solr.
Pulling db (mariadb:5.5)...
Pulling image library/mariadb.
Pulling appserver (kalabox/pantheon-appserver:55)...
Pulling image kalabox/pantheon-appserver.
Pulling cli (kalabox/cli:stable)...
Pulling image kalabox/cli.
Pulling terminus (kalabox/terminus:0.11.2)...
Pulling image kalabox/terminus.
Pulling web (nginx:1.8.1)...
Pulling image library/nginx.
Pulling edge (kalabox/pantheon-edge:stable)...
Pulling image kalabox/pantheon-edge.
Pulling unison (kalabox/unison:stable)...
Pulling image kalabox/unison.
Creating episcopalassetmap_data_1
Creating episcopalassetmap_redis_1
Creating episcopalassetmap_unison_1
Creating episcopalassetmap_solr_1
Creating episcopalassetmap_web_1
Creating episcopalassetmap_db_1
Creating episcopalassetmap_cli_1
Creating episcopalassetmap_edge_1
Creating episcopalassetmap_appserver_1
Creating episcopalassetmap_terminus_1
Running post start tasks.
kalabox_proxy_1 is up-to-date
kalabox_dns_1 is up-to-date
Running post create tasks.
[2016-09-14 17:09:24] [info] An update to Terminus is available. Please update to 0.12.0.
    version: '0.12.0'
[2016-09-14 17:09:24] [info] Added SSH key from file /home/1000/keys/pantheon.kalabox.id_rsa.pub.
    file: '/home/1000/keys/pantheon.kalabox.id_rsa.pub'
Pulling screenshot.
Failed after 5 retries. {"max":5,"backoff":500}: Response code 403 (Forbidden)
HTTPError: Response code 403 (Forbidden)
    at EventEmitter.<anonymous> (/Applications/Kalabox.app/Contents/MacOS/bin/node_modules/download/node_modules/got/index.js.jx:191:24)
    at EventEmitter.emit (events.js:82:17)
    at Object._onImmediate (/Applications/Kalabox.app/Contents/MacOS/bin/node_modules/download/node_modules/got/index.js.jx:57:8)
    at processImmediate [as _immediateCallback] (timers.js:370:15)
```
If I try to access in the browser I get a 500 error. If I restart the app it also hangs on the last step:

```
~/Sites/episcopalassetmap/code dave ☼ kbox restart
Stopping.
Cleaning up.
Running pre stop tasks.
Stopping containers.
Stopping episcopalassetmap_appserver_1 ... done
Stopping episcopalassetmap_edge_1 ... done
Stopping episcopalassetmap_web_1 ... done
Stopping episcopalassetmap_db_1 ... done
Stopping episcopalassetmap_solr_1 ... done
Stopping episcopalassetmap_unison_1 ... done
Stopping episcopalassetmap_redis_1 ... done
Running post stop tasks.
Starting.
Cleaning up.
Running pre start tasks.
Starting containers.
Starting episcopalassetmap_redis_1
Starting episcopalassetmap_data_1
Starting episcopalassetmap_unison_1
Starting episcopalassetmap_solr_1
Starting episcopalassetmap_web_1
Starting episcopalassetmap_db_1
Starting episcopalassetmap_cli_1
Starting episcopalassetmap_terminus_1
Starting episcopalassetmap_appserver_1
Starting episcopalassetmap_edge_1
Running post start tasks.
kalabox_proxy_1 is up-to-date
kalabox_dns_1 is up-to-date
Waiting for site to be ready.
```

It looks like we're both trying to create from multi-dev environments.  I wonder if that's the cause. Here's more info about this app:

```
~/Sites/episcopalassetmap/code dave ☼ kbox config
{
  "appRegistry": "/Users/dave/.kalabox/appRegistry.json",
  "appRoot": "/Users/dave/Sites/episcopalassetmap",
  "appsRoot": "/Users/dave/.kalabox/apps",
  "configSources": [
    "/Applications/Kalabox.app/Contents/MacOS/bin/kalabox.yml",
    "/Applications/Kalabox.app/Contents/MacOS/kalabox.yml",
    "/Users/dave/Sites/episcopalassetmap/kalabox.yml",
    "DEFAULT_GLOBAL_CONFIG",
    "ENV_CONFIG"
  ],
  "devMode": false,
  "domain": "kbox",
  "downloadsRoot": "/Users/dave/.kalabox/downloads",
  "engine": "kalabox-engine-docker",
  "engineGid": 50,
  "engineId": 1000,
  "engineRepo": "kalabox",
  "globalPlugins": [
    "kalabox-core",
    "kalabox-cmd",
    "kalabox-services-kalabox",
    "kalabox-sharing",
    "kalabox-ui",
    "kalabox-app-pantheon",
    "kalabox-app-php"
  ],
  "home": "/Users/dave",
  "imgVersion": "latest",
  "isBinary": true,
  "isNW": false,
  "logLevel": "debug",
  "logLevelConsole": "none",
  "logRoot": "/Users/dave/.kalabox/logs",
  "name": "episcopalassetmap",
  "os": {
    "type": "Darwin",
    "platform": "darwin",
    "release": "15.6.0",
    "arch": "x64"
  },
  "pluginconfig": {
    "cli": "on",
    "services": {
      "web": [
        {
          "port": "8888/tcp",
          "default": true
        },
        {
          "port": "444/tcp",
          "default": true,
          "secure": true
        }
      ],
      "edge": [
        {
          "port": "80/tcp",
          "hostname": "edge"
        },
        {
          "port": "443/tcp",
          "hostname": "edge",
          "secure": true
        }
      ]
    },
    "pantheon": {
      "site": "episcopalassetmap",
      "env": "refresh",
      "uuid": "2bfe76e3-a6ad-4217-8160-53e6ab12ab46",
      "framework": "drupal",
      "upstream": {
        "url": "https://github.com/pantheon-systems/drops-7",
        "branch": "master"
      },
      "images": "v0.13.0-rc.2",
      "php": 55,
      "name": "Dave Hansen-Lange",
      "email": "dave@advomatic.com"
    }
  },
  "plugins": [
    "kalabox-plugin-pantheon"
  ],
  "srcRoot": "/Applications/Kalabox.app/Contents/MacOS/bin",
  "stats": {
    "report": true,
    "url": "http://stats-v2.kalabox.io"
  },
  "sysConfRoot": "/Applications/Kalabox.app/Contents/MacOS",
  "sysPluginRoot": "/Applications/Kalabox.app/Contents/MacOS",
  "type": "pantheon",
  "userConfRoot": "/Users/dave/.kalabox",
  "userPluginRoot": "/Users/dave/.kalabox",
  "version": "0.13.0-rc.2",
  "homeBind": "/Users/dave",
  "sharing": {
    "codeDir": "code",
    "ignore": [
      "Name sites/default/files",
      "Name .DS_Store",
      "Name ._*",
      "Name .sass-cache",
      "Name Thumbs.db",
      "Name ehthumbs.db"
    ],
    "share": "data:/code",
    "codeRoot": "/Users/dave/Sites/episcopalassetmap/code"
  }
}
~/Sites/episcopalassetmap/code dave ☼ kbox services
[
  {
    "name": "appserver",
    "project": "episcopalassetmap"
  },
  {
    "name": "edge",
    "project": "episcopalassetmap",
    "url": [
      "http://edge.episcopalassetmap.kbox",
      "https://edge.episcopalassetmap.kbox"
    ]
  },
  {
    "name": "web",
    "project": "episcopalassetmap",
    "url": [
      "http://episcopalassetmap.kbox",
      "https://episcopalassetmap.kbox"
    ]
  },
  {
    "name": "db",
    "project": "episcopalassetmap",
    "external_connection_info": {
      "database": "pantheon",
      "user": "pantheon",
      "password": "pantheon",
      "host": "episcopalassetmap.kbox",
      "port": "32768"
    }
  },
  {
    "name": "solr",
    "project": "episcopalassetmap"
  },
  {
    "name": "unison",
    "project": "episcopalassetmap"
  },
  {
    "name": "redis",
    "project": "episcopalassetmap"
  }
]
```

**Comment by pirog** [comment]
@labboy0276 @dalin- this happens when your pantheon env does not have a screenshot. 

I am going to reroll the RC2 (which is still pre-release btw!!!) to have a fallback for this. It should be an hour or so before we post it, TravisCI willing.

**Comment by pirog** [comment]
https://github.com/kalabox/kalabox/releases/tag/v0.13.0-rc.2 <--- that should have the fix for the 403 error
