### ISSUE TITLE
Cannot find module 'lodash'

### ISSUE THREAD

**Issue by grshane** [kalabox/kalabox#1627]
Please complete the following steps. **The more steps you complete the more
likely we are to address your issue!**

1. Please review the [current list of issues](https://github.com/kalabox/kalabox/issues) to make sure you are not submitting a duplicate.
2. Please tag your issue appropriately. Please review the [tagging criteria](https://github.com/kalabox/kalabox/blob/HEAD/CONTRIBUTING.md).
3. Based on the issue type tag selected above please fill in the relevant section below.

Bug Report
==========

**Tell us about your setup**

What is your Kalabox version and operating system?
Kalabox 2.0 on Mac 10.11.6
Have you previously installed Kalabox? If so, what version?

Yes, I've installed Kalabox v0.130-rc2 and previous versions

Give a brief description of what happened, including any error messages that appeared.

I try to run any `kbox` command and get 

`kalabox-plugin-php -> Cannot find module 'lodash'
Error: kalabox-plugin-php -> Cannot find module 'lodash'
    at Function.Module._oldRes (module.js:800:15)
    at Function.Module._resolveFilename (module.js:1965:17)
    at Function.Module._load (module.js:360:25)
    at Module.require (module.js:475:17)
    at require (module.js:493:17)
    at module.exports (/Users/grshane/holistic-horse/plugins/kalabox-plugin-php/lib/events.js:11:11)
    at module.exports (/Users/grshane/holistic-horse/plugins/kalabox-plugin-php/index.js:5:29)
    at Promise.try.catch.warning (/Applications/Kalabox.app/Contents/MacOS/bin/lib/require.js.jx:276:20)
    at /Applications/Kalabox.app/Contents/MacOS/bin/lib/require.js.jx:275:29
    at process._tickCallback (node.js:917:13)`

Please detail the steps we can take to replicate this bug. Be as detailed as possible.

> 1. Ran 2.0 installer.
> 2. 'kbox up'
> 3. Recieved error.
> 4. Ran uninstall.sh for 2.0
> 5. Ran uninstall.sh for 0.13-rc2
> 6. Ran 2.0 installer again
> 7. 'kbox up'
>8. Same error. 

Does this bug prevent you from using Kalabox?
Yes

**Comment by grshane** [comment]
I removed the `/Users/grshane/holistic-horse` directory and it cleared up the issue. I got the `kbox up` to run. 

Issue reappeared after:
> 1. Using GUI to create new WordPress app
`kalabox-plugin-php -> Cannot find module 'lodash'
Error: kalabox-plugin-php -> Cannot find module 'lodash'
    at Function.Module._oldRes (module.js:800:15)
    at Function.Module._resolveFilename (module.js:1965:17)
    at Function.Module._load (module.js:360:25)
    at Module.require (module.js:475:17)
    at require (module.js:493:17)
    at module.exports (/Users/grshane/.kalabox/apps/holistic-horse/plugins/kalabox-plugin-php/lib/events.js:11:11)
    at module.exports (/Users/grshane/.kalabox/apps/holistic-horse/plugins/kalabox-plugin-php/index.js:5:29)
    at Promise.try.catch.warning (/Applications/Kalabox.app/Contents/MacOS/bin/lib/require.js.jx:276:20)
    at /Applications/Kalabox.app/Contents/MacOS/bin/lib/require.js.jx:275:29
    at process._tickCallback (node.js:917:13)`

**Comment by pirog** [comment]
@grshane did you download or clone an older version of the `kalabox-app-php` plugin at some point? 

It looks like your app is being create from a skeleton that does not have its NPM dependencies properly installed. Do you have anything in `~/.kalabox/plugins`? or `kalabox-app-php` installed globally? Were you able to run previous versions?
