### ISSUE TITLE
Push to Pantheon, no updates

### ISSUE THREAD

**Issue by defaria** [kalabox/kalabox#1633]
Bug Report
==========

**Tell us about your setup**

What is your Kalabox version and operating system?

Version 2.0.0 (2.0.0)
Mac OS X 10.11.6

Have you previously installed Kalabox? If so, what version?

No

Installed Kalabox
Add pantheon account
pulled multidev account to local,
made changes,
pushed code back to pantheon (same multidev branch)

no errors,
no warnings,
but also no changes in pantheon account

I can't see the commit, and not files were updated.

**Comment by pirog** [comment]
@defaria is there any chance you are experiencing the same thing as this?
https://github.com/kalabox/kalabox/issues/1615

**Comment by anthemwild** [comment]
Getting the same issue...I've tried pushing several times from different networks. No updates in Pantheon. No errors from Kalabox.

**Comment by pirog** [comment]
@anthemwild i would try pushing from the kalabox cli with the debug flag on. This should give you some more output about what is going on.

`kbox push -- -d`

**Comment by anthemwild** [comment]
Sorry...new to Kalabox and Pantheon. I'm getting this error...

`debug: KBOX TERMINUS ==> Terminus returned: []
Cannot read property 'mysql_command' of undefined
TypeError: Cannot read property 'mysql_command' of undefined
    at /Users/vickerr/.kalabox/apps/jjs/plugins/kalabox-plugin-pantheon/lib/push.js:98:40
error:  TypeError: Cannot read property 'mysql_command' of undefined
    at /Users/vickerr/.kalabox/apps/jjs/plugins/kalabox-plugin-pantheon/lib/push.js:98:40
`
I'd really appreciate any help you can offer. Thanks!

**Comment by pirog** [comment]
@anthemwild if you go into `/Users/vickerr/.kalabox/apps/jjs` do you have a code folder with stuff in it? Are you familiar with Pantheon's terminus command line tool at all?

**Comment by anthemwild** [comment]
I guess I'm in over my head...designer playing dev. 

I've not used the Pantheon terminus tool yet. I'll have to do a little homework first. Sorry for the trouble.

**Comment by pirog** [comment]
@anthemwild common tale :/

so `terminus` is responsible for getting the information about your site so that kalabox can pull it down from pantheon and set it up locally. Its possible that this issue is on the terminus/pantheon end so it might be worth pinging them. specifically about why you aren't able to get any of the DB connection info.

**Comment by anthemwild** [comment]
Will do...thanks for all your help!

**Comment by twooten** [comment]
@pirog, just a quick update on this. I've found that Terminus 0.13.2 is not returning anything with the `terminus site connection-info` command for _some_ sites.

Looks like it's being tracked here - https://github.com/pantheon-systems/terminus/issues/1297

**Comment by pirog** [comment]
@twooten !!!! how are you old friend?

so we are using terminus 0.11.2 for our most recent versions. next release will be 0.13.3. do you know if this bug goes back to 0.11.2?

**Comment by twooten** [comment]
hey @pirog, All is well here ;-)

I rolled back to 0.11.2 and it is working as expected. Interesting case that @anthemwild has. 
`terminus site connection-info --site=his-site --env=dev` works with 0.11.2 and 0.13.1 but **not** with 0.13.2.

**Comment by pirog** [comment]
glad to hear it!

So, we actually get this error (and slight variants) pretty frequently in our bugsnag although they should all be from 0.11.2. Its certainly possible this is coming from our end but wanted to let you all know in case it is not.

**Comment by twooten** [comment]
cool, figured it'd be helpful to add as much info to this as possible.

**Comment by dustinleblanc** [comment]
@pirog heard back from @anthemwild and my assumption that this was dealing with multidev and not existing is wrong. I slack'd you his debug output because I didn't want to post it on his behalf here. Hope you guys can help him debug, let me know if you need any Pantheon help on it!

**Comment by pirog** [comment]
@dustinleblanc got the output and will check it out. 

@anthemwild do you know what version of kalabox you are using? Your app says its 2.0.0 but im seeing some functionality that might be 2.0.1 only. 

`kbox version`

**Comment by anthemwild** [comment]
I'm using 2.0. Just attempted a CLI push and got the following...


[2016-10-20 16:39:54] [error] Client error: `POST https://dashboard.pantheon.io/api/users/deaa8be1-d583-484b-aa0a-e718341f27e8/keys` resulted in a `401 Unauthorized` response:
"Invalid or expired session header: X-Pantheon-Session\n"

Pushing code.
[master 376ab12] Kbox CLI test 2
ssh: connect to host codeserver.dev.25c6f7ac-c1ed-447e-a4d1-4b03cca89891.drush.in port 2222: Network unreachable
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Pushing database.
Cannot read property 'mysql_command' of undefined
TypeError: Cannot read property 'mysql_command' of undefined
    at /Users/vickerr/.kalabox/apps/jjs/plugins/kalabox-plugin-pantheon/lib/push.js:98:40

**Comment by pirog** [comment]
@anthemwild 

Looks like you are having an issue connecting to Pantheon or you have an expired token.

Usually this is not an issue with kalabox but your network config. For example do you have port 2222 blocked?
