### ISSUE TITLE
New 2.1.0-rc.2 fails to create project on Windows 10

### ISSUE THREAD

**Issue by bmcclure** [kalabox/kalabox#1666]
I'm running `kbox create pantheon -- --verbose` to test this, and when attempting to create a new project from an existing D8 site on Pantheon, this happens for me on both RC1 and RC2 of 2.1.0:

```
...

ERROR: for web  Cannot start service web: oci runtime error: rootfs_linux.go:53: mounting "/var/lib/docker/aufs/mnt/85024556fcc52b75f5c7f6371af6ee25e348a5cbf02c1535a0e7770cfd305b74/etc/nginx/nginx.conf" to rootfs "/var/lib/docker/aufs/mnt/85024556fcc52b75f5c7f6371af6ee25e348a5cbf02c1535a0e7770cfd305b74" caused "not a directory"

ERROR: for terminus  Cannot start service terminus: Cannot link to a non running container: /goodwayd8_solr_1 AS /goodwayd8_terminus_1/solr_1

ERROR: for appserver  Cannot start service appserver: Cannot link to a non running container: /goodwayd8_solr_1 AS /goodwayd8_appserver_1/goodwayd8_solr_1
ERROR: Encountered errors while bringing up the project.

VError
    at buildVerror (C:\Program Files\Kalabox\bin\lib\util\shell.js.jx:52:10)
    at ChildProcess.<anonymous> (C:\Program Files\Kalabox\bin\lib\util\shell.js.jx:169:16)
    at ChildProcess.emit (events.js:85:17)
    at maybeClose (child_process.js:773:16)
    at Process.ChildProcess._handle.onexit (child_process.js:839:5)
error:  VError
    at buildVerror (C:\Program Files\Kalabox\bin\lib\util\shell.js.jx:52:10)
    at ChildProcess.<anonymous> (C:\Program Files\Kalabox\bin\lib\util\shell.js.jx:169:16)
    at ChildProcess.emit (events.js:85:17)
    at maybeClose (child_process.js:773:16)
    at Process.ChildProcess._handle.onexit (child_process.js:839:5)
```

On RC2 the error is almost the same but slightly different:

```
...
...
ERROR: for web  Cannot start service web: oci runtime error: rootfs_linux.go:53: mounting "/var/lib/docker/aufs/mnt/0a172de3528981922c95503dde4ad913f04ceb1867d9ef70d8dfcd7cc398ed8c/etc/nginx/nginx.conf" to rootfs "/var/lib/docker/aufs/mnt/0a172de3528981922c95503dde4ad913f04ceb1867d9ef70d8dfcd7cc398ed8c" caused "not a directory"

ERROR: for drush  Cannot start service drush: oci runtime error: exec: "usermap": executable file not found in$PATH

ERROR: for terminus  Cannot start service terminus: oci runtime error: exec: "usermap": executable file not found in $PATH

ERROR: for appserver  Cannot start service appserver: oci runtime error: exec: "/src/config/scripts/php-fpm.sh": stat /src/config/scripts/php-fpm.sh: no such file or directory
ERROR: Encountered errors while bringing up the project.
8-php5: Pulling from drush/drush
Digest: sha256:39f2270ffdda46d3c15f069a8633f6d2544d935a6f9da52bab43c2ee15a10dc3
Status: Downloaded newer image for drush/drush:8-php5

8-php5: Pulling from drush/drush
Digest: sha256:39f2270ffdda46d3c15f069a8633f6d2544d935a6f9da52bab43c2ee15a10dc3
Status: Downloaded newer image for drush/drush:8-php5
: 8-php5: Pulling from drush/drush
Digest: sha256:39f2270ffdda46d3c15f069a8633f6d2544d935a6f9da52bab43c2ee15a10dc3
Status: Downloaded newer image for drush/drush:8-php5

    at buildVerror (C:\Program Files\Kalabox\bin\lib\util\shell.js.jx:52:10)
    at ChildProcess.<anonymous> (C:\Program Files\Kalabox\bin\lib\util\shell.js.jx:169:16)
    at ChildProcess.emit (events.js:85:17)
    at maybeClose (child_process.js:773:16)
    at Process.ChildProcess._handle.onexit (child_process.js:839:5)
```

Anything jump out initially that I could try to see what's going on?

Here's a gist with `docker inspect appname_web_1` output:
https://gist.github.com/bmcclure/1321dba8cec42853d9b6ba286e7aa470

**Comment by pirog** [comment]
@bmcclure did you set up your shared drives? Step 5 in the install docs
http://docs.kalabox.io/en/v2.1/users/install/

**Comment by bmcclure** [comment]
@pirog Nope, I thought I RTFM'ed, but I completely glossed over that step. This can be closed I think, working through that now, any other issues I run into are likely unrelated.

**Comment by pirog** [comment]
@bmcclure its a shitty extra step you have to do on Windows for now but hopefully we can automate the set up in the future. Def let me know if that does the trick though.

**Comment by bmcclure** [comment]
That worked, thanks for setting me on the right track!

**Comment by pirog** [comment]
@bmcclure awesome! gonna link up to this 
https://github.com/kalabox/kalabox/issues/1668

we def need to make this requirements more clear during install
