### ISSUE TITLE
v2.1 Hangs on "Waiting for site to be ready."

### ISSUE THREAD

**Issue by mark-rodgers** [kalabox/kalabox#1688]
# Bug Report

**What is your Kalabox version and operating system?**

macOS Sierra v10.12

**Have you previously installed Kalabox? If so, what version?**

Yes, I've installed Kalabox v2.0.2

**Tell us about your bug**

_Kalabox 2.1 installs fine, docker is running, I open up Kalabox and create a new Drupal 7 site and get stuck with "Waiting for site to be ready."_

Please detail the steps we can take to replicate this bug. Be as detailed as possible.

> 1. Install Kalabox 2.1
> 2. Open Kalabox
> 3. ADD SITE > Drupal 7

**Does this bug prevent you from using Kalabox?**
Yes

![image](https://cloud.githubusercontent.com/assets/2798202/19775988/456c5e12-9c27-11e6-9b79-e1236c78f347.png)

![image](https://cloud.githubusercontent.com/assets/2798202/19776009/5630bd7e-9c27-11e6-9e31-5a93c32658a3.png)

**Comment by mark-rodgers** [comment]
I suppose I should have tried restarting before creating this issue. Problem resolved.

**Comment by pirog** [comment]
@mark-rodgers going to reopen this because i think this is actually a bug.

**Comment by mark-rodgers** [comment]
You know what, after I closed this I noticed it started happening again, but a restart did not fix the issue this time. Had to delete the site in Kalabox and create it again. Seems to do this from time to time and the only work around I have found at the time is unfortunately deleting the site and recreating it.

**Comment by pirog** [comment]
@mark-rodgers i haven't seen this yet but i'm going to elevate this.

**Comment by philmprice** [comment]
We are also seeing this issue at our company. We just finished migrating 40+ sites to Pantheon, so we're looking for something (another version?) that will work.

**Comment by pirog** [comment]
@mark-rodgers @philmprice this will definitely be a top priority for our next release. That said and to all users that end up here. Here are some suggestions to get around this.

1. Try restarting Kalabox
2. Try going to your site in the browser even if its still "waiting" (url should be site-name.kbox)

It seems like the biggest things causing this to happen are

1. Site redirects to put everything over https
2. Site has some sort of error (either from a botched pull or in the app itself)

I think in the future we are going to 

1. Make sure we are auto-approving https self-signed certs
2. Just say the site is ready after a reasonable amount of time has passed.

**Comment by pirog** [comment]
So i'm loosing up the requirements for this for our 2.1.1 release but i strongly suspect there might be a deeper issue here, most likely around DNS for `.kbox` not working correctly.

**Comment by dalin-** [comment]
I'm experiencing what I think is the same problem.

When I first installed 2.1, and created a Pantheon site it got stuck on `Waiting for site to be ready.`, and would not resolve in the browser.  

Eventually I get
```
Failed after 40 retries. {"max":40,"backoff":500}: connect ECONNREFUSED
Error: connect ECONNREFUSED
    at errnoException (net.js:837:11)
    at Object.afterConnect [as oncomplete] (net.js:829:19)
```

I tried a machine reboot, and `kbox start` and it made it all the way through, but it was lying.  When accessing in the browser I got an Apache index page as delivered by my Homebrew httpd22.  I stopped all Homebrew services and restarted the Kalabox app and was back to no resolving DNS.  

Here's some more debugging if that helps.  

```
dig episcopalassetmap.kbox

; <<>> DiG 9.8.3-P1 <<>> episcopalassetmap.kbox
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 41425
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;episcopalassetmap.kbox.		IN	A

;; Query time: 37 msec
;; SERVER: 192.168.1.1#53(192.168.1.1)
;; WHEN: Wed Nov  2 13:04:40 2016
;; MSG SIZE  rcvd: 40
```


```
$ cat /etc/resolver/kbox
nameserver 127.0.0.1
```

Hmmm, I saw somewhere else that this should maybe have a port as well???

```
$ docker ps --all
CONTAINER ID        IMAGE                           COMMAND                  CREATED             STATUS                      PORTS                                                                    NAMES
0220bc6c2449        kalabox/dns:stable              "/start.sh"              47 minutes ago      Up 12 minutes               53/tcp, 127.0.0.1:53->53/udp                                             kalabox_dns_1
4cf421e91691        kalabox/proxy:stable            "/init"                  47 minutes ago      Up 12 minutes               127.0.0.1:80->80/tcp, 127.0.0.1:443->443/tcp, 127.0.0.1:8160->8160/tcp   kalabox_proxy_1
d0b49ce9e527        kalabox/pantheon-appserver:55   "/src/config/scripts/"   48 minutes ago      Up 10 minutes               9000/tcp                                                                 episcopalassetmap_appserver_1
09fcdd6305ee        kalabox/terminus:0.13.3         "usermap"                48 minutes ago      Exited (1) 10 minutes ago                                                                            episcopalassetmap_terminus_1
8680c4001434        drush/drush:8-php5              "usermap"                48 minutes ago      Exited (1) 10 minutes ago                                                                            episcopalassetmap_drush_1
0d1d1379df09        kalabox/cli:stable              "usermap true"           48 minutes ago      Exited (1) 10 minutes ago                                                                            episcopalassetmap_cli_1
5a68922a9bcc        kalabox/pantheon-edge:stable    "/root/start.sh"         48 minutes ago      Up 10 minutes               0.0.0.0:32777->80/tcp, 0.0.0.0:32776->443/tcp                            episcopalassetmap_edge_1
76e9c28c4302        redis:2.8                       "true"                   48 minutes ago      Exited (0) 10 minutes ago                                                                            episcopalassetmap_redis-cli_1
e4adf1f6a577        mariadb:10.0                    "docker-entrypoint.sh"   48 minutes ago      Up 10 minutes               0.0.0.0:32775->3306/tcp                                                  episcopalassetmap_db_1
874f0403e7d1        kalabox/pantheon-solr:stable    "/bin/bash /start.sh"    48 minutes ago      Up 10 minutes               449/tcp                                                                  episcopalassetmap_solr_1
efe834dec229        kalabox/unison:2.49             "/run.sh"                48 minutes ago      Up 10 minutes                                                                                        episcopalassetmap_unison_1
e028c9d0273d        nginx:1.8.1                     "/src/config/scripts/"   48 minutes ago      Up 10 minutes               0.0.0.0:32774->80/tcp, 0.0.0.0:32773->443/tcp                            episcopalassetmap_web_1
6ea43dda95b9        redis:2.8                       "docker-entrypoint.sh"   48 minutes ago      Up 10 minutes               6379/tcp                                                                 episcopalassetmap_redis_1
935e7d65a21d        busybox                         "sh"                     48 minutes ago      Exited (0) 10 minutes ago                                                                            episcopalassetmap_data_1
```

```
$ docker logs 0220bc6c2449
dnsmasq: started, version 2.72 cachesize 150
dnsmasq: compile time options: IPv6 GNU-getopt no-DBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP no-conntrack ipset auth no-DNSSEC loop-detect
dnsmasq: using nameserver 208.67.220.220#53
dnsmasq: using nameserver 208.67.222.222#53
dnsmasq: using nameserver 8.8.4.4#53
dnsmasq: using nameserver 8.8.8.8#53
dnsmasq: reading /etc/resolv.conf
dnsmasq: using nameserver 208.67.220.220#53
dnsmasq: using nameserver 208.67.222.222#53
dnsmasq: using nameserver 8.8.4.4#53
dnsmasq: using nameserver 8.8.8.8#53
dnsmasq: using nameserver 192.168.65.1#53
dnsmasq: using nameserver 192.168.65.10#53
dnsmasq: using nameserver 192.168.65.9#53
dnsmasq: using nameserver 192.168.65.8#53
dnsmasq: using nameserver 192.168.65.7#53
dnsmasq: using nameserver 192.168.65.6#53
dnsmasq: using nameserver 192.168.65.5#53
dnsmasq: using nameserver 192.168.65.4#53
dnsmasq: using nameserver 192.168.65.3#53
dnsmasq: cleared cache
dnsmasq: started, version 2.72 cachesize 150
dnsmasq: compile time options: IPv6 GNU-getopt no-DBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP no-conntrack ipset auth no-DNSSEC loop-detect
dnsmasq: using nameserver 208.67.220.220#53
dnsmasq: using nameserver 208.67.222.222#53
dnsmasq: using nameserver 8.8.4.4#53
dnsmasq: using nameserver 8.8.8.8#53
dnsmasq: reading /etc/resolv.conf
dnsmasq: using nameserver 208.67.220.220#53
dnsmasq: using nameserver 208.67.222.222#53
dnsmasq: using nameserver 8.8.4.4#53
dnsmasq: using nameserver 8.8.8.8#53
dnsmasq: using nameserver 192.168.65.1#53
dnsmasq: using nameserver 192.168.65.10#53
dnsmasq: using nameserver 192.168.65.9#53
dnsmasq: using nameserver 192.168.65.8#53
dnsmasq: using nameserver 192.168.65.7#53
dnsmasq: using nameserver 192.168.65.6#53
dnsmasq: using nameserver 192.168.65.5#53
dnsmasq: using nameserver 192.168.65.4#53
dnsmasq: using nameserver 192.168.65.3#53
dnsmasq: cleared cache
dnsmasq: started, version 2.72 cachesize 150
dnsmasq: compile time options: IPv6 GNU-getopt no-DBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP no-conntrack ipset auth no-DNSSEC loop-detect
dnsmasq: using nameserver 208.67.220.220#53
dnsmasq: using nameserver 208.67.222.222#53
dnsmasq: using nameserver 8.8.4.4#53
dnsmasq: using nameserver 8.8.8.8#53
dnsmasq: reading /etc/resolv.conf
dnsmasq: using nameserver 208.67.220.220#53
dnsmasq: using nameserver 208.67.222.222#53
dnsmasq: using nameserver 8.8.4.4#53
dnsmasq: using nameserver 8.8.8.8#53
dnsmasq: using nameserver 192.168.65.1#53
dnsmasq: using nameserver 192.168.65.10#53
dnsmasq: using nameserver 192.168.65.9#53
dnsmasq: using nameserver 192.168.65.8#53
dnsmasq: using nameserver 192.168.65.7#53
dnsmasq: using nameserver 192.168.65.6#53
dnsmasq: using nameserver 192.168.65.5#53
dnsmasq: using nameserver 192.168.65.4#53
dnsmasq: using nameserver 192.168.65.3#53
dnsmasq: cleared cache
dnsmasq: started, version 2.72 cachesize 150
dnsmasq: compile time options: IPv6 GNU-getopt no-DBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP no-conntrack ipset auth no-DNSSEC loop-detect
dnsmasq: using nameserver 208.67.220.220#53
dnsmasq: using nameserver 208.67.222.222#53
dnsmasq: using nameserver 8.8.4.4#53
dnsmasq: using nameserver 8.8.8.8#53
dnsmasq: reading /etc/resolv.conf
dnsmasq: using nameserver 208.67.220.220#53
dnsmasq: using nameserver 208.67.222.222#53
dnsmasq: using nameserver 8.8.4.4#53
dnsmasq: using nameserver 8.8.8.8#53
dnsmasq: using nameserver 192.168.65.1#53
dnsmasq: using nameserver 192.168.65.10#53
dnsmasq: using nameserver 192.168.65.9#53
dnsmasq: using nameserver 192.168.65.8#53
dnsmasq: using nameserver 192.168.65.7#53
dnsmasq: using nameserver 192.168.65.6#53
dnsmasq: using nameserver 192.168.65.5#53
dnsmasq: using nameserver 192.168.65.4#53
dnsmasq: using nameserver 192.168.65.3#53
dnsmasq: cleared cache
```
```
$ docker history 7f05179d5642
IMAGE               CREATED             CREATED BY                                      SIZE                COMMENT
7f05179d5642        17 hours ago        /bin/sh -c #(nop)  CMD ["/start.sh"]            0 B
<missing>           17 hours ago        /bin/sh -c #(nop)  EXPOSE 53/tcp                0 B
<missing>           17 hours ago        /bin/sh -c #(nop) ADD file:2457238de5db2fe2f6   17.85 kB
<missing>           17 hours ago        /bin/sh -c #(nop) ADD file:b8917b6b4c8c79084a   78 B
<missing>           17 hours ago        /bin/sh -c apk add --update dnsmasq &&   rm -   334.2 kB
<missing>           2 weeks ago         /bin/sh -c #(nop) ADD file:8195bd00d7cf963113   5.265 MB
```

```
$ docker inspect 7f05179d5642
[
    {
        "Id": "sha256:7f05179d564233f390cc698c1ff82a54ef3c66a36fd4d02b7cf8c3d3b5eb2668",
        "RepoTags": [
            "kalabox/dns:stable"
        ],
        "RepoDigests": [
            "kalabox/dns@sha256:d5aff85a26bbd873338cdb0b275fe90f4c3492034eddfd3c45656d22d8ff737c"
        ],
        "Parent": "",
        "Comment": "",
        "Created": "2016-11-01T23:50:00.108775609Z",
        "Container": "aa534f2f0a1382738e515a37f6f0451742b4d86d1875156ce664f18bb2435b7c",
        "ContainerConfig": {
            "Hostname": "29e0d700cf3e",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "53/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": [
                "/bin/sh",
                "-c",
                "#(nop) ",
                "CMD [\"/start.sh\"]"
            ],
            "ArgsEscaped": true,
            "Image": "sha256:afb02734ae91dbe3c02c63fa252ebedd5d703cc07f309599e1ca7e42bb6c5486",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": [],
            "Labels": {}
        },
        "DockerVersion": "1.12.2",
        "Author": "",
        "Config": {
            "Hostname": "29e0d700cf3e",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "53/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": [
                "/start.sh"
            ],
            "ArgsEscaped": true,
            "Image": "sha256:afb02734ae91dbe3c02c63fa252ebedd5d703cc07f309599e1ca7e42bb6c5486",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": [],
            "Labels": {}
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 5616808,
        "VirtualSize": 5616808,
        "GraphDriver": {
            "Name": "aufs",
            "Data": null
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:e2f4c9b2f49fc1c8f7f5f1128d25dbb73673174a55461b3eb2f83367e2d5bfad",
                "sha256:04fd37267d7b3da9ac1092ce41843e199eef817ba8af68a3e67f8756b03d4b85",
                "sha256:9b904b897164c92ad6f8d00600a0b15219dffba2fa9bef01b98049f798acf626",
                "sha256:77b89455a9bf0d0a758bd7c241b9f2131aab8c38deca4a2a832a0ac911a95bae"
            ]
        }
    }
]
```
```
$ docker inspect 0220bc6c2449
[
    {
        "Id": "0220bc6c24493a55eaa23dfe8574d433d8a7c8b9fa985d390a7e793b22ade374",
        "Created": "2016-11-02T16:18:55.198522437Z",
        "Path": "/start.sh",
        "Args": [],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 14522,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2016-11-02T17:09:35.175116216Z",
            "FinishedAt": "2016-11-02T17:09:34.533892717Z"
        },
        "Image": "sha256:7f05179d564233f390cc698c1ff82a54ef3c66a36fd4d02b7cf8c3d3b5eb2668",
        "ResolvConfPath": "/var/lib/docker/containers/0220bc6c24493a55eaa23dfe8574d433d8a7c8b9fa985d390a7e793b22ade374/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/0220bc6c24493a55eaa23dfe8574d433d8a7c8b9fa985d390a7e793b22ade374/hostname",
        "HostsPath": "/var/lib/docker/containers/0220bc6c24493a55eaa23dfe8574d433d8a7c8b9fa985d390a7e793b22ade374/hosts",
        "LogPath": "/var/lib/docker/containers/0220bc6c24493a55eaa23dfe8574d433d8a7c8b9fa985d390a7e793b22ade374/0220bc6c24493a55eaa23dfe8574d433d8a7c8b9fa985d390a7e793b22ade374-json.log",
        "Name": "/kalabox_dns_1",
        "RestartCount": 0,
        "Driver": "aufs",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {
                "53/udp": [
                    {
                        "HostIp": "127.0.0.1",
                        "HostPort": "53"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "always",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": [],
            "CapAdd": null,
            "CapDrop": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": -1,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0
        },
        "GraphDriver": {
            "Name": "aufs",
            "Data": null
        },
        "Mounts": [],
        "Config": {
            "Hostname": "0220bc6c2449",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "53/tcp": {},
                "53/udp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "IP=127.0.0.1",
                "DOMAIN=kbox",
                "no_proxy=*.local, 169.254/16",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": [
                "/start.sh"
            ],
            "Image": "kalabox/dns:stable",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "com.docker.compose.config-hash": "6eef4cfb9e0036c3313bd88ea9efe47d9c0d59a41af3cb813f9ad061f3e5f084",
                "com.docker.compose.container-number": "1",
                "com.docker.compose.oneoff": "False",
                "com.docker.compose.project": "kalabox",
                "com.docker.compose.service": "dns",
                "com.docker.compose.version": "1.8.0"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "4c30331d359d261cb8902fb772c8175c9f214dc2b6f5720b7de88ca62428e4c1",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "53/tcp": null,
                "53/udp": [
                    {
                        "HostIp": "127.0.0.1",
                        "HostPort": "53"
                    }
                ]
            },
            "SandboxKey": "/var/run/docker/netns/4c30331d359d",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "bd66dfab7c1b65f422980ab80b69b87cb8fd009fb11cf9c6253a8355070683aa",
            "Gateway": "172.17.0.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "172.17.0.3",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "MacAddress": "02:42:ac:11:00:03",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "f09c8622d46be8f5507caa1d8c9abb1ab75db884ef478bf44e75c0c7a721c9e1",
                    "EndpointID": "bd66dfab7c1b65f422980ab80b69b87cb8fd009fb11cf9c6253a8355070683aa",
                    "Gateway": "172.17.0.1",
                    "IPAddress": "172.17.0.3",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:11:00:03"
                }
            }
        }
    }
]
```

Let me know if there's other logs or whatnot that you want me to pull.

**Comment by pirog** [comment]
@dalin- if you have anything running on ports 80/443/53 then its not going to work so you might want to make sure you turn those things off before installing kalabox.

**Comment by dalin-** [comment]
@pirog 
Are you saying that I should re-install 2.1?  FWIW I have nothing listening on port 53 (not even anything docker/kalabox related):

```
$ sudo lsof -iTCP -sTCP:LISTEN -n -P | grep ':\(443\|80\|53\)'
com.docke 1887   dave   26u  IPv4 0xad63a64113bae4a1      0t0  TCP 127.0.0.1:443 (LISTEN)
com.docke 1887   dave   27u  IPv4 0xad63a64113baed99      0t0  TCP 127.0.0.1:80 (LISTEN)
```

Is this what the problem is?

**Comment by pirog** [comment]
@dalin- port 53 is the DNS port so if that isn't running then it makes sense you aren't resolving .kbox domains. That said it looks, based on your logging that it is running.

AFAICT everything looks good on your end. Do you have any additional software installed that might be messing with your DNS?

**Comment by dalin-** [comment]
@pirog 
My laptop uses my router for DNS (I think this is probably standard). The router uses OpenDNS.  The only other thing that I can think of is that I have a fairly recent version of VirtualBox on this machine, but it's currently not running.  

I'm just grasping at straws here, but are either of these bugs similar:
https://forums.docker.com/t/port-53-not-accessible-from-host/18111/2
http://stackoverflow.com/questions/34759872/docker-port-forward-bind-dns-udp-not-respond

**Comment by dalin-** [comment]
I just realized that I commented on an already closed bug.  Let me know if I should create a new one.  

Today I reinstalled, but still no luck.  Here's the results from docker.log when I start the DNS container:
```
time="2016-11-03T14:35:20.617424559Z" level=debug msg="Calling GET /containers/b0ce2741694c/json" 
time="2016-11-03T14:35:20.619479480Z" level=debug msg="Calling POST /v1.24/containers/b0ce2741694c/start" 
time="2016-11-03T14:35:20.620596001Z" level=debug msg="container mounted via layerStore: /var/lib/docker/aufs/mnt/c28cb248de90648accb22bc0ac6a6f9d3ffa35a6d93f4ccbee49f10b604054eb" 
time="2016-11-03T14:35:20.621136308Z" level=debug msg="Assigning addresses for endpoint kalabox_dns_1's interface on network bridge" 
time="2016-11-03T14:35:20.621536519Z" level=debug msg="RequestAddress(LocalDefault/172.17.0.0/16, <nil>, map[])" 
time="2016-11-03T14:35:20.640423781Z" level=debug msg="Assigning addresses for endpoint kalabox_dns_1's interface on network bridge" 
time="2016-11-03T14:35:20.689047559Z" level=debug msg="Programming external connectivity on endpoint kalabox_dns_1 (d73bb12389d3de25bfb1ebfd13aeaf960728209de14477f7c25ef75a2d858578)" 
time="2016-11-03T14:35:20.689695185Z" level=debug msg="/usr/local/sbin/iptables, [--wait -t nat -A DOCKER -p udp -d 127.0.0.1 --dport 53 -j DNAT --to-destination 172.17.0.10:53 ! -i docker0]" 
time="2016-11-03T14:35:20.696768303Z" level=debug msg="/usr/local/sbin/iptables, [--wait -t filter -A DOCKER ! -i docker0 -o docker0 -p udp -d 172.17.0.10 --dport 53 -j ACCEPT]" 
time="2016-11-03T14:35:20.703641602Z" level=debug msg="/usr/local/sbin/iptables, [--wait -t nat -A POSTROUTING -p udp -s 172.17.0.10 -d 172.17.0.10 --dport 53 -j MASQUERADE]" 
time="2016-11-03T14:35:20.911664469Z" level=debug msg="sandbox set key processing took 85.728617ms for container b0ce2741694c713c568d85b0e0bc9c407b1f57245785d539d6ebf7702818d434" 
time="2016-11-03T14:35:20.973818318Z" level=debug msg="libcontainerd: received containerd event: &types.Event{Type:\"start-container\", Id:\"b0ce2741694c713c568d85b0e0bc9c407b1f57245785d539d6ebf7702818d434\", Status:0x0, Pid:\"\", Timestamp:(*timestamp.Timestamp)(0xc820cd51e0)}" 
time="2016-11-03T14:35:20.996921703Z" level=debug msg="libcontainerd: event unhandled: type:\"start-container\" id:\"b0ce2741694c713c568d85b0e0bc9c407b1f57245785d539d6ebf7702818d434\" timestamp:<seconds:1478183720 nanos:973444247 > " 
```

And Docker is still not listening on port 53:
```
sudo lsof -iTCP -sTCP:LISTEN -n -P | grep ':\(443\|80\|53\)'
com.docke  5968   dave   80u  IPv4 0xad63a64110b5aba9      0t0  TCP 127.0.0.1:443 (LISTEN)
com.docke  5968   dave   81u  IPv4 0xad63a641125ba4a1      0t0  TCP 127.0.0.1:80 (LISTEN)
```

**Comment by pirog** [comment]
@dalin- i think you are going to want to check `udp` instead of `tcp` for port 53.

**Comment by dalin-** [comment]
> i think you are going to want to check udp instead of tcp for port 53

Ah, of course.  

But for now I'm back to 2.0.2 in order to get some work done.  I see that 2.1.1 has some DNS related changes.  When I get some down time I'll give it another go.

**Comment by pirog** [comment]
sounds good!

**Comment by macronomicus** [comment]
Same issue here on Windows, usually DNS works, sometimes not, however, I am still able to use it by going to localhost & the port, you can grab each sites port number from the web container details...
http://localhost:32769

**Comment by pirog** [comment]
@macronomicus you likely need to turn off whatever else you have running on port 80

**Comment by macronomicus** [comment]
Hmmm, perhaps but there shouldnt be, ill netstat and see next time it goes out what might be listening there.

**Comment by pirog** [comment]
It's also worth pointing out that if you are using 2.1.1 and you upgraded
from 2.1.0 you might want to make sure that your hyperV network adapter
doesn't have any DNS servers specified for both IPv4 and IPv6
