### ISSUE TITLE
drush not recognizing site

### ISSUE THREAD

**Issue by ultimike** [kalabox/kalabox#1704]
Bug Report
==========

Running 2.1.0 (on Mac OS X Sierra), I just added an existing Drupal 7 site from Pantheon. The site is up-and-running just fine on my local.

When I go to the terminal, and try "kbox drush status", I see the following:

```
~/.kalabox/apps/my-site-name/code [master]$ kbox drush status
 Drupal version         :  7.51                                           
 PHP configuration      :                                                 
 PHP OS                 :  Linux                                          
 Drush script           :  /usr/local/bin/drush                           
 Drush version          :  8.0.5                                          
 Drush temp directory   :  /tmp                                           
 Drush configuration    :  /home/1000/.drush/drushrc.php                  
 Drush alias files      :  /home/1000/.drush/aliases.drushrc.php          
                           /home/1000/.drush/pantheon.aliases.drushrc.php 
 Drupal root            :  /code                                          
 Drupal Settings File   :  MISSING      
```

I have other local sites (from Pantheon) running on Kalabox that do not have this issue.

thanks,  
-mike

**Comment by ultimike** [comment]
Possibly related, when I try to do a git status, I also get an error with the same site:

```
~/.kalabox/apps/my-site-name/code [master*]$ kbox git status
Unhandled rejection VError: Error inspecting container: pantheonthinkcollege_cli_run_2.: expecting an array or an iterable object but got [object Null]
    at /Applications/Kalabox.app/Contents/MacOS/bin/plugins/kalabox-engine-docker/provider/docker/docker.js.jx:202:13
    at process._tickCallback (node.js:917:13)
From previous event:
    at main (/Applications/Kalabox.app/Contents/MacOS/bin/bin/kbox.js.jx:239:4)
    at Object.<anonymous> (/Applications/Kalabox.app/Contents/MacOS/bin/bin/kbox.js.jx:248:1)
    at Module._compile (module.js:619:26)
    at readX (module.js:1645:5)
    at Object.Module._extensions..jx (module.js:2102:10)
    at Module.load (module.js:440:36)
    at Function.Module._load (module.js:405:12)
    at Module.require (module.js:475:17)
    at require (module.js:493:17)
    at Object.<anonymous> (_jx_source:17:3)
    at Module._compile (module.js:619:26)
    at Module.load (module.js:449:12)
    at Function.Module._load (module.js:405:12)
    at Function.Module.runMain (module.js:871:12)
    at startup (node.js:485:18)
    at node.js:1604:3
```

-mike

**Comment by pirog** [comment]
@ultimike second post here is unrelated but is actually a pretty nasty bug we've seen from a few other people. 

For the drush stuff, you need to have a settings.php file for drush to work. Pantheon does not ship with one so that is a little problematic. I usually just copy over the default.settings.php to settings.php and then things are good.

**Comment by ultimike** [comment]
Mike - cool - that worked.

thanks,
-mike
