### ISSUE TITLE
Windows 10 installation - Docker error

### ISSUE THREAD

**Issue by KenWatts** [kalabox/kalabox#1713]
v2.1.1 on Windows 10 pro

Previously installed 2.0.0, 2.0.1, 2.1.0 -- but I was pretty careful about not only doing uninstalls, but also cleaning up left folders, etc. just to make sure it was fresh.

I attempted to install Kalabox, and got a docker error:
```
Unable to stop: Couldn't stop VM MobyLinuxVM
at <ScriptBlock>, <No file>: line 340
   at Docker.Backend.ContainerEngine.Linux.Stop()
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
```

I looked at the log, and found this:

```
[16:42:23.009][Program        ][Info   ] Version: 1.12.1-stable

[16:42:23.071][Program        ][Info   ] Starting on: 11/7/2016 4:42:23 PM

[16:42:23.071][Program        ][Info   ] Resources: C:\Program Files\Docker\Docker\Resources

[16:42:23.071][Program        ][Info   ] OS: Windows 10 Pro

[16:42:23.087][Program        ][Info   ] Edition: Professional

[16:42:23.087][Program        ][Info   ] Id: 1607

[16:42:23.087][Program        ][Info   ] Build: 14393

[16:42:23.087][Program        ][Info   ] BuildLabName: 14393.351.amd64fre.rs1_release_inmarket.161014-1755

[16:42:23.087][Program        ][Info   ] Sha1: 995236d98308333f27e3a36505dd761ac9c843f3

[16:42:23.087][Program        ][Info   ] You can send feedback, including this log file, at https://github.com/docker/for-win/issues

[16:42:27.384][TrackingStatus ][Info   ] Crash report and usage statistics are enabled

[16:42:27.415][Analytics      ][Info   ] Usage Statistic: appLaunched

[16:42:27.618][NamedPipeClient][Info   ] Sending Version()...

[16:42:27.696][NamedPipeClient][Info   ] Received response for Version

[16:42:27.743][Analytics      ][Info   ] Usage Statistic: heartbeat

[16:42:17.118][BackendServer  ][Info   ] Started

[16:42:27.696][NamedPipeServer][Info   ] Version()

[16:42:27.696][NamedPipeServer][Info   ] Version done.

[16:42:31.009][Updater        ][Info   ] Checking for updates on channel Stable...

[16:42:31.009][Notifications  ][Info   ] Docker is starting...

[16:42:31.056][NamedPipeClient][Info   ] Sending Start(Docker.Core.Settings)...

[16:42:31.071][NamedPipeServer][Info   ] Start(Docker.Core.Settings)

[16:42:31.071][HyperVGuids    ][Info   ] Installing GUIDs...

[16:42:31.087][HyperVGuids    ][Info   ] GUIDs installed

[16:42:31.337][Firewall       ][Info   ] Opening ports for C:\Program Files\Docker\Docker\Resources\com.docker.proxy.exe...

[16:42:31.649][Updater        ][Info   ] Local build 7135 is as good as the remote 7135 on channel Stable

[16:42:32.796][Firewall       ][Info   ] Ports are opened

[16:42:32.799][HyperV         ][Info   ] Create

[16:42:33.041][PowerShell     ][Info   ] Run script with parameters: -Create True -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\mobylinux.iso...

[16:42:47.499][HyperV         ][Info   ] Creating Switch: DockerNAT...

[16:42:51.280][HyperV         ][Info   ] Switch created.

[16:42:54.827][HyperV         ][Info   ] Set IP address on switch

[16:42:56.452][HyperV         ][Info   ] Creating dynamic VHD: C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks\MobyLinuxVM.vhdx

[16:42:58.014][HyperV         ][Info   ] Creating VM MobyLinuxVM...

[16:43:04.046][HyperV         ][Info   ] VM created.

[16:43:04.061][DataKit        ][Info   ] Starting...

[16:43:04.077][PowerShell     ][Info   ] Run script...

[16:43:04.249][DataKit        ][Info   ] Started

[16:43:04.249][VpnKit         ][Info   ] Starting...

[16:43:04.249][PowerShell     ][Info   ] Run script...

[16:43:04.389][VpnKit         ][Info   ] Started

[16:43:04.389][DataKit        ][Info   ] 

[16:43:04.389][DataKit        ][Info   ] +8713us    Datakit  Starting com.docker.db.exe 09081b4 ...

[16:43:04.405][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/config=static

[16:43:04.405][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/address=10.0.75.2

[16:43:04.405][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/netmask=255.255.255.0

[16:43:04.405][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/gateway=10.0.75.1

[16:43:04.405][Database       ][Info   ] Writing com.docker.driver.amd64-linux/network=hybrid

[16:43:04.405][Database       ][Info   ] Writing com.docker.driver.amd64-linux/etc/docker/daemon.json={"registry-mirrors":[],"insecure-registries":[],"debug":false}

[16:43:04.405][Database       ][Info   ] Writing com.docker.driver.amd64-linux/etc/sysctl.conf=

[16:43:04.405][Database       ][Info   ] Writing com.docker.driver.amd64-linux/native/port-forwarding=true

[16:43:05.095][VpnKit         ][Info   ] com.docker.slirp.exe: Logging to stdout (stdout:true DEBUG:false)

[16:43:05.096][VpnKit         ][Info   ] com.docker.slirp.exe: Setting handler to ignore all SIGPIPE signals

[16:43:05.098][VpnKit         ][Info   ] com.docker.slirp.exe: vpnkit version %VERSION% with hostnet version local %HOSTNET_PINNED% uwt version 0.0.3 hvsock version 0.10.0 %HVSOCK_PINNED%

[16:43:05.099][VpnKit         ][Info   ] com.docker.slirp.exe: starting port_forwarding port_control_url:hyperv-connect://902a15a0-30df-4540-a82c-f805c8707b8a max_connections:None vsock_path:

[16:43:05.100][VpnKit         ][Info   ] com.docker.slirp.exe: connecting to 902a15a0-30df-4540-a82c-f805c8707b8a:0B95756A-9985-48AD-9470-78E060895BE7

[16:43:05.102][VpnKit         ][Debug  ] com.docker.slirp.exe: Waiting for connections on socket hyperv-connect://902a15a0-30df-4540-a82c-f805c8707b8a

[16:43:05.103][VpnKit         ][Info   ] com.docker.slirp.exe: connecting to 902a15a0-30df-4540-a82c-f805c8707b8a:30D48B34-7D27-4B0B-AAAF-BBBED334DD59

[16:43:05.105][VpnKit         ][Debug  ] com.docker.slirp.exe: Waiting for connections on socket hyperv-connect://902a15a0-30df-4540-a82c-f805c8707b8a

[16:43:05.106][VpnKit         ][Info   ] com.docker.slirp.exe: hosts file has bindings for localhost

[16:43:05.658][DataKit        ][Info   ] 

[16:43:05.658][DataKit        ][Info   ] +1269873us       fs9p [ERROR] dispatcher caught Unix.Unix_error(Unix.EPIPE, "bytes_read", ""): no more requests will be handled

[16:43:06.596][Database       ][Info   ] Successfully wrote 8 value(s)

[16:43:06.596][Database       ][Info   ] Removing com.docker.driver.amd64-linux/proxy/exclude

[16:43:06.596][Database       ][Info   ] Removing com.docker.driver.amd64-linux/proxy/http

[16:43:06.596][Database       ][Info   ] Removing com.docker.driver.amd64-linux/proxy/https

[16:43:06.833][Database       ][Info   ] Successfully removed 3 value(s)

[16:43:06.849][DataKit        ][Info   ] 

[16:43:06.849][DataKit        ][Info   ] +2460823us       fs9p [ERROR] dispatcher caught Unix.Unix_error(Unix.EPIPE, "bytes_read", ""): no more requests will be handled

[16:43:06.943][Database       ][Info   ] Writing com.docker.driver.amd64-linux/etc/ssl/certs/ca-certificates.crt=C:\WINDOWS\TEMP\tmpBE11.tmp

[16:43:07.355][Database       ][Info   ] Successfully wrote value

[16:43:07.371][DataKit        ][Info   ] 

[16:43:07.371][DataKit        ][Info   ] +2982008us       fs9p [ERROR] dispatcher caught Unix.Unix_error(Unix.EPIPE, "bytes_read", ""): no more requests will be handled

[16:43:07.386][PowerShell     ][Info   ] Run script '$(Find-NetRoute -RemoteIPAddress 8.8.8.8).InterfaceIndex[0]'...

[16:43:07.464][Database       ][Info   ] Writing com.docker.driver.amd64-linux/slirp/dns=nameserver 156.154.70.22
nameserver 156.154.71.22
nameserver 192.168.1.254
search attlocal.net

[16:43:07.765][Database       ][Info   ] Successfully wrote 1 value(s)

[16:43:07.765][HyperV         ][Info   ] Start

[16:43:07.781][DataKit        ][Info   ] 

[16:43:07.781][PowerShell     ][Info   ] Run script with parameters: -Start True...

[16:43:07.781][DataKit        ][Info   ] +3392568us       fs9p [ERROR] dispatcher caught Unix.Unix_error(Unix.EPIPE, "bytes_read", ""): no more requests will be handled

[16:43:07.797][HyperV         ][Info   ] Starting VM MobyLinuxVM...

[16:43:12.562][HyperV         ][Info   ] Wait for the VM to get an IP address

[16:43:13.625][HyperV         ][Info   ] Wait for the VM to get an IP address

[16:43:14.640][HyperV         ][Info   ] Wait for the VM to get an IP address

[16:43:15.672][HyperV         ][Info   ] Wait for the VM to get an IP address

[16:43:16.703][HyperV         ][Info   ] Wait for the VM to get an IP address

[16:43:18.000][HyperV         ][Info   ] Wait for the VM to get an IP address

[16:43:19.015][HyperV         ][Info   ] Wait for the VM to get an IP address

[16:43:20.062][HyperV         ][Info   ] Wait for the VM to get an IP address

[16:43:21.109][HyperV         ][Info   ] Wait for the VM to get an IP address

[16:43:22.156][HyperV         ][Info   ] Wait for the VM to get an IP address

[16:43:23.531][HyperV         ][Info   ] Wait for the VM to get an IP address

[16:43:24.703][HyperV         ][Info   ] Wait for the VM to get an IP address

[16:43:25.750][HyperV         ][Info   ] Wait for the VM to get an IP address

[16:43:26.812][HyperV         ][Info   ] Wait for the VM to get an IP address

[16:43:27.859][HyperV         ][Info   ] Wait for the VM to get an IP address

[16:43:29.172][HyperV         ][Info   ] Wait for the VM to get an IP address

[16:43:30.890][HyperV         ][Info   ] Wait for the VM to get an IP address

[16:43:31.922][HyperV         ][Info   ] Wait for the VM to get an IP address

[16:43:32.953][HyperV         ][Info   ] Wait for the VM to get an IP address

[16:43:34.000][HyperV         ][Info   ] Wait for the VM to get an IP address

[16:43:35.265][HyperV         ][Info   ] Wait for the VM to get an IP address

[16:43:36.312][HyperV         ][Info   ] Wait for the VM to get an IP address

[16:43:37.359][HyperV         ][Info   ] Wait for the VM to get an IP address

[16:43:38.406][HyperV         ][Info   ] Wait for the VM to get an IP address

[16:43:39.469][HyperV         ][Info   ] Wait for the VM to get an IP address

[16:43:40.797][HyperV         ][Info   ] Wait for the VM to get an IP address

[16:43:41.844][HyperV         ][Info   ] Wait for the VM to get an IP address

[16:43:42.875][HyperV         ][Info   ] Wait for the VM to get an IP address

[16:43:43.922][HyperV         ][Info   ] Wait for the VM to get an IP address

[16:43:44.984][HyperV         ][Info   ] Wait for the VM to get an IP address

[16:43:46.281][HyperV         ][Info   ] Wait for the VM to get an IP address

[16:43:47.312][HyperV         ][Info   ] Wait for the VM to get an IP address

[16:43:48.359][HyperV         ][Info   ] Wait for the VM to get an IP address

[16:43:49.390][HyperV         ][Info   ] Wait for the VM to get an IP address

[16:43:50.453][HyperV         ][Info   ] Wait for the VM to get an IP address

[16:43:51.750][HyperV         ][Info   ] Wait for the VM to get an IP address

[16:43:52.781][HyperV         ][Info   ] Wait for the VM to get an IP address

[16:43:53.828][HyperV         ][Info   ] Wait for the VM to get an IP address

[16:43:54.875][HyperV         ][Info   ] Wait for the VM to get an IP address

[16:43:55.890][HyperV         ][Info   ] Wait for the VM to get an IP address

[16:43:57.187][HyperV         ][Info   ] Wait for the VM to get an IP address

[16:43:58.250][HyperV         ][Info   ] Wait for the VM to get an IP address

[16:43:59.297][HyperV         ][Info   ] Wait for the VM to get an IP address

[16:44:00.312][HyperV         ][Info   ] Wait for the VM to get an IP address

[16:44:01.375][HyperV         ][Info   ] Wait for the VM to get an IP address

[16:44:02.953][HyperV         ][Info   ] Wait for the VM to get an IP address

[16:44:03.984][HyperV         ][Info   ] Wait for the VM to get an IP address

[16:44:05.015][HyperV         ][Info   ] Wait for the VM to get an IP address

[16:44:06.062][HyperV         ][Info   ] Wait for the VM to get an IP address

[16:44:07.109][HyperV         ][Info   ] Wait for the VM to get an IP address

[16:44:11.094][HyperV         ][Info   ] Wait for the VM to get an IP address

[16:44:11.094][HyperV         ][Info   ] Wait for the VM to get an IP address

[16:44:11.094][HyperV         ][Info   ] Wait for the VM to get an IP address

[16:44:11.562][HyperV         ][Info   ] Wait for the VM to get an IP address

[16:44:12.625][HyperV         ][Info   ] Wait for the VM to get an IP address

[16:44:13.922][HyperV         ][Info   ] Wait for the VM to get an IP address

[16:44:14.969][HyperV         ][Info   ] Wait for the VM to get an IP address

[16:44:16.016][HyperV         ][Info   ] Wait for the VM to get an IP address

[16:44:17.062][HyperV         ][Info   ] Wait for the VM to get an IP address

[16:44:54.750][HyperV         ][Info   ] Hyper-V is running

[16:44:54.750][HyperV         ][Info   ] Create

[16:44:54.750][PowerShell     ][Info   ] Run script with parameters: -Create True -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\mobylinux.iso...

[16:44:56.234][HyperV         ][Info   ] Using existing Switch: DockerNAT

[16:44:56.687][HyperV         ][Info   ] Using existing Switch IP address

[16:44:56.734][HyperV         ][Info   ] Using existing: MobyLinuxVM (state = Running)

[16:44:56.734][HyperV         ][Info   ] Stop

[16:44:56.734][PowerShell     ][Info   ] Run script with parameters: -Stop True...

[16:44:56.766][HyperV         ][Info   ] Stopping VM MobyLinuxVM...

[16:45:10.281][HyperV         ][Info   ] Kill VM MobyLinuxVM process...

[16:45:11.516][HyperV         ][Info   ] Kill VM MobyLinuxVM process...

[16:45:12.547][HyperV         ][Info   ] Kill VM MobyLinuxVM process...

[16:45:13.687][HyperV         ][Info   ] Kill VM MobyLinuxVM process...

[16:45:14.703][HyperV         ][Info   ] Kill VM MobyLinuxVM process...

[16:45:15.750][HyperV         ][Info   ] Kill VM MobyLinuxVM process...

[16:45:16.766][HyperV         ][Info   ] Kill VM MobyLinuxVM process...

[16:45:17.828][HyperV         ][Info   ] Kill VM MobyLinuxVM process...

[16:45:18.859][HyperV         ][Info   ] Kill VM MobyLinuxVM process...

[16:45:19.891][HyperV         ][Info   ] Kill VM MobyLinuxVM process...

[16:45:20.937][VpnKit         ][Info   ] Killing existing com.docker.slirp with PID 2108

[16:45:20.953][DataKit        ][Info   ] Killing existing com.docker.db with PID 9372

[16:45:20.953][NamedPipeServer][Error  ] Unable to execute Start: Unable to stop: Couldn't stop VM MobyLinuxVM

at <ScriptBlock>, <No file>: line 340    at Docker.Backend.ContainerEngine.Linux.Stop()

   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings)

   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)

   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)

   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)

[16:45:21.359][NamedPipeClient][Error  ] Unable to send Start: Unable to stop: Couldn't stop VM MobyLinuxVM

at <ScriptBlock>, <No file>: line 340

[16:45:21.359][Notifications  ][Error  ] Unable to stop: Couldn't stop VM MobyLinuxVM

at <ScriptBlock>, <No file>: line 340

[16:45:46.058][NamedPipeClient][Info   ] Sending GetDebugInfo()...

[16:45:49.122][NamedPipeServer][Info   ] GetDebugInfo()

[16:46:13.718][ErrorReportWindow][Info   ] Open logs

[16:46:53.189][NamedPipeServer][Info   ] GetDebugInfo done.

[16:46:53.201][NamedPipeClient][Info   ] Received response for GetDebugInfo

[16:46:53.317][Program        ][Info   ] Sending Bugsnag report c9288665-2c3f-49e9-bd4f-5a778d037528...

[16:46:55.161][Program        ][Info   ] Bugsnag report c9288665-2c3f-49e9-bd4f-5a778d037528 sent

[16:46:55.254][NamedPipeClient][Info   ] Sending DownloadVmLogs()...

[16:46:55.256][NamedPipeServer][Info   ] DownloadVmLogs()

[16:46:55.259][PowerShell     ][Info   ] Run script...

[16:47:25.499][HyperV         ][Warning] Unable to download logs: 2016/11/07 16:47:25 Failed to Dial 902a15a0-30df-4540-a82c-f805c8707b8a 445ba2cb-e69b-4912-8b42-d7f494d007ea : A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.



[16:47:25.512][NamedPipeClient][Info   ] Received response for DownloadVmLogs

[16:47:25.504][NamedPipeServer][Info   ] DownloadVmLogs done.

[16:48:46.152][ErrorReportWindow][Info   ] Open logs

```
I shared the drive on Docker, and the indicator in the settings said it was running, but the icon in my tray was red.

I restarted Docker, got the same message.

I decided to try Kalabox anyway, but it appears to be hung.

**Comment by pirog** [comment]
@KenWatts Docker for Windows is still a beta product so if you are having issues that are on the Docker end i would recommend checking out their issue queues.

**Comment by brunetgarcia** [comment]
@KenWatts I had an issue getting Docker to run on the latest Windows 10 also. This addressed the issue for me: https://github.com/docker/for-win/issues/54#issuecomment-257157813

**Comment by pirog** [comment]
@brunetgarcia thanks!

**Comment by KenWatts** [comment]
@brunetgarcia Thanks. By the time I got your message I had done a complete
reinstall, and Docker had offered to upgrade. I let it, and it now
works--so they may have implemented the fix on their end now.

**Comment by pirog** [comment]
@KenWatts good to know and we will be rolling the docker upgrade into the new 2.1.2 release.
