### ISSUE TITLE
Verbose Flag Docs

### ISSUE THREAD

**Issue by grshane** [kalabox/kalabox#1746]
Bug Report
==========

**Tell us about your setup**

What is your Kalabox version and operating system?

v2.1.2 MacOS 10.12.1

Have you previously installed Kalabox? If so, what version?

Yes, many previous installs.

**Tell us about your bug**

When trying to add verbose output to commands you receive an error asking for a second flag.

Please detail the steps we can take to replicate this bug. Be as detailed as possible.

> 1. Run `kbox start --verbose`
> 2. Receive error 

> `$ kbox start --verbose
Did you mean to run kbox start -- --verbose?
Error: Did you mean to run kbox start -- --verbose?
    at Object.exports.run (/Applications/Kalabox.app/Contents/MacOS/bin/lib/core/tasks.js.jx:853:15)
    at processTask (/Applications/Kalabox.app/Contents/MacOS/bin/bin/kbox.js.jx:181:16)
    at Object.<anonymous> (/Applications/Kalabox.app/Contents/MacOS/bin/bin/kbox.js.jx:240:12)
From previous event:
    at main (/Applications/Kalabox.app/Contents/MacOS/bin/bin/kbox.js.jx:239:4)
    at Object.<anonymous> (/Applications/Kalabox.app/Contents/MacOS/bin/bin/kbox.js.jx:248:1)
    at Module._compile (module.js:619:26)
    at readX (module.js:1645:5)
    at Object.Module._extensions..jx (module.js:2102:10)
    at Module.load (module.js:440:36)
    at Function.Module._load (module.js:405:12)
    at Module.require (module.js:475:17)
    at require (module.js:493:17)
    at Object.<anonymous> (_jx_source:17:3)
    at Module._compile (module.js:619:26)
    at Module.load (module.js:449:12)
    at Function.Module._load (module.js:405:12)
    at Function.Module.runMain (module.js:871:12)
    at startup (node.js:485:18)
    at node.js:1604:3`
> 3. Run `kbox start -- --verbose`
> 4. Completes request successfully.

**Tell us more**

Could better documentation have prevented this issue? if so what should we change?

Change the command line help to display `-- --verbose`
Does this bug prevent you from using Kalabox?
No

**Comment by pirog** [comment]
@grshane im not sure what you are reporting here. This is the intended functionality and our usage of the `--` switch to delineate options is explained in the docs 
http://docs.kalabox.io/en/v2.1/users/cli/#using-options

We also specify the syntax in the "usage" that is spit out at the top of running `kbox`
`Usage: kbox.dev <command> [-- <options>]`

I think this sort of covers the bases here. Is there something you think would be better?

**Comment by grshane** [comment]
You can close this. I was not realizing the -- was needed in addition to the -- before the command.

**Comment by pirog** [comment]
word. realize its a little weird but hopefully the docs explain why it has to be this way!
