### ISSUE TITLE
kalabox/proxy:stable is broken please update tag to latest

### ISSUE THREAD

**Issue by ccjjmartin** [kalabox/kalabox#1765]
Bug Report
==========

**Tell us about your setup**

Kalabox: 2.1.3
Docker For Mac: 1.13.0
OS: OS X 10.11.6 (15G1217)

I had previously installed Kalabox and my system crashed so I followed the uninstall directions and reinstalled everything fresh.  I also deleted the contents of my Kalabox and ~/.kalabox directories.

**Tell us about your bug**

kalabox/proxy:stable is broken

**Does this bug prevent you from using Kalabox?**

Yes

**Author's recommended fix to look into**

Looks like the docker repository for the kalabox/proxy just needs to point the stable tag at a different commit, the latest tag appears to be working on my setup.

**Additional details about reproducing the bug**

When trying to install a site from Pantheon I get:

`VError: Failed after 5 retries. {"max":5,"backoff":500}: stable: Pulling from kalabox/proxy`

After following some rebuild steps in: https://github.com/kalabox/kalabox/issues/1318

I found this error:

```
Pulling proxy (kalabox/proxy:stable)...
ERROR: failed to register layer: rename /var/lib/docker/image/aufs/layerdb/tmp/write-set-071331078 
```

Which lead me to find I can reproduce the exact error by:

`docker pull kalabox/proxy:stable` which results in:

```
stable: Pulling from kalabox/proxy
b6c3525e6e94: Extracting [==================================================>] 2.496 MB/2.496 MB
cf70639ad66c: Download complete
bb864b5c0d5e: Download complete
failed to register layer: rename /var/lib/docker/image/aufs/layerdb/tmp/write-set-331053553 /var/lib/docker/image/aufs/layerdb/sha256/bceed376e6f968cafc509cd32709bf52aa1ad62f056facdb1d1ee01e500b122d: directory not empty
```

It could be fixed with the latest version of the kalabox/proxy:latest:

`docker pull kalabox/proxy` which results in:

```
Using default tag: latest
latest: Pulling from kalabox/proxy
4623373f000b: Pull complete
08f94324c768: Pull complete
8cc5bba5e80c: Pull complete
Digest: sha256:648a8071fd50f112642fbb54b9b299ee0f4179e2f601ef09d82b77bb3c2e391f
Status: Downloaded newer image for kalabox/proxy:latest
```

**Additional debugging output from kbox rebuild -- -v**

```
info: Running post start tasks.
Running post start tasks.
verbose: DOCKER COMPOSE ==> Running: ["--project-name","kalabox","--file","/Users/developer/.kalabox/downloads/kalabox/kalabox-4.yml","--file","/Users/developer/.kalabox/downloads/kalabox/kalabox-5.yml","up","-d","proxy"]
Pulling proxy (kalabox/proxy:stable)...
ERROR: failed to register layer: rename /var/lib/docker/image/aufs/layerdb/tmp/write-set-071331078 /var/lib/docker/image/aufs/layerdb/sha256/bceed376e6f968cafc509cd32709bf52aa1ad62f056facdb1d1ee01e500b122d: directory not empty
verbose: DOCKER COMPOSE ==> Running: ["--project-name","kalabox","--file","/Users/developer/.kalabox/downloads/kalabox/kalabox-6.yml","--file","/Users/developer/.kalabox/downloads/kalabox/kalabox-7.yml","up","-d","proxy"]
Pulling proxy (kalabox/proxy:stable)...
ERROR: failed to register layer: rename /var/lib/docker/image/aufs/layerdb/tmp/write-set-701467034 /var/lib/docker/image/aufs/layerdb/sha256/bceed376e6f968cafc509cd32709bf52aa1ad62f056facdb1d1ee01e500b122d: directory not empty
verbose: DOCKER COMPOSE ==> Running: ["--project-name","kalabox","--file","/Users/developer/.kalabox/downloads/kalabox/kalabox-8.yml","--file","/Users/developer/.kalabox/downloads/kalabox/kalabox-9.yml","up","-d","proxy"]
Pulling proxy (kalabox/proxy:stable)...
ERROR: failed to register layer: rename /var/lib/docker/image/aufs/layerdb/tmp/write-set-444668270 /var/lib/docker/image/aufs/layerdb/sha256/bceed376e6f968cafc509cd32709bf52aa1ad62f056facdb1d1ee01e500b122d: directory not empty
verbose: DOCKER COMPOSE ==> Running: ["--project-name","kalabox","--file","/Users/developer/.kalabox/downloads/kalabox/kalabox-10.yml","--file","/Users/developer/.kalabox/downloads/kalabox/kalabox-11.yml","up","-d","proxy"]
Pulling proxy (kalabox/proxy:stable)...
ERROR: failed to register layer: rename /var/lib/docker/image/aufs/layerdb/tmp/write-set-386915458 /var/lib/docker/image/aufs/layerdb/sha256/bceed376e6f968cafc509cd32709bf52aa1ad62f056facdb1d1ee01e500b122d: directory not empty
verbose: DOCKER COMPOSE ==> Running: ["--project-name","kalabox","--file","/Users/developer/.kalabox/downloads/kalabox/kalabox-12.yml","--file","/Users/developer/.kalabox/downloads/kalabox/kalabox-13.yml","up","-d","proxy"]
Pulling proxy (kalabox/proxy:stable)...
ERROR: failed to register layer: rename /var/lib/docker/image/aufs/layerdb/tmp/write-set-436351190 /var/lib/docker/image/aufs/layerdb/sha256/bceed376e6f968cafc509cd32709bf52aa1ad62f056facdb1d1ee01e500b122d: directory not empty
Failed after 5 retries. {"max":5,"backoff":500}: stable: Pulling from kalabox/proxy

stable: Pulling from kalabox/proxy
: stable: Pulling from kalabox/proxy

    at buildVerror (/Applications/Kalabox.app/Contents/MacOS/bin/lib/util/shell.js.jx:52:10)
    at ChildProcess.<anonymous> (/Applications/Kalabox.app/Contents/MacOS/bin/lib/util/shell.js.jx:169:16)
    at ChildProcess.emit (events.js:85:17)
    at maybeClose (child_process.js:773:16)
    at Process.ChildProcess._handle.onexit (child_process.js:839:5)
error:  VError: Failed after 5 retries. {"max":5,"backoff":500}: stable: Pulling from kalabox/proxy

    at /Applications/Kalabox.app/Contents/MacOS/bin/lib/promise.js.jx:70:17
    at process._tickCallback (node.js:917:13)
```

**Comment by ccjjmartin** [comment]
@pirog I think this might be a ticket for you based on you being the owner of this repository (https://github.com/pirog/kalabox-proxy) and seeing your name on a few other issues.

**Comment by pirog** [comment]
@ccjjmartin i cant replicate this

```bash
docker pull kalabox/proxy:stable
stable: Pulling from kalabox/proxy
bb87a7d4a725: Pull complete
7ea79fec25ef: Pull complete
b7c2a5697ea8: Pull complete
Digest: sha256:9e89627d8bd155c03be0dad4fb1538cfd80665af7be8144e06cc8977e1bede00
Status: Downloaded newer image for kalabox/proxy:stable
```

**Comment by ccjjmartin** [comment]
@pirog Someone else may have pushed to docker hub before you got to it.  Works now, thanks for looking at this.  Closing this ticket.

Successful output:

```
Running post start tasks.
verbose: DOCKER COMPOSE ==> Running: ["--project-name","kalabox","--file","/Users/developer/.kalabox/downloads/kalabox/kalabox-4.yml","--file","/Users/developer/.kalabox/downloads/kalabox/kalabox-5.yml","up","-d","proxy"]
Pulling proxy (kalabox/proxy:stable)...
Creating kalabox_proxy_1
```

<img width="922" alt="screen shot 2017-01-21 at 10 57 46 pm" src="https://cloud.githubusercontent.com/assets/12279982/22180134/29dde338-e02d-11e6-807e-52c2f55aa739.png">
