### ISSUE TITLE
"Warning: a promise was created in a handler but was not returned from it" shown in console

### ISSUE THREAD

**Issue by frederickf** [kalabox/kalabox#1770]
**Tell us about your setup**

What is your Kalabox version and operating system?

*2.1.3 on MacOS Sierra 10.12.2*

Have you previously installed Kalabox? If so, what version?

*No. First install.*

**Tell us about your bug**

I've been getting the following warning. It happened during the example app installation and every time I use the command line:

```
:~/gitrepos/kalabox-app-examples/html1$ kbox version
Warning: a promise was created in a handler but was not returned from it, see http://goo.gl/rRqMUw
    at process._tickCallback (node.js:917:13)
From previous event:
    at main (/Applications/Kalabox.app/Contents/MacOS/bin/bin/kbox.js.jx:223:4)
    at Object.<anonymous> (/Applications/Kalabox.app/Contents/MacOS/bin/bin/kbox.js.jx:248:1)
    at Module._compile (module.js:619:26)
    at readX (module.js:1645:5)
    at Object.Module._extensions..jx (module.js:2102:10)
    at Module.load (module.js:440:36)
    at Function.Module._load (module.js:405:12)
    at Module.require (module.js:475:17)
    at require (module.js:493:17)
    at Object.<anonymous> (_jx_source:17:3)
    at Module._compile (module.js:619:26)
    at Module.load (module.js:449:12)
    at Function.Module._load (module.js:405:12)
    at Function.Module.runMain (module.js:871:12)
    at startup (node.js:485:18)
    at node.js:1604:3

2.1.3
```

Please detail the steps we can take to replicate this bug. Be as detailed as possible.

> 1. Install Kalabox
> 2. Use console

**Tell us more**

Does this bug prevent you from using Kalabox?

No.

**Comment by frederickf** [comment]
Here is the output from when I installed the example app:

```
~/gitrepos/kalabox-app-examples/html1$ kbox start
Warning: a promise was created in a handler but was not returned from it, see http://goo.gl/rRqMUw
    at process._tickCallback (node.js:917:13)
From previous event:
    at main (/Applications/Kalabox.app/Contents/MacOS/bin/bin/kbox.js.jx:223:4)
    at Object.<anonymous> (/Applications/Kalabox.app/Contents/MacOS/bin/bin/kbox.js.jx:248:1)
    at Module._compile (module.js:619:26)
    at readX (module.js:1645:5)
    at Object.Module._extensions..jx (module.js:2102:10)
    at Module.load (module.js:440:36)
    at Function.Module._load (module.js:405:12)
    at Module.require (module.js:475:17)
    at require (module.js:493:17)
    at Object.<anonymous> (_jx_source:17:3)
    at Module._compile (module.js:619:26)
    at Module.load (module.js:449:12)
    at Function.Module._load (module.js:405:12)
    at Function.Module.runMain (module.js:871:12)
    at startup (node.js:485:18)
    at node.js:1604:3

Warning: a promise was created in a handler but was not returned from it, see http://goo.gl/rRqMUw
    at main (/Applications/Kalabox.app/Contents/MacOS/bin/bin/kbox.js.jx:239:4)
    at Object.<anonymous> (/Applications/Kalabox.app/Contents/MacOS/bin/bin/kbox.js.jx:248:1)
    at Module._compile (module.js:619:26)
    at readX (module.js:1645:5)
    at Object.Module._extensions..jx (module.js:2102:10)
    at Module.load (module.js:440:36)
    at Function.Module._load (module.js:405:12)
    at Module.require (module.js:475:17)
    at require (module.js:493:17)
    at Object.<anonymous> (_jx_source:17:3)
    at Module._compile (module.js:619:26)
    at Module.load (module.js:449:12)
    at Function.Module._load (module.js:405:12)
    at Function.Module.runMain (module.js:871:12)
    at startup (node.js:485:18)
    at node.js:1604:3

Starting.
Cleaning up.
Running pre start tasks.
Starting containers.
Warning: a promise was created in a handler but was not returned from it, see http://goo.gl/rRqMUw
    at process._tickCallback (node.js:917:13)
From previous event:
    at main (/Applications/Kalabox.app/Contents/MacOS/bin/bin/kbox.js.jx:239:4)
    at Object.<anonymous> (/Applications/Kalabox.app/Contents/MacOS/bin/bin/kbox.js.jx:248:1)
    at Module._compile (module.js:619:26)
    at readX (module.js:1645:5)
    at Object.Module._extensions..jx (module.js:2102:10)
    at Module.load (module.js:440:36)
    at Function.Module._load (module.js:405:12)
    at Module.require (module.js:475:17)
    at require (module.js:493:17)
    at Object.<anonymous> (_jx_source:17:3)
    at Module._compile (module.js:619:26)
    at Module.load (module.js:449:12)
    at Function.Module._load (module.js:405:12)
    at Function.Module.runMain (module.js:871:12)
    at startup (node.js:485:18)
    at node.js:1604:3

Pulling web (nginx:latest)...
Pulling image library/nginx.
Pulling unison (kalabox/unison:2.49)...
Pulling image kalabox/unison.
Creating html1example_web_1
Creating html1example_unison_1
Running post start tasks.
Warning: a promise was created in a handler but was not returned from it, see http://goo.gl/rRqMUw
    at process._tickCallback (node.js:917:13)
From previous event:
    at main (/Applications/Kalabox.app/Contents/MacOS/bin/bin/kbox.js.jx:239:4)
    at Object.<anonymous> (/Applications/Kalabox.app/Contents/MacOS/bin/bin/kbox.js.jx:248:1)
    at Module._compile (module.js:619:26)
    at readX (module.js:1645:5)
    at Object.Module._extensions..jx (module.js:2102:10)
    at Module.load (module.js:440:36)
    at Function.Module._load (module.js:405:12)
    at Module.require (module.js:475:17)
    at require (module.js:493:17)
    at Object.<anonymous> (_jx_source:17:3)
    at Module._compile (module.js:619:26)
    at Module.load (module.js:449:12)
    at Function.Module._load (module.js:405:12)
    at Function.Module.runMain (module.js:871:12)
    at startup (node.js:485:18)
    at node.js:1604:3

Pulling proxy (kalabox/proxy:stable)...
Creating kalabox_proxy_1
Waiting for site to be ready.
###############################################################
                                                               
                    BOOMSHAKALAKA!                             
                                                               
  Your app has started up correctly. Here are some vitals:     
                                                               
  URL: http(s)://html1.example.kbox.site
  LOCATION: /Users/frederick.feibel/gitrepos/kalabox-app-examples/html1
                                                               
###############################################################
```

**Comment by pirog** [comment]
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!
