### ISSUE TITLE
non interactive create pantheon command failing for test/live envs

### ISSUE THREAD

**Issue by leevh** [kalabox/kalabox#1820]
Bug Report
==========

**Tell us about your setup**

What is your Kalabox version and operating system?

2.1.3 - ubuntu 16.04

**Tell us about your bug**

I'm getting an error when using create Pantheon CLI for test or live envs.  For example the following two commands error (shown below):
kbox create pantheon -- --token=TOKEN --site=my-site --env=**test** --name=my-site
kbox create pantheon -- --token=TOKEN --site=my-site --env=**live** --name=my-site

but with "dev" it works
kbox create pantheon -- --token=TOKEN --site=my-site --env=**dev** --name=my-site

The error given is 
```
Error dispatching event listeners [pre-create-configure]: Cannot read property 'php' of undefined
TypeError: Cannot read property 'php' of undefined
    at Promise.all.then.then.pantheonConfig.name (/usr/share/kalabox/plugins/kalabox-app-pantheon/lib/events.js:71:33)
    at process._tickCallback (node.js:917:13)
From previous event:
    at main (/usr/share/kalabox/bin/bin/kbox.js.jx:239:4)
    at Object.<anonymous> (/usr/share/kalabox/bin/bin/kbox.js.jx:248:1)
    at Module._compile (module.js:619:26)
    at readX (module.js:1645:5)
    at Object.Module._extensions..jx (module.js:2102:10)
    at Module.load (module.js:440:36)
    at Function.Module._load (module.js:405:12)
    at Module.require (module.js:475:17)
    at require (module.js:493:17)
    at Object.<anonymous> (_jx_source:17:3)
    at Module._compile (module.js:619:26)
    at Module.load (module.js:449:12)
    at Function.Module._load (module.js:405:12)
    at Function.Module.runMain (module.js:871:12)
    at startup (node.js:485:18)
    at node.js:1604:3


```

**Tell us more**

Could better documentation have prevented this issue? if so what should we change?

No

Does this bug prevent you from using Kalabox?

No, but it is making it more difficult to use in an automated workflow (using in CI)

Thanks!

**Comment by pirog** [comment]
hey @leevh we are going to have some decent docs on doing CI with our successor project lando (https://github.com/kalabox/lando) when we cut its beta release in the next few weeks. id scope things out over there and stay tuned for a launch email.
