### ISSUE TITLE
Unhandled rejection TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by bianqui149** [kalabox/kalabox#1839]
I am getting this error:
Unhandled rejection TypeError: Cannot read property 'name' of undefined
    at /Applications/Kalabox.app/Contents/MacOS/plugins/kalabox-app-pantheon/lib/client.js:25:30
    at arrayMap (/Applications/Kalabox.app/Contents/MacOS/plugins/kalabox-app-pantheon/node_modules/lodash/index.js:1406:25)
    at Function.map (/Applications/Kalabox.app/Contents/MacOS/plugins/kalabox-app-pantheon/node_modules/lodash/index.js:6710:14)
    at parseSites (/Applications/Kalabox.app/Contents/MacOS/plugins/kalabox-app-pantheon/lib/client.js:22:5)
    at /Applications/Kalabox.app/Contents/MacOS/plugins/kalabox-app-pantheon/lib/client.js:327:30
    at process._tickCallback (node.js:917:13)
Enviroment Mac Sierra

**Comment by bianqui149** [comment]
I remove the applications and reinstall, but now I get this error:
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
