### ISSUE TITLE
Drush SQL Import not working

### ISSUE THREAD

**Issue by pirog** [kalabox/kalabox#230]
_From @labboy0276 on March 7, 2015 22:57_

kbox drush sql-cli < /path/to/db.sql is not working, you have to do the import manually as such:

mysql -u kalabox -h example.kbox -P 49153 kalabox < ~/path/to/db.sql

_Copied from original issue: kalabox/kalabox-issues#314_

**Comment by pirog** [comment]
This is what im doing
```
PIROBOOK1:code mpirog$ kbox drush sql-cli < ~/Downloads/happy.sql -A
info: DOCKER => Creating RUN container.
info: DOCKER => Attaching RUN container.

/Users/mpirog/Desktop/kalabox/lib/engine/docker.js:337
          streamIn.setRawMode(true);
                   ^
TypeError: Object #<ReadStream> has no method 'setRawMode'
    at /Users/mpirog/Desktop/kalabox/lib/engine/docker.js:337:20
    at /Users/mpirog/Desktop/kalabox/node_modules/dockerode/lib/container.js:418:5
    at Modem.buildPayload (/Users/mpirog/Desktop/kalabox/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:214:7)
    at ClientRequest.<anonymous> (/Users/mpirog/Desktop/kalabox/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:163:12)
    at ClientRequest.EventEmitter.emit (events.js:117:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1625:21)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:119:23)
    at Socket.socketOnData [as ondata] (http.js:1520:20)
    at TCP.onread (net.js:510:27)
PIROBOOK1:code mpirog$ 
```

@bcauldwell maybe this is a case where we want to use engine.query because we are sending through a bunch of data?
