### ISSUE TITLE
`kbox uninstall -- --purge` has trouble removing containers

### ISSUE THREAD

**Issue by pirog** [kalabox/kalabox#261]
```
PIROBOOK1:citc-2 mpirog$ kbox uninstall -- --purge
info: DOCKER =>  Removing container 7ccbefff02caeb5d9ddabc4489a08e872d353d62e0cc1b535ba4f9a60da3813f. v=true, kill=false
info: DOCKER =>  Container removed. 7ccbefff02caeb5d9ddabc4489a08e872d353d62e0cc1b535ba4f9a60da3813f
Removing the codez.
info: DOCKER =>  Removing container 9fd7c24f65e25cf194025fb36ef38a6959495986e6a224d2779fd4a5d33ba442. v=true, kill=false
info: DOCKER =>  Stopping container. 9fd7c24f65e25cf194025fb36ef38a6959495986e6a224d2779fd4a5d33ba442
Error removing container 9fd7c24f65e25cf194025fb36ef38a6959495986e6a224d2779fd4a5d33ba442.: Cannot read property 'stop' of undefined
```

**Comment by pirog** [comment]
will try to get more verbose output here

**Comment by pirog** [comment]
WIth a different app `kbox uninstall -- --purge`
```
info: DOCKER =>  Removing container 965fad10e271532d65991d7c078cbb35662e5e0e8f7d8f741f2c8499043c8198. v=true, kill=false
info: DOCKER =>  Stopping container. 965fad10e271532d65991d7c078cbb35662e5e0e8f7d8f741f2c8499043c8198
Error removing container 965fad10e271532d65991d7c078cbb35662e5e0e8f7d8f741f2c8499043c8198.: Cannot read property 'stop' of undefined
VError: Error removing container 965fad10e271532d65991d7c078cbb35662e5e0e8f7d8f741f2c8499043c8198.: Cannot read property 'stop' of undefined
    at /Users/mpirog/Desktop/kalabox/node_modules/kalabox-engine-docker/docker.js:880:13
From previous event:
    at Object.remove (/Users/mpirog/Desktop/kalabox/node_modules/kalabox-engine-docker/docker.js:879:11)
From previous event:
    at /Users/mpirog/Desktop/kalabox/lib/engine.js:697:29
From previous event:
    at Object.exports.remove (/Users/mpirog/Desktop/kalabox/lib/engine.js:696:4)
    at /Users/mpirog/Desktop/kalabox/lib/app.js:632:19
From previous event:
    at uninstallComponent (/Users/mpirog/Desktop/kalabox/lib/app.js:631:4)
    at wrapper (/Users/mpirog/Desktop/kalabox/node_modules/lodash/index.js:3466:19)
From previous event:
    at /Users/mpirog/Desktop/kalabox/lib/app.js:682:6
From previous event:
    at Object.exports.uninstall (/Users/mpirog/Desktop/kalabox/lib/app.js:676:4)
    at Object.task.func (/Users/mpirog/Desktop/kalabox/plugins/kalabox-core/tasks/uninstall.js:53:18)
    at Object.exports.run (/Users/mpirog/Desktop/kalabox/lib/core/tasks.js:773:15)
    at processTask (/Users/mpirog/Desktop/kalabox/bin/kbox.js:264:16)
    at /Users/mpirog/Desktop/kalabox/bin/kbox.js:326:19
    at processImmediate [as _immediateCallback] (timers.js:358:17)
```

**Comment by bcauldwell** [comment]
@pirog I am unable to recreate this on 0.9.4. I'm thinking the fix for #327 which results in 0.9.4 might have solved the issue. Can you confirm with a quick test of your own?

**Comment by bcauldwell** [comment]
@pirog you will need to merge pull request for kalabox-services-kalabox and then update to test this.

**Comment by pirog** [comment]
@bcauldwell good to know. testing as soon as i have better `netz.

**Comment by pirog** [comment]
LGTM
