### ISSUE TITLE
Syncthing not running [was: Where do I place custom drush commands?]

### ISSUE THREAD

**Issue by donkoller** [kalabox/kalabox#278]
I have code in file:     MY_COMMAND.drush.inc
Does it go into ~/.drush or somewhere else?

**Comment by pirog** [comment]
Yoyo.

I would drop it in APPDIR/conf/drush that should get auto synced into ~/.drush inside the container.

**Comment by donkoller** [comment]
I am getting the 403 forbidden response in the browser.
However, the drupal code is in /code. (See also note at very bottom of this comment.)

Dons-MacBook-Pro:code donkoller3$ kbox drush cc drush
Enter passphrase for /ssh/.ssh/id_rsa: 
Identity added: /ssh/.ssh/id_rsa (/ssh/.ssh/id_rsa)
'drush' cache was cleared.                                           [success]
Dons-MacBook-Pro:code donkoller3$ kbox drush user-list
Enter passphrase for /ssh/.ssh/id_rsa: 
Identity added: /ssh/.ssh/id_rsa (/ssh/.ssh/id_rsa)
Command user-list needs a higher bootstrap level to run - you will   [error]
need to invoke drush from a more functional Drupal environment to run
this command.
Command user-list requires Drupal core version 6 or 7 to run.        [error]
The drush command 'user-list' could not be executed.                 [error]
The directory /code does not contain a valid Drupal installation     [error]

xxxxxxxxxxxxxxxxxxxx

But the /code directory DOES contain the Drupal core files.

**Comment by pirog** [comment]
can you go into your code directory in your terminal and run `pwd`? paste the results here

**Comment by donkoller** [comment]
/Users/donkoller3/sites/slx-local/code

Site is slx-local.kbox

**Comment by donkoller** [comment]
```Dons-MacBook-Pro:code donkoller3$ ls -a
.					COPYRIGHT.txt				README.txt				profiles
..					INSTALL.mysql.txt			UPGRADE.txt				robots.txt
.DS_Store				INSTALL.pgsql.txt			authorize.php				robots.txt standard file copy.txt
.git					INSTALL.sqlite.txt			cron.php				scripts
.gitignore				INSTALL.txt				includes				sites
.htaccess				KOZNQv8t.html				index.php				themes
.stfolder				LICENSE.txt				install.php				update.php
.stignore				MAINTAINERS.txt				misc					web.config
CHANGELOG.txt				README.md				modules					xmlrpc.php
```

**Comment by pirog** [comment]
visit `10.13.37.42:60008` in your browser. does it look like your sync is working?

**Comment by donkoller** [comment]
I get the syncthing screen at 10.13.37.42:60008. Does not look like it is syncing.

**Comment by pirog** [comment]
can you expand all the tabs, take a screenshot and paste it hither?

**Comment by donkoller** [comment]
After doing a kbox restart, after the sync container starts, I get the message:
```
EVENTS =>  Error dispatching event listeners [post-start].
```
Re the syncthing display, there are no tabs.
![screenshot 2015-07-02 16 39 39](https://cloud.githubusercontent.com/assets/1553723/8487285/0df8a2e4-20d9-11e5-8d9c-b63952486522.png)

**Comment by donkoller** [comment]
By the way, I'm running all this on my Mac (the Win 8.1 machine is on hold for a few days).

**Comment by pirog** [comment]
yeah it looks like the sync startup cycle doesnt finish because of the error

try restart with verbose mode `kbox restart -- -v`

**Comment by donkoller** [comment]
How much do you want to see?
Here's the tail:
```
debug: EVENTS =>  Error dispatching event listeners [post-stop]. Error: App code root not found: slx-2
    at fn (/usr/local/lib/node_modules/kalabox/lib/share.js:151:15)
    at /usr/local/lib/node_modules/kalabox/lib/share.js:297:24
    at arrayEach (/usr/local/lib/node_modules/kalabox/node_modules/lodash/index.js:1342:13)
    at Function.<anonymous> (/usr/local/lib/node_modules/kalabox/node_modules/lodash/index.js:3299:13)
    at /usr/local/lib/node_modules/kalabox/lib/share.js:295:9
    at /usr/local/lib/node_modules/kalabox/lib/share.js:288:6
    at Object.exports.restart (/usr/local/lib/node_modules/kalabox/lib/share.js:261:4)
    at /usr/local/lib/node_modules/kalabox/plugins/kalabox-syncthing/events.js:131:15
    at /usr/local/lib/node_modules/kalabox/lib/core/events.js:131:9
    at /usr/local/lib/node_modules/kalabox/lib/core/events.js:128:20
    at EventEngine._dispatch (/usr/local/lib/node_modules/kalabox/lib/core/events.js:126:18)
    at /usr/local/lib/node_modules/kalabox/lib/core/events.js:106:19
    at EventEngine.emit (/usr/local/lib/node_modules/kalabox/lib/core/events.js:98:21)
    at Object.exports.emit (/usr/local/lib/node_modules/kalabox/lib/core/events.js:196:4)
    at /usr/local/lib/node_modules/kalabox/lib/app.js:587:24
    at exports.stop (/usr/local/lib/node_modules/kalabox/lib/app.js:586:4)
    at Object.exports.restart (/usr/local/lib/node_modules/kalabox/lib/app.js:613:10)
    at Object.task.func (/usr/local/lib/node_modules/kalabox/plugins/kalabox-core/tasks/restart.js:14:18)
    at Object.exports.run (/usr/local/lib/node_modules/kalabox/lib/core/tasks.js:773:15)
    at processTask (/usr/local/lib/node_modules/kalabox/bin/kbox.js:264:16)
    at /usr/local/lib/node_modules/kalabox/bin/kbox.js:326:19
    at processImmediate [as _immediateCallback] (timers.js:358:17)
EVENTS =>  Error dispatching event listeners [post-stop].
Error: App code root not found: slx-2
    at fn (/usr/local/lib/node_modules/kalabox/lib/share.js:151:15)
    at /usr/local/lib/node_modules/kalabox/lib/share.js:297:24
    at arrayEach (/usr/local/lib/node_modules/kalabox/node_modules/lodash/index.js:1342:13)
    at Function.<anonymous> (/usr/local/lib/node_modules/kalabox/node_modules/lodash/index.js:3299:13)
    at /usr/local/lib/node_modules/kalabox/lib/share.js:295:9
    at /usr/local/lib/node_modules/kalabox/lib/share.js:288:6
    at Object.exports.restart (/usr/local/lib/node_modules/kalabox/lib/share.js:261:4)
    at /usr/local/lib/node_modules/kalabox/plugins/kalabox-syncthing/events.js:131:15
    at /usr/local/lib/node_modules/kalabox/lib/core/events.js:131:9
    at /usr/local/lib/node_modules/kalabox/lib/core/events.js:128:20
    at EventEngine._dispatch (/usr/local/lib/node_modules/kalabox/lib/core/events.js:126:18)
    at /usr/local/lib/node_modules/kalabox/lib/core/events.js:106:19
    at EventEngine.emit (/usr/local/lib/node_modules/kalabox/lib/core/events.js:98:21)
    at Object.exports.emit (/usr/local/lib/node_modules/kalabox/lib/core/events.js:196:4)
    at /usr/local/lib/node_modules/kalabox/lib/app.js:587:24
    at exports.stop (/usr/local/lib/node_modules/kalabox/lib/app.js:586:4)
    at Object.exports.restart (/usr/local/lib/node_modules/kalabox/lib/app.js:613:10)
    at Object.task.func (/usr/local/lib/node_modules/kalabox/plugins/kalabox-core/tasks/restart.js:14:18)
    at Object.exports.run (/usr/local/lib/node_modules/kalabox/lib/core/tasks.js:773:15)
    at processTask (/usr/local/lib/node_modules/kalabox/bin/kbox.js:264:16)
    at /usr/local/lib/node_modules/kalabox/bin/kbox.js:326:19
    at processImmediate [as _immediateCallback] (timers.js:358:17)
```

**Comment by pirog** [comment]
i thought your app was named slx-local? what is slx-2?. 

What does `kbox apps` return?

**Comment by donkoller** [comment]
slx-2 was an old app that was deleted. I suppose I needed to run kbox uninstall. ?

**Comment by pirog** [comment]
yeah, run `kbox apps` and see if slx-2 shows up

**Comment by donkoller** [comment]
kbox apps
{
  "slx-local": {
    "running": 0,
    "total": 2
  }
}

**Comment by donkoller** [comment]
Here is how I fixed it. 
   kbox down
   kbox up
   kbox start   ==>  no error messages
10.13.37.42:60008 shows that syncthing is scanning, etc.
Website is up OK

**Comment by donkoller** [comment]
Moral of the story:
Run kbox appname uninstall, don't just delete from sites directory.
