### ISSUE TITLE
Same old issue, linux kernel update, VB fails

### ISSUE THREAD

**Issue by labboy0276** [kalabox/kalabox#288]
Same as before that issue disappeared in the issue transfer.  Not sure if we can tweak this message so it is better on a kernel update.  

All we need to have it says is run this:
```
sudo /etc/init.d/vboxdrv setup
```
Here is the verbose kbox up if it matters:
```
john@kalamuna:~/kalabox/apps$ kbox up -- -v
debug: ENGINE =>  Initializing engine.
debug: ENGINE =>  Engine initialized.
debug: DISCO => AppsRegistry dirs. 0=fiksu, 1=csi, 2=kfp, 3=mac-freight, 4=peel, 5=icrw, 6=solr-test, 7=jazzyballz
debug: CONFIG => App config loaded. appCidsRoot=/home/john/kalabox/apps/fiksu/.cids, name=php-appserver, srcRoot=/home/john/kalabox/apps/fiksu, proxy=[port=80/tcp, default=true], name=mariadb, srcRoot=/home/john/kalabox/apps/fiksu, appName=fiksu, appPlugins=[kalabox-plugin-dbenv, kalabox-plugin-drush, kalabox-plugin-git, kalabox-plugin-php, kalabox-plugin-rsync], appRegistry=/home/john/.kalabox/appRegistry.json, appRoot=/home/john/kalabox/apps/fiksu, apps=[kalabox-app-drupal@0.8.1, kalabox-app-backdrop@0.8.1], appsRoot=/home/john/kalabox/apps, codeDir=code, configSources=[DEFAULT_GLOBAL_CONFIG, ENV_CONFIG], domain=kbox, downloadsRoot=/home/john/.kalabox/downloads, engine=kalabox-engine-docker@0.8.1, engineRepo=kalabox, globalPluginRoot=/home/john/kalabox/plugins, globalPlugins=[kalabox-core, kalabox-syncthing, kalabox-app-drupal, kalabox-app-backdrop], home=/home/john, kalaboxRoot=/home/john/kalabox, kboxRoot=/home/john/kalabox, logLevel=debug, logLevelConsole=info, logRoot=/home/john/.kalabox/logs, type=Linux, platform=linux, release=3.16.0-43-generic, arch=x64, drush-version=6, php-version=5.3.29, pressflow_smart_start=1, file_temporary_path=/tmp, file_public_path=sites/default/files, file_private_path=sites/default/files/private, reroute_email_enable=1, cache=0, preprocess_css=0, preprocess_js=0, fetcher_environment=local, git-username=John Ouellet, git-email=john@kalamuna.com, profile=standard, provisioned=true, services=kalabox-services-kalabox@0.8.2, shareIgnores=[*.7z, *.bz2, *.dmg, *.gz, *.iso, *.jar, *.rar, *.tar, *.tgz, *.un~, *.zip, .*.swp, .*DS_Store, .DS_Store*, ._*, .git, .sass-cache, Icon, Thumbs.db, ehthumbs.db, sites/default/files/*], sharing=true, srcRoot=/home/john/kb2, report=true, url=http://stats.kalabox.biz, sysConfRoot=/home/john/.kalabox, sysProviderRoot=/home/john/.kalabox/.provider, version=0.8.4
debug: CONFIG => App config loaded. appCidsRoot=/home/john/kalabox/apps/csi/.cids, name=php-appserver, srcRoot=/home/john/kalabox/apps/csi, proxy=[port=80/tcp, default=true], name=mariadb, srcRoot=/home/john/kalabox/apps/csi, appName=csi, appPlugins=[kalabox-plugin-dbenv, kalabox-plugin-drush, kalabox-plugin-git, kalabox-plugin-php, kalabox-plugin-rsync], appRegistry=/home/john/.kalabox/appRegistry.json, appRoot=/home/john/kalabox/apps/csi, apps=[kalabox-app-drupal@0.8.1, kalabox-app-backdrop@0.8.1], appsRoot=/home/john/kalabox/apps, codeDir=code, configSources=[DEFAULT_GLOBAL_CONFIG, ENV_CONFIG], domain=kbox, downloadsRoot=/home/john/.kalabox/downloads, engine=kalabox-engine-docker@0.8.1, engineRepo=kalabox, globalPluginRoot=/home/john/kalabox/plugins, globalPlugins=[kalabox-core, kalabox-syncthing, kalabox-app-drupal, kalabox-app-backdrop], home=/home/john, kalaboxRoot=/home/john/kalabox, kboxRoot=/home/john/kalabox, logLevel=debug, logLevelConsole=info, logRoot=/home/john/.kalabox/logs, type=Linux, platform=linux, release=3.16.0-43-generic, arch=x64, drush-version=6, php-version=5.3.29, pressflow_smart_start=1, file_temporary_path=/tmp, file_public_path=sites/default/files, file_private_path=sites/default/files/private, reroute_email_enable=1, cache=0, preprocess_css=0, preprocess_js=0, fetcher_environment=local, git-username=John Ouellet, git-email=john@kalamuna.com, profile=standard, provisioned=true, services=kalabox-services-kalabox@0.8.2, shareIgnores=[*.7z, *.bz2, *.dmg, *.gz, *.iso, *.jar, *.rar, *.tar, *.tgz, *.un~, *.zip, .*.swp, .*DS_Store, .DS_Store*, ._*, .git, .sass-cache, Icon, Thumbs.db, ehthumbs.db, sites/default/files/*], sharing=true, srcRoot=/home/john/kb2, report=true, url=http://stats.kalabox.biz, sysConfRoot=/home/john/.kalabox, sysProviderRoot=/home/john/.kalabox/.provider, version=0.8.4
debug: CONFIG => App config loaded. appCidsRoot=/home/john/kalabox/apps/kfp/.cids, name=php-appserver, srcRoot=/home/john/kalabox/apps/kfp, proxy=[port=80/tcp, default=true], name=mariadb, srcRoot=/home/john/kalabox/apps/kfp, appName=kfp, appPlugins=[kalabox-plugin-dbenv, kalabox-plugin-drush, kalabox-plugin-git, kalabox-plugin-php, kalabox-plugin-rsync], appRegistry=/home/john/.kalabox/appRegistry.json, appRoot=/home/john/kalabox/apps/kfp, apps=[kalabox-app-drupal@0.8.1, kalabox-app-backdrop@0.8.1], appsRoot=/home/john/kalabox/apps, codeDir=code, configSources=[DEFAULT_GLOBAL_CONFIG, ENV_CONFIG], domain=kbox, downloadsRoot=/home/john/.kalabox/downloads, engine=kalabox-engine-docker@0.8.1, engineRepo=kalabox, globalPluginRoot=/home/john/kalabox/plugins, globalPlugins=[kalabox-core, kalabox-syncthing, kalabox-app-drupal, kalabox-app-backdrop], home=/home/john, kalaboxRoot=/home/john/kalabox, kboxRoot=/home/john/kalabox, logLevel=debug, logLevelConsole=info, logRoot=/home/john/.kalabox/logs, type=Linux, platform=linux, release=3.16.0-43-generic, arch=x64, drush-version=6, php-version=5.3.29, pressflow_smart_start=1, file_temporary_path=/tmp, file_public_path=sites/default/files, file_private_path=sites/default/files/private, reroute_email_enable=1, cache=0, preprocess_css=0, preprocess_js=0, fetcher_environment=local, git-username=John Ouellet, git-email=john@kalamuna.com, profile=standard, provisioned=true, services=kalabox-services-kalabox@0.8.2, shareIgnores=[*.7z, *.bz2, *.dmg, *.gz, *.iso, *.jar, *.rar, *.tar, *.tgz, *.un~, *.zip, .*.swp, .*DS_Store, .DS_Store*, ._*, .git, .sass-cache, Icon, Thumbs.db, ehthumbs.db, sites/default/files/*], sharing=true, srcRoot=/home/john/kb2, report=true, url=http://stats.kalabox.biz, sysConfRoot=/home/john/.kalabox, sysProviderRoot=/home/john/.kalabox/.provider, version=0.8.4
debug: CONFIG => App config loaded. appCidsRoot=/home/john/kalabox/apps/mac-freight/.cids, name=php-appserver, srcRoot=/home/john/kalabox/apps/mac-freight, proxy=[port=80/tcp, default=true], name=mariadb, srcRoot=/home/john/kalabox/apps/mac-freight, appName=mac-freight, appPlugins=[kalabox-plugin-dbenv, kalabox-plugin-drush, kalabox-plugin-git, kalabox-plugin-php, kalabox-plugin-rsync], appRegistry=/home/john/.kalabox/appRegistry.json, appRoot=/home/john/kalabox/apps/mac-freight, apps=[kalabox-app-drupal@0.8.1, kalabox-app-backdrop@0.8.1], appsRoot=/home/john/kalabox/apps, codeDir=code, configSources=[DEFAULT_GLOBAL_CONFIG, ENV_CONFIG], domain=kbox, downloadsRoot=/home/john/.kalabox/downloads, engine=kalabox-engine-docker@0.8.1, engineRepo=kalabox, globalPluginRoot=/home/john/kalabox/plugins, globalPlugins=[kalabox-core, kalabox-syncthing, kalabox-app-drupal, kalabox-app-backdrop], home=/home/john, kalaboxRoot=/home/john/kalabox, kboxRoot=/home/john/kalabox, logLevel=debug, logLevelConsole=info, logRoot=/home/john/.kalabox/logs, type=Linux, platform=linux, release=3.16.0-43-generic, arch=x64, drush-version=6, php-version=5.4.40, pressflow_smart_start=1, file_temporary_path=/tmp, file_public_path=sites/default/files, file_private_path=sites/default/files/private, reroute_email_enable=1, cache=0, preprocess_css=0, preprocess_js=0, fetcher_environment=local, git-username=John Ouellet, git-email=john@kalamuna.com, profile=standard, provisioned=true, services=kalabox-services-kalabox@0.8.2, shareIgnores=[*.7z, *.bz2, *.dmg, *.gz, *.iso, *.jar, *.rar, *.tar, *.tgz, *.un~, *.zip, .*.swp, .*DS_Store, .DS_Store*, ._*, .git, .sass-cache, Icon, Thumbs.db, ehthumbs.db, sites/default/files/*], sharing=true, srcRoot=/home/john/kb2, report=true, url=http://stats.kalabox.biz, sysConfRoot=/home/john/.kalabox, sysProviderRoot=/home/john/.kalabox/.provider, version=0.8.4
debug: CONFIG => App config loaded. appCidsRoot=/home/john/kalabox/apps/peel/.cids, name=php-appserver, srcRoot=/home/john/kalabox/apps/peel, proxy=[port=80/tcp, default=true], name=mariadb, srcRoot=/home/john/kalabox/apps/peel, appName=peel, appPlugins=[kalabox-plugin-dbenv, kalabox-plugin-drush, kalabox-plugin-git, kalabox-plugin-php, kalabox-plugin-rsync], appRegistry=/home/john/.kalabox/appRegistry.json, appRoot=/home/john/kalabox/apps/peel, apps=[kalabox-app-drupal@0.8.1, kalabox-app-backdrop@0.8.1], appsRoot=/home/john/kalabox/apps, codeDir=code, configSources=[DEFAULT_GLOBAL_CONFIG, ENV_CONFIG], domain=kbox, downloadsRoot=/home/john/.kalabox/downloads, engine=kalabox-engine-docker@0.8.1, engineRepo=kalabox, globalPluginRoot=/home/john/kalabox/plugins, globalPlugins=[kalabox-core, kalabox-syncthing, kalabox-app-drupal, kalabox-app-backdrop], home=/home/john, kalaboxRoot=/home/john/kalabox, kboxRoot=/home/john/kalabox, logLevel=debug, logLevelConsole=info, logRoot=/home/john/.kalabox/logs, type=Linux, platform=linux, release=3.16.0-43-generic, arch=x64, drush-version=6, php-version=5.4.40, pressflow_smart_start=1, file_temporary_path=/tmp, file_public_path=sites/default/files, file_private_path=sites/default/files/private, reroute_email_enable=1, cache=0, preprocess_css=0, preprocess_js=0, fetcher_environment=local, git-username=John Ouellet, git-email=john@kalamuna.com, profile=standard, provisioned=true, services=kalabox-services-kalabox@0.8.2, shareIgnores=[*.7z, *.bz2, *.dmg, *.gz, *.iso, *.jar, *.rar, *.tar, *.tgz, *.un~, *.zip, .*.swp, .*DS_Store, .DS_Store*, ._*, .git, .sass-cache, Icon, Thumbs.db, ehthumbs.db, sites/default/files/*], sharing=true, srcRoot=/home/john/kb2, report=true, url=http://stats.kalabox.biz, sysConfRoot=/home/john/.kalabox, sysProviderRoot=/home/john/.kalabox/.provider, version=0.8.4
debug: CONFIG => App config loaded. appCidsRoot=/home/john/kalabox/apps/icrw/.cids, name=php-appserver, srcRoot=/home/john/kalabox/apps/icrw, proxy=[port=80/tcp, default=true], name=mariadb, srcRoot=/home/john/kalabox/apps/icrw, appName=icrw, appPlugins=[kalabox-plugin-dbenv, kalabox-plugin-drush, kalabox-plugin-git, kalabox-plugin-php, kalabox-plugin-rsync], appRegistry=/home/john/.kalabox/appRegistry.json, appRoot=/home/john/kalabox/apps/icrw, apps=[kalabox-app-drupal@0.8.1, kalabox-app-backdrop@0.8.1], appsRoot=/home/john/kalabox/apps, codeDir=code, configSources=[DEFAULT_GLOBAL_CONFIG, ENV_CONFIG], domain=kbox, downloadsRoot=/home/john/.kalabox/downloads, engine=kalabox-engine-docker@0.8.1, engineRepo=kalabox, globalPluginRoot=/home/john/kalabox/plugins, globalPlugins=[kalabox-core, kalabox-syncthing, kalabox-app-drupal, kalabox-app-backdrop], home=/home/john, kalaboxRoot=/home/john/kalabox, kboxRoot=/home/john/kalabox, logLevel=debug, logLevelConsole=info, logRoot=/home/john/.kalabox/logs, type=Linux, platform=linux, release=3.16.0-43-generic, arch=x64, drush-version=5, php-version=5.3.29, pressflow_smart_start=1, file_temporary_path=/tmp, file_public_path=sites/default/files, file_private_path=sites/default/files/private, reroute_email_enable=1, cache=0, preprocess_css=0, preprocess_js=0, fetcher_environment=local, git-username=John Ouellet, git-email=john@kalamuna.com, profile=standard, provisioned=true, services=kalabox-services-kalabox@0.8.2, shareIgnores=[*.7z, *.bz2, *.dmg, *.gz, *.iso, *.jar, *.rar, *.tar, *.tgz, *.un~, *.zip, .*.swp, .*DS_Store, .DS_Store*, ._*, .git, .sass-cache, Icon, Thumbs.db, ehthumbs.db, sites/default/files/*], sharing=true, srcRoot=/home/john/kb2, report=true, url=http://stats.kalabox.biz, sysConfRoot=/home/john/.kalabox, sysProviderRoot=/home/john/.kalabox/.provider, version=0.8.4
debug: CONFIG => App config loaded. appCidsRoot=/home/john/kalabox/apps/solr-test/.cids, name=pantheon/appserver, srcRoot=/home/john/kalabox/apps/solr-test, proxy=[port=80/tcp, default=true], name=mariadb, srcRoot=/home/john/kalabox/apps/solr-test, name=kalabox/solr:test, srcRoot=/home/john/kalabox/apps/solr-test, appName=solr-test, appPlugins=[kalabox-plugin-git, kalabox-plugin-pantheon], appRegistry=/home/john/.kalabox/appRegistry.json, appRoot=/home/john/kalabox/apps/solr-test, apps=[kalabox-app-drupal@0.8.1, kalabox-app-backdrop@0.8.1], appsRoot=/home/john/kalabox/apps, codeDir=code, configSources=[DEFAULT_GLOBAL_CONFIG, ENV_CONFIG], domain=kbox, downloadsRoot=/home/john/.kalabox/downloads, engine=kalabox-engine-docker@0.8.1, engineRepo=kalabox, globalPluginRoot=/home/john/kalabox/plugins, globalPlugins=[kalabox-core, kalabox-syncthing, kalabox-app-drupal, kalabox-app-backdrop], home=/home/john, kalaboxRoot=/home/john/kalabox, kboxRoot=/home/john/kalabox, logLevel=debug, logLevelConsole=info, logRoot=/home/john/.kalabox/logs, type=Linux, platform=linux, release=3.16.0-43-generic, arch=x64, framework=drupal, solr=true, redis=false, php=5.3.29, git-username=John Ouellet, git-email=john@kalamuna.com, profile=standard, provisioned=true, services=kalabox-services-kalabox@0.8.2, shareIgnores=[*.7z, *.bz2, *.dmg, *.gz, *.iso, *.jar, *.rar, *.tar, *.tgz, *.un~, *.zip, .*.swp, .*DS_Store, .DS_Store*, ._*, .git, .sass-cache, Icon, Thumbs.db, ehthumbs.db, files, sites/default/files/*], sharing=true, srcRoot=/home/john/kb2, report=true, url=http://stats.kalabox.biz, sysConfRoot=/home/john/.kalabox, sysProviderRoot=/home/john/.kalabox/.provider, version=0.8.4
debug: CONFIG => App config loaded. appCidsRoot=/home/john/kalabox/apps/jazzyballz/.cids, name=php-appserver, srcRoot=/home/john/kalabox/apps/jazzyballz, proxy=[port=80/tcp, default=true], name=mariadb, srcRoot=/home/john/kalabox/apps/jazzyballz, appName=jazzyballz, appPlugins=[kalabox-plugin-dbenv, kalabox-plugin-drush, kalabox-plugin-git, kalabox-plugin-php, kalabox-plugin-rsync], appRegistry=/home/john/.kalabox/appRegistry.json, appRoot=/home/john/kalabox/apps/jazzyballz, apps=[kalabox-app-drupal@0.8.1, kalabox-app-backdrop@0.8.1], appsRoot=/home/john/kalabox/apps, codeDir=code, configSources=[DEFAULT_GLOBAL_CONFIG, ENV_CONFIG], domain=kbox, downloadsRoot=/home/john/.kalabox/downloads, engine=kalabox-engine-docker@0.8.1, engineRepo=kalabox, globalPluginRoot=/home/john/kalabox/plugins, globalPlugins=[kalabox-core, kalabox-syncthing, kalabox-app-drupal, kalabox-app-backdrop], home=/home/john, kalaboxRoot=/home/john/kalabox, kboxRoot=/home/john/kalabox, logLevel=debug, logLevelConsole=info, logRoot=/home/john/.kalabox/logs, type=Linux, platform=linux, release=3.16.0-43-generic, arch=x64, drush-version=6, php-version=5.4.40, pressflow_smart_start=1, file_temporary_path=/tmp, file_public_path=sites/default/files, file_private_path=sites/default/files/private, reroute_email_enable=1, cache=0, preprocess_css=0, preprocess_js=0, fetcher_environment=local, git-username=John Ouellet, git-email=john@kalanuna.com, profile=standard, provisioned=true, services=kalabox-services-kalabox@0.8.2, shareIgnores=[*.7z, *.bz2, *.dmg, *.gz, *.iso, *.jar, *.rar, *.tar, *.tgz, *.un~, *.zip, .*.swp, .*DS_Store, .DS_Store*, ._*, .sass-cache, Icon, Thumbs.db, ehthumbs.db, sites/default/files/*], sharing=true, srcRoot=/home/john/kb2, report=true, url=http://stats.kalabox.biz, sysConfRoot=/home/john/.kalabox, sysProviderRoot=/home/john/.kalabox/.provider, version=0.8.4
debug: DOCKER =>  Initializing provider.
debug: DOCKER =>  Provider initialized.
debug: BOOT2DOCKER =>  Executing command. 0=which, 1=boot2docker
debug: BOOT2DOCKER =>  Command results. /usr/local/bin/boot2docker

info: BOOT2DOCKER =>  Starting up. maxRetries=3, max=3
debug: EVENTS =>  Emitting event [pre-up].
debug: EVENTS =>  No listeners [pre-up].
debug: EVENTS =>  Finished dispatching event listeners [pre-up].
info: BOOT2DOCKER =>  Initializing boot2docker [1].
debug: BOOT2DOCKER =>  Executing command. 0=boot2docker, 1=init
debug: BOOT2DOCKER =>  Command results. Virtual machine Kalabox2 already exists

info: BOOT2DOCKER =>  Sharing folders [1].
info: BOOT2DOCKER =>  Bringing boot2docker up [1].
debug: BOOT2DOCKER =>  Executing command. 0=boot2docker, 1=up
debug: BOOT2DOCKER =>  Error running command "boot2docker,up". Error: code: 1, msg: error in run: Failed to start machine "Kalabox2" (run again with -v for details)

    at /home/john/kb2/lib/util/shell.js:98:13
    at /home/john/kb2/node_modules/shelljs/src/exec.js:107:7
    at ChildProcess.exithandler (child_process.js:758:5)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Socket.<anonymous> (child_process.js:1183:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:485:12)
info: BOOT2DOCKER =>  Bringing up boot2docker failed, retrying. VError: Error running command "boot2docker,up".: code: 1, msg: error in run: Failed to start machine "Kalabox2" (run again with -v for details)

    at /home/john/kb2/node_modules/kalabox-engine-docker/provider/b2d.js:63:13
From previous event:
    at sh (/home/john/kb2/node_modules/kalabox-engine-docker/provider/b2d.js:61:11)
    at shProvider (/home/john/kb2/node_modules/kalabox-engine-docker/provider/b2d.js:150:12)
    at /home/john/kb2/node_modules/kalabox-engine-docker/provider/b2d.js:214:16
    at /home/john/kb2/node_modules/kalabox-engine-docker/node_modules/retry-bluebird/retry-bluebird.js:29:14
From previous event:
    at rec (/home/john/kb2/node_modules/kalabox-engine-docker/node_modules/retry-bluebird/retry-bluebird.js:28:23)
    at module.exports (/home/john/kb2/node_modules/kalabox-engine-docker/node_modules/retry-bluebird/retry-bluebird.js:48:10)
    at /home/john/kb2/node_modules/kalabox-engine-docker/provider/b2d.js:210:14
From previous event:
    at Object.up (/home/john/kb2/node_modules/kalabox-engine-docker/provider/b2d.js:209:6)
From previous event:
    at /home/john/kb2/lib/engine.js:263:31
From previous event:
    at Object.exports.up (/home/john/kb2/lib/engine.js:262:4)
    at Object.task.func (/home/john/kb2/node_modules/kalabox-engine-docker/lib/tasks.js:22:14)
    at Object.exports.run (/home/john/kb2/lib/core/tasks.js:773:15)
    at processTask (/home/john/kb2/bin/kbox.js:264:16)
    at /home/john/kb2/bin/kbox.js:334:15
    at /home/john/kb2/bin/kbox.js:66:5
    at /home/john/kb2/node_modules/async/lib/async.js:154:25
    at processImmediate [as _immediateCallback] (timers.js:367:17)
info: BOOT2DOCKER =>  Bringing boot2docker up [2].
debug: BOOT2DOCKER =>  Executing command. 0=boot2docker, 1=up
debug: BOOT2DOCKER =>  Error running command "boot2docker,up". Error: code: 1, msg: error in run: Failed to start machine "Kalabox2" (run again with -v for details)

    at /home/john/kb2/lib/util/shell.js:98:13
    at /home/john/kb2/node_modules/shelljs/src/exec.js:107:7
    at ChildProcess.exithandler (child_process.js:758:5)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Socket.<anonymous> (child_process.js:1183:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:485:12)
info: BOOT2DOCKER =>  Bringing up boot2docker failed, retrying. VError: Error running command "boot2docker,up".: code: 1, msg: error in run: Failed to start machine "Kalabox2" (run again with -v for details)

    at /home/john/kb2/node_modules/kalabox-engine-docker/provider/b2d.js:63:13
From previous event:
    at sh (/home/john/kb2/node_modules/kalabox-engine-docker/provider/b2d.js:61:11)
    at shProvider (/home/john/kb2/node_modules/kalabox-engine-docker/provider/b2d.js:150:12)
    at /home/john/kb2/node_modules/kalabox-engine-docker/provider/b2d.js:214:16
    at /home/john/kb2/node_modules/kalabox-engine-docker/node_modules/retry-bluebird/retry-bluebird.js:29:14
From previous event:
    at rec (/home/john/kb2/node_modules/kalabox-engine-docker/node_modules/retry-bluebird/retry-bluebird.js:28:23)
    at /home/john/kb2/node_modules/kalabox-engine-docker/node_modules/retry-bluebird/retry-bluebird.js:37:18
From previous event:
    at /home/john/kb2/node_modules/kalabox-engine-docker/node_modules/retry-bluebird/retry-bluebird.js:36:10
From previous event:
    at rec (/home/john/kb2/node_modules/kalabox-engine-docker/node_modules/retry-bluebird/retry-bluebird.js:32:11)
    at module.exports (/home/john/kb2/node_modules/kalabox-engine-docker/node_modules/retry-bluebird/retry-bluebird.js:48:10)
    at /home/john/kb2/node_modules/kalabox-engine-docker/provider/b2d.js:210:14
From previous event:
    at Object.up (/home/john/kb2/node_modules/kalabox-engine-docker/provider/b2d.js:209:6)
From previous event:
    at /home/john/kb2/lib/engine.js:263:31
From previous event:
    at Object.exports.up (/home/john/kb2/lib/engine.js:262:4)
    at Object.task.func (/home/john/kb2/node_modules/kalabox-engine-docker/lib/tasks.js:22:14)
    at Object.exports.run (/home/john/kb2/lib/core/tasks.js:773:15)
    at processTask (/home/john/kb2/bin/kbox.js:264:16)
    at /home/john/kb2/bin/kbox.js:334:15
    at /home/john/kb2/bin/kbox.js:66:5
    at /home/john/kb2/node_modules/async/lib/async.js:154:25
    at processImmediate [as _immediateCallback] (timers.js:367:17)
info: BOOT2DOCKER =>  Bringing boot2docker up [3].
debug: BOOT2DOCKER =>  Executing command. 0=boot2docker, 1=up
debug: BOOT2DOCKER =>  Error running command "boot2docker,up". Error: code: 1, msg: error in run: Failed to start machine "Kalabox2" (run again with -v for details)

    at /home/john/kb2/lib/util/shell.js:98:13
    at /home/john/kb2/node_modules/shelljs/src/exec.js:107:7
    at ChildProcess.exithandler (child_process.js:758:5)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Socket.<anonymous> (child_process.js:1183:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:485:12)
info: BOOT2DOCKER =>  Bringing up boot2docker failed, retrying. VError: Error running command "boot2docker,up".: code: 1, msg: error in run: Failed to start machine "Kalabox2" (run again with -v for details)

    at /home/john/kb2/node_modules/kalabox-engine-docker/provider/b2d.js:63:13
From previous event:
    at sh (/home/john/kb2/node_modules/kalabox-engine-docker/provider/b2d.js:61:11)
    at shProvider (/home/john/kb2/node_modules/kalabox-engine-docker/provider/b2d.js:150:12)
    at /home/john/kb2/node_modules/kalabox-engine-docker/provider/b2d.js:214:16
    at /home/john/kb2/node_modules/kalabox-engine-docker/node_modules/retry-bluebird/retry-bluebird.js:29:14
From previous event:
    at rec (/home/john/kb2/node_modules/kalabox-engine-docker/node_modules/retry-bluebird/retry-bluebird.js:28:23)
    at /home/john/kb2/node_modules/kalabox-engine-docker/node_modules/retry-bluebird/retry-bluebird.js:37:18
From previous event:
    at rec (/home/john/kb2/node_modules/kalabox-engine-docker/node_modules/retry-bluebird/retry-bluebird.js:32:11)
    at module.exports (/home/john/kb2/node_modules/kalabox-engine-docker/node_modules/retry-bluebird/retry-bluebird.js:48:10)
    at /home/john/kb2/node_modules/kalabox-engine-docker/provider/b2d.js:210:14
From previous event:
    at Object.up (/home/john/kb2/node_modules/kalabox-engine-docker/provider/b2d.js:209:6)
From previous event:
    at /home/john/kb2/lib/engine.js:263:31
From previous event:
    at Object.exports.up (/home/john/kb2/lib/engine.js:262:4)
    at Object.task.func (/home/john/kb2/node_modules/kalabox-engine-docker/lib/tasks.js:22:14)
    at Object.exports.run (/home/john/kb2/lib/core/tasks.js:773:15)
    at processTask (/home/john/kb2/bin/kbox.js:264:16)
    at /home/john/kb2/bin/kbox.js:334:15
    at /home/john/kb2/bin/kbox.js:66:5
    at /home/john/kb2/node_modules/async/lib/async.js:154:25
    at processImmediate [as _immediateCallback] (timers.js:367:17)
Error bringing boot2docker up.: BOOT2DOCKER =>  Bringing up boot2docker failed, retrying.
VError: Error bringing boot2docker up.: BOOT2DOCKER =>  Bringing up boot2docker failed, retrying.
    at /home/john/kb2/node_modules/kalabox-engine-docker/provider/b2d.js:218:17
From previous event:
    at /home/john/kb2/node_modules/kalabox-engine-docker/provider/b2d.js:216:15
    at /home/john/kb2/node_modules/kalabox-engine-docker/node_modules/retry-bluebird/retry-bluebird.js:29:14
From previous event:
    at rec (/home/john/kb2/node_modules/kalabox-engine-docker/node_modules/retry-bluebird/retry-bluebird.js:28:23)
    at /home/john/kb2/node_modules/kalabox-engine-docker/node_modules/retry-bluebird/retry-bluebird.js:37:18
From previous event:
    at rec (/home/john/kb2/node_modules/kalabox-engine-docker/node_modules/retry-bluebird/retry-bluebird.js:32:11)
    at module.exports (/home/john/kb2/node_modules/kalabox-engine-docker/node_modules/retry-bluebird/retry-bluebird.js:48:10)
    at /home/john/kb2/node_modules/kalabox-engine-docker/provider/b2d.js:210:14
From previous event:
    at Object.up (/home/john/kb2/node_modules/kalabox-engine-docker/provider/b2d.js:209:6)
From previous event:
    at /home/john/kb2/lib/engine.js:263:31
From previous event:
    at Object.exports.up (/home/john/kb2/lib/engine.js:262:4)
    at Object.task.func (/home/john/kb2/node_modules/kalabox-engine-docker/lib/tasks.js:22:14)
    at Object.exports.run (/home/john/kb2/lib/core/tasks.js:773:15)
    at processTask (/home/john/kb2/bin/kbox.js:264:16)
    at /home/john/kb2/bin/kbox.js:334:15
    at /home/john/kb2/bin/kbox.js:66:5
    at /home/john/kb2/node_modules/async/lib/async.js:154:25
    at processImmediate [as _immediateCallback] (timers.js:367:17)
```

**Comment by labboy0276** [comment]
I am actually finding the command above no longer works with our setup now, this does though:
```
sudo apt-get install --reinstall virtualbox-dkms
```
then running kbox up alleviate all problems.  Again I don't expect you guys to do anything about this, it is more of a reference for future linux users.

**Comment by pirog** [comment]
going to close this in favor of #640

**Comment by jeffesquivels** [comment]
@labboy0276 I'm guessing you had virtualbox-dkms installed before running the `apt-get install --reinstall virtualbox-dkms` command, right?

I'm asking because if this is the case, it may be a separate issue from #640 (which should be solved just by making sure virtualbox-dkms is installed along virtualbox).

**Comment by labboy0276** [comment]
Correct, although I haven;t had to run that command in quite sometime.
Usually only need to run ```sudo /etc/init.d/vboxdrv setup``` Since I use
KB2 only VB now.

On Tue, Nov 10, 2015 at 11:18 PM, Jeffrey Esquivel S. <
notifications@github.com> wrote:

> @labboy0276 <https://github.com/labboy0276> I'm guessing you had
> virtualbox-dkms installed before running the apt-get install --reinstall
> virtualbox-dkms command, right?
>
> I'm asking because if this is the case, it may be a separate issue from
> #640 <https://github.com/kalabox/kalabox/issues/640> (which should be
> solved just by making sure virtualbox-dkms is installed along virtualbox).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/288#issuecomment-155656886>.
>



-- 
*John Ouellet*
*Sr Developer & Support Manager*
415-470-3076
www.kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by jeffesquivels** [comment]
@labboy0276 yes, I thought the dkms thing would solve the issue, but it didn't help (I tested yesterday and I still needed to run `sudo /etc/init.d/vboxdrv setup` before kalabox's VM could start again, so it seems that the detection for that scenario inside kalabox will still be necessary.
