### ISSUE TITLE
After updating to 0.9.x, run kbox update in app & get Error running step: {"name":"core-rebuild"...

### ISSUE THREAD

**Issue by pi-ron** [kalabox/kalabox#348]
I'm getting an error when running `kbox update` within an app's directory, after updating from 0.8.x, using the following steps:

1. `npm install kalabox -g`
2. Change package versions from 0.8.0 to 0.9.0 in app's `packages.json` file:
``````
{
  "name": "parcel-upstream",
  "dependencies": {
    "kalabox-plugin-dbenv": "~0.9.0",
    "kalabox-plugin-drush": "~0.9.0",
    "kalabox-plugin-git": "~0.9.0",
    "kalabox-plugin-php": "~0.9.0",
    "kalabox-plugin-rsync": "~0.9.0"
  }
}
``````

3. Run `kbox update` in app:

``````
Roamings-iMac:parcel-upstream RoamingMac$ kbox update
info: -- Step 1/7 --
info: Authorizing update subroutines...
? Are you sure you want to update this app? Yes
info: -- OK! 14% complete! --

info: -- Step 2/7 --
info: Checking firewall settings...
info: -- OK! 29% complete! --

info: -- Step 3/7 --
info: Checking for Internet access...
info: -- OK! 43% complete! --

info: -- Step 4/7 --
info: Checking for available disk space...
info: -- OK! 57% complete! --

info: -- Step 5/7 --
info: Downloading files...
info: -- OK! 71% complete! --

info: -- Step 6/7 --
info: Updating your app deps...
npm WARN package.json parcel-upstream@ No description
npm WARN package.json parcel-upstream@ No repository field.
npm WARN package.json parcel-upstream@ No README data
npm WARN package.json parcel-upstream@ No license field.
kalabox-plugin-dbenv@0.9.4 node_modules/kalabox-plugin-dbenv
└── lodash@3.10.0

kalabox-plugin-rsync@0.9.1 node_modules/kalabox-plugin-rsync
└── lodash@3.10.0

kalabox-plugin-php@0.9.1 node_modules/kalabox-plugin-php
└── lodash@3.10.0

kalabox-plugin-drush@0.9.2 node_modules/kalabox-plugin-drush
└── lodash@3.10.0

kalabox-plugin-git@0.9.1 node_modules/kalabox-plugin-git
└── lodash@3.10.0
info: -- OK! 86% complete! --

info: -- Step 7/7 --
info: Rebuild?
? Download new containers and rebuild app? Yes
info: BOOT2DOCKER =>  Starting up. maxRetries=3, max=3
info: BOOT2DOCKER =>  Initializing boot2docker [1].
info: BOOT2DOCKER =>  Bringing boot2docker up [1].
info: BOOT2DOCKER =>  Boot2docker is up.
Kalabox engine has been activated.
Error running step: {"name":"core-rebuild","description":"Rebuild?","deps":["core-deps"],"subscribes":[],"isStep":true}: Error querying isRunning: "false".: Invalid cid: false
VError: Error querying isRunning: "false".: Invalid cid: false
    at /usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/docker.js:301:13
From previous event:
    at Object.verify (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-services-kalabox/kalabox.js:265:6)
From previous event:
    at Object.exports.verify (/usr/local/lib/node_modules/kalabox/lib/services.js:89:29)
    at exports.stop (/usr/local/lib/node_modules/kalabox/lib/app.js:564:19)
    at Object.exports.rebuild (/usr/local/lib/node_modules/kalabox/lib/app.js:716:10)
    at /usr/local/lib/node_modules/kalabox/plugins/kalabox-core/update.js:43:22
    at process._tickCallback (node.js:419:13)
``````

**Comment by pi-ron** [comment]
After doing above, tried `kbox rebuild` in app:

``````
Roamings-iMac:parcel-upstream RoamingMac$ kbox rebuild
Error querying isRunning: "false".: Invalid cid: false
Error: Invalid cid: false
    at /usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/docker.js:289:15
    at tryCatcher (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/node_modules/bluebird/js/main/util.js:26:23)
    at Function.Promise.attempt.Promise.try (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/node_modules/bluebird/js/main/method.js:31:24)
    at Object.isRunning (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/docker.js:287:23)
    at Array.eval (eval at <anonymous> (/usr/local/lib/node_modules/kalabox/node_modules/bluebird/js/main/call_get.js:18:12), <anonymous>:8:36)
    at Array.tryCatcher (/usr/local/lib/node_modules/kalabox/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/kalabox/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/usr/local/lib/node_modules/kalabox/node_modules/bluebird/js/main/promise.js:577:18)
    at Promise._settlePromiseAtPostResolution (/usr/local/lib/node_modules/kalabox/node_modules/bluebird/js/main/promise.js:244:10)
    at Async._drainQueue (/usr/local/lib/node_modules/kalabox/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/usr/local/lib/node_modules/kalabox/node_modules/bluebird/js/main/async.js:133:10)
    at Async.drainQueues (/usr/local/lib/node_modules/kalabox/node_modules/bluebird/js/main/async.js:15:14)
    at process._tickCallback (node.js:419:13)
``````

**Comment by pi-ron** [comment]
Similar (or same) error when running `kbox start`.

Tried moving node_modules to node_modules_OLD & ran `npm install` within app directory:

````
Roamings-iMac:parcel-upstream RoamingMac$ npm install
npm WARN package.json parcel-upstream@ No description
npm WARN package.json parcel-upstream@ No repository field.
npm WARN package.json parcel-upstream@ No README data
npm WARN package.json parcel-upstream@ No license field.
kalabox-plugin-php@0.9.1 node_modules/kalabox-plugin-php
└── lodash@3.10.0

kalabox-plugin-drush@0.9.2 node_modules/kalabox-plugin-drush
└── lodash@3.10.0

kalabox-plugin-rsync@0.9.1 node_modules/kalabox-plugin-rsync
└── lodash@3.10.0

kalabox-plugin-git@0.9.1 node_modules/kalabox-plugin-git
└── lodash@3.10.0

kalabox-plugin-dbenv@0.9.4 node_modules/kalabox-plugin-dbenv
└── lodash@3.10.0
``````

Still getting similar error:

``````
Roamings-iMac:parcel-upstream RoamingMac$ kbox start
Error querying isRunning: "false".: Invalid cid: false
Error: Invalid cid: false
    at /usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/docker.js:289:15
    at tryCatcher (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/node_modules/bluebird/js/main/util.js:26:23)
    at Function.Promise.attempt.Promise.try (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/node_modules/bluebird/js/main/method.js:31:24)
    at Object.isRunning (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/docker.js:287:23)
    at Array.eval (eval at <anonymous> (/usr/local/lib/node_modules/kalabox/node_modules/bluebird/js/main/call_get.js:18:12), <anonymous>:8:36)
    at Array.tryCatcher (/usr/local/lib/node_modules/kalabox/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/kalabox/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/usr/local/lib/node_modules/kalabox/node_modules/bluebird/js/main/promise.js:577:18)
    at Promise._settlePromiseAtPostResolution (/usr/local/lib/node_modules/kalabox/node_modules/bluebird/js/main/promise.js:244:10)
    at Async._drainQueue (/usr/local/lib/node_modules/kalabox/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/usr/local/lib/node_modules/kalabox/node_modules/bluebird/js/main/async.js:133:10)
    at Async.drainQueues (/usr/local/lib/node_modules/kalabox/node_modules/bluebird/js/main/async.js:15:14)
    at process._tickCallback (node.js:419:13)
``````

**Comment by pi-ron** [comment]
I've completely re installed now, I didn't see the note re. updating from pre-9.0 versions until today, nothing lost, seems to be working well for first site.

Also, great work on the Pantheon integration, it's a massive deal for us! I saw the mention in Pantheon's newsletter, can't wait to get cracking with that.

Also, introduced the second developer on our team to Kalabox, I'll let you know how she finds it and any feedback.

**Comment by pirog** [comment]
@pi-ron good to know. 0.9.x will be the release for awhile as we prep for the GUI so luckily i dont think this issue will happen for a lot of people.
