### ISSUE TITLE
On kbox create pantheon, terminus says site doesn't exist?

### ISSUE THREAD

**Issue by labboy0276** [kalabox/kalabox#354]
Hello,

I just got added to a site on Pantheon.  I went into my kb2 to download it.  I did ```kbox create pantheon``` selected my new site did all the usual wins to get this going, etc.  The site in question was in my list.  then this happened:

```
info: DOCKER =>  Ad hoc container started. 0506c9644c1ac466ecfd8e2ca16b91ac645613ad70d7298305f65393b665f510
info: DOCKER =>  Removing ad hoc container. 0506c9644c1ac466ecfd8e2ca16b91ac645613ad70d7298305f65393b665f510
Error while installing app: "huddle": EVENTS =>  Error dispatching event listeners [post-install].
VError: Error running ad hoc container with kalabox/terminus:v0.9.0.: Error: Exception thrown - No site exists with this name

    at Object.<anonymous> (/home/john/kb2/node_modules/kalabox-engine-docker/docker.js:696:13)
From previous event:
    at Object.use (/home/john/kb2/node_modules/kalabox-engine-docker/docker.js:695:11)
From previous event:
    at /home/john/kb2/lib/engine.js:566:29
From previous event:
    at Object.exports.use (/home/john/kb2/lib/engine.js:565:4)
    at /home/john/kalabox/apps/huddle/plugins/kalabox-plugin-pantheon/lib/terminus.js:87:29
From previous event:
    at Terminus.__request (/home/john/kalabox/apps/huddle/plugins/kalabox-plugin-pantheon/lib/terminus.js:76:4)
    at Terminus.getConnectionMode (/home/john/kalabox/apps/huddle/plugins/kalabox-plugin-pantheon/lib/terminus.js:176:15)
    at pullCode (/home/john/kalabox/apps/huddle/plugins/kalabox-plugin-pantheon/lib/pull.js:48:23)
    at Object.<anonymous> (/home/john/kalabox/apps/huddle/plugins/kalabox-plugin-pantheon/lib/pull.js:210:22)
From previous event:
    at /home/john/kalabox/apps/huddle/plugins/kalabox-plugin-pantheon/lib/pull.js:203:10
    at /home/john/kb2/lib/core/events.js:131:9
    at /home/john/kb2/lib/core/events.js:128:20
From previous event:
    at EventEngine._dispatch (/home/john/kb2/lib/core/events.js:126:18)
    at /home/john/kb2/lib/core/events.js:106:19
From previous event:
    at EventEngine.emit (/home/john/kb2/lib/core/events.js:98:21)
From previous event:
    at Object.exports.emit (/home/john/kb2/lib/core/events.js:196:4)
    at /home/john/kb2/lib/app.js:433:24
From previous event:
    at Object.exports.install (/home/john/kb2/lib/app.js:432:4)
    at Object.<anonymous> (/home/john/kb2/lib/create.js:336:26)
From previous event:
    at /home/john/kb2/lib/create.js:335:8
    at processImmediate [as _immediateCallback] (timers.js:367:17)
From previous event:
    at createApp (/home/john/kb2/lib/create.js:313:6)
    at PromptUI.completed (/home/john/kb2/lib/create.js:251:18)
    at PromptUI.onCompletion (/home/john/kb2/node_modules/inquirer/lib/ui/prompt.js:69:10)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (/home/john/kb2/node_modules/inquirer/node_modules/rx/dist/rx.js:1793:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/home/john/kb2/node_modules/inquirer/node_modules/rx/dist/rx.js:1730:14)
    at AnonymousObserver.tryCatcher (/home/john/kb2/node_modules/inquirer/node_modules/rx/dist/rx.js:567:29)
    at AutoDetachObserverPrototype.completed (/home/john/kb2/node_modules/inquirer/node_modules/rx/dist/rx.js:5288:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/home/john/kb2/node_modules/inquirer/node_modules/rx/dist/rx.js:1730:14)
    at InnerObserver.onCompleted (/home/john/kb2/node_modules/inquirer/node_modules/rx/dist/rx.js:3425:65)
    at InnerObserver.tryCatcher (/home/john/kb2/node_modules/inquirer/node_modules/rx/dist/rx.js:567:29)
    at AutoDetachObserverPrototype.completed (/home/john/kb2/node_modules/inquirer/node_modules/rx/dist/rx.js:5288:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/home/john/kb2/node_modules/inquirer/node_modules/rx/dist/rx.js:1730:14)
    at AutoDetachObserver.tryCatcher (/home/john/kb2/node_modules/inquirer/node_modules/rx/dist/rx.js:567:29)
    at AutoDetachObserverPrototype.completed (/home/john/kb2/node_modules/inquirer/node_modules/rx/dist/rx.js:5288:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/home/john/kb2/node_modules/inquirer/node_modules/rx/dist/rx.js:1730:14)
    at InnerObserver.onCompleted (/home/john/kb2/node_modules/inquirer/node_modules/rx/dist/rx.js:3425:65)
    at InnerObserver.tryCatcher (/home/john/kb2/node_modules/inquirer/node_modules/rx/dist/rx.js:567:29)
    at AutoDetachObserverPrototype.completed (/home/john/kb2/node_modules/inquirer/node_modules/rx/dist/rx.js:5288:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/home/john/kb2/node_modules/inquirer/node_modules/rx/dist/rx.js:1730:14)
```

**Comment by pirog** [comment]
@labboy0276 first run 

`kbox terminus site connection-mode --json --site=SITENAME --env=ENV` 

then try 

`kbox terminus site connection-mode --json --site=SITENAME --env=ENV --no-cache` 

paste the output of both

**Comment by labboy0276** [comment]
```
john@kalamuna:~/kalabox/apps/huddle$ kbox terminus site connection-mode --json --site=huddle --env=dev
Identity added: /ssh/.ssh/id_rsa (/ssh/.ssh/id_rsa)
Error: Exception thrown - No site exists with this name
```
then
```
john@kalamuna:~/kalabox/apps/huddle$ kbox terminus site connection-mode --json --site=huddle --env=dev --nocache
Identity added: /ssh/.ssh/id_rsa (/ssh/.ssh/id_rsa)
Connection mode: Git
```
So with that i see it stuck in thy cache.  I then removed ~/.terminus and it installed. we win @pirog.  Issue resolved, closing this out.

**Comment by pirog** [comment]
easy cowboy. i dont think a workaround like deleting `~/.terminus` means we should close this out. We probably want to do something like this

```js
/*
 * Get connection mode
 * terminus site connection-mode --site="$PANTHEON_SITE" --env="$PANTHEON_ENV")
 */
Terminus.prototype.getConnectionMode = function(site, env) {

  // @todo: can we use something like optimist to do better
  // options parsing?
  return this.__request(
    ['terminus'],
    ['site', 'connection-mode'],
    ['--json', '--site=' + site, '--env=' + env, '--nocache']
  );

};
```

Can you submit a PR against the pantheon app?

**Comment by labboy0276** [comment]
Good call @pirog && done:

https://github.com/kalabox/kalabox-app-pantheon/pull/6

**Comment by pirog** [comment]
thanks @labboy0276. got a message in that PR pending for @bcauldwell. as soon as you guys see it and verify we should be good to go. once merged feel free to close this.
