### ISSUE TITLE
terminus should wake up databases before attempting to connect to it

### ISSUE THREAD

**Issue by yosefromano** [kalabox/kalabox#360]
trying to push up small code chande and small database change and got this:

ERROR 2003 (HY000): Can't connect to MySQL server on 'dbserver.dev.dd8a6753-d271-4d7e-8062-510dfe8518f2.drush.in' (101)

Error: ERROR 2003 (HY000): Can't connect to MySQL server on 'dbserver.dev.dd8a6753-d271-4d7e-8062-510dfe8518f2.drush.in' (101)

    at MemoryDuplexStream.<anonymous> (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/docker.js:544:24)
    at MemoryDuplexStream.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at MemoryDuplexStream.Readable.push (_stream_readable.js:126:10)
    at MemoryDuplexStream._write (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/node_modules/memorystream/index.js:150:14)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:288:5)
    at MemoryDuplexStream.Writable.write (_stream_writable.js:217:11)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:247:16)
    at IncomingMessage.emit (events.js:104:17)
    at emitReadable_ (_stream_readable.js:424:10)
    at emitReadable (_stream_readable.js:418:7)
    at readableAddChunk (_stream_readable.js:174:11)
    at IncomingMessage.Readable.push (_stream_readable.js:126:10)
    at HTTPParser.parserOnBody (_http_common.js:132:22)
    at Socket.socketOnData (_http_client.js:317:20)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)

**Comment by labboy0276** [comment]
I get this all the time, try clearing the pantheon dev cache either via the dashboard or drush, then try this again

**Comment by yosefromano** [comment]
Worked. Thanks

**Comment by pirog** [comment]
@labboy0276 presumably this is to wake up the DB server?

**Comment by labboy0276** [comment]
@pirog correct, i thought it was just me, but I guess not.

**Comment by pirog** [comment]
good to know. i've changed the issue title to reflect this. there is a wake command in terminus so this shouldnt be super hard to resolve.

**Comment by labboy0276** [comment]
OK @pirog I spent some time on this and I think I got it down:

https://github.com/kalabox/kalabox-app-pantheon/pull/8

I created a new wake command/function in terminus.js.  I then call this during code push/pull since that s the first thing that alwats gets called n kbox push / kbox pull.

Let me now your thoughts.
