### ISSUE TITLE
kbox drush not working correctly

### ISSUE THREAD

**Issue by pi-ron** [kalabox/kalabox#361]
I've just uninstalled / installed 0.9.7 and created a new app (It had the same namespace as a previously installed app, not sure why but it pumped out container exists error when doing kbox install, so ssh'd into docker and removed the containers, installed fine after that).

I've ran my installer in browser, the site functions fine.

When running `kbox drush cc all` this seems to work no worries.

`kbox drush status`

``````
Identity added: /ssh/.ssh/id_rsa (/ssh/.ssh/id_rsa)
 Drupal version         :  7.38
 Default theme          :  garland
 Administration theme   :  garland
 PHP executable         :  /root/.phpbrew/php/php-5.3.29/bin/php
 PHP configuration      :  /root/.phpbrew/php/php-5.3.29/etc/php.ini
 PHP OS                 :  Linux
 Drush version          :  6.6.0
 Drush configuration    :
 Drush alias files      :  /root/.drush/aliases.drushrc.php
 Drupal root            :  /code
``````

I've got an old settings.php file in my codebase, but previously it didn't seem to matter, anyway drush seems to try and connect to the database defined there instead of kalabox database:

``````
$ kbox drush en devel_generate
Identity added: /ssh/.ssh/id_rsa (/ssh/.ssh/id_rsa)
PDO::__construct(): [2002] No such file or directory (trying to      [warning]
connect via unix:///tmp/mysql.sock) environment.inc:546
Command pm-enable needs a higher bootstrap level to run - you will   [error]
need to invoke drush from a more functional Drupal environment to run
this command.
The drush command 'en devel_generate' could not be executed.         [error]
Drush was not able to start (bootstrap) the Drupal database.         [error]
Hint: This may occur when Drush is trying to:
 * bootstrap a site that has not been installed or does not have a
configured database. In this case you can select another site with a
working database setup by specifying the URI to use with the --uri
parameter on the command line. See `drush topic docs-aliases` for
details.
 * connect the database through a socket. The socket file may be
wrong or the php-cli may have no access to it in a jailed shell. See
http://drupal.org/node/1428638 for details.

Drush was attempting to connect to:
 Drupal version           :  7.38
 Site URI                 :  localhost
 Database driver          :  mysql
 Database username        :  root
 Database name            :  local-parcel-upstream
 Default theme            :  garland
 Administration theme     :  garland
 PHP executable           :  /root/.phpbrew/php/php-5.3.29/bin/php
 PHP configuration        :  /root/.phpbrew/php/php-5.3.29/etc/php
                             .ini
 PHP OS                   :  Linux
 Drush version            :  6.6.0
 Drush configuration      :
 Drush alias files        :  /root/.drush/aliases.drushrc.php
 Drupal root              :  /code
 Site path                :  sites/default
 File directory path      :  sites/default/files
 Private file directory   :  sites/default/files/private
 path

``````

Removed settings.php:

``````
$ kbox drush en devel_generate
Identity added: /ssh/.ssh/id_rsa (/ssh/.ssh/id_rsa)
Command pm-enable needs a higher bootstrap level to run - you will   [error]
need to invoke drush from a more functional Drupal environment to run
this command.
The drush command 'en devel_generate' could not be executed.         [error]
Could not find a Drupal settings.php file at                         [error]
sites/default/settings.php.
``````

**Comment by pi-ron** [comment]
Not sure if my kalabox install is just screwed or what, when I am creating new apps I get a container already exists error on kbox install.  Going to try uninstall again.

``````
info: DOCKER =>  Container started. f4c522021fe1fe1b80be0321349c3cd240347add7ccbf8e6afb551bfe7def7ca
Error while installing app: "parcel": Container already exists: 9c7d5dedf85e5279a1a98be8bc712a59c44713e23ac94ee206a52d2ccf7600b6
Error: Container already exists: 9c7d5dedf85e5279a1a98be8bc712a59c44713e23ac94ee206a52d2ccf7600b6
    at /usr/local/lib/node_modules/kalabox/lib/app.js:422:17
From previous event:
    at Promise.resolve.filter.map.concurrency (/usr/local/lib/node_modules/kalabox/lib/app.js:413:8)
From previous event:
    at /usr/local/lib/node_modules/kalabox/lib/app.js:410:6
From previous event:
    at Object.exports.install (/usr/local/lib/node_modules/kalabox/lib/app.js:406:4)
    at Object.task.func (/usr/local/lib/node_modules/kalabox/plugins/kalabox-core/tasks/install.js:25:18)
    at Object.exports.run (/usr/local/lib/node_modules/kalabox/lib/core/tasks.js:773:15)
    at processTask (/usr/local/lib/node_modules/kalabox/bin/kbox.js:268:16)
    at /usr/local/lib/node_modules/kalabox/bin/kbox.js:330:19
    at process._tickCallback (node.js:419:13)
``````

**Comment by pi-ron** [comment]
https://github.com/kalabox/kalabox/issues/362

**Comment by pirog** [comment]
for the drush piece of this you need to have a settings.php to exist for drush to bootstrap even if it is the default settings.php and uses the pressflow settings.

**Comment by pi-ron** [comment]
This was happening when I still had settings.php present.

**Comment by pirog** [comment]
not saying that that is the issue but if you remove settings.php then it will def not work at all.
