### ISSUE TITLE
Updating to 0.9.8 throws error on kbox provision

### ISSUE THREAD

**Issue by pi-ron** [kalabox/kalabox#371]
Sorry to keep smashing you guys with issues! Just tried updating to 0.9.8:

``````
$ npm install kalabox -g # All runs ok

$ kbox provision

module.js:340
    throw err;
          ^
Error: Cannot find module 'sha1'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/kalabox/lib/share.js:13:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/kalabox/lib/app.js:23:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
``````

Should I just uninstall / reinstall?

**Comment by reynoldsalec** [comment]
That might be the best thing to try @pi-ron if it's not too big of a hassle, haven't seen this error, seems like a dependency is missing (which might indicate that not all the node_modules were successfully updated).

Assuming you installed Kalabox via npm originally?

**Comment by pi-ron** [comment]
Yes installed via npm, OK no worries.  Is running the update script as detailed here still the way to go? https://github.com/kalabox/kalabox/wiki/Uninstalling-Kalabox

**Comment by reynoldsalec** [comment]
@bcauldwell had the same issue and found out that sha1 is a dev dependency in kalabox's package.json, but it snuck in as a necessary dependency for production kalaboxes in a PR that was merged in earlier today, hence your issue @pi-ron and the reason why I missed it on code review (I have dev dependencies installed). Much shame on my household, but should be fixed shortly.

**Comment by reynoldsalec** [comment]
Ok, should be set @pi-ron, definitely re-open if it gives you a problem.
