### ISSUE TITLE
kbox create pantheon frequently times out

### ISSUE THREAD

**Issue by jdleonard** [kalabox/kalabox#384]
Maybe 50% of the time I run kbox create pantheon, it times out after entering my password, after selecting "Pull a pre-existing site from Pantheon", or choosing the site. It never lets me know that it has timed out until I control-c out of the command.

It would be great if:
1. A reasonable (short) timeout were set and I were notified of the timeout rather than having to quit the process to find out.
2. It didn't time out.

```
20c9d047c79d:Sites jd$ kbox create pantheon
? Pantheon dashboard email: jd@****************
? Pantheon dashboard password: **************************************
? What do you want to do? Pull a pre-existing site from Pantheon
? Which site? ************


Unhandled rejection Error: TimeoutError: operation timed out
    at /usr/local/lib/node_modules/kalabox/node_modules/kalabox-app-pantheon/app/plugins/kalabox-plugin-pantheon/lib/client.js:209:13
From previous event:
    at /usr/local/lib/node_modules/kalabox/node_modules/kalabox-app-pantheon/app/plugins/kalabox-plugin-pantheon/lib/client.js:207:11
From previous event:
    at Client.__request (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-app-pantheon/app/plugins/kalabox-plugin-pantheon/lib/client.js:192:4)
    at Client.getEnvironments (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-app-pantheon/app/plugins/kalabox-plugin-pantheon/lib/client.js:310:15)
    at /usr/local/lib/node_modules/kalabox/node_modules/kalabox-app-pantheon/lib/create.js:222:29
    at processImmediate [as _immediateCallback] (timers.js:358:17)
From previous event:
    at Object.kbox.create.add.option.inquire.choices (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-app-pantheon/lib/create.js:218:12)
    at Object.utils.runAsync (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/lib/utils/utils.js:29:22)
    at Object.<anonymous> (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/lib/utils/utils.js:75:11)
    at Object.utils.runAsync (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/lib/utils/utils.js:29:22)
    at /usr/local/lib/node_modules/kalabox/node_modules/inquirer/lib/utils/utils.js:51:13
    at tryCatcher (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:567:29)
    at setDisposable (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:5233:36)
    at AnonymousObservable.s [as _subscribe] (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:5250:11)
    at AnonymousObservable.Rx.Observable.observableProto.subscribe.observableProto.forEach (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:1976:19)
    at /usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:2449:21
    at tryCatcher (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:567:29)
    at setDisposable (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:5233:36)
    at AnonymousObservable.s [as _subscribe] (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:5250:11)
    at AnonymousObservable.Rx.Observable.observableProto.subscribe.observableProto.forEach (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:1976:19)
    at MergeObserver.handleSubscribe (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:3369:28)
    at MergeObserver.onNext (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:3375:16)
    at MergeObserver.tryCatcher (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:567:29)
    at AutoDetachObserverPrototype.next (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:5274:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:1710:35)
    at InnerObserver.onNext (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:4810:14)
    at InnerObserver.tryCatcher (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:567:29)
    at AutoDetachObserverPrototype.next (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:5274:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:1710:35)
    at InnerObserver.onNext (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:3409:91)
    at InnerObserver.tryCatcher (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:567:29)
    at AutoDetachObserverPrototype.next (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:5274:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:1710:35)
    at scheduleItem (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:2961:16)
    at Scheduler.scheduleNow [as _schedule] (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:1224:50)
    at Scheduler.Rx.Scheduler.schedulerProto.scheduleWithState (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:970:19)
    at JustSink.run (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:2966:36)
```

**Comment by pirog** [comment]
I get this on occasion as well. I think the timeout might be set on the pantheon side but we can set it up to retry failed requests.

**Comment by labboy0276** [comment]
+1 as I get this as wel

**Comment by pirog** [comment]
good to know. this is likely going to get slotted for the next sprint.

**Comment by alphex** [comment]
Coming over here from https://github.com/kalabox/kalabox/issues/406

As that ticket describes, I have two pantheon accounts.
The primary one has well over 20 (maybe 30?) sites on it.
The second one has 3.

I used the account with 3, and was able to run "kbox create pantheon" and select a site with no problems.
When I went to use the larger account, it times out on me.

I deleted ~/.terminus, and then it started working again.

Hopefully this gets fixes so I don't have to delete a directory as a work around.

Thanks!

**Comment by pirog** [comment]
@alphex good to hear from you and thanks for trying things out!

i also have a similar setup with a work account with many sites and a personal account with very few. This issue isnt in our current sprint but we should be able to look at it in the coming weeks.

**Comment by alphex** [comment]
Appreciated!
Thanks.

**Comment by mdyorke** [comment]
@alphex were you able to find a temporary solution until the team pushes up a fix?  I am experiencing the same problem and removing ~/.terminus doesn't seem to work.

Thanks!

**Comment by alphex** [comment]
ᐧ
I was not.

Just deleting the .terminus directory... I'm unsure if there's other issues
beyond that.

**Comment by pirog** [comment]
So i dont think this specific issue is going to be resolved in the release next week although we are moving to a 2 week release cycle after that and it will definitely be in the next one.

that said we greatly improved the handling of the pantheon auth for the next release so there are some big improvements you will see there.
