### ISSUE TITLE
Error on kbox provision: Error running step "engine-up"

### ISSUE THREAD

**Issue by johnbocalig** [kalabox/kalabox#396]
I installed kalabox 0.9.11 today (first time installaing Kalabox CLI) and got this error in red text:

Error running step: {"name":"engine-up","description":"Setting up and activating the engine...","deps":["engine-docker-provider-profile"],"subscribes":[],"isStep":true}: Error initializing boot2docker.: BOOT2DOCKER =>  Initializing boot2docker failed, retrying.
VError: Error initializing boot2docker.: BOOT2DOCKER =>  Initializing boot2docker failed, retrying.
    at /usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/provider/b2d.js:186:17
From previous event:
    at step.all (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/lib/install.js:69:13)
    at /usr/local/lib/node_modules/kalabox/lib/install/framework.js:414:17
    at /usr/local/lib/node_modules/kalabox/lib/install/framework.js:412:30
From previous event:
    at /usr/local/lib/node_modules/kalabox/lib/install/framework.js:404:29
From previous event:
    at /usr/local/lib/node_modules/kalabox/lib/install/framework.js:399:15
    at Object.exports.run (/usr/local/lib/node_modules/kalabox/lib/install.js:20:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/kalabox/plugins/kalabox-core/util.js:217:23)
    at Object.exports.run (/usr/local/lib/node_modules/kalabox/lib/core/tasks.js:773:15)
    at processTask (/usr/local/lib/node_modules/kalabox/bin/kbox.js:268:16)
    at /usr/local/lib/node_modules/kalabox/bin/kbox.js:338:15
    at /usr/local/lib/node_modules/kalabox/bin/kbox.js:70:5
    at /usr/local/lib/node_modules/kalabox/node_modules/async/lib/async.js:154:25
    at processImmediate [as _immediateCallback] (timers.js:367:17)

I installed kalabox CLI via npm install kalabox -g.
Here is the full log of kbox provision just in case it comes handy:

$ kbox provision
info: -- Step 1/19 --
info: Authorizing install subroutines...
? Are you sure you want to install Kalabox? Yes
info: -- OK! 5% complete! --

info: -- Step 2/19 --
info: Making sure syncthing is not running...
info: -- OK! 11% complete! --

info: -- Step 3/19 --
info: Queuing up syncthing downloads...
info: -- OK! 16% complete! --

info: -- Step 4/19 --
info: Checking firewall settings...
info: -- OK! 21% complete! --

info: -- Step 5/19 --
info: Queuing up provider downloads...
info: -- OK! 26% complete! --

info: -- Step 6/19 --
info: Checking for Internet access...
info: -- OK! 32% complete! --

info: -- Step 7/19 --
info: Checking for available disk space...
info: -- OK! 37% complete! --

info: -- Step 8/19 --
info: Downloading files...
     fetch : https://raw.githubusercontent.com/kalabox/kalabox-boot2docker/master/profile
  progress : [====================] 100% 0.0s

     fetch : https://raw.githubusercontent.com/kalabox/kalabox/master/dockerfiles/syncthing/config.xml
  progress : [====================] 100% 0.0s

     fetch : https://github.com/syncthing/syncthing/releases/download/v0.11.13/syncthing-macosx-amd64-v0.11.13.tar.gz
     fetch : https://github.com/boot2docker/osx-installer/releases/download/v1.7.0/Boot2Docker-1.7.0.pkg
  progress : [====================] 100% 0.0s

info: -- OK! 42% complete! --

info: -- Step 9/19 --
info: Setting up syncthing...
info: -- OK! 47% complete! --

info: -- Step 10/19 --
info: Setting up the provider profile...
info: -- OK! 53% complete! --

info: -- Step 11/19 --
info: Checking if dns is set...
info: -- OK! 58% complete! --

info: -- Step 12/19 --
info: Queuing up services admin commands...
info: -- OK! 63% complete! --

info: -- Step 13/19 --
info: Queuing provider admin commands...
info: -- OK! 68% complete! --

info: -- Step 14/19 --
info: Running admin install commands...
installer: Error - The installer has detected that VirtualBox is still running. Please shutdown all running VirtualBox machines and exit VirtualBox then restart the installation.

info: -- OK! 74% complete! --

info: -- Step 15/19 --
info: Setting up and activating the engine...
info: BOOT2DOCKER =>  Starting up. max=3
info: BOOT2DOCKER =>  Initializing boot2docker [1].
info: BOOT2DOCKER =>  Initializing boot2docker failed, retrying. VError: Error running command "boot2docker,init".: code: 127, msg: /bin/sh: boot2docker: command not found

    at /usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/provider/b2d.js:63:13
    at tryCatcher (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/node_modules/bluebird/js/main/promise.js:577:18)
    at Promise._settlePromises (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/node_modules/bluebird/js/main/promise.js:693:14)
    at Async._drainQueue (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
info: BOOT2DOCKER =>  Initializing boot2docker [2].
info: BOOT2DOCKER =>  Initializing boot2docker failed, retrying. VError: Error running command "boot2docker,init".: code: 127, msg: /bin/sh: boot2docker: command not found

    at /usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/provider/b2d.js:63:13
    at tryCatcher (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/node_modules/bluebird/js/main/promise.js:577:18)
    at Promise._settlePromises (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/node_modules/bluebird/js/main/promise.js:693:14)
    at Async._drainQueue (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
info: BOOT2DOCKER =>  Initializing boot2docker [3].
info: BOOT2DOCKER =>  Initializing boot2docker failed, retrying. VError: Error running command "boot2docker,init".: code: 127, msg: /bin/sh: boot2docker: command not found

    at /usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/provider/b2d.js:63:13
    at tryCatcher (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/node_modules/bluebird/js/main/promise.js:577:18)
    at Promise._settlePromises (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/node_modules/bluebird/js/main/promise.js:693:14)
    at Async._drainQueue (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
Error running step: {"name":"engine-up","description":"Setting up and activating the engine...","deps":["engine-docker-provider-profile"],"subscribes":[],"isStep":true}: Error initializing boot2docker.: BOOT2DOCKER =>  Initializing boot2docker failed, retrying.
VError: Error initializing boot2docker.: BOOT2DOCKER =>  Initializing boot2docker failed, retrying.
    at /usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/provider/b2d.js:186:17
From previous event:
    at step.all (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/lib/install.js:69:13)
    at /usr/local/lib/node_modules/kalabox/lib/install/framework.js:414:17
    at /usr/local/lib/node_modules/kalabox/lib/install/framework.js:412:30
From previous event:
    at /usr/local/lib/node_modules/kalabox/lib/install/framework.js:404:29
From previous event:
    at /usr/local/lib/node_modules/kalabox/lib/install/framework.js:399:15
    at Object.exports.run (/usr/local/lib/node_modules/kalabox/lib/install.js:20:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/kalabox/plugins/kalabox-core/util.js:217:23)
    at Object.exports.run (/usr/local/lib/node_modules/kalabox/lib/core/tasks.js:773:15)
    at processTask (/usr/local/lib/node_modules/kalabox/bin/kbox.js:268:16)
    at /usr/local/lib/node_modules/kalabox/bin/kbox.js:338:15
    at /usr/local/lib/node_modules/kalabox/bin/kbox.js:70:5
    at /usr/local/lib/node_modules/kalabox/node_modules/async/lib/async.js:154:25
    at processImmediate [as _immediateCallback] (timers.js:367:17)

**Comment by labboy0276** [comment]
Hey John,

Just try to run ```kbox provision``` again.  This is an error that is known to us #389 #210 have similar issues.  Just linking them so @pirog knows, etc.

**Comment by johnbocalig** [comment]
OS = OSX 10.10.5 Yosemite

**Comment by johnbocalig** [comment]
Hi labboy,

I just ran kbox provision again and I'm getting the same "engine-up" error as above.

Thanks,
John

**Comment by labboy0276** [comment]
Hello again,

Can you try running this again with kbox provision -- -v which is verbose mode and will give more debug output.  Then paste the output here please.

**Comment by johnbocalig** [comment]
Here you go! Hope this helps...

$ kbox provision -- -v
debug: ENGINE =>  Initializing engine.
debug: ENGINE =>  Engine initialized.
debug: DISCO => App registry does NOT contain appDirs property!
debug: DISCO => AppsRegistry dirs.
debug: [1:19] Starting core-auth
debug: description => Authorizing install subroutines...
debug: dependencies =>
info: -- Step 1/19 --
info: Authorizing install subroutines...
? Are you sure you want to install Kalabox? Yes
debug: Finished core-auth (9450)
info: -- OK! 5% complete! --

debug: [2:19] Starting syncthing-off
debug: description => Making sure syncthing is not running...
debug: dependencies => core-auth
info: -- Step 2/19 --
info: Making sure syncthing is not running...
debug: SYNC => PING http://127.0.0.1:60008
debug: SYNC-REST =>  get:http://127.0.0.1:60008/rest/system/ping {}
debug: SYNC-REST =>  get:http://127.0.0.1:60008/rest/system/ping {}
debug: Finished syncthing-off (3046)
info: -- OK! 11% complete! --

debug: [3:19] Starting syncthing-downloads
debug: description => Queuing up syncthing downloads...
debug: dependencies => core-auth
info: -- Step 3/19 --
info: Queuing up syncthing downloads...
debug: Finished syncthing-downloads (3)
info: -- OK! 16% complete! --

debug: [4:19] Starting core-firewall
debug: description => Checking firewall settings...
debug: dependencies => core-auth
info: -- Step 4/19 --
info: Checking firewall settings...
debug: Finished core-firewall (207)
info: -- OK! 21% complete! --

debug: [5:19] Starting engine-docker-downloads
debug: description => Queuing up provider downloads...
debug: dependencies =>
info: -- Step 5/19 --
info: Queuing up provider downloads...
debug: Finished engine-docker-downloads (2)
info: -- OK! 26% complete! --

debug: [6:19] Starting core-internet
debug: description => Checking for Internet access...
debug: dependencies => core-firewall
info: -- Step 6/19 --
info: Checking for Internet access...
debug: Checking: www.google.com
debug: Finished core-internet (36)
info: -- OK! 32% complete! --

debug: [7:19] Starting core-disk-space
debug: description => Checking for available disk space...
debug: dependencies => core-auth
info: -- Step 7/19 --
info: Checking for available disk space...
debug: Finished core-disk-space (26)
info: -- OK! 37% complete! --

debug: [8:19] Starting core-downloads
debug: description => Downloading files...
debug: dependencies => core-disk-space, core-internet, engine-docker-downloads, syncthing-downloads
info: -- Step 8/19 --
info: Downloading files...
debug: https://github.com/syncthing/syncthing/releases/download/v0.11.13/syncthing-macosx-amd64-v0.11.13.tar.gz -> /Users/johnbocalig/.kalabox/downloads
debug: https://raw.githubusercontent.com/kalabox/kalabox/master/dockerfiles/syncthing/config.xml -> /Users/johnbocalig/.kalabox/downloads
debug: https://raw.githubusercontent.com/kalabox/kalabox-boot2docker/master/profile -> /Users/johnbocalig/.kalabox/downloads
debug: https://github.com/boot2docker/osx-installer/releases/download/v1.7.0/Boot2Docker-1.7.0.pkg -> /Users/johnbocalig/.kalabox/downloads
     fetch : https://raw.githubusercontent.com/kalabox/kalabox-boot2docker/master/profile
  progress : [====================] 100% 0.0s

     fetch : https://raw.githubusercontent.com/kalabox/kalabox/master/dockerfiles/syncthing/config.xml
  progress : [====================] 100% 0.0s

     fetch : https://github.com/syncthing/syncthing/releases/download/v0.11.13/syncthing-macosx-amd64-v0.11.13.tar.gz
     fetch : https://github.com/boot2docker/osx-installer/releases/download/v1.7.0/Boot2Docker-1.7.0.pkg
  progress : [====================] 100% 0.0s

debug: Finished core-downloads (65409)
info: -- OK! 42% complete! --

debug: [9:19] Starting syncthing-setup
debug: description => Setting up syncthing...
debug: dependencies => core-downloads
info: -- Step 9/19 --
info: Setting up syncthing...
debug: Finished syncthing-setup (8242)
info: -- OK! 47% complete! --

debug: [10:19] Starting engine-docker-provider-profile
debug: description => Setting up the provider profile...
debug: dependencies => core-downloads
info: -- Step 10/19 --
info: Setting up the provider profile...
debug: Finished engine-docker-provider-profile (3)
info: -- OK! 53% complete! --

debug: [11:19] Starting services-kalabox-is-dns-set
debug: description => Checking if dns is set...
debug: dependencies => engine-docker-provider-profile
info: -- Step 11/19 --
info: Checking if dns is set...
debug: DNS is set.
debug: Finished services-kalabox-is-dns-set (2)
info: -- OK! 58% complete! --

debug: [12:19] Starting services-kalabox-install-dns-deps
debug: description => Queuing up services admin commands...
debug: dependencies => services-kalabox-is-dns-set
info: -- Step 12/19 --
info: Queuing up services admin commands...
debug: Finished services-kalabox-install-dns-deps (1)
info: -- OK! 63% complete! --

debug: [13:19] Starting engine-docker-install-engine
debug: description => Queuing provider admin commands...
debug: dependencies => core-auth
info: -- Step 13/19 --
info: Queuing provider admin commands...
debug: Finished engine-docker-install-engine (1148)
info: -- OK! 68% complete! --

debug: [14:19] Starting core-run-admin-commands
debug: description => Running admin install commands...
debug: dependencies => engine-docker-install-engine, services-kalabox-install-dns-deps
info: -- Step 14/19 --
info: Running admin install commands...
Password:
installer: Error - The installer has detected that VirtualBox is still running. Please shutdown all running VirtualBox machines and exit VirtualBox then restart the installation.

debug: Finished core-run-admin-commands (13973)
info: -- OK! 74% complete! --

debug: [15:19] Starting engine-up
debug: description => Setting up and activating the engine...
debug: dependencies => engine-docker-provider-profile
info: -- Step 15/19 --
info: Setting up and activating the engine...
debug: iso -> /Users/johnbocalig/.kalabox/.provider/boot2docker.iso
debug: exists -> false
debug: DOCKER =>  Initializing provider.
debug: DOCKER =>  Provider initialized.
info: BOOT2DOCKER =>  Starting up. max=3
debug: EVENTS =>  Emitting event [pre-up].
debug: EVENTS =>  No listeners [pre-up].
debug: EVENTS =>  Finished dispatching event listeners [pre-up].
info: BOOT2DOCKER =>  Initializing boot2docker [1].
debug: BOOT2DOCKER =>  Executing command. 0=boot2docker, 1=init
debug: BOOT2DOCKER =>  Error running command "boot2docker,init". Error: code: 127, msg: /bin/sh: boot2docker: command not found

    at /usr/local/lib/node_modules/kalabox/lib/util/shell.js:98:13
    at /usr/local/lib/node_modules/kalabox/node_modules/shelljs/src/exec.js:107:7
    at ChildProcess.exithandler (child_process.js:758:5)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Socket.<anonymous> (child_process.js:1183:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:485:12)
info: BOOT2DOCKER =>  Initializing boot2docker failed, retrying. VError: Error running command "boot2docker,init".: code: 127, msg: /bin/sh: boot2docker: command not found

    at /usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/provider/b2d.js:63:13
    at tryCatcher (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/node_modules/bluebird/js/main/promise.js:577:18)
    at Promise._settlePromises (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/node_modules/bluebird/js/main/promise.js:693:14)
    at Async._drainQueue (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
info: BOOT2DOCKER =>  Initializing boot2docker [2].
debug: BOOT2DOCKER =>  Executing command. 0=boot2docker, 1=init
debug: BOOT2DOCKER =>  Error running command "boot2docker,init". Error: code: 127, msg: /bin/sh: boot2docker: command not found

    at /usr/local/lib/node_modules/kalabox/lib/util/shell.js:98:13
    at /usr/local/lib/node_modules/kalabox/node_modules/shelljs/src/exec.js:107:7
    at ChildProcess.exithandler (child_process.js:758:5)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Socket.<anonymous> (child_process.js:1183:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:485:12)
info: BOOT2DOCKER =>  Initializing boot2docker failed, retrying. VError: Error running command "boot2docker,init".: code: 127, msg: /bin/sh: boot2docker: command not found

    at /usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/provider/b2d.js:63:13
    at tryCatcher (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/node_modules/bluebird/js/main/promise.js:577:18)
    at Promise._settlePromises (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/node_modules/bluebird/js/main/promise.js:693:14)
    at Async._drainQueue (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
info: BOOT2DOCKER =>  Initializing boot2docker [3].
debug: BOOT2DOCKER =>  Executing command. 0=boot2docker, 1=init
debug: BOOT2DOCKER =>  Error running command "boot2docker,init". Error: code: 127, msg: /bin/sh: boot2docker: command not found

    at /usr/local/lib/node_modules/kalabox/lib/util/shell.js:98:13
    at /usr/local/lib/node_modules/kalabox/node_modules/shelljs/src/exec.js:107:7
    at ChildProcess.exithandler (child_process.js:758:5)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Socket.<anonymous> (child_process.js:1183:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:485:12)
info: BOOT2DOCKER =>  Initializing boot2docker failed, retrying. VError: Error running command "boot2docker,init".: code: 127, msg: /bin/sh: boot2docker: command not found

    at /usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/provider/b2d.js:63:13
    at tryCatcher (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/node_modules/bluebird/js/main/promise.js:577:18)
    at Promise._settlePromises (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/node_modules/bluebird/js/main/promise.js:693:14)
    at Async._drainQueue (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
Error running step: {"name":"engine-up","description":"Setting up and activating the engine...","deps":["engine-docker-provider-profile"],"subscribes":[],"isStep":true}: Error initializing boot2docker.: BOOT2DOCKER =>  Initializing boot2docker failed, retrying.
VError: Error initializing boot2docker.: BOOT2DOCKER =>  Initializing boot2docker failed, retrying.
    at /usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/provider/b2d.js:186:17
From previous event:
    at step.all (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/lib/install.js:69:13)
    at /usr/local/lib/node_modules/kalabox/lib/install/framework.js:414:17
    at /usr/local/lib/node_modules/kalabox/lib/install/framework.js:412:30
From previous event:
    at /usr/local/lib/node_modules/kalabox/lib/install/framework.js:404:29
From previous event:
    at /usr/local/lib/node_modules/kalabox/lib/install/framework.js:399:15
    at Object.exports.run (/usr/local/lib/node_modules/kalabox/lib/install.js:20:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/kalabox/plugins/kalabox-core/util.js:217:23)
    at Object.exports.run (/usr/local/lib/node_modules/kalabox/lib/core/tasks.js:773:15)
    at processTask (/usr/local/lib/node_modules/kalabox/bin/kbox.js:268:16)
    at /usr/local/lib/node_modules/kalabox/bin/kbox.js:338:15
    at /usr/local/lib/node_modules/kalabox/bin/kbox.js:70:5
    at /usr/local/lib/node_modules/kalabox/node_modules/async/lib/async.js:154:25
    at processImmediate [as _immediateCallback] (timers.js:367:17)

**Comment by pirog** [comment]
So the issue is actually just this

```
installer: Error - The installer has detected that VirtualBox is still running. Please shutdown all running VirtualBox machines and exit VirtualBox then restart the installation.
```

I would close out VB and try again. 

We should get the installer to properly error at that point and not further down the chain.

**Comment by johnbocalig** [comment]
Aha! That was it! I had Docker running another vbox instance while I was trying to install. Thanks @pirog and @labboy0276!

**Comment by pirog** [comment]
@labboy0276 @reynoldsalec  maybe we should open up an issue to force close VB before a provision?

**Comment by labboy0276** [comment]
#411 @pirog was created for this.

**Comment by pirog** [comment]
nice. thanks @johnbocalig and @labboy0276. will try to get this into an upcoming sprint
