### ISSUE TITLE
kbox create pantheon -v

### ISSUE THREAD

**Issue by rgeleta** [kalabox/kalabox#404]
Per readme.md, entering
kbox create pantheon -- -h 
provides help for creating a new kbox showing -v or --verbose as an argument
entering
kbox create pantheon -v
fails, first line of error dump is
Expected exactly 0 arguments, but received ["-v"]

Environment: Win 8.1 Pro 64 bit

Problem appears to be caused by lack of -- prior to -v.
Documentation should be updated to note this in the beginning

full error text:
Expected exactly 0 arguments, but received ["-v"].
Error: Expected exactly 0 arguments, but received ["-v"].
    at Object.exports.run (C:\Users\bob\AppData\Roaming\npm\node_modules\kalabox\lib\core\tasks.js:743:13)
    at processTask (C:\Users\bob\AppData\Roaming\npm\node_modules\kalabox\bin\kbox.js:268:16)
    at C:\Users\bob\AppData\Roaming\npm\node_modules\kalabox\bin\kbox.js:338:15
    at C:\Users\bob\AppData\Roaming\npm\node_modules\kalabox\bin\kbox.js:70:5
    at C:\Users\bob\AppData\Roaming\npm\node_modules\kalabox\node_modules\async\lib\async.js:154:25
    at tryCatcher (C:\Users\bob\AppData\Roaming\npm\node_modules\kalabox\node_modules\bluebird\js\main\util.js:26:23)
    at Promise.successAdapter (C:\Users\bob\AppData\Roaming\npm\node_modules\kalabox\node_modules\bluebird\js\main\nodeify.js:23:30)
    at Promise._settlePromiseAt (C:\Users\bob\AppData\Roaming\npm\node_modules\kalabox\node_modules\bluebird\js\main\promise.js:575:21)
    at Promise._settlePromises (C:\Users\bob\AppData\Roaming\npm\node_modules\kalabox\node_modules\bluebird\js\main\promise.js:693:14)
    at Async._drainQueue (C:\Users\bob\AppData\Roaming\npm\node_modules\kalabox\node_modules\bluebird\js\main\async.js:123:16)
    at Async._drainQueues (C:\Users\bob\AppData\Roaming\npm\node_modules\kalabox\node_modules\bluebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\bob\AppData\Roaming\npm\node_modules\kalabox\node_modules\bluebird\js\main\async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:367:17)

**Comment by labboy0276** [comment]
Hey @rgeleta 

I can see your confusions with the readme.  All flagged commands are run like this though:

```kbox COMMAND -- option```

@pirog thoughts on cleaning up the readme a little bit to make it a little more clearer?

**Comment by pirog** [comment]
What would make it more clear than

`Usage: kbox <command> [-- <options>]`

i feel like that spells it out pretty good?
