### ISSUE TITLE
kbox create pantheon times out on OSX.

### ISSUE THREAD

**Issue by alphex** [kalabox/kalabox#406]
When running $ kbox create pantheon, after entering my email and password for pantheon (which I've confirmed via dashboard.pantheon.io I'm entering correctly).

I get a unhandled rejection error.

```
$ kbox create pantheon
? Pantheon dashboard email: duran [at] alphex [dot] com
? Pantheon dashboard password: ***************************
? What do you want to do? Pull a pre-existing site from Pantheon


Unhandled rejection Error: TimeoutError: operation timed out
    at /usr/local/lib/node_modules/kalabox/node_modules/kalabox-app-pantheon/app/plugins/kalabox-plugin-pantheon/lib/client.js:209:13
From previous event:
    at /usr/local/lib/node_modules/kalabox/node_modules/kalabox-app-pantheon/app/plugins/kalabox-plugin-pantheon/lib/client.js:207:11
From previous event:
    at Client.__request (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-app-pantheon/app/plugins/kalabox-plugin-pantheon/lib/client.js:192:4)
    at Client.getSites (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-app-pantheon/app/plugins/kalabox-plugin-pantheon/lib/client.js:278:15)
    at /usr/local/lib/node_modules/kalabox/node_modules/kalabox-app-pantheon/lib/create.js:144:29
    at processImmediate [as _immediateCallback] (timers.js:358:17)
From previous event:
    at Object.kbox.create.add.option.inquire.choices (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-app-pantheon/lib/create.js:141:12)
    at Object.utils.runAsync (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/lib/utils/utils.js:29:22)
    at Object.<anonymous> (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/lib/utils/utils.js:75:11)
    at Object.utils.runAsync (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/lib/utils/utils.js:29:22)
    at /usr/local/lib/node_modules/kalabox/node_modules/inquirer/lib/utils/utils.js:51:13
    at tryCatcher (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:567:29)
    at setDisposable (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:5233:36)
    at AnonymousObservable.s [as _subscribe] (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:5250:11)
    at AnonymousObservable.Rx.Observable.observableProto.subscribe.observableProto.forEach (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:1976:19)
    at /usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:2449:21
    at tryCatcher (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:567:29)
    at setDisposable (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:5233:36)
    at AnonymousObservable.s [as _subscribe] (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:5250:11)
    at AnonymousObservable.Rx.Observable.observableProto.subscribe.observableProto.forEach (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:1976:19)
    at MergeObserver.handleSubscribe (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:3369:28)
    at MergeObserver.onNext (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:3375:16)
    at MergeObserver.tryCatcher (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:567:29)
    at AutoDetachObserverPrototype.next (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:5274:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:1710:35)
```

As a wrinkle.
I have two pantheon accounts (a 2nd one for a client with a different email.)

I'm able to run KBOX CREATE PANTHEON on that other account, and start the process just fine.
But when I do it on my account (the one listed above), it gives this time out.

The one obvious difference, is that my account has 20+ sites on it, and the other account has 3.

Thoughts?
Help?

Thanks!

**Comment by labboy0276** [comment]
Hello

Can you try and delete your ~/.terminus folder and see if you can pull after that?

**Comment by alphex** [comment]
That got me to the select site menu...

Is the issue the ~/.terminus directory holds on to identify, if you're
switching accounts?

Thanks!
ᐧ


] duran goodyear
] alphex information solutions, llc
] w: http://alphex.com // v: 267.225.7439 // e: duran@alphex.com

**Comment by labboy0276** [comment]
Hello again,

Yeah it caches a lot of the terminus commands for KB2.  

@pirog should we rename the issue to try and remove whatever is happening in ~/.terminus to prevent said error above?

**Comment by pirog** [comment]
honestly i dont think deleting `~/.terminus` has anything to do with this issue. You should be able to switch accounts but if you have a lot of sites it can timeout. I have a lot of sites also and sometimes it does timeout for me as well, sometimes it doesn't. 

@alphex have you pinged the terminus people to ask them if they set a timeout on their side?

i think there is already an issue open for this #384 so going to close this as dup. def hit things up on the pther issue so we can all be 2GETHA.
