### ISSUE TITLE
kalabox-plugin-git -> Undefined is not a function on app install.

### ISSUE THREAD

**Issue by madeofpeople** [kalabox/kalabox#439]
```
$ kbox create pantheon
? Pantheon dashboard email: xxxxx@xxxxx.xxxx
? Pantheon dashboard password: ***************
? What do you want to do? Pull a pre-existing site from Pantheon
? Which site? greenbiz
? Which environment? sprint
? What will you call this monster you have created: gbz
? Php version? 5.3.29
? Git username? xxxxxxxxx
? Git email? xxxxx@xxxxxxx.xxx
Building your app...
npm WARN package.json gbz@ No description
npm WARN package.json gbz@ No repository field.
npm WARN package.json gbz@ No README data
npm WARN package.json gbz@ No license field.
kalabox-plugin-rsync@0.9.3 gbz/node_modules/kalabox-plugin-rsync

kalabox-plugin-drush@0.9.4 gbz/node_modules/kalabox-plugin-drush

kalabox-plugin-git@0.9.3 gbz/node_modules/kalabox-plugin-git

bluebird@2.9.34 gbz/node_modules/bluebird

inquirer@0.9.0 gbz/node_modules/inquirer
├── figures@1.3.5
├── ansi-regex@2.0.0
├── strip-ansi@3.0.0
├── cli-width@1.0.1
├── through@2.3.8
├── chalk@1.1.1 (escape-string-regexp@1.0.3, has-ansi@2.0.0, supports-color@2.0.0, ansi-styles@2.1.0)
├── readline2@0.1.1 (mute-stream@0.0.4, strip-ansi@2.0.1)
├── run-async@0.1.0 (once@1.3.2)
└── rx-lite@2.5.2

restler@3.3.0 gbz/node_modules/restler
├── yaml@0.2.3
├── qs@1.2.0
├── iconv-lite@0.2.11
└── xml2js@0.4.0 (xmlbuilder@2.6.4, sax@0.5.8)

fs-extra@0.18.4 gbz/node_modules/fs-extra
├── jsonfile@2.2.1
├── graceful-fs@3.0.8
└── rimraf@2.4.3 (glob@5.0.14)

lodash@3.10.1 gbz/node_modules/lodash
kalabox-plugin-git -> undefined is not a function
Error: kalabox-plugin-git -> undefined is not a function
    at module.exports (/Users/thiago/kalabox/gbz/node_modules/kalabox-plugin-git/index.js:11:8)
    at /usr/local/lib/node_modules/kalabox/lib/require.js:240:20
    at /usr/local/lib/node_modules/kalabox/lib/require.js:239:29
    at requireInternal (/usr/local/lib/node_modules/kalabox/lib/require.js:210:4)
    at /usr/local/lib/node_modules/kalabox/lib/require.js:295:14
    at Object.exports.require (/usr/local/lib/node_modules/kalabox/lib/require.js:291:4)
    at /usr/local/lib/node_modules/kalabox/lib/kbox.js:59:28
    at exports.require (/usr/local/lib/node_modules/kalabox/lib/kbox.js:52:21)
    at wrapper (/usr/local/lib/node_modules/kalabox/node_modules/lodash/index.js:3466:19)
    at Object.exports.loadPlugins (/usr/local/lib/node_modules/kalabox/lib/app.js:127:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/kalabox/lib/create.js:332:26)
    at /usr/local/lib/node_modules/kalabox/lib/create.js:331:8
    at processImmediate [as _immediateCallback] (timers.js:358:17)
    at createApp (/usr/local/lib/node_modules/kalabox/lib/create.js:313:6)
    at PromptUI.completed (/usr/local/lib/node_modules/kalabox/lib/create.js:251:18)
    at PromptUI.onCompletion (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/lib/ui/prompt.js:69:10)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:1793:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:1730:14)
    at AnonymousObserver.tryCatcher (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:567:29)
    at AutoDetachObserverPrototype.completed (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:5288:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:1730:14)
    at InnerObserver.onCompleted (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:3425:65)
    at InnerObserver.tryCatcher (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:567:29)
    at AutoDetachObserverPrototype.completed (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:5288:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:1730:14)
    at AutoDetachObserver.tryCatcher (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:567:29)
    at AutoDetachObserverPrototype.completed (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:5288:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:1730:14)
    at InnerObserver.onCompleted (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:3425:65)
    at InnerObserver.tryCatcher (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:567:29)
    at AutoDetachObserverPrototype.completed (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:5288:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:1730:14)
From previous event:
    at /usr/local/lib/node_modules/kalabox/lib/require.js:243:17
From previous event:
    at requireInternal (/usr/local/lib/node_modules/kalabox/lib/require.js:210:4)
    at /usr/local/lib/node_modules/kalabox/lib/require.js:295:14
From previous event:
    at Object.exports.require (/usr/local/lib/node_modules/kalabox/lib/require.js:291:4)
    at /usr/local/lib/node_modules/kalabox/lib/kbox.js:59:28
From previous event:
    at exports.require (/usr/local/lib/node_modules/kalabox/lib/kbox.js:52:21)
    at wrapper (/usr/local/lib/node_modules/kalabox/node_modules/lodash/index.js:3466:19)
From previous event:
    at Object.exports.loadPlugins (/usr/local/lib/node_modules/kalabox/lib/app.js:127:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/kalabox/lib/create.js:332:26)
From previous event:
    at /usr/local/lib/node_modules/kalabox/lib/create.js:331:8
    at processImmediate [as _immediateCallback] (timers.js:358:17)
From previous event:
    at createApp (/usr/local/lib/node_modules/kalabox/lib/create.js:313:6)
    at PromptUI.completed (/usr/local/lib/node_modules/kalabox/lib/create.js:251:18)
    at PromptUI.onCompletion (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/lib/ui/prompt.js:69:10)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:1793:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:1730:14)
    at AnonymousObserver.tryCatcher (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:567:29)
    at AutoDetachObserverPrototype.completed (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:5288:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:1730:14)
    at InnerObserver.onCompleted (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:3425:65)
    at InnerObserver.tryCatcher (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:567:29)
    at AutoDetachObserverPrototype.completed (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:5288:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:1730:14)
    at AutoDetachObserver.tryCatcher (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:567:29)
    at AutoDetachObserverPrototype.completed (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:5288:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:1730:14)
    at InnerObserver.onCompleted (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:3425:65)
    at InnerObserver.tryCatcher (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:567:29)
    at AutoDetachObserverPrototype.completed (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:5288:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:1730:14)
$ 
```

**Comment by labboy0276** [comment]
@thiago try a npm update kalabox -g then try again

**Comment by madeofpeople** [comment]
nodice

**Comment by madeofpeople** [comment]
Going into the app's folder, doing 
```
kbox stop
kbox uninstall
kbox install
```

seems to fix it, thanks @labboy0276

**Comment by labboy0276** [comment]
we win

**Comment by pirog** [comment]
@madeofpeople when you installed kalabox did you do the git install or the npm install? If you did the git install you need to make sure you've checked out the latest 0.9.x tag if you are on the head of master of 0.9.x you could have issues.

**Comment by madeofpeople** [comment]
NPM!

**Comment by pirog** [comment]
ok. that is helpful! thanks!

**Comment by pirog** [comment]
Pretty sure this is resolved in the 0.10.0, which you should def uninstall and upgrade to!

reopen if i am wrong.

**Comment by madeofpeople** [comment]
I moved to 0.10.0 dev master last week (much improvement).

**Comment by pirog** [comment]
glad to here it! def very excited to be in bug fix land now. 

i would def recommend you uninstall the dev 0.10 and reinstall with the official release. you will also want to make sure you turn off devMode!

of course if you want to cowboy it feel free to continue to roll with the developer install ... just know that its definitely the WILD WEST.
