### ISSUE TITLE
Unhandled rejection TypeError when pulling site from Pantheon

### ISSUE THREAD

**Issue by ehausen** [kalabox/kalabox#441]
When creating my first kalabox container from Pantheon according to docs, I get with red:

Below the red text and screenshots of the whole process. Personal details omitted.
```
Unhandled rejection TypeError: Cannot read property 'filemount' of undefined
    at getInstallSpec (/Users/MyUser/Documents/my-site-.com/kalabox-my-site-/my-site-com/plugins/kalabox-plugin-pantheon/lib/env.js:141:48)
    at /Users/MyUser/Documents/my-site-.com/kalabox-my-site-/my-site-com/plugins/kalabox-plugin-pantheon/lib/env.js:188:22
    at /usr/local/lib/node_modules/kalabox/lib/kbox.js:211:16
From previous event:
    at Object.exports.ifApp (/usr/local/lib/node_modules/kalabox/lib/kbox.js:202:21)
    at module.exports (/Users/MyUser/Documents/my-site-.com/kalabox-my-site-/my-site-com/plugins/kalabox-plugin-pantheon/lib/env.js:20:8)
    at module.exports (/Users/MyUser/Documents/my-site-.com/kalabox-my-site-/my-site-com/plugins/kalabox-plugin-pantheon/index.js:8:26)
    at /usr/local/lib/node_modules/kalabox/lib/require.js:240:20
From previous event:
    at /usr/local/lib/node_modules/kalabox/lib/require.js:239:29
From previous event:
    at requireInternal (/usr/local/lib/node_modules/kalabox/lib/require.js:210:4)
    at /usr/local/lib/node_modules/kalabox/lib/require.js:295:14
From previous event:
    at Object.exports.require (/usr/local/lib/node_modules/kalabox/lib/require.js:291:4)
    at /usr/local/lib/node_modules/kalabox/lib/kbox.js:64:28
From previous event:
    at exports.require (/usr/local/lib/node_modules/kalabox/lib/kbox.js:57:21)
    at wrapper (/usr/local/lib/node_modules/kalabox/node_modules/lodash/index.js:3466:19)
From previous event:
    at Object.exports.loadPlugins (/usr/local/lib/node_modules/kalabox/lib/app.js:127:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/kalabox/lib/create.js:332:26)
From previous event:
    at /usr/local/lib/node_modules/kalabox/lib/create.js:331:8
    at processImmediate [as _immediateCallback] (timers.js:367:17)
From previous event:
    at createApp (/usr/local/lib/node_modules/kalabox/lib/create.js:313:6)
    at PromptUI.completed (/usr/local/lib/node_modules/kalabox/lib/create.js:251:18)
    at PromptUI.onCompletion (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/lib/ui/prompt.js:69:10)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:1793:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:1730:14)
    at AnonymousObserver.tryCatcher (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:567:29)
    at AutoDetachObserverPrototype.completed (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:5288:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:1730:14)
    at InnerObserver.onCompleted (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:3425:65)
    at InnerObserver.tryCatcher (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:567:29)
    at AutoDetachObserverPrototype.completed (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:5288:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:1730:14)
    at AutoDetachObserver.tryCatcher (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:567:29)
    at AutoDetachObserverPrototype.completed (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:5288:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:1730:14)
    at InnerObserver.onCompleted (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:3425:65)
    at InnerObserver.tryCatcher (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:567:29)
    at AutoDetachObserverPrototype.completed (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:5288:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:1730:14)
    at AutoDetachObserver.tryCatcher (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:567:29)
    at AutoDetachObserverPrototype.completed (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:5288:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:1730:14)
    at /usr/local/lib/node_modules/kalabox/node_modules/inquirer/lib/utils/utils.js:53:13
    at /usr/local/lib/node_modules/kalabox/node_modules/lodash/index.js:7173:25
    at /usr/local/lib/node_modules/kalabox/node_modules/inquirer/lib/ui/prompt.js:98:7
    at Object.utils.runAsync (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/lib/utils/utils.js:37:5)
    at Prompt.filter (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/lib/prompts/base.js:184:9)
    at Prompt.done (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/lib/prompts/base.js:72:10)
    at Prompt.<anonymous> (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/lib/prompts/input.js:90:10)
    at Object.utils.runAsync (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/lib/utils/utils.js:37:5)
    at Prompt.filter (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/lib/prompts/base.js:184:9)
```
Screenshots of the whole thing:
<img width="883" alt="screen shot 2015-09-04 at 12 17 00" src="https://cloud.githubusercontent.com/assets/6204129/9680378/21ad4e9a-52ff-11e5-8426-a257c59dd60f.png">
<img width="1126" alt="screen shot 2015-09-04 at 12 17 17" src="https://cloud.githubusercontent.com/assets/6204129/9680385/2bf889d2-52ff-11e5-9f66-175f4b02134d.png">

Continuing normally

**Comment by ehausen** [comment]
Same thing happens with **kbox start**

```
MyUsers-MBP:my-site MyUser$ kbox start
Unhandled rejection TypeError: Cannot read property 'filemount' of undefined
    at getInstallSpec (/Users/MyUser/Documents/my-site.com/kalabox-my-site/my-site/plugins/kalabox-plugin-pantheon/lib/env.js:141:48)
    at /Users/MyUser/Documents/my-site.com/kalabox-my-site/my-site/plugins/kalabox-plugin-pantheon/lib/env.js:188:22
    at /usr/local/lib/node_modules/kalabox/lib/kbox.js:211:16
From previous event:
    at Object.exports.ifApp (/usr/local/lib/node_modules/kalabox/lib/kbox.js:202:21)
    at module.exports (/Users/MyUser/Documents/my-site.com/kalabox-my-site/my-site/plugins/kalabox-plugin-pantheon/lib/env.js:20:8)
    at module.exports (/Users/MyUser/Documents/my-site.com/kalabox-my-site/my-site/plugins/kalabox-plugin-pantheon/index.js:8:26)
    at /usr/local/lib/node_modules/kalabox/lib/require.js:240:20
From previous event:
    at /usr/local/lib/node_modules/kalabox/lib/require.js:239:29
From previous event:
    at requireInternal (/usr/local/lib/node_modules/kalabox/lib/require.js:210:4)
    at /usr/local/lib/node_modules/kalabox/lib/require.js:295:14
From previous event:
    at Object.exports.require (/usr/local/lib/node_modules/kalabox/lib/require.js:291:4)
    at /usr/local/lib/node_modules/kalabox/lib/kbox.js:64:28
From previous event:
    at exports.require (/usr/local/lib/node_modules/kalabox/lib/kbox.js:57:21)
    at wrapper (/usr/local/lib/node_modules/kalabox/node_modules/lodash/index.js:3466:19)
From previous event:
    at Object.exports.loadPlugins (/usr/local/lib/node_modules/kalabox/lib/app.js:127:18)
    at /usr/local/lib/node_modules/kalabox/lib/kbox.js:264:16
From previous event:
    at Object.exports.setAppContext (/usr/local/lib/node_modules/kalabox/lib/kbox.js:263:4)
    at /usr/local/lib/node_modules/kalabox/bin/kbox.js:209:21
From previous event:
    at Object.<anonymous> (/usr/local/lib/node_modules/kalabox/bin/kbox.js:207:6)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
From previous event:
    at main (/usr/local/lib/node_modules/kalabox/bin/kbox.js:199:4)
    at Object.<anonymous> (/usr/local/lib/node_modules/kalabox/bin/kbox.js:227:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
info: SERVICES =>  Startup services need to be started.
info: DOCKER =>  Stopping container. 9d508xxxxxxxxxxxxxxx
etc…
…
```

**Comment by ehausen** [comment]
When going to see my local kbox site:

<img width="943" alt="screen shot 2015-09-04 at 12 57 59" src="https://cloud.githubusercontent.com/assets/6204129/9681165/a45751ce-5304-11e5-8909-cc78de07b5ab.png">

**Comment by pirog** [comment]
Does everything else seem to work ok?

**Comment by ehausen** [comment]
What do you mean?

Same type of error seems to be spit out about every time I run some kbox command. I have not tried creating other apps or containers.

**Comment by ehausen** [comment]
PS. I got EACCESS errors when tried installing kalabox first time, but fixed the correct permissions and the installation seemed to run fine. But there was maybe a week in between.

**Comment by ehausen** [comment]
Investigated further and found the answer:

Connected to another matter Pantheon support stated that:

> This is due to your site not having a framework assigned ...

So the *framework* is missing on Pantheon site --> env.js fails

There should be a check for that all the things exist and then for example a message: "Framework for your Pantheon app does not seem to be assigned. Please contact Pantheon support to get this fixed."

**Comment by pirog** [comment]
Oh! very weird, good to know and easy to fix.

What kind of framework does your site actually have?

On Saturday, September 5, 2015, Erik Hausen <notifications@github.com>
wrote:

> Investigated further and found the answer:
>
> Connected to another matter Pantheon support stated that:
>
> This is due to your site not having a framework assigned ...
>
> So the *framework* is missing on Pantheon site --> env.js fails
>
> There should be a check for that all the things exist and then for example
> a message: "Framework for your Pantheon app does not seem to be assigned.
> Please contact Pantheon support to get this fixed."
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/441#issuecomment-137989145>.
>


-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by ehausen** [comment]
Framework: none

...at the moment. This should not be, but apparently can happen somehow (bad import of Drupal site?). Pantheon staff is setting it to 'drupal' soon.

A workaround would be able optionally to set it to 'drupal' or wordpre..something in kalabox.

I guess I can edit env.js and set it to 'drupal' until I get it changed on Pantheon.

**Comment by pirog** [comment]
My bad. I should have asked what framework it's *supposed* to be although i take the answers to be drupal based on your response. 

So we can do two potential things... 

1. Prompt the user to enter their framework manually
2. Have a null set framework adopt some default values 

In either case it seems we should report this to the user so they can ping Pantheon about it.

A workaround in the meantime is to manually add your framework into the app's kalabox.json file. You may need to run `kbox rebuild` to properly reset some of these environmental variables.

```
"kalabox-plugin-pantheon": {
      "action": "pull",
      "account": "mike@kalamuna.com",
      "drush-version": "6",
      "env": "dev",
      "framework": "drupal8",
      "php": "5.3.29",
      "site": "SUMPTIN",
      "upstream": {
        "url": "git://github.com/pantheon-systems/drops-8.git",
        "product_id": "8a129104-9d37-4082-aaf8-e6f31154644e",
        "branch": "master"
      }
    }
```

**Comment by ehausen** [comment]
If..
> 1. Prompt the user to enter their framework manually
Then maybe there should be a list of the usual frameworks as they should be input correctly

**Comment by pirog** [comment]
Looks like the best bet here might be upgrading to the new terminus 0.8.x which seems to resolve this 
https://github.com/pantheon-systems/cli/pull/433

**Comment by pirog** [comment]
Sadly this will not resolve the issue. Manual prompt it is!

**Comment by pirog** [comment]
Also, on a personal note i was expecting to get a bunch of errors after starting a site this big just because of the normal amount of noise these size sites can have. did not have a single issue so huge props to your dev team :)

**Comment by reynoldsalec** [comment]
Received this same error upon starting a "kbox create pantheon", which results in a premature termination of the create process with the following error:

```
EVENTS =>  Error dispatching event listeners [post-create-app].
Error: Non-zero exit code: 1 cp: omitting directory `/ssh/.kalabox/terminus/session/'
[2015-10-07 20:29:59] [error] Please login first with `terminus auth login`

    at /usr/local/bin/node_modules/kalabox-engine-docker/docker.js.jx:566:28
From previous event:
    at Object.result.wait (/usr/local/bin/node_modules/kalabox-engine-docker/docker.js.jx:545:20)
    at /usr/local/bin/node_modules/kalabox-engine-docker/docker.js.jx:636:18
From previous event:
    at Object.queryData (/usr/local/bin/node_modules/kalabox-engine-docker/docker.js.jx:634:6)
From previous event:
    at Object.exports.queryData (/usr/local/bin/lib/engine.js.jx:637:27)
    at /Users/alec/kalabox/apps/cvt-watchdog/plugins/kalabox-plugin-pantheon/lib/terminus.js:121:31
From previous event:
    at Object.dockerInstance.then.bind.then.then.then.catch.finally.self (/usr/local/bin/node_modules/kalabox-engine-docker/docker.js.jx:716:25)
From previous event:
    at Object.use (/usr/local/bin/node_modules/kalabox-engine-docker/docker.js.jx:715:6)
From previous event:
    at /usr/local/bin/lib/engine.js.jx:575:29
From previous event:
    at Object.exports.use (/usr/local/bin/lib/engine.js.jx:574:4)
    at Terminus.__request (/Users/alec/kalabox/apps/cvt-watchdog/plugins/kalabox-plugin-pantheon/lib/terminus.js:120:29)
    at Terminus.getSiteAliases (/Users/alec/kalabox/apps/cvt-watchdog/plugins/kalabox-plugin-pantheon/lib/terminus.js:316:15)
    at /Users/alec/kalabox/apps/cvt-watchdog/plugins/kalabox-plugin-pantheon/lib/tasks.js:267:23
    at /usr/local/bin/lib/core/events.js.jx:147:11
    at /usr/local/bin/lib/core/events.js.jx:146:24
From previous event:
    at /usr/local/bin/lib/core/events.js.jx:130:23
From previous event:
    at EventEngine._dispatch (/usr/local/bin/lib/core/events.js.jx:127:18)
    at /usr/local/bin/lib/core/events.js.jx:107:19
From previous event:
    at EventEngine.emit (/usr/local/bin/lib/core/events.js.jx:99:21)
From previous event:
    at Object.exports.emit (/usr/local/bin/lib/core/events.js.jx:230:4)
    at Promise.try.then.then.then.then.then.then.then.then.sysRoot (/usr/local/bin/lib/create.js.jx:410:26)
    at process._tickCallback (node.js:812:13)
From previous event:
    at createApp (/usr/local/bin/lib/create.js.jx:408:6)
    at PromptUI.completed (/usr/local/bin/lib/create.js.jx:512:18)
    at PromptUI.onCompletion (/usr/local/bin/node_modules/inquirer/lib/ui/prompt.js.jx:68:10)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:1792:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:1729:14)
    at AnonymousObserver.tryCatcher (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:566:29)
    at AutoDetachObserverPrototype.completed (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:5287:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:1729:14)
    at InnerObserver.onCompleted (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:3424:65)
    at InnerObserver.tryCatcher (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:566:29)
    at AutoDetachObserverPrototype.completed (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:5287:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:1729:14)
    at AutoDetachObserver.tryCatcher (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:566:29)
    at AutoDetachObserverPrototype.completed (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:5287:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:1729:14)
    at InnerObserver.onCompleted (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:3424:65)
    at InnerObserver.tryCatcher (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:566:29)
    at AutoDetachObserverPrototype.completed (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:5287:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:1729:14)
    at AutoDetachObserver.tryCatcher (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:566:29)
    at AutoDetachObserverPrototype.completed (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:5287:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:1729:14)
    at /usr/local/bin/node_modules/inquirer/lib/utils/utils.js.jx:52:13
    at /usr/local/bin/node_modules/lodash/index.js.jx:7172:25
    at /usr/local/bin/node_modules/inquirer/lib/ui/prompt.js.jx:97:7
    at Object.utils.runAsync (/usr/local/bin/node_modules/inquirer/lib/utils/utils.js.jx:36:5)
    at Prompt.filter (/usr/local/bin/node_modules/inquirer/lib/prompts/base.js.jx:183:9)
    at Prompt.done (/usr/local/bin/node_modules/inquirer/lib/prompts/base.js.jx:71:10)
    at Prompt.<anonymous> (/usr/local/bin/node_modules/inquirer/lib/prompts/input.js.jx:89:10)
    at Object.utils.runAsync (/usr/local/bin/node_modules/inquirer/lib/utils/utils.js.jx:36:5)
    at Prompt.filter (/usr/local/bin/node_modules/inquirer/lib/prompts/base.js.jx:183:9)
```

It's clear that an error populating framework is creating this; didn't receive the framework prompt.

Received this on multiple "kbox create pantheon" attempts.

**Comment by pirog** [comment]
@reynoldsalec did we ultimately agree this was caused by the framework not being provided for some reason?

i think a potential "fix" for this is something like

```js
   // Only do stuff if our json is in a good spot
   If (validateKalaboxJson()) {
      // Grab framework from kalabox.json
      var framework = app.config.pluginConf[PLUGIN_NAME].framework;

      // Get our environments based on the framework
      var installEnv = getInstallSpec(framework);
   }
   else {
     //????
   }
```

**Comment by reynoldsalec** [comment]
Yes, although the main problem was the call to terminus site connection-mode --json --site=cvt --env=dev returning "Connection mode: git" instead of valid json. That caused the framework issue.

Did we ever resolve what that Terminus funk was about? I thought it was a DockerHub issue delivering old versions... @pirog

**Comment by pirog** [comment]
@reynoldsalec yeah for whatever reason we were just getting the terminus 0.8.0 container instead of the 0.8.1 one which was causing a mismatch with our local "client". I think new creates should work now, as should kbox rebuild on apps failing. I would try this out to verify. Have you taken the 0.10.3 plunge yet?

I think we should def do the thing above regardless. 

Another thing that we could consider doing, which would be a lot more work and hard to maintain would be actually versioning our client code so we are using the correct stuff on our end depending on the version of terminus you are using. I personally dont  think this is a great idea and we already kind of a do a weaker version of this already its just by app version.

**Comment by pirog** [comment]
@reynoldsalec so i've written a validation function for this but we still need to figure out what to do when validation fails. Current options are:

1. Throw an error saying your framework is MESSED; optionally/potentially autodestroying the app
2. Attempt to get the json into the correct state either via terminus or by prompting user
3. something else???

I don't think it will be that hard to implement 2 which seems ideal but might be excessive for where we are now? 1. would be an easy starting point.

**Comment by reynoldsalec** [comment]
Let's try 1. and go from there @pirog, feel like we need to see this impacting more people and evaluate what a better response would be.

**Comment by pirog** [comment]
sweet. i feel like that makes the most the most sense for now as well.

**Comment by reynoldsalec** [comment]
Hey @ehausen, noticed you've been really helpful in reporting issues and wanted to invite you to our testing "Circle of Trust". We'll keep you updated on new Kalabox releases, alert you to potential bugs we're noticing, and may ask for your help testing different solutions. If you're interested, you can signup at http://bit.ly/kbox-trust

Thanks again for reporting on these issues!
