### ISSUE TITLE
Need reliable way to update kalabox from version to version

### ISSUE THREAD

**Issue by pirog** [kalabox/kalabox#447]

**Comment by pi-ron** [comment]
Hi Mike,

I've just updated kalabox to latest then stepped into app and ran `kbox update` which failed with the error:

``````
Error running step: {"name":"core-rebuild","description":"Rebuild?","deps":["core-deps"],"subscribes":[],"isStep":true}: Error while installing app: "parcel-dev": EVENTS =>  Error dispatching event listeners [post-install].
VError: Error while installing app: "parcel-dev": EVENTS =>  Error dispatching event listeners [post-install].
    at /usr/local/lib/node_modules/kalabox/lib/app.js:432:11
From previous event:
    at exports.install (/usr/local/lib/node_modules/kalabox/lib/app.js:431:9)
    at /usr/local/lib/node_modules/kalabox/lib/app.js:718:12
From previous event:
    at Object.exports.rebuild (/usr/local/lib/node_modules/kalabox/lib/app.js:717:4)
    at /usr/local/lib/node_modules/kalabox/plugins/kalabox-core/update.js:43:22
    at process._tickCallback (node.js:419:13)
``````

**Comment by pi-ron** [comment]
I ran kbox start straight after and it ran alright.
