### ISSUE TITLE
kbox destroy - Cannot read property 'stop' of undefined

### ISSUE THREAD

**Issue by labboy0276** [kalabox/kalabox#448]
Hello in my 0.10.x app I tried to destroy it, but it gives me this:

```
john@kalamuna:~/kalabox/apps/huddle$ kbox destroy
rm: cannot remove `/certs': Device or resource busy
info: DOCKER =>  Removing container 4c5bd4c1b1f3d525a42fda9d948eb1cced982ec432b7ab7fb703ce5e19d89eda. v=true, kill=false
info: DOCKER =>  Container removed. 4c5bd4c1b1f3d525a42fda9d948eb1cced982ec432b7ab7fb703ce5e19d89eda
Removing the codez.
info: DOCKER =>  Removing container kb_huddle_appserver. v=true, kill=false
info: DOCKER =>  Stopping container. kb_huddle_appserver
Error removing container kb_huddle_appserver.: Cannot read property 'stop' of undefined
TypeError: Cannot read property 'stop' of undefined
    at Container.stop (/home/john/kb2/node_modules/kalabox-engine-docker/node_modules/dockerode/lib/container.js:312:46)
    at /home/john/kb2/node_modules/kalabox-engine-docker/docker.js:894:26
    at processImmediate [as _immediateCallback] (timers.js:367:17)
john@kalamuna:~/kalabox/apps/huddle$ 
```

**Comment by pirog** [comment]
This happens when you try to destroy an app that is started/running. 

We should check for this and stop the app first.

**Comment by labboy0276** [comment]
Still not happy:

```
john@kalamuna:~/kalabox/apps/huddle$ kbox stop
info: SERVICES =>  Startup services need to be started.
info: DOCKER =>  Stopping container. 98fba8c3f18863bbc2f5833a8ac58729d94767c61ee953d31820c1d1da13ef98
info: DOCKER =>  Container stopped. 98fba8c3f18863bbc2f5833a8ac58729d94767c61ee953d31820c1d1da13ef98
info: DOCKER =>  Stopping container. 1b7e39ed194c51379529cae7bbd096d6b68c4459032edde1d77c580fea6d488d
info: DOCKER =>  Container already stopped. 1b7e39ed194c51379529cae7bbd096d6b68c4459032edde1d77c580fea6d488d
info: DOCKER =>  Stopping container. a791ba8d159a943b3f3499120827fd07d64a354d8c422d95375d467b9038c060
info: DOCKER =>  Container stopped. a791ba8d159a943b3f3499120827fd07d64a354d8c422d95375d467b9038c060
info: DOCKER =>  Stopping container. 75dfad8a7f372548801e8a8293f17d5069b821ef8f9734e73b51ca457b0fb55a
info: DOCKER =>  Container stopped. 75dfad8a7f372548801e8a8293f17d5069b821ef8f9734e73b51ca457b0fb55a
info: DOCKER =>  Stopping container. 0b162851df31220559d4e41cbf3fe08e4ed3bcda25ab2c4206be36b58b721f5d
info: DOCKER =>  Container stopped. 0b162851df31220559d4e41cbf3fe08e4ed3bcda25ab2c4206be36b58b721f5d
info: DOCKER =>  Starting container 98fba8c3f18863bbc2f5833a8ac58729d94767c61ee953d31820c1d1da13ef98.
info: DOCKER =>  Container started. 98fba8c3f18863bbc2f5833a8ac58729d94767c61ee953d31820c1d1da13ef98
info: DOCKER =>  Starting container 1b7e39ed194c51379529cae7bbd096d6b68c4459032edde1d77c580fea6d488d.
info: DOCKER =>  Container started. 1b7e39ed194c51379529cae7bbd096d6b68c4459032edde1d77c580fea6d488d
info: DOCKER =>  Starting container a791ba8d159a943b3f3499120827fd07d64a354d8c422d95375d467b9038c060.
info: DOCKER =>  Container started. a791ba8d159a943b3f3499120827fd07d64a354d8c422d95375d467b9038c060
info: DOCKER =>  Starting container 75dfad8a7f372548801e8a8293f17d5069b821ef8f9734e73b51ca457b0fb55a.
info: DOCKER =>  Container started. 75dfad8a7f372548801e8a8293f17d5069b821ef8f9734e73b51ca457b0fb55a
info: DOCKER =>  Starting container 0b162851df31220559d4e41cbf3fe08e4ed3bcda25ab2c4206be36b58b721f5d.
info: DOCKER =>  Container started. 0b162851df31220559d4e41cbf3fe08e4ed3bcda25ab2c4206be36b58b721f5d
info: DOCKER =>  Stopping container. 2decfc86fd7e7de0a8d6d3380d6baf8b00c6859f91b504788ff2d3755daff5b2
info: DOCKER =>  Container stopped. 2decfc86fd7e7de0a8d6d3380d6baf8b00c6859f91b504788ff2d3755daff5b2
info: DOCKER =>  Stopping container. 5e7b3b79252315a5890b4ae83b9a9f5060a3c00b16c36cd6ef9d447e4bd66a19
info: DOCKER =>  Container stopped. 5e7b3b79252315a5890b4ae83b9a9f5060a3c00b16c36cd6ef9d447e4bd66a19
info: DOCKER =>  Stopping container. bbe15dfd4b2a622b4757f117c741b9b7001cf1343eea51837ec23ee5b7ebb579
info: DOCKER =>  Container stopped. bbe15dfd4b2a622b4757f117c741b9b7001cf1343eea51837ec23ee5b7ebb579
info: DOCKER =>  Stopping container. 94fded04847199d78dccab0f481aa04914918158a39e51cf470f1ceb90e49d2c
info: DOCKER =>  Container stopped. 94fded04847199d78dccab0f481aa04914918158a39e51cf470f1ceb90e49d2c
info: BOOT2DOCKER =>  Shutting down [1].
info: BOOT2DOCKER =>  Shutting down [2].
info: BOOT2DOCKER =>  Shutting down [3].
info: BOOT2DOCKER =>  Shut down successful.
Kalabox engine has been deactivated.
john@kalamuna:~/kalabox/apps/huddle$ kbox destroy
EVENTS =>  Error dispatching event listeners [pre-uninstall].
Error: code: 1, msg: error in run: VM "Kalabox2" is not running. (Did you run `boot2docker up`?)

    at /home/john/kb2/lib/util/shell.js:100:13
    at /home/john/kb2/node_modules/shelljs/src/exec.js:107:7
    at ChildProcess.exithandler (child_process.js:758:5)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Socket.<anonymous> (child_process.js:1183:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:485:12)
john@kalamuna:~/kalabox/apps/huddle$ 
```

Not sure what to do as I have tried this both when the app is started and stopped.  Problem is that with the new workflow, Kalabox2 VB is not up and it says no.

**Comment by pirog** [comment]
The issue here is that `kbox stop` now auto shuts down the engine if there are no more apps running. We should change this so it only happens you run `kbox stop` aka not on all `post-app-stop` events. 

For uninstall we also want to stop the app if its running first.

**Comment by pirog** [comment]
@labboy0276 this should be in master now. you are going to want to `git pull` and then `npm install` in your kalabox source root to get the latest pantheon app changes (which means that pre-existing pantheon apps may break).

If you want to update pre-existing apps this is the change that was made:
https://github.com/kalabox/kalabox-app-pantheon/commit/e85955e027500f3b69c867568c01bb1e39d2aa2d
