### ISSUE TITLE
Kbox restart operation timed out

### ISSUE THREAD

**Issue by labboy0276** [kalabox/kalabox#450]
On 0.10.x Master, I am seeing this on kbox restart:

Looks similar to the old kbox down issue and not shutting down properly, #343 

```
...
info: DOCKER =>  Container stopped. f2dd54e14886ba1d57eba4886d32eec5a76757b34c729f21733241fb9fd87358
info: BOOT2DOCKER =>  Shutting down [1].
info: BOOT2DOCKER =>  Shutting down [2].
info: BOOT2DOCKER =>  Shut down successful.
Kalabox engine has been deactivated.
Error querying isRunning: "'98fba8c3f18863bbc2f5833a8ac58729d94767c61ee953d31820c1d1da13ef98'".: Error inspecting container.: Error querying docker for list of containers.: operation timed out
VError: Error inspecting container.: Error querying docker for list of containers.: operation timed out
    at /home/john/kb2/node_modules/kalabox-engine-docker/docker.js:278:13
From previous event:
    at inspect (/home/john/kb2/node_modules/kalabox-engine-docker/docker.js:277:11)
    at /home/john/kb2/node_modules/kalabox-engine-docker/docker.js:294:14
From previous event:
    at Object.isRunning (/home/john/kb2/node_modules/kalabox-engine-docker/docker.js:293:6)
From previous event:
    at /home/john/kb2/lib/engine.js:345:29
...
```

**Comment by pirog** [comment]
So it definitely shuts down fine 

```
info: BOOT2DOCKER =>  Shutting down [1].
info: BOOT2DOCKER =>  Shutting down [2].
info: BOOT2DOCKER =>  Shut down successful.
~Kalabox engine has been deactivated.~
```

**Comment by labboy0276** [comment]
This doesn't happen everytime as a FYI, it is hit or miss.

Next time it happens, i will let you know on the containers and post logs and thingz

**Comment by pirog** [comment]
The IDs dont change so the offending container should still be in there. Don't need to wait for it to happen again.

**Comment by labboy0276** [comment]
```
98fba8c3f188        kalabox/skydns:v0.10.0               "/skydns -http 0.0.0."   15 hours ago        Up 2 hours                  172.17.42.1:53->53/udp, 8080/tcp                                                                  kalabox_skydns
```

**Comment by pirog** [comment]
Related to #415?

**Comment by labboy0276** [comment]
yes seems so now that i know it is that container

**Comment by pirog** [comment]
So for this issue (and likely others) i think we should only auto-down the engine on an actual `stop` command and not on ~all~ post stop events.

**Comment by pirog** [comment]
I can replicate this successfully. I'm guessing when it doesnt happen its because you have another app running. @labboy0276 Do you think that sounds about right?

**Comment by pirog** [comment]
@labboy0276 this should be in master now if you want to give it a try and confirm it works. Should only need to `git pull` the core kalabox repo to get the update.
