### ISSUE TITLE
`kbox rebuild` fails on latest master

### ISSUE THREAD

**Issue by pirog** [kalabox/kalabox#463]
```
EVENTS =>  Error dispatching event listeners [post-uninstall].
Error: No mapping found for app: seven
    at /Users/mpirog/Desktop/work/kalabox/lib/share.js:106:15
    at getRescanInterval (/Users/mpirog/Desktop/work/kalabox/lib/share.js:542:35)
    at /Users/mpirog/Desktop/work/kalabox/lib/share.js:556:34
    at arrayEach (/Users/mpirog/Desktop/work/kalabox/node_modules/lodash/index.js:1342:13)
    at Function.<anonymous> (/Users/mpirog/Desktop/work/kalabox/node_modules/lodash/index.js:3299:13)
    at /Users/mpirog/Desktop/work/kalabox/lib/share.js:555:9
    at Object.<anonymous> (/Users/mpirog/Desktop/work/kalabox/lib/share.js:538:6)
    at Object.exports.restart (/Users/mpirog/Desktop/work/kalabox/lib/share.js:532:4)
    at /Users/mpirog/Desktop/work/kalabox/plugins/kalabox-syncthing/events.js:139:15
    at /Users/mpirog/Desktop/work/kalabox/lib/core/events.js:147:11
    at /Users/mpirog/Desktop/work/kalabox/lib/core/events.js:146:24
    at /Users/mpirog/Desktop/work/kalabox/lib/core/events.js:130:23
    at EventEngine._dispatch (/Users/mpirog/Desktop/work/kalabox/lib/core/events.js:127:18)
    at /Users/mpirog/Desktop/work/kalabox/lib/core/events.js:107:19
    at EventEngine.emit (/Users/mpirog/Desktop/work/kalabox/lib/core/events.js:99:21)
    at Object.exports.emit (/Users/mpirog/Desktop/work/kalabox/lib/core/events.js:230:4)
    at /Users/mpirog/Desktop/work/kalabox/lib/app.js:683:24
    at exports.uninstall (/Users/mpirog/Desktop/work/kalabox/lib/app.js:682:4)
    at /Users/mpirog/Desktop/work/kalabox/lib/app.js:715:12
    at Object.exports.rebuild (/Users/mpirog/Desktop/work/kalabox/lib/app.js:714:4)
    at Object.task.func (/Users/mpirog/Desktop/work/kalabox/plugins/kalabox-core/tasks/rebuild.js:20:18)
    at Object.exports.run (/Users/mpirog/Desktop/work/kalabox/lib/core/tasks.js:857:15)
    at processTask (/Users/mpirog/Desktop/work/kalabox/bin/kbox.js:162:16)
    at Object.<anonymous> (/Users/mpirog/Desktop/work/kalabox/bin/kbox.js:211:12)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
    at main (/Users/mpirog/Desktop/work/kalabox/bin/kbox.js:210:4)
    at Object.<anonymous> (/Users/mpirog/Desktop/work/kalabox/bin/kbox.js:219:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by pirog** [comment]
As a follow up here. If you try to do a rebuild here it prevents you from creating, starting, stopping, etc other apps as well.

**Comment by pi-ron** [comment]
Think I may have hit this wall...  I'm seeing a few errors now and can't do much at all.  Everything was cruising along OK yesterday.

Trying to resolve, I just did a restart then `kbox up`

``````
$ kbox status
up
$ kbox apps
Error querying docker for list of containers.: connect ECONNREFUSED
Error: connect ECONNREFUSED
    at errnoException (net.js:904:11)
    at Object.afterConnect [as oncomplete] (net.js:895:19)
``````

**Comment by pi-ron** [comment]
`cd app-dir`

``````
$ kbox start
Error querying isRunning: "'ca5b903600586b81157c572197ee5e51c8ffa73029a78e4de1d0ab8d6db72261'".: Error inspecting container.: Error querying docker for list of containers.: connect ECONNREFUSED
VError: Error inspecting container.: Error querying docker for list of containers.: connect ECONNREFUSED
    at /usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/docker.js:278:13
From previous event:
    at inspect (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/docker.js:277:11)
    at /usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/docker.js:294:14
From previous event:
    at Object.isRunning (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/docker.js:293:6)
From previous event:
    at /usr/local/lib/node_modules/kalabox/lib/engine.js:336:29
From previous event:
    at Object.exports.isRunning.exports.isContainerRunning (/usr/local/lib/node_modules/kalabox/lib/engine.js:335:4)
    at /usr/local/lib/node_modules/kalabox/node_modules/kalabox-services-kalabox/kalabox.js:68:26
From previous event:
    at isServiceRunning (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-services-kalabox/kalabox.js:67:6)
    at serviceInfo.then.filter.concurrency (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-services-kalabox/kalabox.js:266:14)
From previous event:
    at Object.verify (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-services-kalabox/kalabox.js:265:6)
From previous event:
    at Object.exports.verify (/usr/local/lib/node_modules/kalabox/lib/services.js:89:29)
    at Object.exports.start (/usr/local/lib/node_modules/kalabox/lib/app.js:493:19)
    at Object.task.func (/usr/local/lib/node_modules/kalabox/plugins/kalabox-core/tasks/start.js:14:18)
    at Object.exports.run (/usr/local/lib/node_modules/kalabox/lib/core/tasks.js:834:15)
    at processTask (/usr/local/lib/node_modules/kalabox/bin/kbox.js:170:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/kalabox/bin/kbox.js:219:12)
    at process._tickCallback (node.js:419:13)
From previous event:
    at main (/usr/local/lib/node_modules/kalabox/bin/kbox.js:218:4)
    at Object.<anonymous> (/usr/local/lib/node_modules/kalabox/bin/kbox.js:227:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
``````

**Comment by pi-ron** [comment]
Tried to reinstall...

``````
Kalabox engine has been activated.
info: -- OK! 74% complete! --

info: -- Step 15/19 --
info: Preparing apps for updates...
Error running step: {"name":"core-apps-prepare","description":"Preparing apps for updates...","deps":["engine-up"],"subscribes":[],"isStep":true}: Error querying docker for list of containers.: connect ECONNREFUSED
VError: Error querying docker for list of containers.: connect ECONNREFUSED
    at /usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/docker.js:171:13
    at process._tickCallback (node.js:419:13)
``````

**Comment by pi-ron** [comment]
@bcauldwell 

Tried to `npm install kalabox -g` & then `kbox provision` but get the following error in the installer:

``````
Kalabox engine has been activated.
info: -- OK! 74% complete! --

info: -- Step 15/19 --
info: Preparing apps for updates...
Error running step: {"name":"core-apps-prepare","description":"Preparing apps for updates...","deps":["engine-up"],"subscribes":[],"isStep":true}: Error querying docker for list of containers.: connect ECONNREFUSED
VError: Error querying docker for list of containers.: connect ECONNREFUSED
    at /usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/docker.js:171:13
    at process._tickCallback (node.js:419:13)
``````

**Comment by pi-ron** [comment]
Ok, I've uninstalled.  Starting again.

**Comment by bcauldwell** [comment]
That's what I was just about to ask you to do. Also can you confirm the
version of kalabox you are using and your OS?

On Mon, Sep 14, 2015 at 6:08 PM, pi-ron <notifications@github.com> wrote:

> Ok, I've uninstalled. Starting again.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/463#issuecomment-140244992>.
>



-- 
- Benjamin Cauldwell

**Comment by pirog** [comment]
@pi-ron if you are using OSX i might have a nice super fresh kbox BINARY for you to try out in a few minutes.

**Comment by pi-ron** [comment]
Yosimite /0.9.18
On Tue, 15 Sep 2015 at 11:21 am Mike Pirog <notifications@github.com> wrote:

> @pi-ron <https://github.com/pi-ron> if you are using OSX i might have a
> nice super fresh kbox BINARY for you to try out in a few minutes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/463#issuecomment-140246868>.
>
-- 

Cheers,

Tim Daff
*Director*

nextentity
*websites & design *

MOBILE0437 988 399EMAILtim@nextentity.com.au
<https://mail.google.com/mail/ca/u/0/tim@nextentity.com.au>POST5 Anderson
Street
Newhaven, VIC 3925

STATEMENT OF CONFIDENTIALITY: The information contained in this e-mail
(including any attachments) contains information that may be confidential
or may constitute non-public information and may be legally privileged and
confidential. It is intended only for the use of the individual(s) or
entity named above. If the reader of this message is not the intended
recipient, you are hereby notified that any dissemination, distribution or
copy of this e-mail is strictly prohibited and may be unlawful. If you have
received this email in error, please immediately notify the sender and
destroy all hard copies and any copies that may be on your computer. Thank
you.

**Comment by pi-ron** [comment]
Sounds good!
On Tue, 15 Sep 2015 at 11:34 am Tim Daff <tim@nextentity.com.au> wrote:

> Yosimite /0.9.18
> On Tue, 15 Sep 2015 at 11:21 am Mike Pirog <notifications@github.com>
> wrote:
>
>> @pi-ron <https://github.com/pi-ron> if you are using OSX i might have a
>> nice super fresh kbox BINARY for you to try out in a few minutes.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/kalabox/kalabox/issues/463#issuecomment-140246868>.
>>
> --
>
> Cheers,
>
> Tim Daff
> *Director*
>
> nextentity
> *websites & design *
>
> MOBILE0437 988 399EMAILtim@nextentity.com.au
> <https://mail.google.com/mail/ca/u/0/tim@nextentity.com.au>POST5 Anderson
> Street
> Newhaven, VIC 3925
>
> STATEMENT OF CONFIDENTIALITY: The information contained in this e-mail
> (including any attachments) contains information that may be confidential
> or may constitute non-public information and may be legally privileged and
> confidential. It is intended only for the use of the individual(s) or
> entity named above. If the reader of this message is not the intended
> recipient, you are hereby notified that any dissemination, distribution or
> copy of this e-mail is strictly prohibited and may be unlawful. If you have
> received this email in error, please immediately notify the sender and
> destroy all hard copies and any copies that may be on your computer. Thank
> you.
>
>
> --

Cheers,

Tim Daff
*Director*

nextentity
*websites & design *

MOBILE0437 988 399EMAILtim@nextentity.com.au
<https://mail.google.com/mail/ca/u/0/tim@nextentity.com.au>POST5 Anderson
Street
Newhaven, VIC 3925

STATEMENT OF CONFIDENTIALITY: The information contained in this e-mail
(including any attachments) contains information that may be confidential
or may constitute non-public information and may be legally privileged and
confidential. It is intended only for the use of the individual(s) or
entity named above. If the reader of this message is not the intended
recipient, you are hereby notified that any dissemination, distribution or
copy of this e-mail is strictly prohibited and may be unlawful. If you have
received this email in error, please immediately notify the sender and
destroy all hard copies and any copies that may be on your computer. Thank
you.

**Comment by pi-ron** [comment]
All good, things are working again :-)

@pirog How's the binary going?  Exciting times

**Comment by pirog** [comment]
Doing the testing right now!!!

On Mon, Sep 14, 2015 at 7:01 PM, pi-ron <notifications@github.com> wrote:

> All good, things are working again :-)
>
> @pirog <https://github.com/pirog> How's the binary going? Exciting times
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/463#issuecomment-140252977>.
>



-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
