### ISSUE TITLE
Make changes to allow binarization

### ISSUE THREAD

**Issue by pirog** [kalabox/kalabox#464]
So there may be ways to do this and it could be helpful for distribution with the GUI.

**Comment by pirog** [comment]
So you can get this to work if you use `jx`.

You also need to add the following to the top of `bin/kbox.js`

```js
// Partition and parse argv.
if (process.isPackaged || process.IsEmbedded) {
  process.argv.unshift(process.argv[0]);
}
```

```
git clone https://github.com/kalabox/kalabox.git
npm install kalabox --production
jx package bin/kbox.js kbox -native
```

Will end up with e binary called kbox. @reynoldsalec @bcauldwell i'll post the generated binary somewhere. 

[kbox2 | uploaded via ZenHub](https://files.zenhub.io/55f4ab421bbec8046cfd1409)

**Comment by pirog** [comment]
So this seems to fail during `kbox create` when it needs to copy over the app skeleton which makes sense since its trying to make a copy of files that are now compiled inside itself?

**Comment by pirog** [comment]
So you can workaround this just to see what works by doing this whole thing

Add this to the top of `bin/kbox.js`

```js
// Partition and parse argv.
if (process.isPackaged || process.IsEmbedded) {
  process.argv.unshift(process.argv[0]);
}
```

Then build the binary and do the workaround

```
git clone https://github.com/kalabox/kalabox.git
npm install kalabox --production
jx package bin/kbox.js kbox2 -native
mv kbox2 /usr/local/bin/kbox2
cd /usr/local/bin
npm install kalabox-app-pantheon
npm install npm
cd /path/to/my/apps
kbox2 create pantheon
cd myapp
kbox start
```

So far this seems to work

**Comment by pirog** [comment]
So the biggest things we would need to address for the binary to work

- [ ] Change how we copy the app skeleton (pull from internet?)
- [ ] How do we use npm to install the above?

**Comment by pirog** [comment]
[DANGEROUS! Prelim OSX binary](https://files.zenhub.io/55f775cfeadedb3c47414622)

**Comment by pirog** [comment]
[RISKY BIZNIZ](https://files.zenhub.io/55f7857eeadedb3c47414677)

**Comment by pirog** [comment]
[kbox | uploaded via ZenHub](https://files.zenhub.io/55f7a70beadedb3c4741471a)

**Comment by pirog** [comment]
[kbox 222222| uploaded via ZenHub](https://files.zenhub.io/55f7a913eadedb3c47414720)

**Comment by pirog** [comment]
info: DOCKER =>  Starting ad hoc container "fc21598c0a362e18589d61ac7a92c08ba83b2aae342600a1719711366a5c97dd". Binds=[/Users/mpirog/Desktop/apps/florida:/src:rw]
info: DOCKER =>  Ad hoc container started. fc21598c0a362e18589d61ac7a92c08ba83b2aae342600a1719711366a5c97dd

**Comment by pirog** [comment]
[kbox | uploaded via ZenHub](https://files.zenhub.io/55f7acb2eadedb3c47414731)

**Comment by pirog** [comment]
ITS HAPPENING HERE
CREATIN CODE DIR
WRITING STIGNROER
ACTUALLY LOADING CONTAINER
THIGSGIWJRGLIWEHGILH
debug: EVENTS =>  Emitting event [pre-engine-create].
debug: EVENTS =>  Start dispatching event listeners [pre-engine-create].
debug: EVENTS =>  Finished dispatching event listeners [pre-engine-create].
info: DOCKER =>  Creating ad hoc container "kalabox/debian:stable". name=kalabox_temp-93b70b6d-19f2-410e-9c04-76274e74ab1f, Cmd=[bash], Tty=true, Image=kalabox/debian:stable, Env=[KBOX_CODEDIR=code, KALABOX=true, APPNAME=jx, APPDOMAIN=jx.kbox, SSH_KEY=pantheon.kalabox.id_rsa, GITUSER=Mike Pirog, GITEMAIL=mike.pirog@gmail.com, PANTHEON_ACCOUNT=mike.pirog@gmail.com]
info: DOCKER =>  Ad hoc container created. efb1d1968b4d2bb922a9584d47c947248a79b5153cac435ecabb8e408bb09d4e
info: DOCKER =>  Starting ad hoc container "efb1d1968b4d2bb922a9584d47c947248a79b5153cac435ecabb8e408bb09d4e".
info: DOCKER =>  Ad hoc container started. efb1d1968b4d2bb922a9584d47c947248a79b5153cac435ecabb8e408bb09d4e
WE USIN
kalabox/debian:stable
{ Env: [ 'APPDOMAIN=jx.kbox' ],
  HostConfig: { VolumesFrom: [ 'kb_jx_data' ] } }
{ Binds: [ '/Users/pirog/Desktop/apps/jx:/src:rw' ] }
debug: DOCKER =>  Creating exec. AttachStdin=false, AttachStdout=true, AttachStderr=true, Tty=false, Cmd=[cp, /src/code/.stignore, /code/.stignore], stream=true
debug: DOCKER =>  Starting exec. Detach=false, stdin=false, stdout=true, stderr=true
info: DOCKER =>  Removing ad hoc container. efb1d1968b4d2bb922a9584d47c947248a79b5153cac435ecabb8e408bb09d4e
debug: EVENTS =>  Error dispatching event listeners [pre-start]. VError: Error running ad hoc container with kalabox/debian:stable.: Non-zero exit code: 1 cp: cannot stat `/src/code/.stignore': No such file or directory

    at Object.dockerInstance.then.bind.then.then.then.catch.finally.self (/usr/local/bin/node_modules/kalabox-engine-docker/docker.js.jx:720:13)
From previous event:
    at Object.use (/usr/local/bin/node_modules/kalabox-engine-docker/docker.js.jx:719:11)
From previous event:
    at /usr/local/bin/lib/engine.js.jx:575:29
From previous event:
    at Object.exports.use (/usr/local/bin/lib/engine.js.jx:574:4)
    at /usr/local/bin/plugins/kalabox-syncthing/events.js.jx:124:25
From previous event:
    at /usr/local/bin/plugins/kalabox-syncthing/events.js.jx:99:10
    at /usr/local/bin/lib/core/events.js.jx:147:11
    at /usr/local/bin/lib/core/events.js.jx:146:24
From previous event:
    at /usr/local/bin/lib/core/events.js.jx:130:23
From previous event:
    at EventEngine._dispatch (/usr/local/bin/lib/core/events.js.jx:127:18)
    at /usr/local/bin/lib/core/events.js.jx:107:19
From previous event:
    at EventEngine.emit (/usr/local/bin/lib/core/events.js.jx:99:21)
From previous event:
    at Object.exports.emit (/usr/local/bin/lib/core/events.js.jx:230:4)
    at services.verify.then.then.then.map.concurrency (/usr/local/bin/lib/app.js.jx:500:24)
From previous event:
    at exports.start (/usr/local/bin/lib/app.js.jx:499:4)
    at /usr/local/bin/lib/app.js.jx:612:12
From previous event:
    at Object.exports.restart (/usr/local/bin/lib/app.js.jx:611:4)
    at Object.task.func (/usr/local/bin/plugins/kalabox-core/tasks/restart.js.jx:15:18)
    at Object.exports.run (/usr/local/bin/lib/core/tasks.js.jx:857:15)
    at processTask (/usr/local/bin/bin/kbox.js.jx:166:16)
    at Object.<anonymous> (/usr/local/bin/bin/kbox.js.jx:215:12)
    at process._tickCallback (node.js:812:13)
From previous event:
    at main (/usr/local/bin/bin/kbox.js.jx:214:4)
    at Object.<anonymous> (/usr/local/bin/bin/kbox.js.jx:223:1)
    at Module._compile (module.js:518:26)
    at readX (module.js:1284:5)
    at Object.Module._extensions..jx (module.js:1711:10)
    at Module.load (module.js:345:36)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:377:17)
    at require (module.js:395:17)
    at Object.<anonymous> (_jx_source:17:3)
    at Module._compile (module.js:518:26)
    at Module.load (module.js:353:12)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:733:12)
    at startup (node.js:371:18)
    at node.js:1464:3
EVENTS =>  Error dispatching event listeners [pre-start].
Error: Non-zero exit code: 1 cp: cannot stat `/src/code/.stignore': No such file or directory

    at /usr/local/bin/node_modules/kalabox-engine-docker/docker.js.jx:566:28
From previous event:
    at Object.result.wait (/usr/local/bin/node_modules/kalabox-engine-docker/docker.js.jx:545:20)
    at /usr/local/bin/node_modules/kalabox-engine-docker/docker.js.jx:636:18
From previous event:
    at Object.queryData (/usr/local/bin/node_modules/kalabox-engine-docker/docker.js.jx:634:6)
From previous event:
    at Object.exports.queryData (/usr/local/bin/lib/engine.js.jx:637:27)
    at /usr/local/bin/plugins/kalabox-syncthing/events.js.jx:129:27
From previous event:
    at Object.dockerInstance.then.bind.then.then.then.catch.finally.self (/usr/local/bin/node_modules/kalabox-engine-docker/docker.js.jx:716:25)
From previous event:
    at Object.use (/usr/local/bin/node_modules/kalabox-engine-docker/docker.js.jx:715:6)
From previous event:
    at /usr/local/bin/lib/engine.js.jx:575:29
From previous event:
    at Object.exports.use (/usr/local/bin/lib/engine.js.jx:574:4)
    at /usr/local/bin/plugins/kalabox-syncthing/events.js.jx:124:25
From previous event:
    at /usr/local/bin/plugins/kalabox-syncthing/events.js.jx:99:10
    at /usr/local/bin/lib/core/events.js.jx:147:11
    at /usr/local/bin/lib/core/events.js.jx:146:24
From previous event:
    at /usr/local/bin/lib/core/events.js.jx:130:23
From previous event:
    at EventEngine._dispatch (/usr/local/bin/lib/core/events.js.jx:127:18)
    at /usr/local/bin/lib/core/events.js.jx:107:19
From previous event:
    at EventEngine.emit (/usr/local/bin/lib/core/events.js.jx:99:21)
From previous event:
    at Object.exports.emit (/usr/local/bin/lib/core/events.js.jx:230:4)
    at services.verify.then.then.then.map.concurrency (/usr/local/bin/lib/app.js.jx:500:24)
From previous event:
    at exports.start (/usr/local/bin/lib/app.js.jx:499:4)
    at /usr/local/bin/lib/app.js.jx:612:12
From previous event:
    at Object.exports.restart (/usr/local/bin/lib/app.js.jx:611:4)
    at Object.task.func (/usr/local/bin/plugins/kalabox-core/tasks/restart.js.jx:15:18)
    at Object.exports.run (/usr/local/bin/lib/core/tasks.js.jx:857:15)
    at processTask (/usr/local/bin/bin/kbox.js.jx:166:16)
    at Object.<anonymous> (/usr/local/bin/bin/kbox.js.jx:215:12)
    at process._tickCallback (node.js:812:13)
From previous event:
    at main (/usr/local/bin/bin/kbox.js.jx:214:4)
    at Object.<anonymous> (/usr/local/bin/bin/kbox.js.jx:223:1)
    at Module._compile (module.js:518:26)
    at readX (module.js:1284:5)
    at Object.Module._extensions..jx (module.js:1711:10)
    at Module.load (module.js:345:36)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:377:17)
    at require (module.js:395:17)
    at Object.<anonymous> (_jx_source:17:3)
    at Module._compile (module.js:518:26)
    at Module.load (module.js:353:12)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:733:12)
    at startup (node.js:371:18)
    at node.js:1464:3

**Comment by pirog** [comment]
[kbox | uploaded via ZenHub](https://files.zenhub.io/55f7aee5eadedb3c47414740)

**Comment by pirog** [comment]
[kbox | uploaded via ZenHub](https://files.zenhub.io/55f8529aeadedb3c47414ff1)
