### ISSUE TITLE
Error on "kbox create pantheon"

### ISSUE THREAD

**Issue by pi-ron** [kalabox/kalabox#477]
I've tried pulling down an existing Pantheon site, it hasn't been pulled before so no namespace issues.

This is the error I'm getting on `kbox create pantheon`

``````
Error while installing app: "test-restaurant": EVENTS =>  Error dispatching event listeners [post-install].
VError: Error running ad hoc container with kalabox/terminus:v0.9.0.: PHP Notice:  Undefined property: stdClass::$framework in phar:///usr/local/bin/terminus/php/Terminus/SitesCache.php on line 220

    at Object.dockerInstance.then.bind.then.then.then.catch.finally.self (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/docker.js:696:13)
From previous event:
    at Object.use (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/docker.js:695:11)
From previous event:
    at /usr/local/lib/node_modules/kalabox/lib/engine.js:566:29
From previous event:
    at Object.exports.use (/usr/local/lib/node_modules/kalabox/lib/engine.js:565:4)
    at /Users/RoamingMac/Sites/test-restaurant/plugins/kalabox-plugin-pantheon/lib/terminus.js:113:29
From previous event:
    at Terminus.__request (/Users/RoamingMac/Sites/test-restaurant/plugins/kalabox-plugin-pantheon/lib/terminus.js:106:4)
    at Terminus.getUUID (/Users/RoamingMac/Sites/test-restaurant/plugins/kalabox-plugin-pantheon/lib/terminus.js:251:15)
    at terminus.getConnectionMode.then.then.then.then.build.protocol (/Users/RoamingMac/Sites/test-restaurant/plugins/kalabox-plugin-pantheon/lib/pull.js:64:27)
From previous event:
    at pullCode (/Users/RoamingMac/Sites/test-restaurant/plugins/kalabox-plugin-pantheon/lib/pull.js:63:10)
    at /Users/RoamingMac/Sites/test-restaurant/plugins/kalabox-plugin-pantheon/lib/pull.js:211:20
From previous event:
    at /Users/RoamingMac/Sites/test-restaurant/plugins/kalabox-plugin-pantheon/lib/pull.js:209:10
    at /usr/local/lib/node_modules/kalabox/lib/core/events.js:147:11
    at /usr/local/lib/node_modules/kalabox/lib/core/events.js:146:24
From previous event:
    at /usr/local/lib/node_modules/kalabox/lib/core/events.js:130:23
From previous event:
    at EventEngine._dispatch (/usr/local/lib/node_modules/kalabox/lib/core/events.js:127:18)
    at /usr/local/lib/node_modules/kalabox/lib/core/events.js:107:19
From previous event:
    at EventEngine.emit (/usr/local/lib/node_modules/kalabox/lib/core/events.js:99:21)
From previous event:
    at Object.exports.emit (/usr/local/lib/node_modules/kalabox/lib/core/events.js:228:4)
    at /usr/local/lib/node_modules/kalabox/lib/app.js:428:24
From previous event:
    at Object.exports.install (/usr/local/lib/node_modules/kalabox/lib/app.js:427:4)
    at Object.<anonymous> (/usr/local/lib/node_modules/kalabox/lib/create.js:336:26)
From previous event:
    at /usr/local/lib/node_modules/kalabox/lib/create.js:335:8
    at process._tickCallback (node.js:419:13)
From previous event:
    at createApp (/usr/local/lib/node_modules/kalabox/lib/create.js:313:6)
    at PromptUI.completed (/usr/local/lib/node_modules/kalabox/lib/create.js:251:18)
    at PromptUI.onCompletion (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/lib/ui/prompt.js:69:10)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:1793:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:1730:14)
    at AnonymousObserver.tryCatcher (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:567:29)
    at AutoDetachObserverPrototype.completed (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:5288:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:1730:14)
    at InnerObserver.onCompleted (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:3425:65)
    at InnerObserver.tryCatcher (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:567:29)
    at AutoDetachObserverPrototype.completed (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:5288:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:1730:14)
    at AutoDetachObserver.tryCatcher (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:567:29)
    at AutoDetachObserverPrototype.completed (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:5288:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:1730:14)
    at InnerObserver.onCompleted (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:3425:65)
    at InnerObserver.tryCatcher (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:567:29)
    at AutoDetachObserverPrototype.completed (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:5288:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:1730:14)
    at AutoDetachObserver.tryCatcher (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:567:29)
    at AutoDetachObserverPrototype.completed (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:5288:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/lib/node_modules/kalabox/node_modules/inquirer/node_modules/rx/dist/rx.js:1730:14)
    at /usr/local/lib/node_modules/kalabox/node_modules/inquirer/lib/utils/utils.js:53:13
    at /usr/local/lib/node_modules/kalabox/node_modules/lodash/index.js:7173:25
    at /usr/local/lib/node_modules/kalabox/node_modules/inquirer/lib/ui/prompt.js:98:7
``````

**Comment by pirog** [comment]
Hey @pi-ron this is a known issue in 0.9.0 that is fixed in the new 0.10.0 release.
