### ISSUE TITLE
Error on "kbox install" on freshly create pantheon app

### ISSUE THREAD

**Issue by pi-ron** [kalabox/kalabox#478]
Apologies if this is a duplicate, but just want to note it in case...

After doing `kbox create pantheon` on a new app, never been kbox'ed before.

Step into app and run `kbox install` and get this error:

``````
Error while installing app: "mervian-lp": Container already exists: kb_mervian-lp_appserver
Error: Container already exists: kb_mervian-lp_appserver
    at /usr/local/lib/node_modules/kalabox/lib/app.js:416:17
From previous event:
    at Promise.resolve.filter.map.concurrency (/usr/local/lib/node_modules/kalabox/lib/app.js:407:8)
From previous event:
    at /usr/local/lib/node_modules/kalabox/lib/app.js:404:6
From previous event:
    at Object.exports.install (/usr/local/lib/node_modules/kalabox/lib/app.js:400:4)
    at Object.task.func (/usr/local/lib/node_modules/kalabox/plugins/kalabox-core/tasks/install.js:25:18)
    at Object.exports.run (/usr/local/lib/node_modules/kalabox/lib/core/tasks.js:834:15)
    at processTask (/usr/local/lib/node_modules/kalabox/bin/kbox.js:170:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/kalabox/bin/kbox.js:219:12)
    at process._tickCallback (node.js:419:13)
From previous event:
    at main (/usr/local/lib/node_modules/kalabox/bin/kbox.js:218:4)
    at Object.<anonymous> (/usr/local/lib/node_modules/kalabox/bin/kbox.js:227:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
``````

**Comment by pi-ron** [comment]
Then if I `kbox start` on that app get:

``````
EVENTS =>  Error dispatching event listeners [post-start-component].
Error: ln: failed to create symbolic link `/code/sites/default/files': No such file or directory

    at MemoryDuplexStream.<anonymous> (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/docker.js:544:24)
    at MemoryDuplexStream.emit (events.js:95:17)
    at MemoryDuplexStream.<anonymous> (_stream_readable.js:764:14)
    at MemoryDuplexStream.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:426:10)
    at emitReadable (_stream_readable.js:422:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at MemoryDuplexStream.Readable.push (_stream_readable.js:127:10)
    at MemoryDuplexStream._write (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/node_modules/memorystream/index.js:150:14)
    at doWrite (_stream_writable.js:225:10)
    at writeOrBuffer (_stream_writable.js:215:5)
    at MemoryDuplexStream.Writable.write (_stream_writable.js:182:11)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:247:16)
    at IncomingMessage.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:426:10)
    at emitReadable (_stream_readable.js:422:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at IncomingMessage.Readable.push (_stream_readable.js:127:10)
    at HTTPParser.parserOnBody [as onBody] (http.js:142:22)
    at Socket.socketOnData [as ondata] (http.js:1583:20)
    at TCP.onread (net.js:527:27)
    at Object.result.wait (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/docker.js:539:20)
    at /usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/docker.js:612:18
    at Object.queryData (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/docker.js:610:6)
    at Object.exports.queryData (/usr/local/lib/node_modules/kalabox/lib/engine.js:628:27)
    at /Users/RoamingMac/Sites/mervian-lp/plugins/kalabox-plugin-pantheon/lib/env.js:328:28
    at /usr/local/lib/node_modules/kalabox/lib/core/events.js:147:11
    at /usr/local/lib/node_modules/kalabox/lib/core/events.js:146:24
    at /usr/local/lib/node_modules/kalabox/lib/core/events.js:130:23
    at EventEngine._dispatch (/usr/local/lib/node_modules/kalabox/lib/core/events.js:127:18)
    at /usr/local/lib/node_modules/kalabox/lib/core/events.js:107:19
    at EventEngine.emit (/usr/local/lib/node_modules/kalabox/lib/core/events.js:99:21)
    at Object.exports.emit (/usr/local/lib/node_modules/kalabox/lib/core/events.js:228:4)
    at /usr/local/lib/node_modules/kalabox/lib/app.js:467:24
    at startComponent (/usr/local/lib/node_modules/kalabox/lib/app.js:466:4)
    at services.verify.then.then.then.map.concurrency (/usr/local/lib/node_modules/kalabox/lib/app.js:509:12)
    at Object.exports.start (/usr/local/lib/node_modules/kalabox/lib/app.js:508:4)
    at Object.task.func (/usr/local/lib/node_modules/kalabox/plugins/kalabox-core/tasks/start.js:14:18)
    at Object.exports.run (/usr/local/lib/node_modules/kalabox/lib/core/tasks.js:834:15)
    at processTask (/usr/local/lib/node_modules/kalabox/bin/kbox.js:170:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/kalabox/bin/kbox.js:219:12)
    at process._tickCallback (node.js:419:13)
    at main (/usr/local/lib/node_modules/kalabox/bin/kbox.js:218:4)
    at Object.<anonymous> (/usr/local/lib/node_modules/kalabox/bin/kbox.js:227:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
``````

**Comment by pirog** [comment]
@pi-ron yeah i think there is a duplicate container issue and also this second kbox start issue!

**Comment by pirog** [comment]
@pi-ron closing this as dup of #362
