### ISSUE TITLE
kbox down seems to fail when you have no apps installed

### ISSUE THREAD

**Issue by pirog** [kalabox/kalabox#521]
Error while shutting down.: EVENTS =>  Error dispatching event listeners [pre-down].
VError: Unexpected error while trying to determine if syncthing http://10.13.37.42:60008 is up.: Error REST request: action=get address=http://10.13.37.42:60008
verb=system/ping data=null opts=[object Object].: operation timed out
    at C:\Users\pirog\Desktop\kalabox\lib\share\sync\sync.js:290:13
From previous event:
    at Sync.__isUpInternal (C:\Users\pirog\Desktop\kalabox\lib\share\sync\sync.js:284:9)
    at Sync.isUp (C:\Users\pirog\Desktop\kalabox\lib\share\sync\sync.js:303:15)
    at C:\Users\pirog\Desktop\kalabox\lib\share.js:332:23
From previous event:
    at getRemoteSyncIfStarted (C:\Users\pirog\Desktop\kalabox\lib\share.js:331:4)
    at C:\Users\pirog\Desktop\kalabox\lib\share.js:381:3
    at C:\Users\pirog\Desktop\kalabox\lib\core\events.js:158:24
From previous event:
    at C:\Users\pirog\Desktop\kalabox\lib\core\events.js:130:23
From previous event:
    at EventEngine._dispatch (C:\Users\pirog\Desktop\kalabox\lib\core\events.js:127:18)
    at C:\Users\pirog\Desktop\kalabox\lib\core\events.js:107:19
From previous event:
    at EventEngine.emit (C:\Users\pirog\Desktop\kalabox\lib\core\events.js:99:21)
From previous event:
    at exports.emit (C:\Users\pirog\Desktop\kalabox\lib\core\events.js:230:4)
    at Object.down (C:\Users\pirog\Desktop\kalabox\node_modules\kalabox-engine-docker\provider\b2d.js:392:23)
From previous event:
    at C:\Users\pirog\Desktop\kalabox\lib\engine.js:293:31
From previous event:
    at Object.exports.down (C:\Users\pirog\Desktop\kalabox\lib\engine.js:292:4)
    at Object.task.func (C:\Users\pirog\Desktop\kalabox\node_modules\kalabox-engine-docker\lib\tasks.js:35:14)
    at Object.exports.run (C:\Users\pirog\Desktop\kalabox\lib\core\tasks.js:857:15)
    at processTask (C:\Users\pirog\Desktop\kalabox\bin\kbox.js:168:16)
    at Object.<anonymous> (C:\Users\pirog\Desktop\kalabox\bin\kbox.js:231:12)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
From previous event:
    at main (C:\Users\pirog\Desktop\kalabox\bin\kbox.js:230:4)
    at Object.<anonymous> (C:\Users\pirog\Desktop\kalabox\bin\kbox.js:239:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by pirog** [comment]
I think this was bogus
