### ISSUE TITLE
Better document uninstall process and what to do with the binary.

### ISSUE THREAD

**Issue by rgeleta** [kalabox/kalabox#541]
In command prompt (non administrator)
`kbox version` returns 0.9.15

In gui
Control Panel > Programs > Programs and Features 
no kbox or kalabox

In command prompt (non administrator)
`npm uninstall kalabox` fails, with 
npm WARN uninstall not installed in C:\Users\bob\node_modules: "kalabox"
`npm uninstall kbox` fails with similar message
BTW, there is no directory C:\Users\bob\node_modules

on kbox-windows-amd64-v0.10.2.exe, run as administrator
quick popup window flashes by
in command prompt (non administrator)
`kbox version` returns 0.9.15

In git bash shell
`kbox version` returns 0.9.15
`which kbox` returns
/c/Users/bob/AppData/Roaming/npm/kbox

Directory of C:\Users\bob\AppData\Roaming\npm
 dir etc
 file kbox
 file kbox.cmd
 dir node_modules

and in dir node_modules there is 
 dir kalabox

suggested next steps for removing 0.9.15 ?

**Comment by rgeleta** [comment]
Additional info
Directory of C:\Users\bob\AppData\Roaming\npm
dir etc
file kbox
file kbox.cmd
dir node_modules
and in node_modules there is a dir kalabox

**Comment by pirog** [comment]
I think the issue here is we just want to better document somethings. I'll start to stub this out here:

@rgeleta are you following the uninstall instructions from the wiki? you will want to run the uninstall script first. 

As for the binary, it's actually a binary not an installer or pkg so its drag and drop. What you will want to do is put it somewhere in your path and rename it to `kbox`. For you might want to use just `C:\Users\bob\AppData\Roaming\npm`, remove kbox and kbox.cmd. Move the binary into that directory and then rename it `kbox`. 

Open a command prompt and run `kbox version` and you should get 0.10.2.

**Comment by rgeleta** [comment]
making progress
```
cd C:\Users\bob\AppData\Roaming\npm
scripts\uninstall-win32.bat
```
uninstaller ran, gave me a warning that if I wanted to uninstall Virtualbox I would have to do that manually, good, I did not want to uninstall it. Also good: git was still installed.
copied kbox-windows-amd64-v0.10.2.exe to kbox
from git `kbox version` returned 0.10.2 - good
from windows command 
`kbox version` returned not found error
`path` returned long path.  too long?  unknown
reboot system
from windows command
`kbox version` returned not found error
from git bash
```
cd /c/Users/bob/AppData/Roaming/npm
mv kbox kbox.exe
which kbox
/c/Users/bob/AppData/Roaming/npm/kbox
cd ..
kbox version
0.10.2
```
from windows command prompt
`kbox version`
returns 0.10.2

So, for the doc, when doing a manual copy and rename of the install file, its name should be
`kbox.exe`

git bash is smart enough to recognize that the file `kbox.exe` qualifies as a bash command `kbox`

**Comment by pirog** [comment]
Whoops that's my bad @rgeleta. If you are renaming the file in Explorer i dont think you need to specify the suffix but if you are renaming it in cmd.exe or bash then yes you need to specify it.

**Comment by rgeleta** [comment]
more progress (I think)
skipping ahead, it dawned on me after seeing failures documented below, I did not redo
`npm install -g kalabox`
so if that caused problem, the following is only for documentation of what can go wrong.

now that 0.10.2 is installed and on path, do, create new box
in windows command prompt (non administrator)
```
K:\websites\badcamp>mkdir site.dev.kala

K:\websites\badcamp>cd site.dev.kala

K:\websites\badcamp\site.dev.kala>kbox create pantheon
? Pantheon dashboard email: someone@example.com
? Pantheon dashboard password: **********
? Which site? mypantheonsite
? Which environment? dev
? What will you call this monster you have created: bc2015b
Building your app...
###############################################################

                    Welcome to Kalabox 2!

 We see this is your first time running a Kalabox command that
 requires the use of the Kalabox engine. Before we can do this
 We need to install some special things to make sure you are
 good to go. Please agree to the prompt below to install all
 the magic. (takes about 5 minutes with average download speed)

###############################################################
info: -- Step 1/23 --
info: Authorizing trilling subroutines...
? Install all the magic and get this party started? Yes
info: -- OK! 4% complete! --

info: -- Step 2/23 --
info: Making sure syncthing is not running...
info: -- OK! 9% complete! --

info: -- Step 3/23 --
info: Adding syncthing image to build list...
info: -- OK! 13% complete! --

info: -- Step 4/23 --
info: Queuing up syncthing downloads...
info: -- OK! 17% complete! --

info: -- Step 5/23 --
info: Queuing up support files...
info: -- OK! 22% complete! --

info: -- Step 6/23 --
info: Checking firewall settings...
info: -- OK! 26% complete! --

info: -- Step 7/23 --
info: Adding services images to build list...
info: -- OK! 30% complete! --

info: -- Step 8/23 --
info: Queuing provider admin commands...
info: -- OK! 35% complete! --

info: -- Step 9/23 --
info: Queuing up provider downloads...
info: -- OK! 39% complete! --

info: -- Step 10/23 --
info: Checking for Internet access...
info: -- OK! 43% complete! --

info: -- Step 11/23 --
info: Downloading files...
     fetch : https://raw.githubusercontent.com/kalabox/kalabox/master/dockerfile
s/syncthing/config.xml
  progress : [====================] 100% 0.0s

     fetch : https://raw.githubusercontent.com/kalabox/windosu/master/invisible.
vbs


     fetch : https://raw.githubusercontent.com/kalabox/diskspace.js/master/drive
space.exe


     fetch : https://raw.githubusercontent.com/kalabox/kalabox-boot2docker/maste
r/b2d.inf


     fetch : https://raw.githubusercontent.com/kalabox/kalabox-boot2docker/maste
r/profile


     fetch : https://github.com/syncthing/syncthing/releases/download/v0.11.25/s
yncthing-windows-amd64-v0.11.25.zip
     fetch : https://github.com/boot2docker/windows-installer/releases/download/
v1.8.0/docker-install.exe
  progress : [====================] 100% 0.0s

info: -- OK! 48% complete! --

info: -- Step 12/23 --
info: Setting up syncthing...
info: -- OK! 52% complete! --

info: -- Step 13/23 --
info: Running admin install commands...
info: -- OK! 57% complete! --

info: -- Step 14/23 --
info: Checking for available disk space...
info: -- OK! 61% complete! --

info: -- Step 15/23 --
info: Setting up the provider profile...
info: -- OK! 65% complete! --

info: -- Step 16/23 --
info: Updating install info...
info: -- OK! 70% complete! --

info: -- Step 17/23 --
info: Setting up and activating the engine...
info: BOOT2DOCKER =>  Starting up. disksize=20041, max=3
info: BOOT2DOCKER =>  Initializing boot2docker [1].
info: BOOT2DOCKER =>  Initializing boot2docker failed, retrying. VError: Error r
unning command ""C:\Program Files\Boot2Docker for Windows\boot2docker.exe" --hos
tip="10.13.37.1",--disksize=20041,init".: code: 1, msg: The system cannot find t
he path specified.

    at C:\Users\bob\AppData\Roaming\npm\node_modules\kalabox-engine-docker\provi
der\b2d.js.jx:189:13
From previous event:
    at sh (C:\Users\bob\AppData\Roaming\npm\node_modules\kalabox-engine-docker\p
rovider\b2d.js.jx:187:11)
    at shProvider (C:\Users\bob\AppData\Roaming\npm\node_modules\kalabox-engine-
docker\provider\b2d.js.jx:284:12)
    at C:\Users\bob\AppData\Roaming\npm\node_modules\kalabox-engine-docker\provi
der\b2d.js.jx:316:16
    at C:\Users\bob\AppData\Roaming\npm\node_modules\kalabox-engine-docker\node_
modules\retry-bluebird\retry-bluebird.js.jx:28:14
    at rec (C:\Users\bob\AppData\Roaming\npm\node_modules\kalabox-engine-docker\
node_modules\retry-bluebird\retry-bluebird.js.jx:27:23)
    at module.exports (C:\Users\bob\AppData\Roaming\npm\node_modules\kalabox-eng
ine-docker\node_modules\retry-bluebird\retry-bluebird.js.jx:47:10)
    at Promise.try.then.then.then.shareCmd (C:\Users\bob\AppData\Roaming\npm\nod
e_modules\kalabox-engine-docker\provider\b2d.js.jx:306:14)
From previous event:
    at Object.up (C:\Users\bob\AppData\Roaming\npm\node_modules\kalabox-engine-d
ocker\provider\b2d.js.jx:305:6)
From previous event:
    at C:\Users\bob\AppData\Roaming\npm\node_modules\kalabox-engine-docker\lib\i
nstall.js.jx:248:39
From previous event:
    at step.all (C:\Users\bob\AppData\Roaming\npm\node_modules\kalabox-engine-do
cker\lib\install.js.jx:247:8)
    at C:\Users\bob\AppData\Roaming\npm\lib\install\framework.js.jx:452:17
    at C:\Users\bob\AppData\Roaming\npm\lib\install\framework.js.jx:450:30
From previous event:
    at Promise.each.then.events.emit.state (C:\Users\bob\AppData\Roaming\npm\lib
\install\framework.js.jx:442:29)
From previous event:
    at C:\Users\bob\AppData\Roaming\npm\lib\install\framework.js.jx:432:22
    at Object.exports.run (C:\Users\bob\AppData\Roaming\npm\lib\install.js.jx:17
2:10)
    at C:\Users\bob\AppData\Roaming\npm\lib\engine.js.jx:127:26
From previous event:
    at verifyProviderInstalled (C:\Users\bob\AppData\Roaming\npm\lib\engine.js.j
x:123:6)
    at Object.exports.up (C:\Users\bob\AppData\Roaming\npm\lib\engine.js.jx:157:
10)
    at C:\Users\bob\AppData\Roaming\npm\lib\create.js.jx:376:21
    at process._tickCallback (node.js:812:13)
From previous event:
    at createApp (C:\Users\bob\AppData\Roaming\npm\lib\create.js.jx:375:6)
    at PromptUI.completed (C:\Users\bob\AppData\Roaming\npm\lib\create.js.jx:512
:18)
    at PromptUI.onCompletion (C:\Users\bob\AppData\Roaming\npm\node_modules\inqu
irer\lib\ui\prompt.js.jx:68:10)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (C:\Us
ers\bob\AppData\Roaming\npm\node_modules\inquirer\node_modules\rx\dist\rx.js.jx:
1792:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onComple
ted (C:\Users\bob\AppData\Roaming\npm\node_modules\inquirer\node_modules\rx\dist
\rx.js.jx:1729:14)
    at AnonymousObserver.tryCatcher (C:\Users\bob\AppData\Roaming\npm\node_modul
es\inquirer\node_modules\rx\dist\rx.js.jx:566:29)
    at AutoDetachObserverPrototype.completed (C:\Users\bob\AppData\Roaming\npm\n
ode_modules\inquirer\node_modules\rx\dist\rx.js.jx:5287:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompl
eted (C:\Users\bob\AppData\Roaming\npm\node_modules\inquirer\node_modules\rx\dis
t\rx.js.jx:1729:14)
    at InnerObserver.onCompleted (C:\Users\bob\AppData\Roaming\npm\node_modules\
inquirer\node_modules\rx\dist\rx.js.jx:3424:65)
    at InnerObserver.tryCatcher (C:\Users\bob\AppData\Roaming\npm\node_modules\i
nquirer\node_modules\rx\dist\rx.js.jx:566:29)
    at AutoDetachObserverPrototype.completed (C:\Users\bob\AppData\Roaming\npm\n
ode_modules\inquirer\node_modules\rx\dist\rx.js.jx:5287:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompl
eted (C:\Users\bob\AppData\Roaming\npm\node_modules\inquirer\node_modules\rx\dis
t\rx.js.jx:1729:14)
    at AutoDetachObserver.tryCatcher (C:\Users\bob\AppData\Roaming\npm\node_modu
les\inquirer\node_modules\rx\dist\rx.js.jx:566:29)
    at AutoDetachObserverPrototype.completed (C:\Users\bob\AppData\Roaming\npm\n
ode_modules\inquirer\node_modules\rx\dist\rx.js.jx:5287:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompl
eted (C:\Users\bob\AppData\Roaming\npm\node_modules\inquirer\node_modules\rx\dis
t\rx.js.jx:1729:14)
    at InnerObserver.onCompleted (C:\Users\bob\AppData\Roaming\npm\node_modules\
inquirer\node_modules\rx\dist\rx.js.jx:3424:65)
    at InnerObserver.tryCatcher (C:\Users\bob\AppData\Roaming\npm\node_modules\i
nquirer\node_modules\rx\dist\rx.js.jx:566:29)
    at AutoDetachObserverPrototype.completed (C:\Users\bob\AppData\Roaming\npm\n
ode_modules\inquirer\node_modules\rx\dist\rx.js.jx:5287:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompl
eted (C:\Users\bob\AppData\Roaming\npm\node_modules\inquirer\node_modules\rx\dis
t\rx.js.jx:1729:14)
    at AutoDetachObserver.tryCatcher (C:\Users\bob\AppData\Roaming\npm\node_modu
les\inquirer\node_modules\rx\dist\rx.js.jx:566:29)
    at AutoDetachObserverPrototype.completed (C:\Users\bob\AppData\Roaming\npm\n
ode_modules\inquirer\node_modules\rx\dist\rx.js.jx:5287:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompl
eted (C:\Users\bob\AppData\Roaming\npm\node_modules\inquirer\node_modules\rx\dis
t\rx.js.jx:1729:14)
    at C:\Users\bob\AppData\Roaming\npm\node_modules\inquirer\lib\utils\utils.js
.jx:52:13
    at C:\Users\bob\AppData\Roaming\npm\node_modules\lodash\index.js.jx:7172:25
    at C:\Users\bob\AppData\Roaming\npm\node_modules\inquirer\lib\ui\prompt.js.j
x:97:7
    at Object.utils.runAsync (C:\Users\bob\AppData\Roaming\npm\node_modules\inqu
irer\lib\utils\utils.js.jx:36:5)
    at Prompt.filter (C:\Users\bob\AppData\Roaming\npm\node_modules\inquirer\lib
\prompts\base.js.jx:183:9)
    at Prompt.done (C:\Users\bob\AppData\Roaming\npm\node_modules\inquirer\lib\p
rompts\base.js.jx:71:10)
    at Prompt.<anonymous> (C:\Users\bob\AppData\Roaming\npm\node_modules\inquire
r\lib\prompts\input.js.jx:89:10)
    at Object.utils.runAsync (C:\Users\bob\AppData\Roaming\npm\node_modules\inqu
irer\lib\utils\utils.js.jx:36:5)
    at Prompt.filter (C:\Users\bob\AppData\Roaming\npm\node_modules\inquirer\lib
\prompts\base.js.jx:183:9)
info: BOOT2DOCKER =>  Initializing boot2docker [2].
info: BOOT2DOCKER =>  Initializing boot2docker failed, retrying. VError: Error r
unning command ""C:\Program Files\Boot2Docker for Windows\boot2docker.exe" --hos
tip="10.13.37.1",--disksize=20041,init".: code: 1, msg: The system cannot find t
he path specified.

    at C:\Users\bob\AppData\Roaming\npm\node_modules\kalabox-engine-docker\provi
der\b2d.js.jx:189:13
From previous event:
    at sh (C:\Users\bob\AppData\Roaming\npm\node_modules\kalabox-engine-docker\p
rovider\b2d.js.jx:187:11)
    at shProvider (C:\Users\bob\AppData\Roaming\npm\node_modules\kalabox-engine-
docker\provider\b2d.js.jx:284:12)
    at C:\Users\bob\AppData\Roaming\npm\node_modules\kalabox-engine-docker\provi
der\b2d.js.jx:316:16
    at C:\Users\bob\AppData\Roaming\npm\node_modules\kalabox-engine-docker\node_
modules\retry-bluebird\retry-bluebird.js.jx:28:14
    at rec (C:\Users\bob\AppData\Roaming\npm\node_modules\kalabox-engine-docker\
node_modules\retry-bluebird\retry-bluebird.js.jx:27:23)
    at C:\Users\bob\AppData\Roaming\npm\node_modules\kalabox-engine-docker\node_
modules\retry-bluebird\retry-bluebird.js.jx:36:18
    at process._tickCallback (node.js:812:13)
info: BOOT2DOCKER =>  Initializing boot2docker [3].
info: BOOT2DOCKER =>  Initializing boot2docker failed, retrying. VError: Error r
unning command ""C:\Program Files\Boot2Docker for Windows\boot2docker.exe" --hos
tip="10.13.37.1",--disksize=20041,init".: code: 1, msg: The system cannot find t
he path specified.

    at C:\Users\bob\AppData\Roaming\npm\node_modules\kalabox-engine-docker\provi
der\b2d.js.jx:189:13
From previous event:
    at sh (C:\Users\bob\AppData\Roaming\npm\node_modules\kalabox-engine-docker\p
rovider\b2d.js.jx:187:11)
    at shProvider (C:\Users\bob\AppData\Roaming\npm\node_modules\kalabox-engine-
docker\provider\b2d.js.jx:284:12)
    at C:\Users\bob\AppData\Roaming\npm\node_modules\kalabox-engine-docker\provi
der\b2d.js.jx:316:16
    at C:\Users\bob\AppData\Roaming\npm\node_modules\kalabox-engine-docker\node_
modules\retry-bluebird\retry-bluebird.js.jx:28:14
    at rec (C:\Users\bob\AppData\Roaming\npm\node_modules\kalabox-engine-docker\
node_modules\retry-bluebird\retry-bluebird.js.jx:27:23)
    at C:\Users\bob\AppData\Roaming\npm\node_modules\kalabox-engine-docker\node_
modules\retry-bluebird\retry-bluebird.js.jx:36:18
    at process._tickCallback (node.js:812:13)
info: VError: Error initializing boot2docker.: BOOT2DOCKER =>  Initializing boot
2docker failed, retrying.
info: -- INSTALL FAILURE. --

K:\websites\badcamp\site.dev.kala>cd
```

so let's try to step back and recreate a proper environment
and (novel idea) try to follow directions
in git bash shell
```
bob@inspirn8 MINGW64 /k/websites/badcamp
$ cd site.dev.kala

bob@inspirn8 MINGW64 /k/websites/badcamp/site.dev.kala
$ ls
bc2015b/

bob@inspirn8 MINGW64 /k/websites/badcamp/site.dev.kala
$ cd bc2015b/

bob@inspirn8 MINGW64 /k/websites/badcamp/site.dev.kala/bc2015b
$ ls
config/       kalabox.json   package.json  scripts/
dockerfiles/  node_modules/  plugins/

bob@inspirn8 MINGW64 /k/websites/badcamp/site.dev.kala/bc2015b
$ kbox destroy
###############################################################

               Hi there! Updates are required!

 We see you just updated your kalabox code! That means that
 you should run our updater before you proceed.

          Please run `kbox update` before you proceed!                                                                        

###############################################################

bob@inspirn8 MINGW64 /k/websites/badcamp/site.dev.kala/bc2015b
$ kbox update
info: -- Step 1/20 --
info: Authorizing trilling subroutines...
info: Non-interactive mode.
{ [VError: Error running step: {"name":"core-auth","description":"Authorizing tr                                              illing subroutines...","deps":[],"subscribes":[],"first":true,"last":false,"isSt                                              ep":true}: EINVAL, invalid argument]
  jse_shortmsg: 'Error running step: {"name":"core-auth","description":"Authoriz                                              ing trilling subroutines...","deps":[],"subscribes":[],"first":true,"last":false                                              ,"isStep":true}',
  jse_summary: 'Error running step: {"name":"core-auth","description":"Authorizi                                              ng trilling subroutines...","deps":[],"subscribes":[],"first":true,"last":false,                                              "isStep":true}: EINVAL, invalid argument',
  jse_cause: { [Error: EINVAL, invalid argument] errno: 18, code: 'EINVAL', sysc                                              all: 'uv_pipe_open' },
  message: 'Error running step: {"name":"core-auth","description":"Authorizing t                                              rilling subroutines...","deps":[],"subscribes":[],"first":true,"last":false,"isS                                              tep":true}: EINVAL, invalid argument' }

bob@inspirn8 MINGW64 /k/websites/badcamp/site.dev.kala/bc2015b
$ ls -la
total 17
drwxr-xr-x 1 bob 197609    0 Oct  4 09:49 ./
drwxr-xr-x 1 bob 197609    0 Oct  4 12:29 ../
drwxr-xr-x 1 bob 197609    0 Oct  4 09:49 .cids/
drwxr-xr-x 1 bob 197609    0 Oct  4 00:31 config/
drwxr-xr-x 1 bob 197609    0 Oct  4 00:31 dockerfiles/
-rw-r--r-- 1 bob 197609 1390 Oct  4 00:31 kalabox.json
drwxr-xr-x 1 bob 197609    0 Oct  4 00:31 node_modules/
-rw-r--r-- 1 bob 197609  496 Oct  4 00:31 package.json
drwxr-xr-x 1 bob 197609    0 Oct  4 00:31 plugins/
drwxr-xr-x 1 bob 197609    0 Oct  4 00:31 scripts/

bob@inspirn8 MINGW64 /k/websites/badcamp/site.dev.kala/bc2015b
$ 

```
next steps
run uninstall script
run `npm install -g kalabox`
destroy old box
build new box

**Comment by rgeleta** [comment]
in windows command box
`cd c:\Users\bob\AppData\Roaming\npm\node_modules\kalabox`
note kalabox at end of path, not kalabox2
`scripts\uninstall-win32.bat`
gives
```
Welcome to the Kalabox uninstaller script.

This script will destroy your current Kalabox build. If you want
to save your current build for later please either vagrant package
your existing build or export the relevant VirtualBox appliance.

MAKE SURE THAT YOU'VE EXITED THE KALABOX APP OR THIS WILL BLOW UP!!!

ALSO MAKE SURE YOU VISIT 127.0.0.1:60008 AND SHUTDOWN SYNCTHING

WHAT YOU WANT TO DO?

1. Remove all the things.
2. Forget this ever happened.

Choose your destiny:1
Stopping and removing Kalabox2
The system cannot find the path specified.
DESTROYED!

Removing Kalabox directories
The system cannot find the file specified.
REMOVED!

"YOU WILL NEED TO UNINSTALL VIRTUALBOX MANUALLY TO COMPLETE THE UNINSTALL"
Press any key to continue . . .

C:\Users\bob\AppData\Roaming\npm\node_modules\kalabox>
```

so, hmmm

Suggestions (acknowledging they may not be possible to implement due to circumstances beyond your control)

1. Re: `MAKE SURE THAT YOU'VE EXITED THE KALABOX APP OR THIS WILL BLOW UP!!!`
what does this mean?  How do I do that?

2. Re: `ALSO MAKE SURE YOU VISIT 127.0.0.1:60008 AND SHUTDOWN SYNCTHING`
could batch file query a syncthing api (if such exists) to determine if it is running and if so, bail out?

3. batch file lines 34,35, suggest wrapping
```"C:\Program Files\Boot2Docker for Windows\boot2docker.exe" --vm="Kalabox2" destroy
ECHO DESTROYED!```
inside `IF EXIST ...`

**Comment by pirog** [comment]
Will try to address some of these.

1. The nice thing about using the binary is that it is completely self contained aka it has no other dependencies you need. What this means is if you are using the binary you don't need to worry about using `npm` or the kalabox source code in `C:\Users\bob\AppData\Roaming\npm\node_modules\kalabox`. For uninstall you will want to grab the script to go with your latest release https://github.com/kalabox/kalabox/releases

2. We currently only "officially" support Win7. This is going to be true until we reach a stable beta and can justify adding in additional testing infrastructure to support more versions of things. That said many people have been able to install on Win8.1 but YMMV. 

3. We also have only tested installing and running commands with cmd.exe. Eventually and for similar reasons to 2 we will add official support for other shells but for now its recommended you use cmd.exe. 

4. Your error during the install process looks like boot2docker never got installed. This could happen for a number of reasons. Can you check to see if it exists on your computer and post the path where it lives if it does indeed exist. You can check `"C:\Program Files\Boot2Docker for Windows"` or open up cmd.exe and run `where boot2docker`. If neither of these are working it possible you didn't approve the UAC prompt to install or you might not have admin permissions?
