### ISSUE TITLE
Drupal 8 Install fail through Pantheon

### ISSUE THREAD

**Issue by labboy0276** [kalabox/kalabox#542]
Hello!

Spun out a d8 site on Pantheon, went to install it, I see the main error is this:

```
ssh: Could not resolve hostname codeserver.dev.Strict Standards: Non-static method Terminus::get_logger() should not be called stati: Name or service not known
fatal: The remote end hung up unexpectedly
```

Here is the whole output at the end.

```
info: DOCKER =>  Ad hoc container created. 9b4cf8c8047bb028a576bada382b8a9ea3bb1e8699083204f116a7e15ae90572
info: DOCKER =>  Starting ad hoc container "9b4cf8c8047bb028a576bada382b8a9ea3bb1e8699083204f116a7e15ae90572". Binds=[/Users/john:/ssh, /Users/john/kalabox/apps/d8tester:/src], VolumesFrom=[]
Cloning into '.'...
ssh: Could not resolve hostname codeserver.dev.Strict Standards: Non-static method Terminus::get_logger() should not be called stati: Name or service not known
fatal: The remote end hung up unexpectedly
info: DOCKER =>  Ad hoc container started. 9b4cf8c8047bb028a576bada382b8a9ea3bb1e8699083204f116a7e15ae90572
EVENTS =>  Error dispatching event listeners [post-create-app].
Error: Processing failed.
    at Request.<anonymous> (/home/john/kalabox/apps/d8tester/plugins/kalabox-plugin-pantheon/lib/client.js:365:21)
    at Request.emit (events.js:85:15)
    at Request.mixin._fireSuccess (/home/john/kalabox/apps/d8tester/node_modules/restler/lib/restler.js:220:12)
    at /home/john/kalabox/apps/d8tester/node_modules/restler/lib/restler.js:158:20
    at parsers.json (/home/john/kalabox/apps/d8tester/node_modules/restler/lib/restler.js:408:9)
    at parsers.auto (/home/john/kalabox/apps/d8tester/node_modules/restler/lib/restler.js:393:21)
    at Request.mixin._encode (/home/john/kalabox/apps/d8tester/node_modules/restler/lib/restler.js:195:29)
    at /home/john/kalabox/apps/d8tester/node_modules/restler/lib/restler.js:154:16
    at Request.mixin._decode (/home/john/kalabox/apps/d8tester/node_modules/restler/lib/restler.js:170:7)
    at null.<anonymous> (/home/john/kalabox/apps/d8tester/node_modules/restler/lib/restler.js:147:14)
    at emit (events.js:98:20)
    at _stream_readable.js:883:16
    at /home/john/kalabox/apps/d8tester/plugins/kalabox-plugin-pantheon/lib/client.js:361:14
    at /home/john/kalabox/apps/d8tester/node_modules/retry-bluebird/retry-bluebird.js:29:14
    at rec (/home/john/kalabox/apps/d8tester/node_modules/retry-bluebird/retry-bluebird.js:28:23)
    at /home/john/kalabox/apps/d8tester/node_modules/retry-bluebird/retry-bluebird.js:37:18
    at process._tickCallback (node.js:812:13)
john@kalamuna:~/kalabox/apps$ cd d8tester
```

**Comment by labboy0276** [comment]
Also, switched to master branch to try and debug and fix this for us, similarish error, I think it reminiscent of the terminus issue we have a couple months ago while @pirog  was away.  

```
info: DOCKER =>  Removing ad hoc container. 9d293eecb393dd1f8ddc67583dd083be1f9096f24018c8cbc88590c11404ac2e
Unexpected token S
SyntaxError: Unexpected token S
    at Object.parse (native)
    at /home/john/kalabox/apps/d8tester/plugins/kalabox-plugin-pantheon/lib/terminus.js:259:17
From previous event:
    at Terminus.getConnectionMode (/home/john/kalabox/apps/d8tester/plugins/kalabox-plugin-pantheon/lib/terminus.js:258:4)
    at Object.pullCode (/home/john/kalabox/apps/d8tester/plugins/kalabox-plugin-pantheon/lib/pull.js:50:21)
    at /home/john/kalabox/apps/d8tester/plugins/kalabox-plugin-pantheon/lib/tasks.js:271:23
From previous event:
    at /home/john/kalabox/apps/d8tester/plugins/kalabox-plugin-pantheon/lib/tasks.js:270:8
    at /home/john/kb2/lib/core/events.js:147:11
    at /home/john/kb2/lib/core/events.js:146:24
From previous event:
    at /home/john/kb2/lib/core/events.js:130:23
From previous event:
    at EventEngine._dispatch (/home/john/kb2/lib/core/events.js:127:18)
    at /home/john/kb2/lib/core/events.js:107:19
From previous event:
    at EventEngine.emit (/home/john/kb2/lib/core/events.js:99:21)
From previous event:
    at Object.exports.emit (/home/john/kb2/lib/core/events.js:230:4)
    at /home/john/kb2/lib/create.js:410:26
    at processImmediate [as _immediateCallback] (timers.js:367:17)
From previous event:
    at createApp (/home/john/kb2/lib/create.js:408:6)
    at PromptUI.completed (/home/john/kb2/lib/create.js:512:18)
    at PromptUI.onCompletion (/home/john/kb2/node_modules/inquirer/lib/ui/prompt.js:69:10)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (/home/john/kb2/node_modules/inquirer/node_modules/rx/dist/rx.js:1793:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/home/john/kb2/node_modules/inquirer/node_modules/rx/dist/rx.js:1730:14)
    at AnonymousObserver.tryCatcher (/home/john/kb2/node_modules/inquirer/node_modules/rx/dist/rx.js:567:29)
    at AutoDetachObserverPrototype.completed (/home/john/kb2/node_modules/inquirer/node_modules/rx/dist/rx.js:5288:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/home/john/kb2/node_modules/inquirer/node_modules/rx/dist/rx.js:1730:14)
    at InnerObserver.onCompleted (/home/john/kb2/node_modules/inquirer/node_modules/rx/dist/rx.js:3425:65)
    at InnerObserver.tryCatcher (/home/john/kb2/node_modules/inquirer/node_modules/rx/dist/rx.js:567:29)
    at AutoDetachObserverPrototype.completed (/home/john/kb2/node_modules/inquirer/node_modules/rx/dist/rx.js:5288:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/home/john/kb2/node_modules/inquirer/node_modules/rx/dist/rx.js:1730:14)
    at AutoDetachObserver.tryCatcher (/home/john/kb2/node_modules/inquirer/node_modules/rx/dist/rx.js:567:29)
    at AutoDetachObserverPrototype.completed (/home/john/kb2/node_modules/inquirer/node_modules/rx/dist/rx.js:5288:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/home/john/kb2/node_modules/inquirer/node_modules/rx/dist/rx.js:1730:14)
    at InnerObserver.onCompleted (/home/john/kb2/node_modules/inquirer/node_modules/rx/dist/rx.js:3425:65)
    at InnerObserver.tryCatcher (/home/john/kb2/node_modules/inquirer/node_modules/rx/dist/rx.js:567:29)
    at AutoDetachObserverPrototype.completed (/home/john/kb2/node_modules/inquirer/node_modules/rx/dist/rx.js:5288:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/home/john/kb2/node_modules/inquirer/node_modules/rx/dist/rx.js:1730:14)
    at AutoDetachObserver.tryCatcher (/home/john/kb2/node_modules/inquirer/node_modules/rx/dist/rx.js:567:29)
    at AutoDetachObserverPrototype.completed (/home/john/kb2/node_modules/inquirer/node_modules/rx/dist/rx.js:5288:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/home/john/kb2/node_modules/inquirer/node_modules/rx/dist/rx.js:1730:14)
    at /home/john/kb2/node_modules/inquirer/lib/utils/utils.js:53:13
    at /home/john/kb2/node_modules/lodash/index.js:7173:25
    at /home/john/kb2/node_modules/inquirer/lib/ui/prompt.js:98:7
    at Object.utils.runAsync (/home/john/kb2/node_modules/inquirer/lib/utils/utils.js:37:5)
    at Prompt.filter (/home/john/kb2/node_modules/inquirer/lib/prompts/base.js:184:9)
    at Prompt.done (/home/john/kb2/node_modules/inquirer/lib/prompts/base.js:72:10)
    at Prompt.<anonymous> (/home/john/kb2/node_modules/inquirer/lib/prompts/input.js:90:10)
    at Object.utils.runAsync (/home/john/kb2/node_modules/inquirer/lib/utils/utils.js:37:5)
    at Prompt.filter (/home/john/kb2/node_modules/inquirer/lib/prompts/base.js:184:9)
john@kalamuna:~/kalabox/apps$ 
```

**Comment by labboy0276** [comment]
PS work around is to ```kbox start``` then do a manual ```kbox git clone``` of the pantheon d8 instance.  That will get you up and running per say.

**Comment by pirog** [comment]
As far as i can tell this doesnt have anything to do with drupal 8. Another thing to mention here is its not recommended to be pulling the latest kalabox code since that code is not rigorously tested and it may require you running updates. If you dont want to risk things blowing up you should wait for an official release before updating.

**Comment by labboy0276** [comment]
Well, this happened with the binary 0.10.2 + master so you know

**Comment by pirog** [comment]
i have no idea what the binary + master means. are you using both?

**Comment by labboy0276** [comment]
No, that would be silly.  I had the binary originally, the first error on this issue happened.  Then I pured all things and used master to see and the 2nd error I posted happened.

**Comment by pirog** [comment]
yeah dont use master. if you want to use the course code use the branch for the version you are on.

**Comment by labboy0276** [comment]
I will switch to the 0.10.x branch but I am sure I will still get the error is the point of all this.

**Comment by pirog** [comment]
I would keep using the binary and post the issue you get with that. It's really difficult on our end if you are posting multiple errors inside a single ticket using multiple versions of the product and not indicating any of that in the actual issue.

**Comment by labboy0276** [comment]
Ok the first issue is the one I got with the binary.  Sorry for the confusion.

**Comment by labboy0276** [comment]
PS I was on the 0.10x branch it appears not master

**Comment by labboy0276** [comment]
This was due to a corrupt VB instance of Kalabox2 for some reason.  Not sure how that got there, but closing this.
