### ISSUE TITLE
Getting an error 

### ISSUE THREAD

**Issue by vishalred** [kalabox/kalabox#582]
Hi,

 I downloaded kalabox and when I run kbox I get the below error. I am not clear on how I can install the docker engine.

Cannot find module kalabox-engine-docker@^0.9.0 try an npm install first.
Error: Cannot find module kalabox-engine-docker@^0.9.0 try an npm install first.
    at /usr/local/lib/node_modules/kalabox/lib/require.js:205:13
From previous event:
    at requireInternal (/usr/local/lib/node_modules/kalabox/lib/require.js:203:4)
    at /usr/local/lib/node_modules/kalabox/lib/require.js:295:14
    at processImmediate [as _immediateCallback] (timers.js:374:17)
From previous event:
    at Object.exports.require (/usr/local/lib/node_modules/kalabox/lib/require.js:291:4)
    at /usr/local/lib/node_modules/kalabox/lib/kbox.js:64:28
From previous event:
    at exports.require (/usr/local/lib/node_modules/kalabox/lib/kbox.js:57:21)
    at /usr/local/lib/node_modules/kalabox/lib/engine.js:49:12
From previous event:
    at /usr/local/lib/node_modules/kalabox/lib/engine.js:37:21
    at /usr/local/lib/node_modules/kalabox/node_modules/lodash/index.js:7173:25
    at Object.exports.init (/usr/local/lib/node_modules/kalabox/lib/engine.js:236:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/kalabox/lib/init.js:86:24)
    at processImmediate [as _immediateCallback] (timers.js:374:17)
From previous event:
    at Object.<anonymous> (/usr/local/lib/node_modules/kalabox/lib/init.js:85:4)
    at Object.init (/usr/local/lib/node_modules/kalabox/node_modules/lodash/index.js:7173:25)
    at main (/usr/local/lib/node_modules/kalabox/bin/kbox.js:196:15)
    at Object.<anonymous> (/usr/local/lib/node_modules/kalabox/bin/kbox.js:227:1)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:118:18)
    at node.js:952:3
EACCES: permission denied, open '/home/vishal/.kalabox/logs/main.log.2015-10-11'
Error: EACCES: permission denied, open '/home/vishal/.kalabox/logs/main.log.2015-10-11'
    at Error (native)

thank you, v

**Comment by labboy0276** [comment]
Hello

How did you download this?  Did you use the binary or the npm install, almost looks like you may have used the dev install.

I would also use this module prior to running this:
https://github.com/mattgrill/NPM-Doctor 

This will fix your perm errors/

**Comment by vishalred** [comment]
Hi,
Thank you for the quick reply. I I had installed using npm.  I removed it and downloaded the binary as that was the recommended method . It is working for me now.

The documentation seems to be very boiler plate . How do I make my own workflow using aws ? Please advice how should I go about learning kalabox.

Thank you,
Vishal

**Comment by pirog** [comment]
Hey @vishalred! 

Yeah docs are admittedly pretty barebones right now. That will change when we get to a full beta. In the meantime i think your best bet is to check out the pantheon app  (https://github.com/kalabox/kalabox-app-pantheon) for inspiration on the best way to roll your own apps.
