### ISSUE TITLE
kbox create fails, then succeeds!

### ISSUE THREAD

**Issue by pi-ron** [kalabox/kalabox#639]
kbox create pantheon fails first up

``````
Error dispatching event listeners [post-create-app]: Error running ad hoc container with kalabox/terminus:v0.10.0.: Non-zero exit code: 1 [2015-10-27 21:28:49] [info] An update to Terminus is available. Please update to version 0.9.1.
[2015-10-27 21:28:53] [error] Exception thrown - Was unable to parse malformed url: http:///pantheon_healthcheck

VError: Error running ad hoc container with kalabox/terminus:v0.10.0.: Non-zero exit code: 1 [2015-10-27 21:28:49] [info] An update to Terminus is available. Please update to version 0.9.1.
[2015-10-27 21:28:53] [error] Exception thrown - Was unable to parse malformed url: http:///pantheon_healthcheck

    at Object.dockerInstance.then.bind.then.then.then.catch.finally.self (/usr/local/bin/node_modules/kalabox-engine-docker/docker.js.jx:720:13)
From previous event:
    at Object.use (/usr/local/bin/node_modules/kalabox-engine-docker/docker.js.jx:719:11)
From previous event:
    at /usr/local/bin/lib/engine.js.jx:579:29
From previous event:
    at Object.exports.use (/usr/local/bin/lib/engine.js.jx:576:4)
    at Terminus.__request (/Users/RoamingMac/Sites/p-care-tas/plugins/kalabox-plugin-pantheon/lib/terminus.js:120:29)
    at Terminus.wakeSite (/Users/RoamingMac/Sites/p-care-tas/plugins/kalabox-plugin-pantheon/lib/terminus.js:235:15)
    at terminus.getConnectionMode.then.then.then.then.build.protocol (/Users/RoamingMac/Sites/p-care-tas/plugins/kalabox-plugin-pantheon/lib/pull.js:75:23)
From previous event:
    at Object.pullCode (/Users/RoamingMac/Sites/p-care-tas/plugins/kalabox-plugin-pantheon/lib/pull.js:74:6)
    at /Users/RoamingMac/Sites/p-care-tas/plugins/kalabox-plugin-pantheon/lib/tasks.js:401:23
From previous event:
    at /Users/RoamingMac/Sites/p-care-tas/plugins/kalabox-plugin-pantheon/lib/tasks.js:400:8
    at /usr/local/bin/lib/core/events.js.jx:149:11
    at /usr/local/bin/lib/core/events.js.jx:148:24
From previous event:
    at /usr/local/bin/lib/core/events.js.jx:132:23
From previous event:
    at EventEngine._dispatch (/usr/local/bin/lib/core/events.js.jx:129:18)
    at /usr/local/bin/lib/core/events.js.jx:108:19
From previous event:
    at EventEngine.emit (/usr/local/bin/lib/core/events.js.jx:100:21)
From previous event:
    at Object.exports.emit (/usr/local/bin/lib/core/events.js.jx:232:4)
    at appEngine.get.catch.then.then.then.then.then.then.then.then.then.then.sysRoot (/usr/local/bin/lib/create.js.jx:413:26)
    at process._tickCallback (node.js:812:13)
From previous event:
    at createApp (/usr/local/bin/lib/create.js.jx:411:6)
    at PromptUI.completed (/usr/local/bin/lib/create.js.jx:526:18)
    at PromptUI.onCompletion (/usr/local/bin/node_modules/inquirer/lib/ui/prompt.js.jx:68:10)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:1792:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:1729:14)
    at AnonymousObserver.tryCatcher (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:566:29)
    at AutoDetachObserverPrototype.completed (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:5287:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:1729:14)
    at InnerObserver.onCompleted (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:3424:65)
    at InnerObserver.tryCatcher (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:566:29)
    at AutoDetachObserverPrototype.completed (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:5287:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:1729:14)
    at AutoDetachObserver.tryCatcher (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:566:29)
    at AutoDetachObserverPrototype.completed (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:5287:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:1729:14)
    at InnerObserver.onCompleted (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:3424:65)
    at InnerObserver.tryCatcher (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:566:29)
    at AutoDetachObserverPrototype.completed (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:5287:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:1729:14)
    at AutoDetachObserver.tryCatcher (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:566:29)
    at AutoDetachObserverPrototype.completed (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:5287:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:1729:14)
    at /usr/local/bin/node_modules/inquirer/lib/utils/utils.js.jx:52:13
    at /usr/local/bin/node_modules/lodash/index.js.jx:7172:25
    at /usr/local/bin/node_modules/inquirer/lib/ui/prompt.js.jx:97:7
    at Object.utils.runAsync (/usr/local/bin/node_modules/inquirer/lib/utils/utils.js.jx:36:5)
    at Prompt.filter (/usr/local/bin/node_modules/inquirer/lib/prompts/base.js.jx:183:9)
    at Prompt.done (/usr/local/bin/node_modules/inquirer/lib/prompts/base.js.jx:71:10)
    at Prompt.<anonymous> (/usr/local/bin/node_modules/inquirer/lib/prompts/input.js.jx:89:10)
    at Object.utils.runAsync (/usr/local/bin/node_modules/inquirer/lib/utils/utils.js.jx:36:5)
    at Prompt.filter (/usr/local/bin/node_modules/inquirer/lib/prompts/base.js.jx:183:9)
``````

I then went in to pantheon and saw the dev environment had a very old backup, I created a new dev backup and ran `kbox create pantheon` again and it succeeded.

**Comment by pirog** [comment]
@pi-ron how old is old?

**Comment by pi-ron** [comment]
@pirog Mon, Oct 12th 2015... Not that old

**Comment by pirog** [comment]
hmmm, im honestly not sure why the database backup being old would cause this. have you looked over at the terminus issue queue since this all seems to be coming from the terminus container?

**Comment by pi-ron** [comment]
I think it may have been due to Pantheon workflow operations being a bit haywire last week.

**Comment by pirog** [comment]
Because this error is terminus specific im going to agree. At some point we hope to have a status page to cover the status of dependencies like this.
