### ISSUE TITLE
Need to recompile VB DKMS on kernel update with sudo /etc/init.d/vboxdrv setup

### ISSUE THREAD

**Issue by pirog** [kalabox/kalabox#640]
for detailszzz
https://github.com/kalabox/kalabox-app-pantheon/issues/39
#288

**Comment by pirog** [comment]
THis might be a duplicate with #288

**Comment by jeffesquivels** [comment]
My first idea for dealing with this issue would be to make sure the package dkms is installed along with virtualbox, as per the [documentation](https://www.virtualbox.org/wiki/Linux_Downloads):

> Note: Ubuntu/Debian users might want to install the dkms package to ensure that the VirtualBox host kernel modules (vboxdrv, vboxnetflt and vboxnetadp) are properly updated if the linux kernel version changes during the next apt-get upgrade.

This seems faster and easier than programmaticaly finding out if  the drivers need to be rebuild for the current kernel.

**Comment by jeffesquivels** [comment]
Well, I just realized a had a pending update on my machine that included a new kernel, so I installed dkms before updating to test this one out with no luck, I still had to `sudo /etc/init.d/vboxdrv setup` before my VM could be started again (either manually from VB or with `kbox up`).

So it seems that manually testing for this condition before starting the VM will still be needed.

**Comment by pirog** [comment]
@jeffesquivels so by default i thnk DKMS is installed when you install VB but there seem to be some circumstances where this doesn't happen. 

What kind of conditions should we test for and where do you think we should test them?

**Comment by pirog** [comment]
So @jeffesquivels im in the middle of starting to boot up testing infrastructure and i think this can be broken into two issues

1. ensure DKMS is installed before VB is installed
2. have some sort of mechanism to handle recompiling kernels 

do you think that sounds about right?

**Comment by pirog** [comment]
Ok so i got the DKMS part of this resolved. Going to open a ticket for that part of this and then rename this one to reflect its just for the `sudo /etc/init.d/vboxdrv setup` part

**Comment by jeffesquivels** [comment]
@pirog I was reading /etc/init.d/vboxdrv and it seems this is the code it uses to determine if the modules are loaded (i.e. it's basically the code used when running `/etc/init.d/vboxdrv status`):

```
lsmod | grep -q "vboxdrv[^_-]"
```

I guess we could do this check somewhere before starting B2D, and either tell the user to run `sudo /etc/init.d/vboxdrv setup` or directly run it in case it fails.

**Comment by pirog** [comment]
@jeffesquivels that sounds good to me. We have a utility method to kick off an "admin" commmand (sudo in this case) so i would be fine just running the command for the user and telling them what is going on.

Do you know if `lsmod` works on fedora as well now that we support that?

**Comment by jeffesquivels** [comment]
@pirog great to hear Fedora is supported now too. I think lsmod is a pretty standard tool, haven't found official doc about it, but they used it in [this article](http://basiclinuxcommand.com/system-device/check-device-driver-module-loaded-linux-fedora-using-lsmod.html) to do the job.

What I'm not sure about is if the module name is still the same, I'll try to find out.

I agree on running the command directly if possible as long as the user is informed (because it can take a long time to compile everything).

**Comment by pirog** [comment]
Good to know. i know the vboxdrv command is different in fedora, and i think different in fedora > 21 a well.

**Comment by labboy0276** [comment]
FYI,
My kernel just updated and this werks now in 0.10.6, woot!

It does this:

```
john@kalamuna:~/kalabox/apps/huddle$ kbox start
info: BOOT2DOCKER =>  Starting up. maxRetries=3, max=3
info: BOOT2DOCKER =>  Initializing boot2docker [1].
info: Sharing folders [1].
info: BOOT2DOCKER =>  Bringing boot2docker up [1].
info: BOOT2DOCKER =>  VirtualBox's kernel modules seem to be down. Trying to bring them up. VError: Error running command "/home/john/.kalabox/bin/boot2docker,--sshkey="/home/john/.ssh/boot2docker.kalabox.id_rsa" --retries=50,up".: code: 1, msg: 
  WARNING: The 'boot2docker' command line interface is officially deprecated.

  Please switch to Docker Machine (https://docs.docker.com/machine/) ASAP.

  Docker Toolbox (https://docker.com/toolbox) is the recommended install method.

error in run: Failed to start machine "Kalabox2": exit status 1

    at /usr/local/bin/node_modules/kalabox-engine-docker/provider/lib/bin.js.jx:94:13
From previous event:
    at Object.sh (/usr/local/bin/node_modules/kalabox-engine-docker/provider/lib/bin.js.jx:92:11)
    at shProvider (/usr/local/bin/node_modules/kalabox-engine-docker/provider/b2d.js.jx:70:16)
    at /usr/local/bin/node_modules/kalabox-engine-docker/provider/b2d.js.jx:169:14
    at /usr/local/bin/node_modules/kalabox-engine-docker/node_modules/retry-bluebird/retry-bluebird.js.jx:28:14
    at rec (/usr/local/bin/node_modules/kalabox-engine-docker/node_modules/retry-bluebird/retry-bluebird.js.jx:27:23)
    at module.exports (/usr/local/bin/node_modules/kalabox-engine-docker/node_modules/retry-bluebird/retry-bluebird.js.jx:47:10)
    at _up (/usr/local/bin/node_modules/kalabox-engine-docker/provider/b2d.js.jx:163:12)
    at /usr/local/bin/node_modules/kalabox-engine-docker/provider/b2d.js.jx:269:14
From previous event:
    at Object.up (/usr/local/bin/node_modules/kalabox-engine-docker/provider/b2d.js.jx:268:6)
From previous event:
    at /usr/local/bin/lib/engine.js.jx:160:31
From previous event:
    at exports.up (/usr/local/bin/lib/engine.js.jx:159:4)
    at /usr/local/bin/lib/engine.js.jx:192:16
From previous event:
    at verifyProviderUp (/usr/local/bin/lib/engine.js.jx:188:6)
From previous event:
    at verifyProviderIsReady (/usr/local/bin/lib/engine.js.jx:226:4)
    at Object.exports.isRunning.exports.isContainerRunning (/usr/local/bin/lib/engine.js.jx:347:10)
    at /usr/local/bin/node_modules/kalabox-services-kalabox/kalabox.js.jx:67:26
From previous event:
    at isServiceRunning (/usr/local/bin/node_modules/kalabox-services-kalabox/kalabox.js.jx:66:6)
    at serviceInfo.then.filter.concurrency (/usr/local/bin/node_modules/kalabox-services-kalabox/kalabox.js.jx:386:14)
From previous event:
    at Object.verify (/usr/local/bin/node_modules/kalabox-services-kalabox/kalabox.js.jx:385:6)
From previous event:
    at Object.exports.verify (/usr/local/bin/lib/services.js.jx:89:29)
    at Object.exports.start (/usr/local/bin/lib/app.js.jx:735:19)
    at Object.task.func (/usr/local/bin/plugins/kalabox-core/tasks/start.js.jx:24:18)
    at Object.exports.run (/usr/local/bin/lib/core/tasks.js.jx:876:15)
    at processTask (/usr/local/bin/bin/kbox.js.jx:170:16)
    at Object.<anonymous> (/usr/local/bin/bin/kbox.js.jx:233:12)
    at process._tickCallback (node.js:812:13)
From previous event:
    at main (/usr/local/bin/bin/kbox.js.jx:232:4)
    at Object.<anonymous> (/usr/local/bin/bin/kbox.js.jx:241:1)
    at Module._compile (module.js:518:26)
    at readX (module.js:1284:5)
    at Object.Module._extensions..jx (module.js:1711:10)
    at Module.load (module.js:345:36)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:377:17)
    at require (module.js:395:17)
    at Object.<anonymous> (_jx_source:17:3)
    at Module._compile (module.js:518:26)
    at Module.load (module.js:353:12)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:733:12)
    at startup (node.js:371:18)
    at node.js:1464:3
[sudo] password for john: 
info: BOOT2DOCKER =>  Bringing boot2docker up [2].
info: BOOT2DOCKER =>  Boot2docker is up.
```

etc etc etc

**Comment by pirog** [comment]
very nice!!!!

**Comment by jeffesquivels** [comment]
¡Ajúa! :)

**Comment by labboy0276** [comment]
Hello!

This issue is back in 0.11.x in some shape or form.  I updated my laptop this AM and it had a kernel update in it, the error is a little different, but still the same result.  I am also only on the VB that Kalabox installs, I did not install it myself, etc etc etc.  Here is thy error with what I did below this fun error print out:

```
john@kalamuna:~/kalabox/apps/k2m$ kbox start
info: DOCKER-MACHINE =>  Starting "Kalabox2"...
info: DOCKER-MACHINE =>  (Kalabox2) Creating a new host-only adapter produced an error: /usr/bin/VBoxManage hostonlyif create failed:
info: DOCKER-MACHINE =>  (Kalabox2) 0%...
(Kalabox2) Progress state: NS_ERROR_FAILURE
(Kalabox2) VBoxManage: error: Failed to create the host-only adapter
(Kalabox2) VBoxManage: error: VBoxNetAdpCtl: Error while adding new interface: failed to open /dev/vboxnetctl: No such file or directory
(Kalabox2) VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component HostNetworkInterfaceWrap, interface IHostNetworkInterface
(Kalabox2) VBoxManage: error: Context: "RTEXITCODE handleCreate(HandlerArg*)" at line 71 of file VBoxManageHostonly.cpp
(Kalabox2) 
(Kalabox2) This is a known VirtualBox bug. Let's try to recover anyway...
Error setting up host only network on machine start: Failed to find a new host-only adapter
info: DOCKER-MACHINE =>  Run exited with code: 1
info: DOCKER-MACHINE =>  Starting "Kalabox2"...
info: DOCKER-MACHINE =>  (Kalabox2) Creating a new host-only adapter produced an error: /usr/bin/VBoxManage hostonlyif create failed:
(Kalabox2) 0%...
(Kalabox2) Progress state: NS_ERROR_FAILURE
(Kalabox2) VBoxManage: error: Failed to create the host-only adapter
(Kalabox2) VBoxManage: error: VBoxNetAdpCtl: Error while adding new interface: failed to open /dev/vboxnetctl: No such file or directory
(Kalabox2) VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component HostNetworkInterfaceWrap, interface IHostNetworkInterface
(Kalabox2) VBoxManage: error: Context: "RTEXITCODE handleCreate(HandlerArg*)" at line 71 of file VBoxManageHostonly.cpp
(Kalabox2)
info: DOCKER-MACHINE =>  (Kalabox2) This is a known VirtualBox bug. Let's try to recover anyway...
Error setting up host only network on machine start: Failed to find a new host-only adapter
info: DOCKER-MACHINE =>  Run exited with code: 1
info: DOCKER-MACHINE =>  Starting "Kalabox2"...
info: DOCKER-MACHINE =>  (Kalabox2) Creating a new host-only adapter produced an error: /usr/bin/VBoxManage hostonlyif create failed:
info: DOCKER-MACHINE =>  (Kalabox2) 0%...
(Kalabox2) Progress state: NS_ERROR_FAILURE
(Kalabox2) VBoxManage: error: Failed to create the host-only adapter
(Kalabox2) VBoxManage: error: VBoxNetAdpCtl: Error while adding new interface: failed to open /dev/vboxnetctl: No such file or directory
(Kalabox2) VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component HostNetworkInterfaceWrap, interface IHostNetworkInterface
(Kalabox2) VBoxManage: error: Context: "RTEXITCODE handleCreate(HandlerArg*)" at line 71 of file VBoxManageHostonly.cpp
(Kalabox2) 
(Kalabox2) This is a known VirtualBox bug. Let's try to recover anyway...
Error setting up host only network on machine start: Failed to find a new host-only adapter
info: DOCKER-MACHINE =>  Run exited with code: 1
info: DOCKER-MACHINE =>  Starting "Kalabox2"...
info: DOCKER-MACHINE =>  (Kalabox2) Creating a new host-only adapter produced an error: /usr/bin/VBoxManage hostonlyif create failed:
info: DOCKER-MACHINE =>  (Kalabox2) 0%...
(Kalabox2) Progress state: NS_ERROR_FAILURE
(Kalabox2) VBoxManage: error: Failed to create the host-only adapter
(Kalabox2) VBoxManage: error: VBoxNetAdpCtl: Error while adding new interface: failed to open /dev/vboxnetctl: No such file or directory
(Kalabox2) VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component HostNetworkInterfaceWrap, interface IHostNetworkInterface
(Kalabox2) VBoxManage: error: Context: "RTEXITCODE handleCreate(HandlerArg*)" at line 71 of file VBoxManageHostonly.cpp
(Kalabox2) 
(Kalabox2) This is a known VirtualBox bug. Let's try to recover anyway...
Error setting up host only network on machine start: Failed to find a new host-only adapter
info: DOCKER-MACHINE =>  Run exited with code: 1
info: DOCKER-MACHINE =>  Starting "Kalabox2"...
info: DOCKER-MACHINE =>  (Kalabox2) Creating a new host-only adapter produced an error: /usr/bin/VBoxManage hostonlyif create failed:
info: DOCKER-MACHINE =>  (Kalabox2) 0%...
(Kalabox2) Progress state: NS_ERROR_FAILURE
(Kalabox2) VBoxManage: error: Failed to create the host-only adapter
(Kalabox2) VBoxManage: error: VBoxNetAdpCtl: Error while adding new interface: failed to open /dev/vboxnetctl: No such file or directory
(Kalabox2) VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component HostNetworkInterfaceWrap, interface IHostNetworkInterface
(Kalabox2) VBoxManage: error: Context: "RTEXITCODE handleCreate(HandlerArg*)" at line 71 of file VBoxManageHostonly.cpp
(Kalabox2) 
(Kalabox2) This is a known VirtualBox bug. Let's try to recover anyway...
Error setting up host only network on machine start: Failed to find a new host-only adapter
info: DOCKER-MACHINE =>  Run exited with code: 1
Unhandled rejection VError: Error bringing machine up.: Failed after 5 retries. {"max":5,"backoff":500}: : code1err:more:Starting "Kalabox2"...
(Kalabox2) Creating a new host-only adapter produced an error: /usr/bin/VBoxManage hostonlyif create failed:
(Kalabox2) 0%...
(Kalabox2) Progress state: NS_ERROR_FAILURE
(Kalabox2) VBoxManage: error: Failed to create the host-only adapter
(Kalabox2) VBoxManage: error: VBoxNetAdpCtl: Error while adding new interface: failed to open /dev/vboxnetctl: No such file or directory
(Kalabox2) VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component HostNetworkInterfaceWrap, interface IHostNetworkInterface
(Kalabox2) VBoxManage: error: Context: "RTEXITCODE handleCreate(HandlerArg*)" at line 71 of file VBoxManageHostonly.cpp
(Kalabox2) 
(Kalabox2) This is a known VirtualBox bug. Let's try to recover anyway...

    at /usr/local/bin/plugins/kalabox-engine-docker/provider/docker/machine.js.jx:140:13
From previous event:
    at _up (/usr/local/bin/plugins/kalabox-engine-docker/provider/docker/machine.js.jx:139:11)
    at /usr/local/bin/plugins/kalabox-engine-docker/provider/docker/machine.js.jx:164:14
From previous event:
    at Object.up (/usr/local/bin/plugins/kalabox-engine-docker/provider/docker/machine.js.jx:163:6)
From previous event:
    at /usr/local/bin/lib/engine.js.jx:136:31
From previous event:
    at exports.up (/usr/local/bin/lib/engine.js.jx:135:4)
    at /usr/local/bin/lib/engine.js.jx:172:16
From previous event:
    at verifyProviderUp (/usr/local/bin/lib/engine.js.jx:168:6)
From previous event:
    at verifyProviderIsReady (/usr/local/bin/lib/engine.js.jx:206:4)
    at Object.exports.list (/usr/local/bin/lib/engine.js.jx:329:10)
    at /usr/local/bin/lib/app.js.jx:302:34
From previous event:
    at exports.cleanup (/usr/local/bin/lib/app.js.jx:301:4)
    at /usr/local/bin/lib/app.js.jx:344:12
From previous event:
    at Object.exports.start (/usr/local/bin/lib/app.js.jx:343:4)
    at Object.task.func (/usr/local/bin/plugins/kalabox-core/lib/tasks/start.js.jx:24:25)
    at Object.exports.run (/usr/local/bin/lib/core/tasks.js.jx:884:15)
    at processTask (/usr/local/bin/bin/kbox.js.jx:168:16)
    at Object.<anonymous> (/usr/local/bin/bin/kbox.js.jx:231:12)
    at process._tickCallback (node.js:803:1)
From previous event:
    at main (/usr/local/bin/bin/kbox.js.jx:230:4)
    at Object.<anonymous> (/usr/local/bin/bin/kbox.js.jx:239:1)
    at Module._compile (module.js:595:24)
    at readX (module.js:1488:3)
    at Object.Module._extensions..jx (module.js:1921:8)
    at Module.load (module.js:416:30)
    at Function.Module._load (module.js:380:8)
    at Module.require (module.js:451:15)
    at require (module.js:469:13)
    at Object.<anonymous> (_jx_source:17:1)
    at Module._compile (module.js:595:24)
    at Module.load (module.js:425:6)
    at Function.Module._load (module.js:380:8)
    at Function.Module.runMain (module.js:813:8)
    at startup (node.js:374:8)
    at node.js:1461:1
```

So per usual marching orders I ran:

```
john@kalamuna:~/kalabox/apps/k2m$ sudo /etc/init.d/vboxdrv setup
[sudo] password for john: 
Sorry, try again.
[sudo] password for john: 
Stopping VirtualBox kernel modules ...done.
Uninstalling old VirtualBox DKMS kernel modulesError! Could not locate dkms.conf file.
File:  does not exist.
 ...done.
Trying to register the VirtualBox kernel modules using DKMSError! DKMS tree already contains: vboxhost-5.0.14
You cannot add the same module/version combo more than once.
 ...failed!
  (Failed, trying without DKMS)
Recompiling VirtualBox kernel modules ...done.
Starting VirtualBox kernel modules ...done.
```

After that, the box is happy again.

Thoughts?

**Comment by jeffesquivels** [comment]
@labboy0276 I'm guessing may be the way we detected the issue (and subsequently fired the command to fix it) is not working with this scenario.

Reading the error message it seems as if kalabox is detecting the problem as something else (because the failure is setting up the host-only adapter) which means it may go another route to try to fix the issue instead of the ```/etc/init.d/vboxdrv setup``` one.

Let me take a look at it and I'll let you know.

**Comment by pirog** [comment]
I've also seen this happen on Fedora. I also think @jeffesquivels is probably right here. 

Don't think we will be able to get this into 0.11.2 given GUI priority but seems like a good candidate for 0.11.3.

**Comment by pirog** [comment]
Going to move this into the 0.11.3 milestone. I think until this is resolved you need to do some extra wrangling to get fedora to work out of the box.

**Comment by pirog** [comment]
@jeffesquivels @labboy0276 

we are going to be releasing a native .deb package in 0.12.x to install kalabox which should def resolve this issue.
