### ISSUE TITLE
HTTP code is  500 which indicates error: server error - Invalid volume specification

### ISSUE THREAD

**Issue by angarsky** [kalabox/kalabox#652]
Hi!

Today I started with "kbox-win-amd64-v0.10.5-alpha5.exe" - it's much more better than previous versions. I managed to perform 'kbox update' succefully - it's perfect! Then I decided to create a pantheon instance - 'kbox create pantheon' and got an error. I get this error every times when I try to start pantheon instance - 'kbox angarsky-test restart':

```
Error dispatching event listeners [pre-start]: Error running ad hoc container wi
th kalabox/debian:stable.: HTTP code is 500 which indicates error: server error
- Invalid volume specification: G:/Kalabox/angarsky-test:/src:rw

VError: Error running ad hoc container with kalabox/debian:stable.: HTTP code is
 500 which indicates error: server error - Invalid volume specification: G:/Kala
box/angarsky-test:/src:rw

    at Object.dockerInstance.then.bind.then.then.then.catch.finally.self (G:\Kal
abox\node_modules\kalabox-engine-docker\docker.js.jx:735:13)
From previous event:
    at Object.use (G:\Kalabox\node_modules\kalabox-engine-docker\docker.js.jx:73
4:11)
From previous event:
    at G:\Kalabox\lib\engine.js.jx:579:29
From previous event:
    at Object.exports.use (G:\Kalabox\lib\engine.js.jx:576:4)
    at G:\Kalabox\plugins\kalabox-syncthing\events.js.jx:119:25
From previous event:
    at G:\Kalabox\plugins\kalabox-syncthing\events.js.jx:95:10
    at G:\Kalabox\lib\core\events.js.jx:149:11
    at G:\Kalabox\lib\core\events.js.jx:148:24
From previous event:
    at G:\Kalabox\lib\core\events.js.jx:132:23
From previous event:
    at EventEngine._dispatch (G:\Kalabox\lib\core\events.js.jx:129:18)
    at G:\Kalabox\lib\core\events.js.jx:108:19
From previous event:
    at EventEngine.emit (G:\Kalabox\lib\core\events.js.jx:100:21)
From previous event:
    at Object.exports.emit (G:\Kalabox\lib\core\events.js.jx:232:4)
    at services.verify.then.then.then.then.map.concurrency (G:\Kalabox\lib\app.j
s.jx:726:24)
From previous event:
    at exports.start (G:\Kalabox\lib\app.js.jx:725:4)
    at G:\Kalabox\lib\app.js.jx:842:12
From previous event:
    at Object.exports.restart (G:\Kalabox\lib\app.js.jx:841:4)
    at Object.task.func (G:\Kalabox\plugins\kalabox-core\tasks\restart.js.jx:15:
18)
    at Object.exports.run (G:\Kalabox\lib\core\tasks.js.jx:876:15)
    at processTask (G:\Kalabox\bin\kbox.js.jx:173:16)
    at Object.<anonymous> (G:\Kalabox\bin\kbox.js.jx:236:12)
    at process._tickCallback (node.js:812:13)
From previous event:
    at main (G:\Kalabox\bin\kbox.js.jx:235:4)
    at Object.<anonymous> (G:\Kalabox\bin\kbox.js.jx:244:1)
    at Module._compile (module.js:518:26)
    at readX (module.js:1284:5)
    at Object.Module._extensions..jx (module.js:1711:10)
    at Module.load (module.js:345:36)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:377:17)
    at require (module.js:395:17)
    at Object.<anonymous> (_jx_source:17:3)
    at Module._compile (module.js:518:26)
    at Module.load (module.js:353:12)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:733:12)
    at startup (node.js:371:18)
    at node.js:1464:3
```

How can I fix it?

**Comment by pirog** [comment]
hey @angarsky, i think the issue here is that the app needs to live inside your home folder so i'd recommend putting it somewhere inside C:\Users\YOURNAME.

**Comment by angarsky** [comment]
@pirog thanks for idea! I will try to do it tomorrow and write about results.

**Comment by pirog** [comment]
Awesome! Def let us know if that resolves your issue

On Monday, November 2, 2015, angarsky <notifications@github.com> wrote:

> @pirog <https://github.com/pirog> thanks for idea! I will try to do it
> tomorrow and write about results.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/652#issuecomment-153093850>.
>


-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by angarsky** [comment]
It works!!! @pirog thanks for help and quick replies!

**Comment by pirog** [comment]
@angarsky awesome! going to close this out then.
