### ISSUE TITLE
"Out of Sync" message from Syncthing

### ISSUE THREAD

**Issue by escapesequence** [kalabox/kalabox#677]
When I go to 120.0.0.1:6008 I see alternate "Scanning" and "Out of Sync" messages.

I have high CPU(30s), memory(93%) and disk(99%) usage, which syncthing is seems to be mostly responsible for.

There are two syncthing processes, but only one of them seems to be in use.

Related? I can not get the site to show up in the browser (Note: it did at one point after first install).  I wonder if it is related to the dns problems but I have tried halting and restarting the VirtualBox VM, "kbox restart", and "kbox down" / "kbox up".  I am almost ready to "kbox destroy" and start over.

**Comment by escapesequence** [comment]
This is Win8.1.
I have 4G RAM on this laptop.

FYI: After doing a "kbox stop", CPU falls to 6%, memory to 71%, and disk to 2%!!!

**Comment by escapesequence** [comment]
Questions:
1) What is the difference between "kbox destroy" and "kbox uninstall"?? (I think I will need to start over - I might have done something to get make the files out of sync.)

2) after the "kbox destroy" I can do "kbox create pantheon" again?? Anything I need to know before I go down that path?

3) I saw a mention of hosts file wrt dns problems, what can I put in my hosts file that would fix dns (for example, I can't use http, I have to use https)?

**Comment by escapesequence** [comment]
I haven't done anything with this for a day.  Spent some time reading past issues related to "kbox destroy".

Did a "kbox apps" - preliminary to my planned destroy - and I got this unpleasantness:
info: BOOT2DOCKER => Starting up. maxRetries=3, max=3
info: BOOT2DOCKER => Initializing boot2docer [1].
info: BOOT2DOCKER => Bringing boot2docker up [1].
info: BOOT2DOCKER => Boot2docker is up.
Kalabox engine has been activated.
Error querying docker for list of containers.: connect ETIMEDOUT
Error: connect ETMEDOUT
    at errnoException (net.js:837:11)
    at Object.afterConnect [as oncomplete] (net.js:829:19)

**Comment by escapesequence** [comment]
"kbox config" looks normal, so I did another "kbox apps" and it was fine.

It appears the the query for apps timesout while kbox is brought back to life.

**Comment by escapesequence** [comment]
I went ahead with the "kbox destroy".  Looks good until the last 2 lines:
<b>EBUSY. unlink 'C:\Users\John\Desktop\testsite44'
Error EBUSY, unlink 'C:\Users\John\Desktop\testsite44'</b>

**Comment by escapesequence** [comment]
"kbox apps" now returns
<b>"testsite44": {
"running": 0,
"total": 0</b>      <==== was 4
but the testsite44 directory and contents are still there.

I assume that the 'EBUSY, unlink' error was just informing me that the directory could not be removed - probably rb/c I have files open in an editor (doh!).  I tried to delete the directory manually, and sure enough, I can't b/c there are files open in another program.

So I removed the directory from my code editor and tried the "kbox destroy" again. Same error.

I did a "kbox config" and I still see references to my app (testsite44)!!
Under appComponents, image, appName and more.

I had syncthing in a browser window.  I restarted it and closed the window. Still same error.

I did a "kbox stop" then "kbox destroy". Same error.

Now I will reboot and try again (stay tuned...)

**Comment by escapesequence** [comment]
OMG

When preparing to restart my computer I did a "kbox stop".

I can delete the directory when kbox is stopped(!)  Something in kalabox is preventing the directory from being deleted? and that prevents the destroy?

I tried shutting down syncthing (there is a commend to do that in the browser window) but that didn't help (PS there are still two syncthing.exe processes but no activity).

QUESTION: What is "kbox uninstall"?  (I've seen references to that in prior issues).  Should I / Do I have to do that?

Right now, I'm at an impasse.  I will do a "kbox create pantheon" with another site in the meantime.

**Comment by escapesequence** [comment]
Thought: should I try "kbox rebuild" then "kbox destroy"?

**Comment by escapesequence** [comment]
I decided to do a rebuild as I'd rather reinstall than leave this app hanging around.

The re-build failed.  I guess because the earlier "kbox destroy" actually destroyed something.

<b>Error dispatching event listeners [pre-start]: Error running ad hoc container with kalabox/debian:stable.: HTTP code is 404 which indicated error: no such container - no such id: kb_testsite44_data

I will now uninstall kalabox and start fresh.

**Comment by escapesequence** [comment]
FYI once again some variability in uninstall.  The key files in the .ssh directory were not deleted.  I know the uninstall script is supposed to delete these.

**Comment by escapesequence** [comment]
Huzzah! Victory!
BOOMSHAKALAKA!
HOLLA!!!!!!

What I did differently (to get past the TIMEDOUT Error on pulling Syncthing):
1) I got a message about running "kbox update" after I did the rebuild.  So I ran "kbox update" for the heck of it.  Not sure that it did anything significant.

2) I noticed that the IP 10.13.37.1 was still showing up when I do a "netstat -an" so I decided to uninstall the VirtualBox Host-Only Network Adapter.

3) I didn't just restart, I shutdown the computer, then rebooted.

**Comment by escapesequence** [comment]
After the successful install, I did a "kbox start".  Then I looked at the Syncthing page in my browser(127.0.0.1:60008).  <b>It again shows that the testsite44 folder is out of sync!!!!</b>

I haven't yet done anything! Also CPU and memory use is very high.

**Comment by escapesequence** [comment]
<b>SUMMARY</b>
1) Sometimes uninstall doesn't remove the files under .ssh
<i>Suggestion: check that they have been deleted - if the haven't write a message to the screen</i>

2) The VB HO adapter probably has to be uninstalled before re-installing Kalabox
<i>Suggestion: update message to the screen</i>
The current message says that uninstalling VB is an option.  Those (like me) that use VB for other things, will NOT uninstall VB but they should uninstall the VB HO Adapter associated with Kalabox

3) There is a problem with Syncthing "out of the box".
<i>Shouldn't an app be in sync when started fresh???</i>
And Syncthing seems to be thrashing - it never gets 'in synch', I just keep getting the "Out of Sync" message.

**Comment by escapesequence** [comment]
Errata:
1) I've seen "kbox install" and "kbox uninstall" in the issues.  How do these commands differ from start/stop?  Why are they are not listed when I do a "kbox -h"?

2) I have a problem when using http://myapp.kbox.  I've seen that at least one other person had a problem with that also.  The solution is to update the hosts file.  There should be a note of this in the wiki.

**Comment by escapesequence** [comment]
Additional info:

1) Syncthing tells me that 124MB are in sych.  The files (and sizes) that it says are out of synch are:
 Del          icon 	128 B
Sync 	icon-apps-active.png 	249 B
Sync 	icon-apps.png 	372 B
Sync 	icon-panopoly-active.png 	1.65 KiB
Sync 	icon-panopoly.png 	1.46 KiB
Del 	        icon 	128 B
Sync 	icon-apps-active.png 	249 B
Sync 	icon-apps.png 	372 B
Sync 	icon-panopoly-active.png 	1.65 KiB
Sync 	icon-panopoly.png 	1.46 KiB
Note: this list appears to repeat.  Not sure why.

2) Doing a search for "10.13.37.42" in the issues, I noticed this in issue #641:
To connect the Docker client to the Docker daemon, please set:
    export DOCKER_HOST=tcp://10.13.37.42:2375
    unset DOCKER_CERT_PATH
    unset DOCKER_TLS_VERIFY

My entry in hosts is: "10.13.37.42 testsite44.kbox".  I wonder if the proper thing is to set DOCKER_HOST and if the failure to do so is what has Syncthing upset???

Also: does the port (2375, above) vary from install to install?  My 10.13.37.42 uses port 2200.

**Comment by pirog** [comment]
@escapesequence so there is obviously of lot of content in this issue. im going to go through it and try to address each of your concerns as best as possible in an itemized fashion. please standby.

**Comment by pirog** [comment]
### Syncthing concerns

1. High syncthing CPU/memory usage is a known issue on the syncthing side of things. I would def check the issue queue over there. We update syncthing as new releases come out. If you have lower mem/cpu and/or an older computer this might be too much. 

3. Based on the error reports we are getting in sycnthing does generally work "out of the box". Some "out of sync" messages or warnings are ok esp if they are just static assets. If you have out of sync code files then that is an issue.

### Kbox commands

1. AFAIK `kbox uninstall` doesn't exist anymore. Kbox `destroy` should remove all the containers supporting your app plus the files and code inside of that app. We have an `uninstall` method behind the scenes which just destroys the containers but keeps the code and config. Destroy is meant to be run on any app built using `kbox create`. 

2. Kbox `install` and `uninstall` were removed in a previous version so that is why they dont show up for you. Start will start all the containers needed to run your app, put in a reverse proxy entry for you to access your site at site.kbox and set up syncthing to share your code between the container and your host machine. Stop will reverse all of that.

### Uninstall concerns

1. I think removing the Host Only Adapter is not a bad idea. This also is somewhat addressed over at #630 

2. What SSH keys is it not removing? It should only remove the kalabox boot2docker ones. 

### Dns concerns

1. You will not want to be using your host file for anything. That will likely mess stuff up. We are using DNSMASQ to handle all .kbox domains. All of this works via the Virtualbox Host Only Adapter that is set up for Kalabox2. 

2 You will also not want to set DOCKER_HOST manually. We set those env vars up when we run kbox commands for you. The port should not vary from install to install. Port 2200 is for ssh forwarding. 2375 is for the docker daemon. 

3. If you cannot reach your site at site.kbox you will want to make sure you have run `kbox start` on your app and that your VB Host Only Adapter is working correctly. **YOU DEFINITELY SHOULD NOT EDIT YOUR HOSTS FILE.**

There are also some open issues to address a couple issue you are having.

1. Timed out on kbox up and then kbox start #680 
2. UNLINK errors on kbox destroy #684 

I hope these things generally help

**Comment by escapesequence** [comment]
1) <b>ssh</b>
Maybe it is leaving the pantheon files.  Often when I have done uninstall-win32, there are 2 files left. I though that there were only 2 files placed in .ssh - but now that I think of it, it may be that I was reinstalling after an incomplete "kbox create pantheon".

2) <b>hosts file</b>
<b><i>I doubled checked: when I don't have an entry in the hosts file, my browser directs me to my ISP site not found page.</b></i>

3) <b>Syncthing</b>
The assets <i>are</i> static.  There are only 5 (repeated twice, for some reason). As you probably know, Syncthing v0.12.2 is now out.

The PC I using right now is a 2-year old laptom running Win8.1 with 4G memory.  Kalabox+Atom+Firefox  runs fine.  Just a bit slower than I would like - and I think Syncthing is a big reason for that.  I will be working with a more powerful computer soon.

Thanks for your help.  And thanks for Kalabox.

**Comment by escapesequence** [comment]
<i>Syncthing</i>

1) Thrashing
 I reduced RAM used by my VirtualBox Kalambox VM by 256K and changed the sync interval from 2s to 5s (on both local and VM).

2) Out of Sync
I traced the 15 files to panopoly, radix base, and radix subtheme icons.  I tried to change .stignore but with no luck so far.  Will try again as I learn more.

**Comment by escapesequence** [comment]
Closing this and opening #696 (hosts issue) and #697 (Syncthing not retaining changes).
