### ISSUE TITLE
Error getting docker config on some commands

### ISSUE THREAD

**Issue by labboy0276** [kalabox/kalabox#782]
Hello

On some commands (rebuild, stop), I am getting an odd error:

```
info: DOCKER =>  Container already stopped. 4a458fdf04deda48c3054f2cb56eda72388e120980a32a6516ddba64a935b623
Error dispatching event listeners [post-stop]: Error inspecting container: kb_cor777_appserver.: Error initializing docker.: Error getting docker config.: Error running command "ssh,-o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -p 2022 -i "/home/john/.ssh/boot2docker.kalabox.id_rsa" docker@localhost,sudo ifconfig eth1 10.13.37.42 netmask 255.255.255.0 broadcast 10.13.37.255 up".: code: 255, msg: 
VError: Error inspecting container: kb_cor777_appserver.: Error initializing docker.: Error getting docker config.: Error running command "ssh,-o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -p 2022 -i "/home/john/.ssh/boot2docker.kalabox.id_rsa" docker@localhost,sudo ifconfig eth1 10.13.37.42 netmask 255.255.255.0 broadcast 10.13.37.255 up".: code: 255, msg: 
    at /usr/local/bin/node_modules/kalabox-engine-docker/docker.js.jx:290:13
From previous event:
    at Object.inspect (/usr/local/bin/node_modules/kalabox-engine-docker/docker.js.jx:289:11)
From previous event:
    at /usr/local/bin/lib/engine.js.jx:422:29
From previous event:
    at Object.exports.inspect (/usr/local/bin/lib/engine.js.jx:421:4)
    at engine.list.map.concurrency (/usr/local/bin/lib/share.js.jx:33:19)
From previous event:
    at isAppRunning (/usr/local/bin/lib/share.js.jx:32:4)
    at /usr/local/bin/lib/share.js.jx:152:14
From previous event:
    at getDataContainers (/usr/local/bin/lib/share.js.jx:143:4)
    at getVolumes (/usr/local/bin/lib/share.js.jx:193:10)
    at Object.exports.restart (/usr/local/bin/lib/share.js.jx:416:17)
    at Object.fn (/usr/local/bin/plugins/kalabox-syncthing/events.js.jx:130:15)
    at /usr/local/bin/lib/core/events.js.jx:178:14
    at /usr/local/bin/lib/core/events.js.jx:177:24
From previous event:
    at /usr/local/bin/lib/core/events.js.jx:161:23
From previous event:
    at EventEngine._dispatch (/usr/local/bin/lib/core/events.js.jx:158:18)
    at /usr/local/bin/lib/core/events.js.jx:137:19
From previous event:
    at EventEngine.emit (/usr/local/bin/lib/core/events.js.jx:129:21)
From previous event:
    at Object.exports.emit (/usr/local/bin/lib/core/events.js.jx:261:4)
    at /usr/local/bin/lib/app.js.jx:833:24
From previous event:
    at exports.stop (/usr/local/bin/lib/app.js.jx:832:4)
    at Object.exports.rebuild (/usr/local/bin/lib/app.js.jx:982:10)
    at Object.task.func (/usr/local/bin/plugins/kalabox-core/tasks/rebuild.js.jx:20:18)
    at Object.exports.run (/usr/local/bin/lib/core/tasks.js.jx:876:15)
    at processTask (/usr/local/bin/bin/kbox.js.jx:170:16)
    at Object.<anonymous> (/usr/local/bin/bin/kbox.js.jx:233:12)
    at process._tickCallback (node.js:812:13)
From previous event:
    at main (/usr/local/bin/bin/kbox.js.jx:232:4)
    at Object.<anonymous> (/usr/local/bin/bin/kbox.js.jx:241:1)
    at Module._compile (module.js:518:26)
    at readX (module.js:1284:5)
    at Object.Module._extensions..jx (module.js:1711:10)
    at Module.load (module.js:345:36)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:377:17)
    at require (module.js:395:17)
    at Object.<anonymous> (_jx_source:17:3)
    at Module._compile (module.js:518:26)
    at Module.load (module.js:353:12)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:733:12)
    at startup (node.js:371:18)
    at node.js:1464:3
```

My kbox as about 9 sites in it btw at this point.  I will delete some to see if it goes away.

**Comment by pirog** [comment]
@labboy0276 any update on this issue after you removed some sites?

i know there is an issue for alpha7 regarding loading the engine config that might end up resolving this

**Comment by labboy0276** [comment]
I just purged and started over and everything is ok for now.  I am not 100% sure if it was me messing with the containers for all the drush shizzy that busted it.  I will close this out since there is another issue and will re-open if it gets sad again,

**Comment by pirog** [comment]
Sweet! Sounds like a good plan.
