### ISSUE TITLE
node_module folder has disappeared

### ISSUE THREAD

**Issue by qcutter** [kalabox/kalabox#813]
Im running Kalabox on OSX. I had a problem with my pantheon environment that forced me to remove my app and try to recreate my local env. After running kbox destroy, cleaning things up, removing ~/.kalabox, Re created the env. everything is fine until i try to start my kalabox engine. Every complaint is from items not being available in the usr/local/bin/node_module folder. When I check the entire folder is gone. How do I get this folder and its items back?

**Comment by pirog** [comment]
SO `kbox destroy` will only remove the app, you dont need to uninstall kalabox completely. Removing `~/.kalabox` without doing an actual uninstall is going to cause issues. 

I think your best bet is to grab and run one of the uninstall scripts and start over. There should not be a /usr/local/bin/node_modules unless you specifically install node_modules there for some reason. 

Are you installing with the binary or doing the dev install?

**Comment by qcutter** [comment]
Yes, Im running the 10.6.alpha6 binary for OSX, I did a complete reinstall using the units script. Re downloaded the binary and ran it, still no node_module directory in usr/local/bin

**Comment by pirog** [comment]
there should not be a node_module directory there

**Comment by qcutter** [comment]
So I have done a complete install and the box push is still failing. here is the complete error with some identifying thing obfuscated by me:

#####
info: DOCKER =>  Removing ad hoc container. 84ba22ce444c0e4ba40e54b2f1fb7b37dfa7e836a99d5414a3b5f2f36a368806

Error running ad hoc container with kalabox/terminus:t0.9.3.: Non-zero exit code: 1 {"date":"2015-12-16 20:06:58","level":"ERROR","message":"There is no such field."}

Error: Non-zero exit code: 1 {"date":"2015-12-16 20:06:58","level":"ERROR","message":"There is no such field."}

    at /usr/local/bin/node_modules/kalabox-engine-docker/docker.js.jx:609:28
From previous event:
    at Object.result.wait (/usr/local/bin/node_modules/kalabox-engine-docker/docker.js.jx:569:20)
    at /usr/local/bin/node_modules/kalabox-engine-docker/docker.js.jx:678:18
From previous event:
    at Object.queryData (/usr/local/bin/node_modules/kalabox-engine-docker/docker.js.jx:676:6)
From previous event:
    at /usr/local/bin/lib/engine.js.jx:682:29
From previous event:
    at Object.exports.queryData (/usr/local/bin/lib/engine.js.jx:681:4)
    at queryFunc (/Users/myuserdir/pantheon/mypantheondir/plugins/kalabox-plugin-pantheon/lib/terminus.js:107:31)
From previous event:
    at Object.dockerInstance.then.bind.then.then.then.catch.finally.self (/usr/local/bin/node_modules/kalabox-engine-docker/docker.js.jx:754:25)
From previous event:
    at Object.use (/usr/local/bin/node_modules/kalabox-engine-docker/docker.js.jx:753:6)
From previous event:
    at /usr/local/bin/lib/engine.js.jx:583:29
From previous event:
    at Object.exports.use (/usr/local/bin/lib/engine.js.jx:580:4)
    at /Users/myuserdir/pantheon/mypantheondir/plugins/kalabox-plugin-pantheon/lib/terminus.js:110:29
From previous event:
    at Terminus.__request (/Users/myuserdir/pantheon/mypantheondir/plugins/kalabox-plugin-pantheon/lib/terminus.js:103:4)
    at Terminus.getConnectionMode (/Users/myuserdir/pantheon/mypantheondir/plugins/kalabox-plugin-pantheon/lib/terminus.js:216:15)
    at Object.pushCode (/Users/myuserdir/pantheon/mypantheondir/plugins/kalabox-plugin-pantheon/lib/push.js:42:21)
    at /Users/myuserdir/pantheon/mypantheondir/plugins/kalabox-plugin-pantheon/lib/tasks.js:515:27
    at process._tickCallback (node.js:803:1)
From previous event:
    at null.completed (/Users/myuserdir/pantheon/mypantheondir/plugins/kalabox-plugin-pantheon/lib/tasks.js:514:12)
    at PromptUI.onCompletion (/Users/myuserdir/pantheon/mypantheondir/node_modules/inquirer/lib/ui/prompt.js:56:10)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (/Users/myuserdir/pantheon/mypantheondir/node_modules/rx-lite/rx.lite.js:1826:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/Users/myuserdir/pantheon/mypantheondir/node_modules/rx-lite/rx.lite.js:1763:14)
    at AnonymousObserver.tryCatcher (/Users/myuserdir/pantheon/mypantheondir/node_modules/rx-lite/rx.lite.js:537:29)
    at AutoDetachObserverPrototype.completed (/Users/myuserdir/pantheon/mypantheondir/node_modules/rx-lite/rx.lite.js:5435:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/Users/myuserdir/pantheon/mypantheondir/node_modules/rx-lite/rx.lite.js:1763:14)
    at InnerObserver.onCompleted (/Users/myuserdir/pantheon/mypantheondir/node_modules/rx-lite/rx.lite.js:2885:65)
    at InnerObserver.tryCatcher (/Users/myuserdir/pantheon/mypantheondir/node_modules/rx-lite/rx.lite.js:537:29)
    at AutoDetachObserverPrototype.completed (/Users/myuserdir/pantheon/mypantheondir/node_modules/rx-lite/rx.lite.js:5435:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/Users/myuserdir/pantheon/mypantheondir/node_modules/rx-lite/rx.lite.js:1763:14)
    at AutoDetachObserver.tryCatcher (/Users/myuserdir/pantheon/mypantheondir/node_modules/rx-lite/rx.lite.js:537:29)
    at AutoDetachObserverPrototype.completed (/Users/myuserdir/pantheon/mypantheondir/node_modules/rx-lite/rx.lite.js:5435:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/Users/myuserdir/pantheon/mypantheondir/node_modules/rx-lite/rx.lite.js:1763:14)
    at InnerObserver.onCompleted (/Users/myuserdir/pantheon/mypantheondir/node_modules/rx-lite/rx.lite.js:2885:65)
    at InnerObserver.tryCatcher (/Users/myuserdir/pantheon/mypantheondir/node_modules/rx-lite/rx.lite.js:537:29)
    at AutoDetachObserverPrototype.completed (/Users/myuserdir/pantheon/mypantheondir/node_modules/rx-lite/rx.lite.js:5435:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/Users/myuserdir/pantheon/mypantheondir/node_modules/rx-lite/rx.lite.js:1763:14)
    at AutoDetachObserver.tryCatcher (/Users/myuserdir/pantheon/mypantheondir/node_modules/rx-lite/rx.lite.js:537:29)
    at AutoDetachObserverPrototype.completed (/Users/myuserdir/pantheon/mypantheondir/node_modules/rx-lite/rx.lite.js:5435:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/Users/myuserdir/pantheon/mypantheondir/node_modules/rx-lite/rx.lite.js:1763:14)
    at /Users/myuserdir/pantheon/mypantheondir/node_modules/inquirer/lib/utils/utils.js:18:13
    at f (/Users/myuserdir/pantheon/mypantheondir/node_modules/once/once.js:17:25)
    at /Users/myuserdir/pantheon/mypantheondir/node_modules/inquirer/lib/ui/prompt.js:85:7
    at module.exports (/Users/myuserdir/pantheon/mypantheondir/node_modules/run-async/index.js:23:5)

**Comment by pirog** [comment]
Reopened https://github.com/kalabox/kalabox/issues/679 to handle this. going to close this as a duplicate.
