### ISSUE TITLE
Re-authorizing to Pantheon Failed

### ISSUE THREAD

**Issue by reynoldsalec** [kalabox/kalabox#821]
After starting up the GUI and selecting my existing Pantheon account from the sidebar menu, the GUI was unable to re-authenticate me to Pantheon.

**Full Error Message:**

```
info: BOOT2DOCKER =>  Starting up. maxRetries=3, max=3
info: BOOT2DOCKER =>  Initializing boot2docker [1].
info: BOOT2DOCKER =>  Bringing boot2docker up [1].
info: BOOT2DOCKER =>  Boot2docker is up.
[22118:0104/131633:INFO:CONSOLE(73)] ""Kalabox engine has been activated."", source: /Users/alec/workspace/kalabox-ui/node_modules/kalabox/node_modules/kalabox-engine-docker/lib/tasks.js (73)
[22118:0104/131700:INFO:CONSOLE(268)] ""Your Pantheon session has expired. We need to reauth!"", source: /Users/alec/workspace/kalabox-ui/node_modules/kalabox/node_modules/kalabox-app-pantheon/vendor/kalabox-app-pantheon/app/plugins/kalabox-plugin-pantheon/lib/client.js (268)
[22118:0104/131700:INFO:CONSOLE(27)] ""TypeError: Cannot read property 'substring' of undefined"", source: file:///Users/alec/workspace/kalabox-ui/generated/src/modules/kalabox/kalabox.js (27)
[22118:0104/131700:INFO:CONSOLE(28)] ""Error: TypeError: Cannot read property 'substring' of undefined\n    at Object.ensureErrorObject (file:///Users/alec/workspace/kalabox-ui/generated/src/lib/vendor/bluebird/js/browser/bluebird.js:4794:20)\n    at Promise._rejectUncheckedCheckError (file:///Users/alec/workspace/kalabox-ui/generated/src/lib/vendor/bluebird/js/browser/bluebird.js:2837:22)\n    at Promise._settlePromiseAt (/Users/alec/workspace/kalabox-ui/node_modules/kalabox/node_modules/bluebird/js/main/promise.js:579:21)\n    at Promise._settlePromises (/Users/alec/workspace/kalabox-ui/node_modules/kalabox/node_modules/bluebird/js/main/promise.js:697:14)\n    at Async._drainQueue (/Users/alec/workspace/kalabox-ui/node_modules/kalabox/node_modules/bluebird/js/main/async.js:123:16)\n    at Async._drainQueues (/Users/alec/workspace/kalabox-ui/node_modules/kalabox/node_modules/bluebird/js/main/async.js:133:10)\n    at Immediate.Async.drainQueues [as _onImmediate] (/Users/alec/workspace/kalabox-ui/node_modules/kalabox/node_modules/bluebird/js/main/async.js:15:14)\n    at processImmediate [as _immediateCallback] (timers.js:321:17)"", source: file:///Users/alec/workspace/kalabox-ui/generated/src/modules/kalabox/kalabox.js (28)
info: BOOT2DOCKER =>  Shutting down [1].
info: BOOT2DOCKER =>  Shutting down [1].
info: BOOT2DOCKER =>  Shut down successful.
[22118:0104/132304:INFO:CONSOLE(78)] ""Kalabox engine has been deactivated."", source: /Users/alec/workspace/kalabox-ui/node_modules/kalabox/node_modules/kalabox-engine-docker/lib/tasks.js (78)
info: BOOT2DOCKER =>  Shut down successful.
[22118:0104/132304:INFO:CONSOLE(78)] ""Kalabox engine has been deactivated."", source: /Users/alec/workspace/kalabox-ui/node_modules/kalabox/node_modules/kalabox-engine-docker/lib/tasks.js (78)
[22120:0104/132304:WARNING:channel.cc(553)] Failed to send message to ack remove remote endpoint (local ID 1, remote ID 1)
[22231:0104/132304:WARNING:channel.cc(553)] Failed to send message to ack remove remote endpoint (local ID 1, remote ID 1)
[22231:0104/132304:WARNING:channel.cc(320)] RawChannel write error
[22120:0104/132304:WARNING:channel.cc(320)] RawChannel write error

**Comment by pirog** [comment]
This should be resolved in the 0.11.0 release on Friday
