### ISSUE TITLE
Path mangled when building/rebuilding Pantheon site

### ISSUE THREAD

**Issue by dwoods** [kalabox/kalabox#880]
Using 0.11 on Ubuntu.

When I run 'kbox create pantheon', it throws an error, and running 'kbox rebuild' right after gives the same error.  It looks like the path to the code directory gets messed up somewere along the line.  

You can see the proper path to the project in the output below (/home/dwoods/work/sites/viu-international-2), vs.the path it tries to reference in the error message (/src/rk/sites/viu-international-2).  It looks like '/src/' gets put right in the middle of the  'work' part of the path.

Output of the rebuild:
```
info: COMPOSE =>  0=--project-name, 1=kalabox, 2=--file, 3=/home/dwoods/.kalabox/downloads/kalabox/kalabox-1.yml, 4=ps, 5=-q, 6=syncthing, 7=undefined
info: COMPOSE =>  0=--project-name, 1=viu-international-2, 2=--file, 3=/home/dwoods/work/sites/viu-international-2/kalabox-compose.yml, 4=--file, 5=/home/dwoods/work/sites/viu-international-2/kalabox-cli.yml, 6=stop, mode=collect
info: DOCKER-COMPOSE =>  Run exited with code: 0
info: COMPOSE =>  0=--project-name, 1=viu-international-2, 2=--file, 3=/home/dwoods/work/sites/viu-international-2/kalabox-compose.yml, 4=--file, 5=/home/dwoods/work/sites/viu-international-2/kalabox-cli.yml, 6=rm, 7=--force, 8=-v, 9=appserver, 10=db, 11=edge, 12=redis, 13=solr, 14=cli, 15=terminus, mode=collect
info: DOCKER-COMPOSE =>  No stopped containers
info: DOCKER-COMPOSE =>  Run exited with code: 0
info: COMPOSE =>  0=--project-name, 1=viu-international-2, 2=--file, 3=/home/dwoods/work/sites/viu-international-2/kalabox-compose.yml, 4=--file, 5=/home/dwoods/work/sites/viu-international-2/kalabox-cli.yml, 6=pull, mode=collect
Pulling redis (kalabox/pantheon-redis:v0.11.0)...
info: DOCKER-COMPOSE =>  v0.11.0: Pulling from kalabox/pantheon-redis
info: DOCKER-COMPOSE =>  Digest: sha256:d3e5eded0cea6fbf068a2fba29effc25adf10312b3be1a88b3bcc931b5813c37
Pulling data (busybox:latest)...
info: DOCKER-COMPOSE =>  Status: Downloaded newer image for kalabox/pantheon-redis:v0.11.0
info: DOCKER-COMPOSE =>  latest: Pulling from library/busybox
info: DOCKER-COMPOSE =>  Digest: sha256:c1bc9b4bffe665bf014a305cc6cf3bca0e6effeb69d681d7a208ce741dad58e0
Pulling db (kalabox/pantheon-mariadb:v0.11.0)...
info: DOCKER-COMPOSE =>  Status: Downloaded newer image for busybox:latest
info: DOCKER-COMPOSE =>  v0.11.0: Pulling from kalabox/pantheon-mariadb
info: DOCKER-COMPOSE =>  Digest: sha256:ea1bc1c30cd9785e5fb9ef19220754f13768a6e531cba3b2a6d8871d72da1fb1
Pulling cli (kalabox/cli:dev)...
info: DOCKER-COMPOSE =>  Status: Downloaded newer image for kalabox/pantheon-mariadb:v0.11.0
info: DOCKER-COMPOSE =>  dev: Pulling from kalabox/cli
info: DOCKER-COMPOSE =>  Digest: sha256:94d0ed2249430475ed682eb7cc3a349dfa8b0da1d0aca46d8308a8f59216e3c4
Pulling terminus (kalabox/terminus:v0.11.0)...
info: DOCKER-COMPOSE =>  Status: Downloaded newer image for kalabox/cli:dev
info: DOCKER-COMPOSE =>  v0.11.0: Pulling from kalabox/terminus
info: DOCKER-COMPOSE =>  Digest: sha256:e3c196f8c9f122df358df481974142e19bbc5945105fbb4f5bd4a5bea9ff4784
info: DOCKER-COMPOSE =>  Status: Downloaded newer image for kalabox/terminus:v0.11.0
Pulling solr (kalabox/pantheon-solr:v0.11.0)...
info: DOCKER-COMPOSE =>  v0.11.0: Pulling from kalabox/pantheon-solr
info: DOCKER-COMPOSE =>  Digest: sha256:c6b22f86eb221da16c0f42e824f1ab92d8847cb75f9d2d10fd3203fe21b81209
info: DOCKER-COMPOSE =>  Status: Downloaded newer image for kalabox/pantheon-solr:v0.11.0
Pulling appserver (kalabox/pantheon-appserver:v0.11.0)...
info: DOCKER-COMPOSE =>  v0.11.0: Pulling from kalabox/pantheon-appserver
info: DOCKER-COMPOSE =>  Digest: sha256:e75d4fc51616f9c7612ce0360a7ea85df758c1fbab9088cf9dd5da48b49f38bc
info: DOCKER-COMPOSE =>  Status: Downloaded newer image for kalabox/pantheon-appserver:v0.11.0
Pulling edge (kalabox/pantheon-edge:v0.11.0)...
info: DOCKER-COMPOSE =>  v0.11.0: Pulling from kalabox/pantheon-edge
info: DOCKER-COMPOSE =>  Digest: sha256:043d1d3ee80e4212aef97132b51c2c1c30433ab8db926757aa5695a98dd619a6
info: DOCKER-COMPOSE =>  Status: Downloaded newer image for kalabox/pantheon-edge:v0.11.0
info: DOCKER-COMPOSE =>  Run exited with code: 0
info: COMPOSE =>  0=--project-name, 1=viu-international-2, 2=--file, 3=/home/dwoods/work/sites/viu-international-2/kalabox-compose.yml, 4=--file, 5=/home/dwoods/work/sites/viu-international-2/kalabox-cli.yml, 6=build, mode=collect
redis uses an image, skipping
data uses an image, skipping
db uses an image, skipping
cli uses an image, skipping
terminus uses an image, skipping
solr uses an image, skipping
appserver uses an image, skipping
edge uses an image, skipping
info: DOCKER-COMPOSE =>  Run exited with code: 0
info: COMPOSE =>  0=--project-name, 1=kalabox, 2=--file, 3=/home/dwoods/.kalabox/downloads/kalabox/kalabox-2.yml, 4=ps, 5=-q, 6=syncthing, 7=undefined
info: COMPOSE =>  0=--project-name, 1=kalabox, 2=--file, 3=/home/dwoods/.kalabox/downloads/kalabox/kalabox-3.yml, 4=run, 5=--entrypoint, 6=/bin/mkdir, 7=--rm, 8=syncthing, 9=-p, 10=/code/viu-international-2, mode=false
info: COMPOSE =>  0=--project-name, 1=kalabox, 2=--file, 3=/home/dwoods/.kalabox/downloads/kalabox/kalabox-4.yml, 4=run, 5=--entrypoint, 6=touch, 7=--rm, 8=syncthing, 9=/code/viu-international-2/.stfolder, mode=false
info: COMPOSE =>  0=--project-name, 1=kalabox, 2=--file, 3=/home/dwoods/.kalabox/downloads/kalabox/kalabox-5.yml, 4=run, 5=--entrypoint, 6=/bin/cp, 7=--rm, 8=syncthing, 9=/src/rk/sites/viu-international-2/code/.stignore, 10=/code/viu-international-2/.stignore, mode=false
Error dispatching event listeners [pre-app-start]: code: 1err:cp: can't stat '/src/rk/sites/viu-international-2/code/.stignore': No such file or directory

VError: code: 1err:cp: can't stat '/src/rk/sites/viu-international-2/code/.stignore': No such file or directory

    at /usr/local/bin/lib/util/shell.js.jx:134:16
    at /usr/local/bin/node_modules/shelljs/src/exec.js.jx:106:7
    at ChildProcess.exithandler (child_process.js:669:1)
    at ChildProcess.emit (events.js:85:9)
    at maybeClose (child_process.js:773:12)
    at Process.ChildProcess._handle.onexit (child_process.js:839:1)
From previous event:
    at Object.exports.exec (/usr/local/bin/lib/util/shell.js.jx:131:10)
    at Object.sh (/usr/local/bin/plugins/kalabox-engine-docker/provider/docker/lib/bin.js.jx:99:20)
    at /usr/local/bin/plugins/kalabox-engine-docker/provider/docker/compose.js.jx:60:18
From previous event:
    at shCompose (/usr/local/bin/plugins/kalabox-engine-docker/provider/docker/compose.js.jx:42:6)
    at Object.run (/usr/local/bin/plugins/kalabox-engine-docker/provider/docker/compose.js.jx:341:12)
    at /usr/local/bin/plugins/kalabox-engine-docker/index.js.jx:260:24
    at arrayMap (/usr/local/bin/node_modules/lodash/index.js.jx:1405:25)
    at Function.map (/usr/local/bin/node_modules/lodash/index.js.jx:6709:14)
    at Object.run (/usr/local/bin/plugins/kalabox-engine-docker/index.js.jx:177:26)
From previous event:
    at /usr/local/bin/lib/engine.js.jx:471:29
From previous event:
    at Object.exports.run (/usr/local/bin/lib/engine.js.jx:470:4)
    at Promise.fromNode.then.then.then.then.then.then.kbox.engine.inspect.then.then.webService (/usr/local/bin/plugins/kalabox-syncthing/lib/events.js.jx:178:30)
From previous event:
    at Object.fn (/usr/local/bin/plugins/kalabox-syncthing/lib/events.js.jx:165:10)
    at /usr/local/bin/lib/core/events.js.jx:172:19
From previous event:
    at /usr/local/bin/lib/core/events.js.jx:161:23
From previous event:
    at EventEngine._dispatch (/usr/local/bin/lib/core/events.js.jx:158:18)
    at /usr/local/bin/lib/core/events.js.jx:137:19
From previous event:
    at EventEngine.emit (/usr/local/bin/lib/core/events.js.jx:129:21)
From previous event:
    at Object.exports.emit (/usr/local/bin/lib/core/events.js.jx:261:4)
    at /usr/local/bin/lib/app.js.jx:348:24
From previous event:
    at exports.start (/usr/local/bin/lib/app.js.jx:347:4)
    at /usr/local/bin/lib/app.js.jx:522:12
From previous event:
    at Object.exports.rebuild (/usr/local/bin/lib/app.js.jx:521:4)
    at Object.task.func (/usr/local/bin/plugins/kalabox-core/lib/tasks/rebuild.js.jx:15:18)
    at Object.exports.run (/usr/local/bin/lib/core/tasks.js.jx:879:15)
    at processTask (/usr/local/bin/bin/kbox.js.jx:168:16)
    at Object.<anonymous> (/usr/local/bin/bin/kbox.js.jx:231:12)
    at process._tickCallback (node.js:803:1)
From previous event:
    at main (/usr/local/bin/bin/kbox.js.jx:230:4)
    at Object.<anonymous> (/usr/local/bin/bin/kbox.js.jx:239:1)
    at Module._compile (module.js:595:24)
    at readX (module.js:1488:3)
    at Object.Module._extensions..jx (module.js:1921:8)
    at Module.load (module.js:416:30)
    at Function.Module._load (module.js:380:8)
    at Module.require (module.js:451:15)
    at require (module.js:469:13)
    at Object.<anonymous> (_jx_source:17:1)
    at Module._compile (module.js:595:24)
    at Module.load (module.js:425:6)
    at Function.Module._load (module.js:380:8)
    at Function.Module.runMain (module.js:813:8)
    at startup (node.js:374:8)
    at node.js:1461:1
```

**Comment by pirog** [comment]
@dwoods can you run `kbox config` inside your app directory and post the results here. 

might want to make sure you sanitize. looking specifically for the `home` and `syncthing.codeRoot` properties. 

/src/ is a path inside the container so that actually is correct however it looks like its trimming your path a little too much aka should be /src/work/... instead of /src/rk/ ... perhaps something weird because dwoods and work contain similar chars?

**Comment by pirog** [comment]
@dwoods would also try creating a site in a directory like /home/dwoods/apps and see what happens

**Comment by pirog** [comment]
Looks like we are just using _.trimLeft() like idiots.
https://github.com/lodash/lodash/issues/1367

I think we might want to split both paths and then take the union to find the correct src root.

**Comment by pirog** [comment]
Ok, we've got an open PR for this fix. Should get into the v0.11.1 release
https://github.com/kalabox/kalabox/pull/881

**Comment by dwoods** [comment]
Great, thanks so much!
