### ISSUE TITLE
Docker compose has problems dealing with, presumably, special characters

### ISSUE THREAD

**Issue by johnnypea** [kalabox/kalabox#886]
I created this issue already here https://github.com/kalabox/kalabox-app-pantheon/issues/81 but I was suggested by @pirog to post it here as well.

Looks like it has some problem with initializing "CLI" container...

```
Pulling cli (kalabox/cli:dev)...
info: DOCKER-COMPOSE =>  dev: Pulling from kalabox/cli
info: DOCKER-COMPOSE =>  Digest: sha256:a72a11b4e5fbb46c2533f31b0b9db1fa63291b91b6b0080423f41da06f16765c
info: DOCKER-COMPOSE =>  Status: Downloaded newer image for kalabox/cli:dev
Creating myapp_cli_1
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/compose/compose/cli/main.py", line 54, in main
  File "/compose/compose/cli/docopt_command.py", line 23, in sys_dispatch
  File "/compose/compose/cli/docopt_command.py", line 26, in dispatch
  File "/compose/compose/cli/main.py", line 171, in perform_command
  File "/compose/compose/cli/main.py", line 546, in up
  File "/compose/compose/project.py", line 264, in up
  File "/compose/compose/service.py", line 389, in execute_convergence_plan
  File "/compose/compose/service.py", line 300, in create_container
  File "/compose/compose/container.py", line 46, in create
  File "/compose/venv/lib/python2.7/site-packages/docker/api/container.py", line 114, in create_container
  File "/compose/venv/lib/python2.7/site-packages/docker/api/container.py", line 119, in create_container_config
  File "/compose/venv/lib/python2.7/site-packages/docker/utils/utils.py", line 693, in create_container_config
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)
docker-compose returned -1
info: DOCKER-COMPOSE =>  Run exited with code: 255
```

Kalabox v0.11

OS X 10.11.3

**Comment by pirog** [comment]
@johnnypea have you looked for this in the docker-compose issue queue at all?

**Comment by pirog** [comment]
@johnnypea once we upgrade to docker compose 1.6 i would try this again and see if its resolved

**Comment by johnnypea** [comment]
I found the source of the problem. It's failing because of the special characters in my name (Ján Bočínec) used in `kalabox-cli.yml` line 24 and 26 from the variable `$KALABOX_APP_PANTHEON_CONFIG_NAME`. I removed accents from the name (on Pantheon dashboard) and it worked like a charm. But I think it is still the issue.

Docker Compose 1.6 doesn't solve it.

**Comment by heronog** [comment]
I can reproduce the bug and the workaround. Removing non-ascii chars from my info in Pantheon did work.

**Comment by pirog** [comment]
Awesome! I wonder if there is something we can do on our end to translate the non-ascii characters to get this to work properly without the workaround.

**Comment by pirog** [comment]
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!
