### ISSUE TITLE
Error Http code 500 when running kbox create pantheon

### ISSUE THREAD

**Issue by shaal** [kalabox/kalabox#888]
on a windows 10 machine,
after running kbox create pantheon - i am getting this error http 500.

![kbox11-pantheon-create-error-screencapture](https://cloud.githubusercontent.com/assets/22901/12583224/a2d37e82-c40f-11e5-9d26-3b29a786bcf4.jpg)

```
C:\Users\shaal\Documents\kbox-pantheon>kbox create pantheon
? Choose a Pantheon account. (Use arrow keys)
? Choose a Pantheon account. david@3paces.com
? Which site? 3paces-template
? Which environment? dev
? What will you call this monster you have created: 3paces-template
info: COMPOSE =>  0=--project-name, 1=kalabox, 2=--file, 3=C:\Users\shaal\.kalabox\downloads\kalabox\kalabox-1.yml, 4=ps, 5=-q, 6=syncthing, 7=undefined
info: COMPOSE =>  0=--project-name, 1=kalabox, 2=--file, 3=C:\Users\shaal\.kalabox\downloads\kalabox\kalabox-2.yml, 4=run, 5=-d, 6=--entrypoint, 7=/bin/mkdir, 8=--rm, 9=syncthing, 10=-p, 11=/code/3paces-template, mode=false
info: COMPOSE =>  0=--project-name, 1=kalabox, 2=--file, 3=C:\Users\shaal\.kalabox\downloads\kalabox\kalabox-3.yml, 4=run, 5=-d, 6=--entrypoint, 7=touch, 8=--rm, 9=syncthing, 10=/code/3paces-template/.stfolder, mode=false
info: COMPOSE =>  0=--project-name, 1=kalabox, 2=--file, 3=C:\Users\shaal\.kalabox\downloads\kalabox\kalabox-4.yml, 4=run, 5=-d, 6=--entrypoint, 7=/bin/cp, 8=--rm, 9=syncthing, 10=/src/Documents\kbox-pantheon\3paces-template\code/.stignore, 11=/code/3paces-template/.stignore, mode=false
info: COMPOSE =>  0=--project-name, 1=kalabox, 2=--file, 3=C:\Users\shaal\.kalabox\downloads\kalabox\kalabox-5.yml, 4=ps, 5=-q, 6=syncthing, 7=undefined
info: COMPOSE =>  0=--project-name, 1=3paces-template, 2=--file, 3=C:\Users\shaal\Documents\kbox-pantheon\3paces-template\kalabox-compose.yml, 4=--file, 5=C:\Users\shaal\Documents\kbox-pantheon\3paces-template\kalabox-cli.yml, 6=--file, 7=C:\Users\shaal\.kalabox\downloads\3paces-template\3paces-template-6.yml, 8=up, 9=-d, mode=collect
Creating 3pacestemplate_redis_1
Creating 3pacestemplate_data_1
Creating 3pacestemplate_solr_1
Creating 3pacestemplate_db_1
Creating 3pacestemplate_appserver_1
Creating 3pacestemplate_edge_1
Creating 3pacestemplate_cli_1
Creating 3pacestemplate_terminus_1
info: DOCKER-COMPOSE.EXE =>  Run exited with code: 0
info: COMPOSE =>  0=--project-name, 1=3paces-template, 2=--file, 3=C:\Users\shaal\Documents\kbox-pantheon\3paces-template\kalabox-compose.yml, 4=--file, 5=C:\Users\shaal\Documents\kbox-pantheon\3paces-template\kalabox-cli.yml, 6=--file, 7=C:\Users\shaal\.kalabox\downloads\3paces-template\3paces-template-6.yml, 8=ps, 9=-q, 10=appserver, 11=undefined
info: COMPOSE =>  0=--project-name, 1=3paces-template, 2=--file, 3=C:\Users\shaal\Documents\kbox-pantheon\3paces-template\kalabox-compose.yml, 4=--file, 5=C:\Users\shaal\Documents\kbox-pantheon\3paces-template\kalabox-cli.yml, 6=--file, 7=C:\Users\shaal\.kalabox\downloads\3paces-template\3paces-template-6.yml, 8=ps, 9=-q, 10=edge, 11=undefined
info: TERMINUS =>  Run definition:  compose=[C:\Users\shaal\Documents\kbox-pantheon\3paces-template\kalabox-compose.yml, C:\Users\shaal\Documents\kbox-pantheon\3paces-template\kalabox-cli.yml, C:\Users\shaal\.kalabox\downloads\3paces-template\3paces-template-6.yml], project=3paces-template, services=[terminus], mode=collect, entrypoint=[bash, --login, -c], cmd=[terminus, sites, aliases, --format=json]
info: COMPOSE =>  0=--project-name, 1=3paces-template, 2=--file, 3=C:\Users\shaal\Documents\kbox-pantheon\3paces-template\kalabox-compose.yml, 4=--file, 5=C:\Users\shaal\Documents\kbox-pantheon\3paces-template\kalabox-cli.yml, 6=--file, 7=C:\Users\shaal\.kalabox\downloads\3paces-template\3paces-template-6.yml, 8=run, 9=-d, 10=--entrypoint, 11=tail, 12=terminus, 13=-f, 14=/dev/null, mode=false
info: TERMINUS =>  Run returned:
info: TERMINUS =>  Run definition:  compose=[C:\Users\shaal\Documents\kbox-pantheon\3paces-template\kalabox-compose.yml, C:\Users\shaal\Documents\kbox-pantheon\3paces-template\kalabox-cli.yml, C:\Users\shaal\.kalabox\downloads\3paces-template\3paces-template-6.yml], project=3paces-template, services=[terminus], mode=collect, entrypoint=[bash, --login, -c], cmd=[terminus, site, wake, --site=3paces-template, --env=dev, --format=json]
info: COMPOSE =>  0=--project-name, 1=3paces-template, 2=--file, 3=C:\Users\shaal\Documents\kbox-pantheon\3paces-template\kalabox-compose.yml, 4=--file, 5=C:\Users\shaal\Documents\kbox-pantheon\3paces-template\kalabox-cli.yml, 6=--file, 7=C:\Users\shaal\.kalabox\downloads\3paces-template\3paces-template-6.yml, 8=run, 9=-d, 10=--entrypoint, 11=tail, 12=terminus, 13=-f, 14=/dev/null, mode=false
info: TERMINUS =>  Run returned:
info: TERMINUS =>  Run definition:  compose=[C:\Users\shaal\Documents\kbox-pantheon\3paces-template\kalabox-compose.yml, C:\Users\shaal\Documents\kbox-pantheon\3paces-template\kalabox-cli.yml, C:\Users\shaal\.kalabox\downloads\3paces-template\3paces-template-6.yml], project=3paces-template, services=[terminus], mode=collect, entrypoint=[bash, --login, -c], cmd=[terminus, site, connection-info, --format=json, --site=3paces-template, --env=dev]
info: COMPOSE =>  0=--project-name, 1=3paces-template, 2=--file, 3=C:\Users\shaal\Documents\kbox-pantheon\3paces-template\kalabox-compose.yml, 4=--file, 5=C:\Users\shaal\Documents\kbox-pantheon\3paces-template\kalabox-cli.yml, 6=--file, 7=C:\Users\shaal\.kalabox\downloads\3paces-template\3paces-template-6.yml, 8=run, 9=-d, 10=--entrypoint, 11=tail, 12=terminus, 13=-f, 14=/dev/null, mode=false
info: TERMINUS =>  Run returned:  sftp_username=dev.b64377b3-8d85-4747-a741-02fdd319a4af, sftp_host=appserver.dev.b64377b3-8d85-4747-a741-02fdd319a4af.drush.in, sftp_password=Use your account password, sftp_url=sftp://dev.b64377b3-8d85-4747-a741-02fdd319a4af@appserver.dev.b64377b3-8d85-4747-a741-02fdd319a4af.drush.in:2222, sftp_command=sftp -o Port=2222 dev.b64377b3-8d85-4747-a741-02fdd319a4af@appserver.dev.b64377b3-8d85-4747-a741-02fdd319a4af.drush.in, git_username=codeserver.dev.b64377b3-8d85-4747-a741-02fdd319a4af, git_host=codeserver.dev.b64377b3-8d85-4747-a741-02fdd319a4af.drush.in, git_port=2222, git_url=ssh://codeserver.dev.b64377b3-8d85-4747-a741-02fdd319a4af@codeserver.dev.b64377b3-8d85-4747-a741-02fdd319a4af.drush.in:2222/~/repository.git, git_command=git clone ssh://codeserver.dev.b64377b3-8d85-4747-a741-02fdd319a4af@codeserver.dev.b64377b3-8d85-4747-a741-02fdd319a4af.drush.in:2222/~/repository.git 3paces-template, mysql_host=dbserver.dev.b64377b3-8d85-4747-a741-02fdd319a4af.drush.in, mysql_username=pantheon, mysql_password=868b879377244bcca650e2d36ca424fb, mysql_port=11718, mysql_database=pantheon, mysql_url=mysql://pantheon:868b879377244bcca650e2d36ca424fb@dbserver.dev.b64377b3-8d85-4747-a741-02fdd319a4af.drush.in:11718/pantheon, mysql_command=mysql -u pantheon -p868b879377244bcca650e2d36ca424fb -h dbserver.dev.b64377b3-8d85-4747-a741-02fdd319a4af.drush.in -P 11718 pantheon
info: KGIT =>  compose=[C:\Users\shaal\Documents\kbox-pantheon\3paces-template\kalabox-compose.yml, C:\Users\shaal\Documents\kbox-pantheon\3paces-template\kalabox-cli.yml, C:\Users\shaal\.kalabox\downloads\3paces-template\3paces-template-6.yml], project=3paces-template, mode=attach, services=[cli], entrypoint=kgit, cmd=[clone, ssh://codeserver.dev.b64377b3-8d85-4747-a741-02fdd319a4af@codeserver.dev.b64377b3-8d85-4747-a741-02fdd319a4af.drush.in:2222/~/repository.git, ./]
info: COMPOSE =>  0=--project-name, 1=3paces-template, 2=--file, 3=C:\Users\shaal\Documents\kbox-pantheon\3paces-template\kalabox-compose.yml, 4=--file, 5=C:\Users\shaal\Documents\kbox-pantheon\3paces-template\kalabox-cli.yml, 6=--file, 7=C:\Users\shaal\.kalabox\downloads\3paces-template\3paces-template-6.yml, 8=run, 9=-d, 10=--entrypoint, 11=tail, 12=cli, 13=-f, 14=/dev/null, mode=false
fatal: destination path '.' already exists and is not an empty directory.
info: COMPOSE =>  0=--project-name, 1=3paces-template, 2=--file, 3=C:\Users\shaal\Documents\kbox-pantheon\3paces-template\kalabox-compose.yml, 4=--file, 5=C:\Users\shaal\Documents\kbox-pantheon\3paces-template\kalabox-cli.yml, 6=--file, 7=C:\Users\shaal\.kalabox\downloads\3paces-template\3paces-template-6.yml, 8=run, 9=-d, 10=--entrypoint, 11=ln, 12=--rm, 13=appserver, 14=-nsf, 15=/media, 16=/code/sites/default/files, mode=false
info: TERMINUS =>  Run definition:  compose=[C:\Users\shaal\Documents\kbox-pantheon\3paces-template\kalabox-compose.yml, C:\Users\shaal\Documents\kbox-pantheon\3paces-template\kalabox-cli.yml, C:\Users\shaal\.kalabox\downloads\3paces-template\3paces-template-6.yml], project=3paces-template, services=[terminus], mode=collect, entrypoint=[bash, --login, -c], cmd=[terminus, site, backups, list, --format=json, --element=db, --site=3paces-template, --env=dev]
info: COMPOSE =>  0=--project-name, 1=3paces-template, 2=--file, 3=C:\Users\shaal\Documents\kbox-pantheon\3paces-template\kalabox-compose.yml, 4=--file, 5=C:\Users\shaal\Documents\kbox-pantheon\3paces-template\kalabox-cli.yml, 6=--file, 7=C:\Users\shaal\.kalabox\downloads\3paces-template\3paces-template-6.yml, 8=run, 9=-d, 10=--entrypoint, 11=tail, 12=terminus, 13=-f, 14=/dev/null, mode=false
info: TERMINUS =>  Run returned:  0=[file=3paces-template_dev_2016-01-25T05-50-07_UTC_database.sql.gz, size=0.3MB, date=2016-01-25 05:50:16, initiator=manual, file=3paces-template_dev_2016-01-25T05-32-38_UTC_database.sql.gz, size=0.2MB, date=2016-01-25 05:32:49, initiator=manual, file=3paces-template_dev_2016-01-25T04-27-27_UTC_database.sql.gz, size=0.1MB, date=2016-01-25 04:27:36, initiator=manual]
info: TERMINUS =>  Run definition:  compose=[C:\Users\shaal\Documents\kbox-pantheon\3paces-template\kalabox-compose.yml, C:\Users\shaal\Documents\kbox-pantheon\3paces-template\kalabox-cli.yml, C:\Users\shaal\.kalabox\downloads\3paces-template\3paces-template-6.yml], project=3paces-template, services=[terminus], mode=collect, entrypoint=[bash, --login, -c], cmd=[terminus, site, backups, get, --site=3paces-template, --env=dev, --element=db, --to=/backups, --latest, --format=json]
info: COMPOSE =>  0=--project-name, 1=3paces-template, 2=--file, 3=C:\Users\shaal\Documents\kbox-pantheon\3paces-template\kalabox-compose.yml, 4=--file, 5=C:\Users\shaal\Documents\kbox-pantheon\3paces-template\kalabox-cli.yml, 6=--file, 7=C:\Users\shaal\.kalabox\downloads\3paces-template\3paces-template-6.yml, 8=run, 9=-d, 10=--entrypoint, 11=tail, 12=terminus, 13=-f, 14=/dev/null, mode=false
info: TERMINUS =>  Run returned:  0=/backups/3paces-template_dev_2016-01-25T05-50-07_UTC_database.sql.gz
info: COMPOSE =>  0=--project-name, 1=3paces-template, 2=--file, 3=C:\Users\shaal\Documents\kbox-pantheon\3paces-template\kalabox-compose.yml, 4=--file, 5=C:\Users\shaal\Documents\kbox-pantheon\3paces-template\kalabox-cli.yml, 6=--file, 7=C:\Users\shaal\.kalabox\downloads\3paces-template\3paces-template-6.yml, 8=run, 9=-d, 10=--entrypoint, 11=import-mysql, 12=--rm, 13=db, 14=/backups/3paces-template_dev_2016-01-25T05-50-07_UTC_database.sql.gz, mode=false
info: TERMINUS =>  Run definition:  compose=[C:\Users\shaal\Documents\kbox-pantheon\3paces-template\kalabox-compose.yml, C:\Users\shaal\Documents\kbox-pantheon\3paces-template\kalabox-cli.yml, C:\Users\shaal\.kalabox\downloads\3paces-template\3paces-template-6.yml], project=3paces-template, services=[terminus], mode=collect, entrypoint=[bash, --login, -c], cmd=[terminus, site, backups, list, --format=json, --element=files, --site=3paces-template, --env=dev]
info: COMPOSE =>  0=--project-name, 1=3paces-template, 2=--file, 3=C:\Users\shaal\Documents\kbox-pantheon\3paces-template\kalabox-compose.yml, 4=--file, 5=C:\Users\shaal\Documents\kbox-pantheon\3paces-template\kalabox-cli.yml, 6=--file, 7=C:\Users\shaal\.kalabox\downloads\3paces-template\3paces-template-6.yml, 8=run, 9=-d, 10=--entrypoint, 11=tail, 12=terminus, 13=-f, 14=/dev/null, mode=false
info: TERMINUS =>  Run returned:  0=[file=3paces-template_dev_2016-01-25T05-50-07_UTC_files.tar.gz, size=0.1MB, date=2016-01-25 05:50:14, initiator=manual, file=3paces-template_dev_2016-01-25T05-32-38_UTC_files.tar.gz, size=0.1MB, date=2016-01-25 05:32:47, initiator=manual, file=3paces-template_dev_2016-01-25T04-27-27_UTC_files.tar.gz, size=0.1MB, date=2016-01-25 04:27:34, initiator=manual]
info: TERMINUS =>  Run definition:  compose=[C:\Users\shaal\Documents\kbox-pantheon\3paces-template\kalabox-compose.yml, C:\Users\shaal\Documents\kbox-pantheon\3paces-template\kalabox-cli.yml, C:\Users\shaal\.kalabox\downloads\3paces-template\3paces-template-6.yml], project=3paces-template, services=[terminus], mode=collect, entrypoint=[bash, --login, -c], cmd=[terminus, site, backups, get, --site=3paces-template, --env=dev, --element=files, --to=/backups, --latest, --format=json]
info: COMPOSE =>  0=--project-name, 1=3paces-template, 2=--file, 3=C:\Users\shaal\Documents\kbox-pantheon\3paces-template\kalabox-compose.yml, 4=--file, 5=C:\Users\shaal\Documents\kbox-pantheon\3paces-template\kalabox-cli.yml, 6=--file, 7=C:\Users\shaal\.kalabox\downloads\3paces-template\3paces-template-6.yml, 8=run, 9=-d, 10=--entrypoint, 11=tail, 12=terminus, 13=-f, 14=/dev/null, mode=false
info: TERMINUS =>  Run returned:  0=/backups/3paces-template_dev_2016-01-25T05-50-07_UTC_files.tar.gz
info: COMPOSE =>  0=--project-name, 1=3paces-template, 2=--file, 3=C:\Users\shaal\Documents\kbox-pantheon\3paces-template\kalabox-compose.yml, 4=--file, 5=C:\Users\shaal\Documents\kbox-pantheon\3paces-template\kalabox-cli.yml, 6=--file, 7=C:\Users\shaal\.kalabox\downloads\3paces-template\3paces-template-6.yml, 8=run, 9=-d, 10=--entrypoint, 11=tail, 12=appserver, 13=-f, 14=/dev/null, mode=false
Error dispatching event listeners [post-create-app]: HTTP code is 500 which indicates error: server error - json: cannot unmarshal array into Go value of type string

Error: HTTP code is 500 which indicates error: server error - json: cannot unmarshal array into Go value of type string

    at D:\Programs\Kalabox\node_modules\dockerode\node_modules\docker-modem\lib\modem.js.jx:228:17
    at getCause (D:\Programs\Kalabox\node_modules\dockerode\node_modules\docker-modem\lib\modem.js.jx:256:7)
    at Modem.buildPayload (D:\Programs\Kalabox\node_modules\dockerode\node_modules\docker-modem\lib\modem.js.jx:227:5)
    at null.<anonymous> (D:\Programs\Kalabox\node_modules\dockerode\node_modules\docker-modem\lib\modem.js.jx:203:14)
    at emit (events.js:98:14)
    at _stream_readable.js:889:8
    at process._tickCallback (node.js:803:1)
```

**Comment by pirog** [comment]
This is a known issue on Windows. Go into your app directory and run Kbox
pull to resolve

On Tuesday, January 26, 2016, shaal <notifications@github.com> wrote:

> after running kbox create pantheon - i am getting this error http 500
>
> [image: kbox11-pantheon-create-error-screencapture]
> <https://camo.githubusercontent.com/75cfecabd85782a019e6dc731f810010e391ba19/68747470733a2f2f636c6f756467697468756275736572636f6e74656e74636f6d2f6173736574732f32323930312f31323538333232342f61326433376538322d633430662d313165352d396432362d3362323961373836626366346a7067>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/888>.
>


-- 
Mike Pirog
Co-Founder, Kalabox Inc

**Comment by pirog** [comment]
Here is the current issue tracking this
https://github.com/kalabox/kalabox/issues/856
