### ISSUE TITLE
Network timed out error in version 0.11.1

### ISSUE THREAD

**Issue by shaal** [kalabox/kalabox#900]
on windows 10 machine -
I downloaded the latest version of kalabox - 0.11.1
I ran kbox update, successful.

I tried running 'kbox destroy', and got these errors -
```
kbox destroy
###############################################################

             WARNING! APP DESTRUCTION IMMINENT

  Before you continue please be aware that after you destroy
  an app there will be nothing left. That means yours app's
  codes, files, databases, indeces, caches, containers and
  EVERYTHING ELSE that has to do with your app WILL BE GONE.

###############################################################
? So, are you still prepared to DESTROY? (y/N) y
? So, are you still prepared to DESTROY? Yes
info: COMPOSE =>  0=--project-name, 1=kalabox, 2=--file, 3=C:\Users\shaal\.kalabox\downloads\kalabox\kalabox-1.yml, 4=ps, 5=-q, 6=syncthing, 7=undefined
info: COMPOSE =>  0=--project-name, 1=3paces, 2=--file, 3=C:\Users\shaal\Documents\kbox-pantheon\3paces\kalabox-compose.yml, 4=--file, 5=C:\Users\shaal\Documents\kbox-pantheon\3paces\kalabox-cli.yml, 6=stop, mode=collect
info: DOCKER-COMPOSE.EXE =>  Stopping 3paces_edge_1 ...

Stopping 3paces_appserver_1 ...
info: DOCKER-COMPOSE.EXE =>  Stopping 3paces_db_1 ...



Stopping 3paces_db_1 ... done
Stopping 3paces_solr_1 ... donee
info: DOCKER-COMPOSE.EXE =>  Run exited with code: 0
info: COMPOSE =>  0=--project-name, 1=3paces, 2=--file, 3=C:\Users\shaal\Documents\kbox-pantheon\3paces\kalabox-compose.yml, 4=--file, 5=C:\Users\shaal\Documents\kbox-pantheon\3paces\kalabox-cli.yml, 6=rm, 7=--force, 8=-v, mode=collect
info: DOCKER-COMPOSE.EXE =>  Going to remove 3paces_terminus_1, 3paces_cli_1, 3paces_edge_1, 3paces_appserver_1, 3paces_db_1, 3paces_solr_1, 3paces_data_1, 3paces_redis_1
Removing 3paces_terminus_1 ...

Removing 3paces_cli_1 ...
info: DOCKER-COMPOSE.EXE =>  Removing 3paces_edge_1 ...

Removing 3paces_appserver_1 ...



Removing 3paces_edge_1 ... done

Removing 3paces_appserver_1 ... done


Removing 3paces_data_1 ... donee
info: DOCKER-COMPOSE.EXE =>  Run exited with code: 0
info: COMPOSE =>  0=--project-name, 1=kalabox, 2=--file, 3=C:\Users\shaal\.kalabox\downloads\kalabox\kalabox-2.yml, 4=run, 5=-d, 6=--entrypoint, 7=tail, 8=syncthing, 9=-f, 10=/dev/null, mode=false
Error dispatching event listeners [post-app-destroy]: code: 1err:Pulling syncthing (kalabox/syncthing:v0.11.1)...
Pulling repository docker.io/kalabox/syncthing
Network timed out while trying to connect to https://index.docker.io/v1/repositories/kalabox/syncthing/images. You may want to check your internet connection or if you are behind a proxy.

VError: code: 1err:Pulling syncthing (kalabox/syncthing:v0.11.1)...
Pulling repository docker.io/kalabox/syncthing
Network timed out while trying to connect to https://index.docker.io/v1/repositories/kalabox/syncthing/images. You may want to check your internet connection or if you are behind a proxy.

    at D:\Programs\Kalabox\lib\util\shell.js.jx:134:16
    at D:\Programs\Kalabox\node_modules\shelljs\src\exec.js.jx:106:7
    at ChildProcess.exithandler (child_process.js:669:1)
    at ChildProcess.emit (events.js:85:9)
    at maybeClose (child_process.js:773:12)
    at Process.ChildProcess._handle.onexit (child_process.js:839:1)
From previous event:
    at Object.exports.exec (D:\Programs\Kalabox\lib\util\shell.js.jx:131:10)
    at Object.sh (D:\Programs\Kalabox\plugins\kalabox-engine-docker\provider\docker\lib\bin.js.jx:99:20)
    at D:\Programs\Kalabox\plugins\kalabox-engine-docker\provider\docker\compose.js.jx:60:18
From previous event:
    at shCompose (D:\Programs\Kalabox\plugins\kalabox-engine-docker\provider\docker\compose.js.jx:42:6)
    at Object.run (D:\Programs\Kalabox\plugins\kalabox-engine-docker\provider\docker\compose.js.jx:343:12)
    at D:\Programs\Kalabox\plugins\kalabox-engine-docker\index.js.jx:207:24
    at arrayMap (D:\Programs\Kalabox\node_modules\lodash\index.js.jx:1405:25)
    at Function.map (D:\Programs\Kalabox\node_modules\lodash\index.js.jx:6709:14)
    at Object.run (D:\Programs\Kalabox\plugins\kalabox-engine-docker\index.js.jx:177:26)
From previous event:
    at D:\Programs\Kalabox\lib\engine.js.jx:471:29
From previous event:
    at Object.exports.run (D:\Programs\Kalabox\lib\engine.js.jx:470:4)
    at Object.fn (D:\Programs\Kalabox\plugins\kalabox-syncthing\lib\events.js.jx:288:26)
    at D:\Programs\Kalabox\lib\core\events.js.jx:172:19
From previous event:
    at D:\Programs\Kalabox\lib\core\events.js.jx:161:23
From previous event:
    at EventEngine._dispatch (D:\Programs\Kalabox\lib\core\events.js.jx:158:18)
    at D:\Programs\Kalabox\lib\core\events.js.jx:137:19
From previous event:
    at EventEngine.emit (D:\Programs\Kalabox\lib\core\events.js.jx:129:21)
From previous event:
    at Object.exports.emit (D:\Programs\Kalabox\lib\core\events.js.jx:261:4)
    at D:\Programs\Kalabox\lib\app.js.jx:475:24
    at process._tickCallback (node.js:803:1)
From previous event:
    at Object.exports.destroy (D:\Programs\Kalabox\lib\app.js.jx:474:4)
    at PromptUI.completed (D:\Programs\Kalabox\plugins\kalabox-core\lib\tasks\destroy.js.jx:67:22)
    at PromptUI.onCompletion (D:\Programs\Kalabox\node_modules\inquirer\lib\ui\prompt.js.jx:68:10)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (D:\Programs\Kalabox\node_modules\inquirer\node_modules\rx\dist\rx.js.jx:1792:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (D:\Programs\Kalabox\node_modules\inquirer\node_modules\rx\dist\rx.js.jx:1729:14)
    at AnonymousObserver.tryCatcher (D:\Programs\Kalabox\node_modules\inquirer\node_modules\rx\dist\rx.js.jx:566:29)
    at AutoDetachObserverPrototype.completed (D:\Programs\Kalabox\node_modules\inquirer\node_modules\rx\dist\rx.js.jx:5287:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (D:\Programs\Kalabox\node_modules\inquirer\node_modules\rx\dist\rx.js.jx:1729:14)
    at InnerObserver.onCompleted (D:\Programs\Kalabox\node_modules\inquirer\node_modules\rx\dist\rx.js.jx:3424:65)
    at InnerObserver.tryCatcher (D:\Programs\Kalabox\node_modules\inquirer\node_modules\rx\dist\rx.js.jx:566:29)
    at AutoDetachObserverPrototype.completed (D:\Programs\Kalabox\node_modules\inquirer\node_modules\rx\dist\rx.js.jx:5287:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (D:\Programs\Kalabox\node_modules\inquirer\node_modules\rx\dist\rx.js.jx:1729:14)
    at AutoDetachObserver.tryCatcher (D:\Programs\Kalabox\node_modules\inquirer\node_modules\rx\dist\rx.js.jx:566:29)
    at AutoDetachObserverPrototype.completed (D:\Programs\Kalabox\node_modules\inquirer\node_modules\rx\dist\rx.js.jx:5287:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (D:\Programs\Kalabox\node_modules\inquirer\node_modules\rx\dist\rx.js.jx:1729:14)
    at InnerObserver.onCompleted (D:\Programs\Kalabox\node_modules\inquirer\node_modules\rx\dist\rx.js.jx:3424:65)
    at InnerObserver.tryCatcher (D:\Programs\Kalabox\node_modules\inquirer\node_modules\rx\dist\rx.js.jx:566:29)
    at AutoDetachObserverPrototype.completed (D:\Programs\Kalabox\node_modules\inquirer\node_modules\rx\dist\rx.js.jx:5287:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (D:\Programs\Kalabox\node_modules\inquirer\node_modules\rx\dist\rx.js.jx:1729:14)
```

after that i deleted the directory of that kbox container.
and tried to create it again, and then i got a whole new set of errors -

```
kbox create pantheon
? Choose a Pantheon account. (Use arrow keys)
? Choose a Pantheon account. david@3paces.com
? Which site? 3paces
? Which environment? dev
? What will you call this monster you have created: 3paces
info: COMPOSE =>  0=--project-name, 1=kalabox, 2=--file, 3=C:\Users\shaal\.kalabox\downloads\kalabox\kalabox-1.yml, 4=ps, 5=-q, 6=syncthing, 7=undefined
info: COMPOSE =>  0=--project-name, 1=kalabox, 2=--file, 3=C:\Users\shaal\.kalabox\downloads\kalabox\kalabox-2.yml, 4=run, 5=-d, 6=--entrypoint, 7=tail, 8=syncthing, 9=-f, 10=/dev/null, mode=false
Error dispatching event listeners [pre-app-start]: code: 1err:Pulling syncthing (kalabox/syncthing:v0.11.1)...
Pulling repository docker.io/kalabox/syncthing
Network timed out while trying to connect to https://index.docker.io/v1/repositories/kalabox/syncthing/images. You may want to check your internet connection or if you are behind a proxy.

VError: code: 1err:Pulling syncthing (kalabox/syncthing:v0.11.1)...
Pulling repository docker.io/kalabox/syncthing
Network timed out while trying to connect to https://index.docker.io/v1/repositories/kalabox/syncthing/images. You may want to check your internet connection or if you are behind a proxy.

    at D:\Programs\Kalabox\lib\util\shell.js.jx:134:16
    at D:\Programs\Kalabox\node_modules\shelljs\src\exec.js.jx:106:7
    at ChildProcess.exithandler (child_process.js:669:1)
    at ChildProcess.emit (events.js:85:9)
    at maybeClose (child_process.js:773:12)
    at Process.ChildProcess._handle.onexit (child_process.js:839:1)
From previous event:
    at Object.exports.exec (D:\Programs\Kalabox\lib\util\shell.js.jx:131:10)
    at Object.sh (D:\Programs\Kalabox\plugins\kalabox-engine-docker\provider\docker\lib\bin.js.jx:99:20)
    at D:\Programs\Kalabox\plugins\kalabox-engine-docker\provider\docker\compose.js.jx:60:18
From previous event:
    at shCompose (D:\Programs\Kalabox\plugins\kalabox-engine-docker\provider\docker\compose.js.jx:42:6)
    at Object.run (D:\Programs\Kalabox\plugins\kalabox-engine-docker\provider\docker\compose.js.jx:343:12)
    at D:\Programs\Kalabox\plugins\kalabox-engine-docker\index.js.jx:207:24
    at arrayMap (D:\Programs\Kalabox\node_modules\lodash\index.js.jx:1405:25)
    at Function.map (D:\Programs\Kalabox\node_modules\lodash\index.js.jx:6709:14)
    at Object.run (D:\Programs\Kalabox\plugins\kalabox-engine-docker\index.js.jx:177:26)
From previous event:
    at D:\Programs\Kalabox\lib\engine.js.jx:471:29
From previous event:
    at Object.exports.run (D:\Programs\Kalabox\lib\engine.js.jx:470:4)
    at Promise.fromNode.then.then.then.then.touchCmd (D:\Programs\Kalabox\plugins\kalabox-syncthing\lib\events.js.jx:150:30)
From previous event:
    at Object.fn (D:\Programs\Kalabox\plugins\kalabox-syncthing\lib\events.js.jx:140:10)
    at D:\Programs\Kalabox\lib\core\events.js.jx:172:19
From previous event:
    at D:\Programs\Kalabox\lib\core\events.js.jx:161:23
From previous event:
    at EventEngine._dispatch (D:\Programs\Kalabox\lib\core\events.js.jx:158:18)
    at D:\Programs\Kalabox\lib\core\events.js.jx:137:19
From previous event:
    at EventEngine.emit (D:\Programs\Kalabox\lib\core\events.js.jx:129:21)
From previous event:
    at Object.exports.emit (D:\Programs\Kalabox\lib\core\events.js.jx:261:4)
    at D:\Programs\Kalabox\lib\app.js.jx:348:24
From previous event:
    at Object.exports.start (D:\Programs\Kalabox\lib\app.js.jx:347:4)
    at D:\Programs\Kalabox\lib\create.js.jx:404:25
From previous event:
    at Promise.try.then.then.then.then.then.then.then.tap.tap.sysRoot (D:\Programs\Kalabox\lib\create.js.jx:403:8)
    at process._tickCallback (node.js:803:1)
From previous event:
    at createApp (D:\Programs\Kalabox\lib\create.js.jx:385:6)
    at PromptUI.completed (D:\Programs\Kalabox\lib\create.js.jx:495:16)
    at PromptUI.onCompletion (D:\Programs\Kalabox\node_modules\inquirer\lib\ui\prompt.js.jx:68:10)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (D:\Programs\Kalabox\node_modules\inquirer\node_modules\rx\dist\rx.js.jx:1792:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (D:\Programs\Kalabox\node_modules\inquirer\node_modules\rx\dist\rx.js.jx:1729:14)
    at AnonymousObserver.tryCatcher (D:\Programs\Kalabox\node_modules\inquirer\node_modules\rx\dist\rx.js.jx:566:29)
    at AutoDetachObserverPrototype.completed (D:\Programs\Kalabox\node_modules\inquirer\node_modules\rx\dist\rx.js.jx:5287:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (D:\Programs\Kalabox\node_modules\inquirer\node_modules\rx\dist\rx.js.jx:1729:14)
    at InnerObserver.onCompleted (D:\Programs\Kalabox\node_modules\inquirer\node_modules\rx\dist\rx.js.jx:3424:65)
    at InnerObserver.tryCatcher (D:\Programs\Kalabox\node_modules\inquirer\node_modules\rx\dist\rx.js.jx:566:29)
    at AutoDetachObserverPrototype.completed (D:\Programs\Kalabox\node_modules\inquirer\node_modules\rx\dist\rx.js.jx:5287:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (D:\Programs\Kalabox\node_modules\inquirer\node_modules\rx\dist\rx.js.jx:1729:14)
    at AutoDetachObserver.tryCatcher (D:\Programs\Kalabox\node_modules\inquirer\node_modules\rx\dist\rx.js.jx:566:29)
    at AutoDetachObserverPrototype.completed (D:\Programs\Kalabox\node_modules\inquirer\node_modules\rx\dist\rx.js.jx:5287:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (D:\Programs\Kalabox\node_modules\inquirer\node_modules\rx\dist\rx.js.jx:1729:14)
    at InnerObserver.onCompleted (D:\Programs\Kalabox\node_modules\inquirer\node_modules\rx\dist\rx.js.jx:3424:65)
    at InnerObserver.tryCatcher (D:\Programs\Kalabox\node_modules\inquirer\node_modules\rx\dist\rx.js.jx:566:29)
    at AutoDetachObserverPrototype.completed (D:\Programs\Kalabox\node_modules\inquirer\node_modules\rx\dist\rx.js.jx:5287:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (D:\Programs\Kalabox\node_modules\inquirer\node_modules\rx\dist\rx.js.jx:1729:14)

```

**Comment by pirog** [comment]
Do you have a healthy connection to the internet? seems like you dont
Network timed out while trying to connect to https://index.docker.io/v1/repositories/kalabox/syncthing/images. You may want to check your internet connection or if you are behind a proxy.

**Comment by shaal** [comment]
my internet connection is solid and very fast, and i am not behind proxy.
I put this link in my browser as soon as this error comes out - and it's loading perfectly in my browser.

**Comment by pirog** [comment]
This error is coming directly from docker so i would check over in there queues. 

Only advice i can give you beyond that is to try rebooting your kalabox2 VM.

**Comment by pirog** [comment]
It's also helpful to put a less vague description of your error when you open a bug report. 

Please see: https://github.com/kalabox/kalabox/wiki/Circle-of-Trust-Testing-Guide

**Comment by pirog** [comment]
Here is, i think, the relevant docker-machine issue
https://github.com/docker/machine/issues/1857

**Comment by pirog** [comment]
Researching this a little more it looks like docker doesn't plan to fix this and that fundamentally its how virtualbox works. 

I think the best thing we could do on the kalabox front is to check for this and then restart the engine if needed.

**Comment by shaal** [comment]
I uninstalled kbox, deleted all the container files/directories, I uninstalled virtualbox, I restarted windows.

after 'kbox create pantheon' - it went through more steps than ever before in my experience.
(yet, at the end - there was a network error)
```
###############################################################

                    Welcome to Kalabox 2!

 We see this is your first time running a Kalabox command that
 requires the use of the Kalabox engine. Before we can do this
 We need to install some special things to make sure you are
 good to go. Please agree to the prompt below to install all
 the magic. (takes about 5 minutes with average download speed)

###############################################################
info: INSTALL =>  -- Step 1/22 --
info: INSTALL =>  Authorizing trilling subroutines...
? Install all the magic and get this party started? Yes
info: INSTALL =>  -- OK! 5% complete! --

info: INSTALL =>  -- Step 2/22 --
info: INSTALL =>  Making sure syncthing is not running...
info: INSTALL =>  -- OK! 9% complete! --

info: INSTALL =>  -- Step 3/22 --
info: INSTALL =>  Adding services images to build list...
info: INSTALL =>  -- OK! 14% complete! --

info: INSTALL =>  -- Step 4/22 --
info: INSTALL =>  Adding syncthing image to build list...
info: INSTALL =>  -- OK! 18% complete! --

info: INSTALL =>  -- Step 5/22 --
info: INSTALL =>  Queuing up syncthing downloads...
info: INSTALL =>  -- OK! 23% complete! --

info: INSTALL =>  -- Step 6/22 --
info: INSTALL =>  Checking firewall settings...
info: INSTALL =>  -- OK! 27% complete! --

info: INSTALL =>  -- Step 7/22 --
info: INSTALL =>  Checking for available disk space...
info: INSTALL =>  -- OK! 32% complete! --

info: INSTALL =>  -- Step 8/22 --
info: INSTALL =>  Updating Kalabox ISO if needed...
info: INSTALL =>  -- OK! 36% complete! --

info: INSTALL =>  -- Step 9/22 --
info: INSTALL =>  Queuing provider admin commands...
info: INSTALL =>  -- OK! 41% complete! --

info: INSTALL =>  -- Step 10/22 --
info: INSTALL =>  Queuing up provider downloads...
info: INSTALL =>  -- OK! 45% complete! --

info: INSTALL =>  -- Step 11/22 --
info: INSTALL =>  Checking for Internet access...
info: INSTALL =>  -- OK! 50% complete! --

info: INSTALL =>  -- Step 12/22 --
info: INSTALL =>  Downloading files...
     fetch : http://download.virtualbox.org/virtualbox/5.0.12/VirtualBox-5.0.12-104815-Win.exe
     fetch : https://raw.githubusercontent.com/kalabox/kalabox/v0.10/dockerfiles/syncthing/config.xml
     fetch : https://github.com/docker/compose/releases/download/1.5.2/docker-compose-Windows-x86_64.exe
     fetch : https://github.com/syncthing/syncthing/releases/download/v0.11.26/syncthing-windows-amd64-v0.11.26.zip
     fetch : https://github.com/docker/machine/releases/download/v0.5.6/docker-machine_windows-amd64.exe
     fetch : https://github.com/msysgit/msysgit/releases/download/Git-1.9.5-preview20150319/Git-1.9.5-preview20150319.exe
  progress : [====================] 100% 0.0s

info: INSTALL =>  -- OK! 55% complete! --

info: INSTALL =>  -- Step 13/22 --
info: INSTALL =>  Setting up syncthing...
info: INSTALL =>  -- OK! 59% complete! --

info: INSTALL =>  -- Step 14/22 --
info: INSTALL =>  Running admin install commands...
info: UTIL EXEC ADMIN =>  Files were extracted to: C:\Users\shaal\.kalabox\downloads\vbox
info: INSTALL =>  -- OK! 64% complete! --

info: INSTALL =>  -- Step 15/22 --
info: INSTALL =>  Setting up the docker machine...
info: INSTALL =>  -- OK! 68% complete! --

info: INSTALL =>  -- Step 16/22 --
info: INSTALL =>  Updating install info...
info: INSTALL =>  -- OK! 73% complete! --

info: INSTALL =>  -- Step 17/22 --
info: INSTALL =>  Setting up and activating the engine...
info: DOCKER-MACHINE.EXE =>  Starting "Kalabox2"...
info: DOCKER-MACHINE.EXE =>  (Kalabox2) Waiting for an IP...
info: DOCKER-MACHINE.EXE =>  Machine "Kalabox2" was started.
info: DOCKER-MACHINE.EXE =>  Started machines may have new IP addresses. You may need to re-run the `docker-machine env` command.
info: DOCKER-MACHINE.EXE =>  Run exited with code: 0
info: INSTALL =>  -- OK! 77% complete! --

info: INSTALL =>  -- Step 18/22 --
info: INSTALL =>  Pulling images...
info: COMPOSE =>  0=--project-name, 1=kalabox, 2=--file, 3=C:\Users\shaal\.kalabox\downloads\kalabox\kalabox-1.yml, 4=pull, mode=collect
Pulling proxy (kalabox/proxy:v0.11.1)...
info: DOCKER-COMPOSE.EXE =>  v0.11.1: Pulling from kalabox/proxy
info: DOCKER-COMPOSE.EXE =>  Digest: sha256:c64edf8e8f8b9ab26235a4bd3e1d49802d0aa4821eba08ea85e19eb2efe2a854
Pinfo: DOCKER-COMPOSE.EXE =>  Status: Downloaded newer image for kalabox/proxy:v0.11.1
ulling dns (kalabox/dns:v0.11.1)...
info: DOCKER-COMPOSE.EXE =>  v0.11.1: Pulling from kalabox/dns
info: DOCKER-COMPOSE.EXE =>  Digest: sha256:16e0317e4002b84d98a32d3eba7b7990de0bf5ba1052f4134239b8ffa4afa078
info: DOCKER-COMPOSE.EXE =>  Status: Downloaded newer image for kalabox/dns:v0.11.1
info: DOCKER-COMPOSE.EXE =>  Run exited with code: 0
info: COMPOSE =>  0=--project-name, 1=kalabox, 2=--file, 3=C:\Users\shaal\.kalabox\downloads\kalabox\kalabox-2.yml, 4=pull, mode=collect
Pulling syncthing (kalabox/syncthing:v0.11.1)...
info: DOCKER-COMPOSE.EXE =>  v0.11.1: Pulling from kalabox/syncthing
info: DOCKER-COMPOSE.EXE =>  Digest: sha256:8c98288339427a7177e4767484dcad5e97eb0f67935723df40c7c4a6b92d176a
info: DOCKER-COMPOSE.EXE =>  Status: Downloaded newer image for kalabox/syncthing:v0.11.1
info: DOCKER-COMPOSE.EXE =>  Run exited with code: 0
info: COMPOSE =>  0=--project-name, 1=kalabox, 2=--file, 3=C:\Users\shaal\.kalabox\downloads\kalabox\kalabox-3.yml, 4=build, mode=collect
proxy uses an image, skipping
dns uses an image, skipping
info: DOCKER-COMPOSE.EXE =>  Run exited with code: 0
info: COMPOSE =>  0=--project-name, 1=kalabox, 2=--file, 3=C:\Users\shaal\.kalabox\downloads\kalabox\kalabox-4.yml, 4=build, mode=collect
syncthing uses an image, skipping
info: DOCKER-COMPOSE.EXE =>  Run exited with code: 0
info: INSTALL =>  -- OK! 82% complete! --

info: INSTALL =>  -- Step 19/22 --
info: INSTALL =>  Setting up DNS...
info: WIN ELEVATED =>  netsh interface ipv4 add dnsservers "VirtualBox Host-Only Network #3" 10.13.37.100 validate=no index=1
info: WIN ELEVATED =>  ipconfig /flushdns
info: INSTALL =>  -- OK! 86% complete! --

info: INSTALL =>  -- Step 20/22 --
info: INSTALL =>  Creating services...
info: COMPOSE =>  0=--project-name, 1=kalabox, 2=--file, 3=C:\Users\shaal\.kalabox\downloads\kalabox\kalabox-5.yml, 4=up, 5=-d, 6=--force-recreate, mode=collect
Recreating kalabox_proxy_1
Recreating kalabox_dns_1
info: DOCKER-COMPOSE.EXE =>  Run exited with code: 0
info: INSTALL =>  -- OK! 91% complete! --

info: INSTALL =>  -- Step 21/22 --
info: INSTALL =>  Updating install info...
info: INSTALL =>  -- OK! 95% complete! --

info: INSTALL =>  -- Step 22/22 --
info: INSTALL =>  Finishing install
info: INSTALL =>  -- OK! 100% complete! --

info: INSTALL =>  Huzzah! Victory!
info: COMPOSE =>  0=--project-name, 1=kalabox, 2=--file, 3=C:\Users\shaal\.kalabox\downloads\kalabox\kalabox-6.yml, 4=ps, 5=-q, 6=syncthing, 7=undefined
info: COMPOSE =>  0=--project-name, 1=kalabox, 2=--file, 3=C:\Users\shaal\.kalabox\downloads\kalabox\kalabox-7.yml, 4=run, 5=-d, 6=--entrypoint, 7=tail, 8=syncthing, 9=-f, 10=/dev/null, mode=false
info: COMPOSE =>  0=--project-name, 1=kalabox, 2=--file, 3=C:\Users\shaal\.kalabox\downloads\kalabox\kalabox-8.yml, 4=run, 5=-d, 6=--entrypoint, 7=tail, 8=syncthing, 9=-f, 10=/dev/null, mode=false
info: COMPOSE =>  0=--project-name, 1=kalabox, 2=--file, 3=C:\Users\shaal\.kalabox\downloads\kalabox\kalabox-9.yml, 4=run, 5=-d, 6=--entrypoint, 7=tail, 8=syncthing, 9=-f, 10=/dev/null, mode=false
info: COMPOSE =>  0=--project-name, 1=kalabox, 2=--file, 3=C:\Users\shaal\.kalabox\downloads\kalabox\kalabox-10.yml, 4=ps, 5=-q, 6=syncthing, 7=undefined
info: COMPOSE =>  0=--project-name, 1=3paces-template, 2=--file, 3=C:\Users\shaal\Documents\kbox-pantheon\3paces-template\kalabox-compose.yml, 4=--file, 5=C:\Users\shaal\Documents\kbox-pantheon\3paces-template\kalabox-cli.yml, 6=--file, 7=C:\Users\shaal\.kalabox\downloads\3paces-template\3paces-template-11.yml, 8=up, 9=-d, mode=collect
Recreating 3pacestemplate_redis_1
Pulling redis (kalabox/pantheon-redis:v0.11.1)...
info: DOCKER-COMPOSE.EXE =>  Pulling repository docker.io/kalabox/pantheon-redis
ERROR: Network timed out while trying to connect to https://index.docker.io/v1/repositories/kalabox/pantheon-redis/images. You may want to check your internet connection or if you are behind a proxy.
info: DOCKER-COMPOSE.EXE =>  Run exited with code: 1
code1err:more:Pulling repository docker.io/kalabox/pantheon-redis

VError: code1err:more:Pulling repository docker.io/kalabox/pantheon-redis

    at ChildProcess.<anonymous> (D:\Programs\Kalabox\lib\util\shell.js.jx:247:16)
    at ChildProcess.emit (events.js:85:9)
    at maybeClose (child_process.js:773:12)
    at Process.ChildProcess._handle.onexit (child_process.js:839:1)
From previous event:
    at Object.exports.spawn (D:\Programs\Kalabox\lib\util\shell.js.jx:211:10)
    at Object.sh (D:\Programs\Kalabox\plugins\kalabox-engine-docker\provider\docker\lib\bin.js.jx:92:20)
    at D:\Programs\Kalabox\plugins\kalabox-engine-docker\provider\docker\compose.js.jx:60:18
From previous event:
    at shCompose (D:\Programs\Kalabox\plugins\kalabox-engine-docker\provider\docker\compose.js.jx:42:6)
    at Object.up [as start] (D:\Programs\Kalabox\plugins\kalabox-engine-docker\provider\docker\compose.js.jx:257:12)
    at D:\Programs\Kalabox\plugins\kalabox-engine-docker\index.js.jx:129:22
From previous event:
    at Object.start (D:\Programs\Kalabox\plugins\kalabox-engine-docker\index.js.jx:128:20)
From previous event:
    at D:\Programs\Kalabox\lib\engine.js.jx:430:29
From previous event:
    at Object.exports.start (D:\Programs\Kalabox\lib\engine.js.jx:429:4)
    at D:\Programs\Kalabox\lib\app.js.jx:352:19
From previous event:
    at Object.exports.start (D:\Programs\Kalabox\lib\app.js.jx:351:4)
    at D:\Programs\Kalabox\lib\create.js.jx:404:25
From previous event:
    at Promise.try.then.then.then.then.then.then.then.tap.tap.sysRoot (D:\Programs\Kalabox\lib\create.js.jx:403:8)
    at process._tickCallback (node.js:803:1)
From previous event:
    at createApp (D:\Programs\Kalabox\lib\create.js.jx:385:6)
    at PromptUI.completed (D:\Programs\Kalabox\lib\create.js.jx:495:16)
    at PromptUI.onCompletion (D:\Programs\Kalabox\node_modules\inquirer\lib\ui\prompt.js.jx:68:10)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (D:\Programs\Kalabox\node_modules\inquirer\node_modules\rx\dist\rx.js.jx:1792:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (D:\Programs\Kalabox\node_modules\inquirer\node_modules\rx\dist\rx.js.jx:1729:14)
    at AnonymousObserver.tryCatcher (D:\Programs\Kalabox\node_modules\inquirer\node_modules\rx\dist\rx.js.jx:566:29)
    at AutoDetachObserverPrototype.completed (D:\Programs\Kalabox\node_modules\inquirer\node_modules\rx\dist\rx.js.jx:5287:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (D:\Programs\Kalabox\node_modules\inquirer\node_modules\rx\dist\rx.js.jx:1729:14)
    at InnerObserver.onCompleted (D:\Programs\Kalabox\node_modules\inquirer\node_modules\rx\dist\rx.js.jx:3424:65)
    at InnerObserver.tryCatcher (D:\Programs\Kalabox\node_modules\inquirer\node_modules\rx\dist\rx.js.jx:566:29)
    at AutoDetachObserverPrototype.completed (D:\Programs\Kalabox\node_modules\inquirer\node_modules\rx\dist\rx.js.jx:5287:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (D:\Programs\Kalabox\node_modules\inquirer\node_modules\rx\dist\rx.js.jx:1729:14)
    at AutoDetachObserver.tryCatcher (D:\Programs\Kalabox\node_modules\inquirer\node_modules\rx\dist\rx.js.jx:566:29)
    at AutoDetachObserverPrototype.completed (D:\Programs\Kalabox\node_modules\inquirer\node_modules\rx\dist\rx.js.jx:5287:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (D:\Programs\Kalabox\node_modules\inquirer\node_modules\rx\dist\rx.js.jx:1729:14)
    at InnerObserver.onCompleted (D:\Programs\Kalabox\node_modules\inquirer\node_modules\rx\dist\rx.js.jx:3424:65)
    at InnerObserver.tryCatcher (D:\Programs\Kalabox\node_modules\inquirer\node_modules\rx\dist\rx.js.jx:566:29)
    at AutoDetachObserverPrototype.completed (D:\Programs\Kalabox\node_modules\inquirer\node_modules\rx\dist\rx.js.jx:5287:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (D:\Programs\Kalabox\node_modules\inquirer\node_modules\rx\dist\rx.js.jx:1729:14)
```

**Comment by pirog** [comment]
@shaal i rolled i new release of the kalabox boot2docker iso that should have a backup dns server in it
https://github.com/kalabox/kalabox-iso/releases/tag/v0.11.3

we will roll this out in our v0.11.3 release but you should be able to just download and replace the kalabox.iso

```
~/.kalabox/bin/docker-machine stop Kalabox2
cd ~/.docker/machine/machines/Kalabox2
rm boot2docker.iso
curl -L https://github.com/kalabox/kalabox-iso/releases/download/v0.11.3/kalabox.iso > boot2docker.iso
```
